Rust-GCC/gccrs

- gcc/rust/backend/rust-compile-item.h
- gcc/rust/backend/rust-compile-stmt.h
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.h
- gcc/rust/checks/errors/privacy/rust-pub-restricted-visitor.cc
- gcc/rust/checks/errors/privacy/rust-pub-restricted-visitor.h
- gcc/rust/checks/errors/privacy/rust-reachability.cc
- gcc/rust/checks/errors/privacy/rust-reachability.h
- gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
- gcc/rust/checks/errors/privacy/rust-visibility-resolver.h
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-const-checker.h
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/checks/errors/rust-unsafe-checker.h
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/hir/rust-ast-lower-item.h
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
- gcc/rust/hir/tree/rust-hir-full-decls.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-visitor.h
- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/metadata/rust-export-metadata.cc
- gcc/rust/typecheck/rust-hir-type-check-item.h
- gcc/rust/typecheck/rust-hir-type-check-stmt.cc
- gcc/rust/typecheck/rust-hir-type-check-stmt.h
- gcc/rust/typecheck/rust-tycheck-dump.h
- gcc/rust/util/rust-attributes.cc
This HIR node represents macros which should be exported into the final Rust metadata files. Because our metadata exporter operates on the HIR, while macros are inherently tied to the AST, we need a way to propagate exported macros up until the metadata export pass on the HIR. Hence the existence of this class, whose sole purpose is to keep enough information for the metadata exporter to retrieve the original AST::MacroRulesDefinition. Handling for actually exporting these macros will come later.
* hir/tree/rust-hir-item.h (class ExportedMacro): Add new ExportedMacro class.
* hir/tree/rust-hir.cc (ExportedMacro::accept_vis): New function.
(ExportedMacro::get_locus): Likewise.
(ExportedMacro::get_item_kind): Likewise.
(ExportedMacro::clone_item_impl): Likewise.
* …
> hir: Add ExportedMacro node and handling.

- README.md
- gcc/rust/Make-lang.in
- gcc/rust/config-lang.in
- gcc/rust/lang-specs.h
- gcc/rust/rustspec.cc
ChangeLog:
* README.md (process): Rename `rust1` to `crab1` in examples.
* Make-lang.in: Rename `rust1` to `crab1`.
* config-lang.in: Likewise.
* lang-specs.h: Likewise.
* rustspec.cc (lang_specific_driver): Likewise.
> gccrs: Rename compiler proper to crab1

- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/resolve/rust-ast-resolve-expr.h
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-pattern.cc
- gcc/rust/resolve/rust-ast-resolve-pattern.h
- gcc/rust/resolve/rust-ast-resolve-stmt.h
- gcc/testsuite/rust/compile/multiple_bindings1.rs
This is an attempt to provide handling for multiple bindings to the same identifier. It works for function and closure parameters only for now (i.e. E0415). Additionally, it lays down the base for resolving `AltPattern` bindings.
I followed rustc's implementation for the most part.
https://github.com/rust-lang/rust/blob/master/compiler/rustc_resolve/src/late.rs#L3168.
If initially approved, I'll extend it for pattern bindings as well (i.e. E0416) and add tests.
Partially addresses #1136
> resolve: Handle multiple bindings to the same identifier

- gcc/rust/backend/rust-compile-block.h
- gcc/rust/backend/rust-compile-expr.h
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.h
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-const-checker.h
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/checks/errors/rust-unsafe-checker.h
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-full-decls.h
- gcc/rust/hir/tree/rust-hir-visitor.h
- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.h
This should allow for 'if let' expressions to be lowered more easily.
> Unify HIR::IfLetExprConseqIf{,Let} into HIR::IfLetExprConseqElse

- gcc/rust/resolve/rust-ast-resolve-pattern.cc
- gcc/rust/resolve/rust-ast-resolve-pattern.h
- gcc/testsuite/rust/compile/torture/alt_patterns1.rs
~Doesn't even fix~ Addresses #1136
The main changes in this commit can be logically split into two parts:
1) Pushing new pattern binding contexts in alt patterns. At the start   
of each AltPattern we push an 'Or' context which represents the relation
between the bindings of different alts.
Before we resolve each alt arm we need to push a 'Product' context to represent
the relation between the bindings of this specific alt arm and each other.
This 'Product' context is removed after the alt arm visit and the its bindings
are pushed into the 'Or' context.
Eventually, the 'Or' context is removed as well after it fulfills its duty.
Its bindings are then pushed into the previous context similarly and so on.
2) Checking for consistent bindings between the alt arms which is handled
by …
> resolve: Add name resolution for AltPattern

- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
In my opinion, `Session::dump_hir` is to dump items in one crate using `items->as_string()`  while `Session::dump_hir_pretty` is to dump items with identation using `items->accept_vis()`. So the diff between two dump methods are mainly identation (e.g. hierarchy)? (If it's incorrect, please tell me the right one). 
My plan is implementing some `HIR::Dump::visit()` based on `as_string()`.  In first commit, I dump inner attrs for `Dump::visit(BlockExpr &)` according to [BlockExpr::as_string()](https://github.com/Rust-GCC/gccrs/blob/2c1e7b55dab5564f92d890c4953f9fd387bb30d7/gcc/rust/hir/tree/rust-hir.cc#L929-#L943). 
I wonder if I am on the right track. Please give some suggestions. Thank you!
> Impl `Rust::HIR::Dump::visit`

- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/rust/typecheck/rust-coercion.cc
- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/rust/typecheck/rust-hir-type-check-stmt.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-typecheck-context.cc
- gcc/rust/typecheck/rust-tyty-util.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/rust/typecheck/rust-unify.cc
- gcc/testsuite/rust/compile/issue-1981.rs
> Fix bad method resolution and add move_val_init

- .github/workflows/commit-format.yml
ChangeLog:
* .github/workflows/commit-format.yml: Skip job on PRs to master.
Addresses #1853
> ci: Do not run `check-gccrs-prefix` on PRs to master

- gcc/rust/hir/rust-ast-lower-implitem.h
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/hir/rust-ast-lower-item.h
- gcc/rust/hir/rust-ast-lower-stmt.cc
- gcc/rust/hir/rust-ast-lower-stmt.h
- gcc/rust/hir/rust-ast-lower-type.h
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/hir/rust-ast-lower.h
- gcc/rust/resolve/rust-ast-resolve-expr.h
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-item.h
- gcc/rust/resolve/rust-ast-resolve-stmt.cc
- gcc/rust/resolve/rust-ast-resolve-stmt.h
- gcc/rust/resolve/rust-ast-resolve-struct-expr-field.h
- gcc/rust/resolve/rust-ast-resolve-toplevel.h
- gcc/rust/resolve/rust-ast-resolve-type.h
- gcc/rust/resolve/rust-ast-resolve.h
* hir/rust-ast-lower-implitem.h (RUST_AST_LOWER_IMPLITEM_H): cleanup header usage
* hir/rust-ast-lower-item.cc: likewise
* hir/rust-ast-lower-item.h (RUST_AST_LOWER_ITEM): likewise
* hir/rust-ast-lower-stmt.cc: likewise
* hir/rust-ast-lower-stmt.h (RUST_AST_LOWER_STMT): likewise
* hir/rust-ast-lower-type.h: likewise
* hir/rust-ast-lower.cc: likewise
* hir/rust-ast-lower.h: likewise
* resolve/rust-ast-resolve-expr.h: likewise
* resolve/rust-ast-resolve-item.cc: likewise
* resolve/rust-ast-resolve-item.h: likewise
* resolve/rust-ast-resolve-stmt.cc: likewise
* resolve/rust-ast-resolve-stmt.h: likewise
* resolve/rust-ast-resolve-struct-expr-field.h: likewise
* resolve/rust-ast-resolve-toplevel.h: likewise
* resolve/rust-ast-resolve-type.h: likewise
* …
> gccrs: Cleanup unused headers

- gcc/rust/ast/rust-ast.h
- gcc/rust/hir/rust-ast-lower-enumitem.h
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/hir/rust-ast-lower-stmt.cc
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-path.cc
- gcc/rust/resolve/rust-ast-resolve-path.h
- gcc/rust/resolve/rust-ast-resolve-toplevel.h
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-type-util.cc
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
- gcc/testsuite/rust/compile/issue-850.rs
- gcc/testsuite/rust/compile/issue-855.rs
> Support use declaration to export the type properly

- gcc/rust/checks/errors/rust-feature-gate.cc
- gcc/rust/checks/errors/rust-feature.h
Fix #1952 
* checks/errors/rust-feature-gate.cc: Adjust 'ld'->'u'.
* checks/errors/rust-feature.h: Adjust
the type of `m_issue`: 'uint64_t' -> 'unsigned'.
> Fix `FeatureGate::gate` will crash on 32-bit x86.

- gcc/rust/metadata/rust-imports.cc
Some were still present from the original adaptation of the Go metadata
imports and exports.
* metadata/rust-imports.cc (add_search_path): Change `Go` -> `Rust`.
(Import::try_package_in_directory): Likewise.
(Import::find_export_data): Likewise.
> rust-imports: Fix last few mentions of Go.

- gcc/rust/ast/rust-ast-dump.cc
Having the extra semicolon causes parsing errors when importing macros
exported using the AST dump, as no rule expects multiple tokens after a
single macro rule definition.
* ast/rust-ast-dump.cc (Dump::visit): Remove extraneous semicolon when
dumping macro rules.
> ast: Dump each MacroRule properly without the extra semicolon

- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/testsuite/rust/compile/issue-2037.rs
Trait objects are not required to use the 'dyn' keyword though it is depreciated in later editions/version of Rustc. This patch handles the case when we query the type for an HIR::Item which happens to be an HIR::Trait and return a trait object or error.
Fixes #2037
* typecheck/rust-hir-type-check-item.cc (TypeCheckItem::visit): return a TraitObject
* rust/compile/issue-2037.rs: New test.
> gccrs: Fix ICE on parsing trait object missing dyn keyword

- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/rust/hir/rust-ast-lower-type.h
* hir/rust-ast-lower-type.h: Move all remaining definitions to source file.
* hir/rust-ast-lower-type.cc (ASTLoweringType::translate): Moved to source file.
(ASTLoweringType::visit): Likewise.
(ASTLowerGenericParam::translate): Likewise.
(ASTLowerGenericParam::visit): Likewise.
(ASTLoweringTypeBounds::translate): Likewise.
(ASTLoweringTypeBounds::visit): Likewise.
(ASTLowerWhereClauseItem::translate): Likewise.
(ASTLowerWhereClauseItem::visit): Likewise.
Small refactor before I work on #2015
> ast: Refactor rust-ast-lower-type.h to source file

- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-item.h
- gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
- gcc/rust/resolve/rust-ast-resolve-path.cc
- gcc/testsuite/rust/compile/privacy8.rs
- ast: Fix location for pub(crate)
- resolver: Allow SimplePath to resolve to their root segment
- privacy: Check for pub(crate) when resolving visibility path.
Fixes #2000
Fixes #1448
This causes the function to return true and the checks to pass, but it
requires more thinking - how should we deal with pub(crate) in the current system?
Should we simply treat it as a pub item in the current crate, but export it as
a private item in the metadata?
I'll look into this more in the coming days.
> Add proper support for `pub(crate)`

- Dockerfile
We do not need to set the system's compiler to `gccrs`, as we are mostly
interested in *having* gccrs - not necessarily using it as a C and C++
compiler as well.
ChangeLog:
* Dockerfile: Remove update-alternatives invocation.
Fixes #2047
> docker: Do not run update-alternatives on invalid path

- gcc/rust/util/rust-attributes.cc
Fixes #2025
* util/rust-attributes.cc: Add stable to the table of known attributes
> gccrs: Add missing known attribute stable

- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty-subst.h
- gcc/testsuite/rust/compile/const_generics_5.rs
- gcc/testsuite/rust/compile/issue-2039.rs
- gcc/testsuite/rust/compile/issue-2043.rs
There were a few small issues going on here:
- Missing name resolution for self parameters with a specified type
- When we handle lifetime generics the argument mappings were empty
- They ended up being treated as errors wrongly but there is a difference between empty and error
- Remove bad check for does type support generics we can rely on the type's error handling here
Fixes #2039 #2043
> Fix bad handling of generic lifetimes

- gcc/rust/typecheck/rust-casts.cc
- gcc/testsuite/rust/compile/cast5.rs
In rust cast to char is allowed only from u8 type. This patch handles fix the case when the type is infered from an integer value, allowing only the u8 case'
Fixes #2027
* typecheck/rust-casts.cc (TypeCastRules::cast_rules): case INTEGRAL handles TypeKind::CHAR
* rust/compile/cast5.rs: New test.
> gccrs: Fix bad cast as a char

- gcc/rust/backend/rust-compile-item.cc
- gcc/testsuite/rust/execute/torture/issue-2080.rs
We are getting constant expressions for the initilizers for static items this hits an assertion in the GCC middle-end which is looking for a constructor so we need to unwrap the constant expression using DECL_INITIAL as the initilizer to the global static.
Fixes #2080
* backend/rust-compile-item.cc (CompileItem::visit): unwrap the constant expression
* rust/execute/torture/issue-2080.rs: New test.
> gccrs: Fix ICE using constructors for intilizers in statics

- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/ast/rust-macro.h
- gcc/rust/ast/rust-path.h
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-expand-visitor.h
- gcc/rust/util/rust-attributes.cc
Add proc macros expansion stub functions.
Fixes #1986
> Add derive proc_macro expansion stubs

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-base.h
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-expr.h
- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/typecheck/rust-hir-path-probe.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/testsuite/rust/compile/issue-2070.rs
> Support qualified trait item call expression

- gcc/rust/rust-lang.cc
Yesterday's commit 3757e8d71794cece4a5c9d08245b7ad111044853 "Merge commit 6baa95c9c5b3fea96fd22d03d961db4e4cf48d88' into HEAD [#2112]" brought in the #1713 change from GCC upstream master branch that broke the rules (via code copied verbatim from elsehwhere in GCC).
gcc/rust/
* rust-lang.cc (grs_langhook_type_for_mode): Placate clang-format.
> Placate clang-format, 'gcc/rust/rust-lang.cc:grs_langhook_type_for_mode'

- gcc/rust/ast/rust-ast-dump.cc
- gcc/rust/ast/rust-ast-dump.h
- gcc/rust/ast/rust-ast.h
AST::Visitable is an abstract class with a unique accept_vis() method.
Make all abstract AST node class inherit from this class.
Allows for easy definition of operations on nodes that must accept a
visitor.
The static Dump::dump() is an example of such use: the static method
accepts any AST node, creates a Dump visitor and have it visit the AST
starting at the node.
This change also inserts a debug(Visitable&) function in the global
namespace to make it easy to call from the debugger (similar to
debug_tree or debug(rtx*) functions).
```
* ast/rust-ast-dump.cc (Dump::debug): New.
* ast/rust-ast-dump.h (Dump::debug): Untemplate it.
(debug): New.
* ast/rust-ast.h (class Visitable): New.
(class TokenTree): Inherit from Visitable.
(class MacroMatch): Likewise.
(class …
```
> gccrs: Introduce AST::Visitable class for AST

- gcc/rust/ast/rust-ast-tokenstream.cc
Inner attribute did not output exclamation tokens as there was no way to differentiate inner from outer attributes previously.
> Fix inner attribute tokenstream

- gcc/rust/backend/rust-compile-item.h
- gcc/rust/backend/rust-compile-stmt.cc
- gcc/rust/backend/rust-compile-stmt.h
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.h
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-const-checker.h
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/checks/errors/rust-unsafe-checker.h
- gcc/rust/checks/lints/rust-lint-marklive.h
- gcc/rust/hir/rust-ast-lower-stmt.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
- gcc/rust/hir/tree/rust-hir-full-decls.h
- gcc/rust/hir/tree/rust-hir-stmt.h
- gcc/rust/hir/tree/rust-hir-visitor.h
- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/typecheck/rust-hir-type-check-stmt.cc
- gcc/rust/typecheck/rust-hir-type-check-stmt.h
- gcc/rust/typecheck/rust-tycheck-dump.h
Simplifies the HIR with intent to address #1446.
> Unify HIR::ExprStmt deriving classes

- gcc/rust/ast/rust-ast-tokenstream.cc
StructExprStructFields inherit from StructExprStruct and shall output the struct name and curly braces.
> Fix StructExprStructFields tokenstream

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/macro-issue2092.rs
A matcher like `$(a),?` is no longer accepted.
Fixes #2092.
* parse/rust-parse-impl.h
(Parser<ManagedTokenSource>::parse_macro_match_repetition):
reject separator in `?` repetition
* rust/compile/macro-issue2092.rs: New test.
> parser: macro: reject separator in `?` repetition

- gcc/rust/ast/rust-ast.h
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/resolve/rust-ast-resolve-expr.h
- gcc/testsuite/lib/prune.exp
- gcc/testsuite/rust/compile/break-rust1.rs
- gcc/testsuite/rust/compile/break-rust2.rs
- gcc/testsuite/rust/compile/break-rust3.rs
Since https://github.com/Rust-GCC/gccrs/issues/1996 has received positive feedback, here's a tentative implementation 😄
TODO:
* Suggestions welcome!
* ...or is the current one fine?
* It would be nice to make it a little bit more explicit that this is not _really_ an ICE, there is no bug to report, etc.
* rustc says: "the compiler expectedly panicked. this is a feature."
* I've no idea how to do GNU-style changelogs! I've read [this doc](https://www.gnu.org/prep/standards/html_node/Change-Logs.html) and skimmed through some other gccrs commits, and tried to write some entries based on that
* glibc people have accepted my patches without Changelog entries; are they really required?
* Or... is it worth it?
* `make check-rust` seems to pass locally, that's a start
* Need to test that `break …
> break rust 💥

- libgrust/libproc_macro/Makefile.am
- libgrust/libproc_macro/Makefile.in
- libgrust/libproc_macro/literal.cc
- libgrust/libproc_macro/literal.h
- libgrust/libproc_macro/proc_macro.cc
- libgrust/libproc_macro/proc_macro.h
- libgrust/libproc_macro/rust/bridge/literal.rs
Add `Literal` type matching the rust's one.
> libproc_macro: Add literal type

- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/hir/rust-ast-lower-expr.h
[I have no idea what I'm doing](https://github.com/vkurilin/ihniwid), but using a `?` was causing an ICE and now it does not (I get regular errors instead), so, good? A step towards https://github.com/Rust-GCC/gccrs/issues/166 perhaps?
> Lower ErrorPropagationExpr from AST to HIR

- gcc/testsuite/rust/compile/issue-852.rs
Fixes #852
* rust/compile/issue-852.rs: New test.
> gccrs: Add testcase to show matching of enum variants

- gcc/rust/ast/rust-ast-dump.cc
* ast/rust-ast-dump.cc: implement visit() function for QualifiedPathInType.
Fixed bad formatting of type alias in ast dump.
Fixes #2023 
Output of AST expanded dump when running the code the linked issue:
```
macro_rules! forward_ref_binop{
(impl $imp:ident , $method:ident for $t:ty , $u:ty) => 
{ forward_ref_binop ! ( impl $ imp , $ method for $ t , $ u , # [ stable ( feature = "rust1" , since = "1.0.0" ) ] ) ; }
;
(impl $imp:ident , $method:ident for $t:ty , $u:ty , # [$attr:meta]) => 
{ # [ $ attr ] impl < a > $ imp < $ u > for & a $ t { type Output = < $ t as $ imp < $ u >> :: Output ; # [ inline ] fn $ method ( self , other : $ u ) -> < $ t as $ imp < $ u >> :: Output { $ imp :: $ method ( * self , other ) } } # [ $ attr ] impl < a > $ imp < & a $ u > for $ t { …
```
> Fix Bad formatting in AST expanded dump with associated types

- gcc/rust/hir/rust-ast-lower-pattern.cc
- gcc/rust/hir/rust-ast-lower-pattern.h
- gcc/rust/hir/rust-ast-lower-stmt.cc
- gcc/testsuite/rust/compile/let_alt.rs
Changes the ```rust_sorry_at``` for ```AltPattern``` in ```let``` statements to a ```rust_error_at```.
> Add error message for AltPattern in let statements

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/issue-1807.rs
Reference patterns cannot contain AltPatterns per the Rust reference,
so we should not call into `parse_pattern` to parse the referenced pattern,
but rather the more restrictive `parse_pattern_no_alt`.
* parse/rust-parse-impl.h (Parser::parse_reference_pattern): Do not
call into `parse_pattern` anymore.
* rust/compile/issue-1807.rs: New test.
Fixes #1807
> parser: Parse reference patterns correctly

- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/rust-session-manager.cc
- gcc/rust/rust-session-manager.h
Fixes #2022 
Removed the Session::dump_ast function, and all the elements associated with it.
* rust-session-manager.cc (Session::enable_dump): Removed else if (arg == "parse").
(Session::compile_crate): Removed the statement that called the dump_ast.
(Session::dump_ast): Removed dump_ast function.
* rust-session-manager.h (struct CompileOptions): Removed the PARSER_AST_DUMP option.
Signed-off-by: M V V S Manoj Kumar <mvvsmanojkumar@gmail.com>
Do let me know if I need to change something or missed anything .
> Deleted the as_string AST dump

- libgrust/libproc_macro/Makefile.am
- libgrust/libproc_macro/Makefile.in
- libgrust/libproc_macro/ident.cc
- libgrust/libproc_macro/ident.h
- libgrust/libproc_macro/rust/bridge/ident.rs
Add Ident cpp representation and high level interface.
Needs #2104
> libproc_macro: Add Ident type

- gcc/rust/lang.opt
In https://gcc.gnu.org/PR108890 "Translation mistakes 2023" @rillig lists several issues with GCC/Rust diagnostics and option help texts (but also a few non-GCC/Rust).
This commit fixes mistakes only related to GCC/Rust, specifically to the file `gcc/rust/lang.opt`.
closes https://github.com/Rust-GCC/gccrs/issues/1916
PR translation/108890
gcc/rust/
* lang.opt: Fix translation mistakes 2023 in
GCC/Rust [PR108890]
(line 67): change the inconsistent tab to spaces
(line 75): wrap bare placeholder `integer`
(line 79): remove redundant text of `Choose which`
(line 96): remove redundant text of `Choose which`
(line 112): remove redundant `Flag to`
(line 124): correct the exclusive term `When to stop`
(line 124): correct typo of `copimlation`
> Fix translation mistakes 2023 in GCC/Rust [PR108890]

- libgrust/libproc_macro/literal.cc
> libproc_macro: fix literal drop

- .github/workflows/clang-format.yml
Add the libgrust directory to the clang-format github action.
ChangeLog:
* .github/workflows/clang-format.yml: Add libgrust directory.
Fixes #2148
> Add libgrust to clang-format checker

- gcc/rust/typecheck/rust-hir-dot-operator.cc
- gcc/testsuite/rust/compile/issue-2139.rs
We were missing a check for trait item selection to ensure they are actually methods and remove assertion to check if the trait item is a function this is a valid error check not an assertion.
Fixes #2139
* typecheck/rust-hir-dot-operator.cc (MethodResolver::select): verify it is a method
* rust/compile/issue-2139.rs: New test.
> gccrs: Fix ICE during method resolution

- gcc/rust/backend/rust-compile-implitem.h
- gcc/rust/backend/rust-compile-item.cc
- gcc/rust/lang.opt
- gcc/rust/rust-lang.cc
- gcc/testsuite/rust/compile/issue-2136-1.rs
- gcc/testsuite/rust/compile/issue-2136-2.rs
> fix ICE with recursive function calls

- gcc/rust/rust-session-manager.cc
The ```README``` should probably also be adjusted.
> Fix -frust-dump-* error messages

- gcc/rust/ast/rust-ast-dump.cc
Use parentheses to remove any ambiguities when dumping expressions with
unary ! and -.
* ast/rust-ast-dump.cc (Dump::visit): print parentheses around
unique expression operand.
> gccrs: Minor tuning in AST dump

- gcc/rust/hir/tree/rust-hir-pattern.h
A small patch to address #2041, split off since it's a shared dependency for two other patches.
> Add accessors to HIR::StructPatternFieldIdentPat

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.h
This is required to solve #2105
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::resolve_fn_trait_call): return the assoicated predicate
* typecheck/rust-hir-type-check-expr.h: update prototype
> gccrs: resolve the associated_predicate when mapping Fn traits

- gcc/rust/typecheck/rust-hir-trait-reference.cc
- gcc/rust/typecheck/rust-hir-trait-reference.h
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-type-util.cc
- gcc/rust/typecheck/rust-type-util.h
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty-subst.h
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/compile/issue-2135.rs
When resolving a qualified path we need to use the predicate to lookup the
relevant assoicated impl block where possible. The issue here is that
it might not have one due to a valid error in the impl block or it might
be used within a trait this is a valid case. Generally we will be able to
resolve to an impl block then it can grab that type and move on.
Fixes #2135
> qualified path syntax is used to disambiguate predicates

- gcc/rust/lang.opt
- gcc/rust/rust-session-manager.cc
- gcc/rust/rust-session-manager.h
Add a new option to gather extern crates location.
* lang.opt: Add frust-extern option.
* rust-session-manager.cc (Session::handle_extern_option): Add frust-extern option handler.
* rust-session-manager.h (struct Session): Add an unordered map to store library name and locations.
> Add frust-extern option

- gcc/rust/Make-lang.in
- libgrust/Makefile.am
- libgrust/Makefile.in
- libgrust/libproc_macro/Makefile.am
- libgrust/libproc_macro/Makefile.in
- libgrust/libproc_macro/group.cc
- libgrust/libproc_macro/group.h
- libgrust/libproc_macro/ident.cc
- libgrust/libproc_macro/ident.h
- libgrust/libproc_macro/literal.cc
- libgrust/libproc_macro/literal.h
- libgrust/libproc_macro/proc_macro.h
- libgrust/libproc_macro/punct.cc
- libgrust/libproc_macro/punct.h
- libgrust/libproc_macro/tokenstream.cc
- libgrust/libproc_macro/tokenstream.h
- libgrust/libproc_macro/tokentree.cc
- libgrust/libproc_macro/tokentree.h
Refactor a bit the global structure of libproc_macro to make is more usable and fix the link issue against the compiler.
> Modularize libproc macro

- gcc/rust/expand/rust-macro-substitute-ctx.cc
- gcc/testsuite/rust/compile/macro52.rs
Fixes ICE from #2129, although #2129 still has problems with ```AltPattern```.
> Fix out of bounds indexing while expanding macros with repetition

- libgrust/libproc_macro/proc_macro.cc
- libgrust/libproc_macro/proc_macro.h
Add a proc_macro type to identify the location of a proc macro function in the proc macro library. This model is slightly based upon the rustc format, the main difference resides within the fact we do not use a bridge/server communication but instead a function pointer directly to the macro function.
> Proc macro type

- gcc/rust/ast/rust-macro.cc
- gcc/rust/ast/rust-macro.h
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/rust/util/bi-map.h
- gcc/rust/util/rust-hir-map.cc
This commit regroups information related to builtin macros in one place instead
of spreading it over multiple files. It also adds a simple bi-directional
hashmap in order to perform lookups from a key as well as a value.
* ast/rust-macro.cc (builtin_macro_from_string): Move function.
* ast/rust-macro.h (enum class): Move enum.
(builtin_macro_from_string): Move function.
* expand/rust-macro-builtins.cc (builtin_macro_from_string): New function.
(make_macro_path_str): Use new bi-map.
(parse_single_string_literal): Use new `BuiltinMacro` enum.
(MacroBuiltin::include_bytes_handler): Likewise.
(MacroBuiltin::include_str_handler): Likewise.
(MacroBuiltin::compile_error_handler): Likewise.
(MacroBuiltin::concat_handler): Likewise.
(MacroBuiltin::env_handler): Likewise. …
> builtin: Cleanup handling of builtin macros

- gcc/rust/backend/rust-compile-base.cc
- gcc/testsuite/rust/compile/issue-2178.rs
When we have a block expression for cosntants or statics we need to ensure we compile the locals for the implicit function we generate in GIMPLE before feeding it directly into the constant folder to evaluate the data.
Fixes #2178
* backend/rust-compile-base.cc: add missing compile_locals call
* rust/compile/issue-2178.rs: New test.
> gccrs: Add missing compile locals for constants and statics

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/parse_specialization.rs
```default``` appears to come before function/method qualifiers, not after
> Fix "default unsafe fn ..." parsing

- gcc/rust/ast/rust-ast-full-decls.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-full-decls.h
Fixes Issue #1568 
This is HIR equivalent Node for AST::InineAsm.As gccrs doesn't have a symbol class, I have made every instance of it a string.
Signed-off-by: M V V S Manoj Kumar <mvvsmanojkumar@gmail.com>
* hir/tree/rust-hir-expr.h (class InlineAsm):Added class declaration.
* hir/tree/rust-hir-full-decls.h (class InlineAsm):Added class definition.
The rustc guide for reference [here](https://rustc-dev-guide.rust-lang.org/asm.html#hir)
Do go through this an tell me if I need to include something or could add anything else. Once you review it, I'll remove the comments, such as
```
//   pub enum InlineAsmRegClass {
//     X86(X86InlineAsmRegClass),
//     Arm(ArmInlineAsmRegClass),
//     AArch64(AArch64InlineAsmRegClass),
//     RiscV(RiscVInlineAsmRegClass),
// …
```
> Added HIR::InlineAsm

- gcc/testsuite/rust/compile/const-issue1440.rs
- gcc/testsuite/rust/compile/torture/issue-1432.rs
* rust/compile/const-issue1440.rs: Remove LE conditional compilation.
* rust/compile/torture/issue-1432.rs: Likewise.
Addresses parts of #2184
> Address invalid little-endian-only testcases

- gcc/rust/ast/rust-ast-dump.cc
* ast/rust-ast-dump.cc (Dump::visit): Implement dump for
`TupleIndexExpr`.
> dump: Dump `TupleIndexExpr`s

- gcc/rust/lex/rust-token.h
- gcc/rust/util/rust-token-converter.cc
- libgrust/libproc_macro/Makefile.am
- libgrust/libproc_macro/Makefile.in
- libgrust/libproc_macro/ffistring.cc
- libgrust/libproc_macro/ffistring.h
- libgrust/libproc_macro/literal.cc
- libgrust/libproc_macro/literal.h
- libgrust/libproc_macro/rust/bridge.rs
- libgrust/libproc_macro/rust/bridge/ffistring.rs
- libgrust/libproc_macro/rust/bridge/literal.rs
Rust interface literal internals were taking a type and storing that type. This lead to multiple problems such as various conversion from string to int/float/other type as well as dead end on undetermined types (type checker runs at a later stage).
Fixes #2182 
Fixes #2201
> libproc_macro: Change rust literal internals

- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/ast/rust-item.h
- gcc/rust/ast/rust-macro.h
* ast/rust-ast.h: Add `outer_attrs` to Node.
* ast/rust-expr.h: Make use of new inheritance methods.
* ast/rust-item.h: Likewise.
* ast/rust-macro.h: Likewise.
* ast/rust-path.h: Likewise.
* ast/rust-stmt.h: Likewise.
This PR adds a vector of outer attributes to almost all nodes, which makes procedural macros easier to handle - there is no longer the need to `static_cast` to a node known to have outer attributes.
> ast: Add `outer_attrs` to all `Item`s

- gcc/rust/expand/rust-macro-substitute-ctx.cc
- gcc/rust/lex/rust-token.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/macro-issue2194.rs
> Handle keyword metavariables during macro expansion

- gcc/rust/ast/rust-ast-collector.cc
Propagate back type suffix to created tokens.
Fixes #2205
> ast: Propagate type suffix

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/doc_macro.rs
Allows parsing of ```#[doc = include_str!(...)]``` for ```libcore```. Depends on #2177
> Parse AST::AttrInputMacro attributes

- gcc/rust/resolve/rust-early-name-resolver.cc
* resolve/rust-early-name-resolver.cc (EarlyNameResolver::go): Cleanup
order of calls when accumulating #[macro_use] macros.
(EarlyNameResolver::visit): Likewise.
Very simple PR because that part of the code just bugged me.
> enr: Cleanup #[macro_use] accumulation

- gcc/rust/typecheck/rust-hir-trait-reference.cc
Fix for this warning:
```
../../src/gcc/rust/typecheck/rust-hir-trait-reference.cc:40:2: warning: extra ‘;’ [-Wpedantic]
40 | };
|  ^
```
(untested; done via github edit window)
> gccrs: remove stray semicolon

- gcc/rust/typecheck/rust-casts.cc
- gcc/testsuite/rust/compile/issue-2195.rs
When attempting casts we can try a type coercion first, this is a TryCoercion which will return a result. In the event this is ok we need to perform a true coercion so that we don't leave missing infeence variable's ununified.
Fixes #2195
> gccrs: Fix cast site to not miss type-unifications

- gcc/rust/expand/rust-macro-invoc-lexer.cc
- gcc/rust/expand/rust-macro-substitute-ctx.cc
Fixes #2250
* expand/rust-macro-invoc-lexer.cc: Add missing copyright header.
> macro-invoc-lexer: Add Copyright header.

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/expand/rust-derive-clone.cc
- gcc/rust/expand/rust-derive-clone.h
- gcc/rust/expand/rust-derive.cc
- gcc/rust/expand/rust-derive.h
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-expand-visitor.h
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/util/rust-hir-map.cc
- gcc/testsuite/rust/compile/derive_macro1.rs
- gcc/testsuite/rust/compile/derive_macro3.rs
- gcc/testsuite/rust/compile/macro43.rs
- gcc/testsuite/rust/execute/torture/derive_macro1.rs
- gcc/testsuite/rust/execute/torture/derive_macro3.rs
This PR adds basic support for builtin derive macros and, more specifically, deriving Clone on some simple structures (tuple structs and empty structs). Keeping it as a draft as it still needs some work. Needs #2214
> derive: Add base for builtin derives and #[derive(Clone)]

- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/expand/rust-derive-clone.cc
- gcc/testsuite/rust/execute/torture/derive_macro4.rs
* expand/rust-derive-clone.cc (DeriveClone::visit_struct): Implement proper
cloning for structs with fields.
* ast/rust-ast-builder.cc (AstBuilder::struct_expr): New function.
(AstBuilder::struct_expr_field): Likewise.
(AstBuilder::field_access): Likewise.
(AstBuilder::let): Likewise.
* ast/rust-ast-builder.h: Declare new functions.
* rust/execute/torture/derive_macro4.rs: New test.
> derive: Add #[derive(Clone)] for regular structs

- gcc/rust/Make-lang.in
- gcc/rust/expand/rust-derive-copy.cc
- gcc/rust/expand/rust-derive-copy.h
Addresses #2172 
From looking at `rustc`'s dump of a simple struct which is `#[derive(Copy)]`, it does not seem like we need to do anything particular like instantiating `AssertParamIsCopy<T>`s for each field's type. So I'm not sure how the "this field does not implement Copy" get generated and when. We'll have to investigate this further
> Add #[derive(Copy)] support

- Makefile.def
- Makefile.in
The bootstrap was failing due to a missing target which was not available during the bootstrap.
ChangeLog:
* Makefile.def: Add libgrust target to bootstrap.
* Makefile.in: Regenerate.
Fixes #2181
> fixup: Fix bootstrap build

- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/testsuite/rust/compile/derive_macro7.rs
Fixes #2257.
Derive builtins do not need a real transcriber, but still need one. It
will however never be called since builtin derive macros get expanded
differently, and benefit from knowing on what kind of items they are
applied (struct, enums, unions) rather than receiving a list of tokens
like regular builtin macros.
* expand/rust-macro-builtins.cc (MacroBuiltin::dummy): New function.
* expand/rust-macro-builtins.h: Declare it.
* rust/compile/derive_macro7.rs: New test.
> builtin-derive-macros: Add dummy builtin transcriber for builtin derive macros.

- gcc/rust/ast/rust-ast-dump.cc
This commit fixes printing of literals based on their type.
Previous implementation printed literals the same, regardless their type. Now we are printing:
* int, float, bool don't require special printing
* char        -> `'<char>'`
* string      -> `"<string>"`
* byte        -> `b'<byte>'`
* byte_string -> `b"<byte_string>"`
Fixes #2220
> ast: dump literals correctly

- gcc/rust/util/rust-optional.h
This should fix #2242. Can someone trigger the bootstrap CI to verify?
> Fix warning generated by Optional

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/testsuite/rust/compile/issue-2165.rs
- gcc/testsuite/rust/compile/issue-2166.rs
Concrete types can resolve to assoicated impl blocks which will allow us to resolve the path to the projection type instead of the placeholder trait associated type which can change. The projection will be fixed and is safer to use.
Fixes #2165 #2166
* typecheck/rust-hir-trait-resolve.cc: when the bound is concrete keep the mapping
* typecheck/rust-hir-type-check-path.cc (TypeCheckExpr::visit): add missing call
* typecheck/rust-hir-type-check-type.cc (TypeCheckType::visit): make this the same as paths
* rust/compile/issue-2165.rs: New test.
* rust/compile/issue-2166.rs: New test.
> gccrs: Respect the concrete type when resolving qualifed path types

- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/rust/typecheck/rust-type-util.cc
- gcc/rust/typecheck/rust-type-util.h
- gcc/rust/typecheck/rust-unify.cc
- gcc/testsuite/rust/compile/traits2.rs
- gcc/testsuite/rust/compile/traits3.rs
This is an initiative to begin getting rid of the can_eq interface.
Addresses #2019
* typecheck/rust-hir-type-check-implitem.cc (TypeCheckImplItemWithTrait::visit): use new interface
* typecheck/rust-type-util.cc (types_compatable): implementation of new interface
* typecheck/rust-type-util.h (types_compatable): prototype
* typecheck/rust-unify.cc (UnifyRules::expect_placeholder): It is allow for unification against placeholders
* rust/compile/traits2.rs: update error message
* rust/compile/traits3.rs: update error message
> gccrs: introduce new types_compatable

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/break1.rs
- gcc/testsuite/rust/compile/break2.rs
- gcc/testsuite/rust/compile/cfg2.rs
- gcc/testsuite/rust/compile/continue1.rs
- gcc/testsuite/rust/compile/generics4.rs
- gcc/testsuite/rust/compile/generics6.rs
- gcc/testsuite/rust/compile/generics7.rs
- gcc/testsuite/rust/compile/issue-2029.rs
- gcc/testsuite/rust/compile/issue-2139.rs
- gcc/testsuite/rust/compile/issue-2190-1.rs
- gcc/testsuite/rust/compile/issue-925.rs
- gcc/testsuite/rust/compile/method1.rs
- gcc/testsuite/rust/compile/shadow1.rs
- gcc/testsuite/rust/compile/type-bindings1.rs
- gcc/testsuite/rust/compile/unary_negation.rs
- gcc/testsuite/rust/compile/unary_not.rs
- gcc/testsuite/rust/compile/unconstrained_type_param.rs
- gcc/testsuite/rust/compile/usize1.rs
fixes https://github.com/Rust-GCC/gccrs/issues/2064
Remove every `{ dg-error "failed to type resolve expression" }` annotation that causes a failure when running the testsuite.
* typecheck/rust-hir-type-check-expr.cc: Remove obsolete error diagnostic
* rust/compile/break1.rs: remove dg-error "failed to type resolve expression"
* rust/compile/break2.rs: Likewise
* rust/compile/cfg2.rs: Likewise
* rust/compile/continue1.rs: Likewise
* rust/compile/generics4.rs: Likewise
* rust/compile/generics6.rs: Likewise
* rust/compile/generics7.rs: Likewise
* rust/compile/issue-2029.rs: Likewise
* rust/compile/issue-2139.rs: Likewise
* rust/compile/issue-2190-1.rs: Likewise
* rust/compile/issue-925.rs: Likewise
* rust/compile/method1.rs: Likewise
* …
> fixup: Remove obsolete error diagnostic

- gcc/rust/backend/rust-compile-item.cc
- gcc/rust/typecheck/rust-hir-trait-reference.h
- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/testsuite/rust/compile/issue-2019-1.rs
We have been concentrating on generic impl blocks for so long that we have not handled the simple concrete impl block case where associated types need to be setup when compling a function/method on a trait impl block which uses associated types.
Addresses #2019
* backend/rust-compile-item.cc (CompileItem::visit): ensure assoicated types are setup
* typecheck/rust-hir-trait-reference.h: new interface for concrete impl block
* typecheck/rust-hir-trait-resolve.cc (AssociatedImplTrait::setup_raw_associated_types): ensure we setup assoicated types for this impl block
* rust/compile/issue-2019-1.rs: New test.
> gccrs: ensure assoicated types are setup for concrete trait impl blocks

- gcc/rust/expand/rust-derive-clone.cc
- gcc/rust/expand/rust-derive-clone.h
- gcc/rust/expand/rust-derive-copy.cc
- gcc/rust/expand/rust-derive-copy.h
- gcc/rust/expand/rust-derive.cc
- gcc/rust/expand/rust-derive.h
* expand/rust-derive.h: Store AstBuilder and location.
* expand/rust-derive.cc (DeriveVisitor::DeriveVisitor): Update constructor.
* expand/rust-derive-clone.h: Remove members now stored in `DeriveVisitor`.
* expand/rust-derive-copy.h: Likewise.
* expand/rust-derive-clone.cc (DeriveClone::DeriveClone): Update constructor.
* expand/rust-derive-copy.cc (DeriveCopy::DeriveCopy): Likewise.
> derive: Factor common fields inside the base visitor

- gcc/rust/backend/rust-compile-base.cc
- gcc/testsuite/rust/compile/issue-2019-2.rs
- gcc/testsuite/rust/compile/issue-2019-3.rs
Fixes #2019
* backend/rust-compile-base.cc (HIRCompileBase::resolve_method_address): match the fntype to the candidate
* rust/compile/issue-2019-2.rs: New test.
* rust/compile/issue-2019-3.rs: New test.
> gccrs: fortify resolve_method_address to match the types

- gcc/rust/typecheck/rust-unify.cc
- gcc/testsuite/rust/compile/issue-2036.rs
We use placeholders for assoicated types on traits but if we are unifying types against a placeholder its not possible to check the bounds as the placeholder does not have enough information yet at this point to determine if bounds will or won't be satisfied. That check will occur when associated types and generics are setup.
Fixes #2036
* typecheck/rust-unify.cc (UnifyRules::go): dont check bounds on placeholders
* rust/compile/issue-2036.rs: New test.
> gccrs: we can't check the bounds involving empty placeholder types

- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-lex.h
- libcpp/charset.cc
- libcpp/include/cpplib.h
Addresses #2287 #418
```
* lex/rust-lex.cc (is_whitespace): add all lacked codepoints valid as whitespaces
(is_identifier_start): new function to check XID_Start and underscore
(is_identifier_continue): new function to check XID_Continue
(Lexer::build_token):tokenize Unicode identifiers
(Lexer::parse_partial_string_continue):add comments
(Lexer::parse_partial_unicode_escape):add comments
(Lexer::parse_raw_identifier):change to use `is_identifier_scontinue`
(Lexer::parse_identifier_or_keyword):change to use `is_identifier_continue`
(Lexer::parse_char_or_lifetime):change to use `is_identifier_start` and `is_identifier_continue`
(Lexer::skip_codepoint_input):do not attempt to skip input when bumping EOF
* lex/rust-lex.h:add `current_char32` field
```
libcpp/ChangeLog:
``` …
```
> Tokenize Unicode identifiers

- gcc/rust/ast/rust-ast-dump.cc
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/ast/rust-macro.h
- gcc/rust/ast/rust-stmt.h
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/hir/rust-ast-lower-block.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/braced_macro_arm.rs
- gcc/testsuite/rust/compile/braced_macro_statements1.rs
- gcc/testsuite/rust/compile/braced_macro_statements2.rs
- gcc/testsuite/rust/compile/braced_macro_statements3.rs
- gcc/testsuite/rust/compile/issue-2225.rs
- gcc/testsuite/rust/compile/macro53.rs
Fixes various bugs in statement macro handling
- Parses braced macros as statements where appropriate
- Checks for semicolons (sometimes) when expanding statement macros
- Handles final statement vs. tail expression changing for macros
- Distinguishes between expression and statement macros in AST
This PR takes an approach similar to rustc (and gccrs before #2206) where statement macros are parsed as statements and the parser "recovers" into parsing an expression when required.  I didn't use the existing block expr vs. non-block expr handling because it doesn't handle match arms correctly (or interpolated expression macros once those are implemented).
Closes #2239
> Fix parsing of statement macros 

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-item.h
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty-subst.h
- gcc/testsuite/rust/compile/issue-1893.rs
This was a bug I have been trying to fix for at least 2 months. There were many small
things going wrong in the type-system so it took me to fix:
- https://github.com/Rust-GCC/gccrs/issues/2036
- https://github.com/Rust-GCC/gccrs/issues/2019
- https://github.com/Rust-GCC/gccrs/issues/2165
- https://github.com/Rust-GCC/gccrs/issues/2166
Those issues were all part of the fix for this. This patch set also contains a few fixes to get #1893 working. The main
issue was a nasty issue in how we do generics there is more information about it in the commit. As most generics use the
symbol T we basically didn't notice this most of the time they mostly worked but when you have a generic such as: <Self, T>
Then we try to substitute it with <T,U> we iterated in a loop of Self and T and replaced Self …
> TryFrom trait bound issue

- gcc/rust/resolve/rust-ast-resolve-path.cc
- gcc/rust/resolve/rust-ast-resolve-type.cc
Added rustc E0433 error code. Failed to resolve: Use of Undeclared Crate, Module, or Type
https://github.com/MahadMuhammad/gccrs/assets/95980383/204f81a1-312c-42d0-93f6-af5b199f2f60
* gcc/rust/resolve/rust-ast-resolve-path.cc : Added ErrorCode("E0433") to 'rust_error_at' function.
* gcc/rust/resolve/rust-ast-resolve-type.cc : Added ErrorCode("E0433") to 'rust_error_at' function.
Signed-off-by: Muhammad Mahad <mahadtxt@gmail.com>
> ErrorCode[E0433]: Use of Undeclared Crate, Module, or Type

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-tyty.cc
- Tested code from rustc [E0277](https://doc.rust-lang.org/error_codes/E0277.html):
```rust
// here we declare the Foo trait with a bar method
trait Foo {
fn bar(&self);
}
// we now declare a function which takes an object implementing the Foo trait
fn some_func<T: Foo>(foo: T) {
foo.bar();
}
fn main() {
// we now call the method with the i32 type, which doesn't implement
// the Foo trait
some_func(5i32); // error: the trait bound `i32 : Foo` is not satisfied
}
``` 
---
- Output:
```bash
mahad@linux:~/Desktop/mahad/mahad-testsuite$ ../gccrs-build/gcc/crab1 E0277.rs -frust-incomplete-and-experimental-compiler-do-not-use
E0277.rs:14:15: error: bounds not satisfied for i32 ‘Foo’ is not satisfied [E0277]
7 | fn some_func<T: Foo>(foo: T) {
|                 ~~~
......
14 |     some_func(5i32); …
```
> ErrorCode[E0277] Type Does Not Implement Expected Trait

- gcc/rust/typecheck/rust-autoderef.cc
- gcc/rust/typecheck/rust-hir-dot-operator.cc
- gcc/rust/typecheck/rust-hir-dot-operator.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-type-util.cc
- gcc/rust/typecheck/rust-type-util.h
- gcc/testsuite/rust/compile/issue-2304.rs
When we do operator overloading we can get multiple candidates and we need to use the optional arguments to filter the candidates event further. In the bug we had:
```<integer> + <usize>```
Without the Add impl blocks for the primitive interger types we unify against the rhs to figure out that the lhs should be a usize but when we are using the impl blocks we need to use the rhs to ensure that its possible to coerce the rhs to the expected fntype parameter to filter the candidates.
Fixes #2304
* typecheck/rust-autoderef.cc: use new selection filter
* typecheck/rust-hir-dot-operator.cc (MethodResolver::Select): new slection Filter
* typecheck/rust-hir-dot-operator.h: New select prototype
* typecheck/rust-hir-type-check-expr.cc: call select
* typecheck/rust-type-util.cc …
> gccrs: Add method selection to operator overloading

- gcc/rust/typecheck/rust-autoderef.cc
It is unsafe to deref raw pointers during autoderef this adds a check to stop autoderef early when we are about to try and deref pointers.
Fixes #2015
* typecheck/rust-autoderef.cc (AutoderefCycle::cycle): add check for pointers
> gccrs: Stop autoderef of raw pointer types

- gcc/rust/lang.opt
This option enables an experimental name resolution algorithm. Disabled
by default.
* lang.opt: Add -frust-name-resolution-2.0 option
> rust: Add -frust-name-resolution-2.0 option

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Non-Existent Field Extraction in Struct Pattern
variant `Foo::D` does not have a field named `b`
```rust
// https://doc.rust-lang.org/error_codes/E0026.html
fn main() {
struct Thing {
x: u32,
y: u32,
}
let thing = Thing { x: 0, y: 0 };
match thing {
Thing { x, z } => {} // error: `Thing::z` field doesn't exist
}
}
```
```bash
mahad@linux:~/Desktop/mahad/gccrs-build$ gcc/crab1 ../mahad-testsuite/E0026.rs -frust-incomplete-and-experimental-compiler-do-not-use
../mahad-testsuite/E0026.rs:11:20: error: variant Thing does not have a field named z [E0026]
11 |         Thing { x, z } => {} // error: `Thing::z` field doesn't exist
|                    ^
../mahad-testsuite/E0026.rs:11:9: error: pattern does not mention fields y
11 |         Thing { x, z } => {} // error: `Thing::z` field doesn't …
```
> [E0026] Non-Existent Field Extraction in Struct Pattern

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- The pattern has `x` fields, but the corresponding tuple variant has `y` field.
```rust
// https://doc.rust-lang.org/error_codes/E0023.html
fn main() {
enum Fruit {
Apple(u32, u32),
Pear(u32),
}
let x = Fruit::Apple(1, 2);
match x {
Fruit::Apple(a) => {} // error! : this pattern has 1 fields but the corresponding tuple variant has 2 field
_ => {}
}
}
```
```bash
mahad@linux:~/Desktop/mahad/gccrs-build$ gcc/crab1 ../mahad-testsuite/E0023.rs -frust-incomplete-and-experimental-compiler-do-not-use
../mahad-testsuite/E0023.rs:11:5: error: this pattern has 1 fields but the corresponding tuple variant has 2 field [E0023]
11 |     Fruit::Apple(a) => {}, // error!
|     ^~~~~ …
```
> [E0023] Incorrect Number of Fields in Pattern Extraction

- gcc/rust/lex/rust-lex.cc
- gcc/testsuite/rust/compile/torture/utf8_whitespaces.rs
Addresses https://github.com/Rust-GCC/gccrs/issues/2287
This pr is going to be rebased after https://github.com/Rust-GCC/gccrs/pull/2307 is merged
```
* lex/rust-lex.cc (Lexer::build_token):add check for all kinds of whitespaces
* rust/compile/torture/utf8_whitespaces.rs: New test.
```
> Fix lexer to skip utf-8 whitespaces

- gcc/testsuite/rust/compile/torture/raw_identifiers.rs
- gcc/testsuite/rust/compile/torture/utf8_identifiers.rs
Addresses https://github.com/Rust-GCC/gccrs/issues/2287
This pr is going to be rebased after https://github.com/Rust-GCC/gccrs/pull/2307 is merged
```
* rust/compile/torture/raw_identifiers.rs: New test.
* rust/compile/torture/utf8_identifiers.rs: New test.
Signed-off-by: Raiki Tamura <tamaron1203@gmail.com>
```
> Missing tests for utf-8 identifiers

- gcc/rust/typecheck/rust-casts.cc
- gcc/rust/typecheck/rust-coercion.cc
- gcc/rust/typecheck/rust-coercion.h
- gcc/rust/typecheck/rust-hir-trait-reference.h
- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/testsuite/rust/compile/issue-2330.rs
I copied swap_nonoverlapping badly from libcore which uses an unsafe
pointer case of x as *mut u8, I thought this was x as *mut T when i was
copying code form libcore this caused new infererence variables to be
introduced which actually automatically turned this swap_nonoverlapping
function to turn into a swap_nonoverlapping<u8> and lost the general
generic one in the type system context.
Rust allows for you to cast any pointer to another pointer of different
base type. The rules here are really subtle though because we need to
handle the case where we do really need to unify the types here there
are a few cases to consider but the main three are:
*u32 vs *u32 -> valid pointers match = simple coercion
*<?> vs *u8 -> inference variable unified with u8 which is valid
*T vs *u8 -> invalid …
> Fix bad generic inference on unsafe pointer casts

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- Fixes #2336
* typecheck/rust-hir-type-check-pattern.cc (emit_invalid_field_error): Refactored field error function (TypeCheckPattern::visit): called 'emit_invalid_field_error' function
> Refactored Field Error Function

- gcc/rust/lex/rust-lex.cc
- gcc/testsuite/rust/compile/bytecharstring.rs
closes #2308
```
* lex/rust-lex.cc (Lexer::parse_byte_char):add check for range of codepoint
* rust/compile/bytecharstring.rs:add test for it
```
NOTE: this pr depends on (includes commit from) PR https://github.com/Rust-GCC/gccrs/pull/2307
so please merge this after PR https://github.com/Rust-GCC/gccrs/pull/2307 is merged
> Fix lexing byte literal

- gcc/rust/ast/rust-pattern.h
- gcc/rust/parse/rust-parse-impl.h
Type hint was not propagated properly in literals, being replaced by a default `str` instead.
Needs #2340
> Fix type hint propagation

- gcc/rust/backend/rust-compile-block.cc
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-item.cc
- gcc/rust/backend/rust-compile-struct-field-expr.cc
- gcc/rust/backend/rust-compile.cc
- gcc/rust/checks/errors/privacy/rust-privacy-check.cc
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/checks/errors/privacy/rust-pub-restricted-visitor.cc
- gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/checks/lints/rust-lint-marklive.cc
- gcc/rust/checks/lints/rust-lint-scan-deadcode.h
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-type.h
- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/metadata/rust-export-metadata.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-stmt.cc
- gcc/rust/typecheck/rust-hir-type-check-struct.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-hir-type-check.cc
The pending HIR dump pass change requires some simple refactoring. These are
mainly repetitive changes (use inheritance, add missing methods to access
private fields, make life of visitor a bit easier, ...)
> Refactoring in prevision of the HIR dump changes

- gcc/testsuite/rust/compile/rust_abi.rs
* rust/compile/rust_abi.rs: New test.
> abi: Add testcase for using "Rust" as ABI string

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
A pattern for a struct fails to specify a sub-pattern for every one of the struct's fields. - pattern does not mention fields `x`, `y`
```rust
// https://doc.rust-lang.org/error_codes/E0027.html
fn main() {
struct Dog {
name: u32,
age: u32,
}
let d = Dog { name: 1, age: 8 };
// This is incorrect.
match d {
Dog { age: x } => {}
}
}
```
```rust
mahad@linux:~/Desktop/mahad/gccrs-build$ gcc/crab1 ../mahad-testsuite/E0027.rs -frust-incomplete-and-experimental-compiler-do-not-use
../mahad-testsuite/E0027.rs:13:9: error: pattern does not mention fields name [E0027]
13 |         Dog { age: x } => {}
|         ^~~
TOTAL                              :   0.00 …
```
> [E0027] struct pattern fails to specify struct's fields

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
We were using the call-expr id for the autoderef mappings but this doesn't work when the call expression itself is part of a coercion-site so this changes the code to use the call-expression function path expression for the id instead which will not be duplicated again.
Addresses #2105
* backend/rust-compile-expr.cc (CompileExpr::generate_possible_fn_trait_call): use fnexpr
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::resolve_fn_trait_call): likewise
> gccrs: fix ICE with inserting autoderef mappings

- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
- gcc/testsuite/rust/compile/issue-2105.rs
In order to setup the Output assoicated type we can rely on using generic argument bindings. So for example when we have the FnOnce trait:
```
#[lang = "fn_once"]
pub trait FnOnce<Args> {
#[lang = "fn_once_output"]
type Output;
extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
}
```
Thn we might have a function such as:
```pub fn map<R, F: FnOnce(T) -> R>(self, f: F) -> Option<R> { ... }```
This trait bound predicate of FnOnce(T) -> R we setup generics for the bound as:
```FnOnce<(T), Output=R>```
This means we can reuse our generic arguments handling to get this support.
Fixes #2105
* typecheck/rust-tyty-bounds.cc (TypeCheckBase::get_predicate_from_bound):
* util/rust-hir-map.cc (Mappings::lookup_trait_item_lang_item):
* util/rust-hir-map.h: …
> gccrs: Track fn_once output lang item properly

- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-lex.h
Addresses #2309
```
gccrs: Remove unnecessary methods of Rust::Lexer
* lex/rust-lex.cc (Lexer::build_token): Replace function call.
(Lexer::parse_string): Likewise.
(Lexer::parse_identifier_or_keyword): Likewise.
(Lexer::parse_raw_string): Likewise.
(Lexer::parse_char_or_lifetime): Likewise.
(Lexer::get_input_codepoint_length): Deleted.
(Lexer::peek_codepoint_input): Deleted.
(Lexer::skip_codepoint_input): Deleted.
* lex/rust-lex.h: Remove some methods and fields
```
> Remove unnecessary methods/fields of `Rust::Lexer`

- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-pattern.h
Minor changes in HIR interface: add missing getters, make some classes
inherit from FullVisitable.
* hir/tree/rust-hir-expr.h (class ArrayElems): Inherit from FullVisitable.
(class StructExprField): Likewise.
* hir/tree/rust-hir-item.h (class WhereClauseItem): Likewise.
(class UseTree): Likewise.
(UseTreeRebind::get_path, UseTreeRebind::get_identifier)
(UseTreeRebind::get_bind_type): New.
(UseDeclaration::get_use_tree): New.
(struct TraitFunctionDecl): Change struct to ...
(class TraitFunctionDecl): ... class.
(TraitFunctionDecl::get_where_clause): New.
(StructField::get_outer_attrs): New.
(struct TupleField): Change struct to ...
(class TupleField): ... class.
(TupleField::get_visibility, TupleField::get_outer_attrs): New.
* hir/tree/rust-hir-pattern.h (class …
> gccrs: minor HIR interface cleanup

- gcc/rust/typecheck/rust-tyty-subst.cc
Associated type binding outside of type
parameter Declaration and where Clause - [E0229](https://doc.rust-lang.org/error_codes/E0229.html) 
```rust
struct Foo<A, B>(A, B);
fn main() {
let a;
a = Foo::<A = i32, B = f32>(123f32);
// { dg-error ErrorCode("E0229") "associated type bindings are not allowed here" "" { target *-*-* } .-1 }
// { dg-error {Failed to resolve expression of function call} "" { target *-*-* } .-2 }
}
```
```rust
mahad@linux:~/Desktop/mahad/gccrs-build$ gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/type-bindings1.rs -frust-incomplete-and-experimental-compiler-do-not-use
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/type-bindings1.rs:5:15: error: associated type bindings are not allowed here [E0229]
5 |     a = Foo::<A = i32, B = …
```
> [E0229] associated type bindings error

- gcc/rust/typecheck/rust-hir-path-probe.h
Ambiguous Method Call Error - more than one method has the same prototype.
```rust
// https://doc.rust-lang.org/error_codes/E0034.html
struct Test;
trait Trait1 {
fn foo();
}
trait Trait2 {
fn foo();
}
impl Trait1 for Test { fn foo() {} }
impl Trait2 for Test { fn foo() {} }
fn main() {
Test::foo() // { dg-error "multiple applicable items in scope for: test" } 
// error, which foo() to call?
}
```
```rust
mahad@linux:~/Desktop/mahad/gccrs-build$ gcc/crab1 ../mahad-testsuite/E0034.rs  -frust-incomplete-and-experimental-compiler-do-not-use
../mahad-testsuite/E0034.rs:16:11: error: multiple applicable items in scope for: foo [E0034]
12 | impl Trait1 for Test { fn foo() {} }
|                        ~~
13 | impl Trait2 for Test { fn foo() {} }
|                        ~~
......
16 | …
```
> [E0034] Ambiguous Method Call Error

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-stmt.cc
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-pattern.h
- gcc/rust/hir/tree/rust-hir-stmt.h
- gcc/rust/hir/tree/rust-hir-type.h
- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-stmt.cc
Some more HIR cleanup.
* hir/tree/rust-hir-expr.h (BorrowExpr::is_double_borrow): New.
(StructExprStructFields::get_struct_base): New.
(MethodCallExpr::has_params): New.
(ClosureExpr::has_params): New.
(BlockExpr::get_inner_attrs): New.
(WhileLoopExpr::get_patterns): New.
(ForLoopExpr::get_pattern): New.
(IfLetExpr::get_if_block): Return ref to unique_ptr.
(IfLetExprConseqElse::get_else_block): Likewise.
(MatchExpr::get_inner_attrs): New.
* hir/tree/rust-hir-item.h (Module::get_module_name): New.
(ExternCrate::get_referenced_crate)
(ExternCrate::get_as_clause_name): New.
(UseTreeGlob::get_glob_type, UseTreeGlob::get_path): New.
(UseTreeList::get_path_type, UseTreeList::get_path)
(UseTreeList::get_trees): New.
* hir/tree/rust-hir-pattern.h …
> gccrs: HIR cleanup

- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-pattern.h
- gcc/rust/checks/lints/rust-lint-scan-deadcode.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
Fixes https://github.com/Rust-GCC/gccrs/issues/2333
```
* ast/rust-ast.h: Modify constructors of `Rust::Identifier`
* ast/rust-pattern.h: Likewise.
* hir/tree/rust-hir-item.h: Likewise.
* parse/rust-parse-impl.h (Parser::parse_macro_rules_def): Likewise.
(Parser::parse_decl_macro_def): Likewise.
(Parser::parse_macro_match_fragment): Likewise.
(Parser::parse_module): Likewise.
(Parser::parse_use_tree): Likewise.
(Parser::parse_function): Likewise.
(Parser::parse_type_param): Likewise.
(Parser::parse_type_alias): Likewise.
(Parser::parse_struct): Likewise.
(Parser::parse_struct_field): Likewise.
(Parser::parse_enum): Likewise.
(Parser::parse_enum_item): Likewise.
(Parser::parse_union): Likewise.
(Parser::parse_static_item): Likewise.
(Parser::parse_trait): Likewise. …
```
> Add location info to `Rust::Identifier`

- gcc/rust/typecheck/rust-hir-type-check-item.cc
missing foo in implementation of trait 'Foo'
```rust
// https://doc.rust-lang.org/error_codes/E0046.html
trait Foo {
fn foo();
}
struct Bar;
impl Foo for Bar {}
// error: not all trait items implemented, missing: `foo`
```
---
```rust
➜  gccrs-build gcc/crab1 -frust-incomplete-and-experimental-compiler-do-not-use ../mahad-testsuite/E0046.rs
../mahad-testsuite/E0046.rs:9:1: error: missing foo in implementation of trait ‘Foo’ [E0046]
4 |     fn foo();
|     ~~
......
9 | impl Foo for Bar {}
| ^~~~
TOTAL                              :   0.00          0.00          0.00          146k
Extra diagnostic checks enabled; compiler may run slowly.
Configure with …
```
> [E0046] Missing Items in Trait Implementation

- gcc/rust/expand/rust-macro-expand.cc
- gcc/testsuite/rust/compile/macro-issue2273.rs
> Ignore semicolon following a macro expansion in expression context

- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-lex.h
- gcc/rust/rust-session-manager.cc
- gcc/testsuite/rust/compile/broken_utf8.rs
Addresses https://github.com/Rust-GCC/gccrs/issues/2287
```
* lex/rust-lex.cc (Lexer::input_source_is_valid_utf8): New method of `Lexer`.
* lex/rust-lex.h: Likewise.
* rust-session-manager.cc (Session::compile_crate): Add error.
* rust/compile/broken_utf8.rs: New test.
```
> Add utf-8 validation for input source

- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
The parameters of any trait method must match between a trait implementation and the trait definition
```rust
fn main() {
trait Foo {
fn foo(x: u16);
fn bar(&self);
}
struct Bar;
impl Foo for Bar {
// error, expected u16, found i16
fn foo(x: i16) { }
// error, types differ in mutability
fn bar(&mut self) { }
}
}
```
```rust
➜  gccrs-build gcc/crab1 -frust-incomplete-and-experimental-compiler-do-not-use ../mahad-testsuite/E0053.rs
../mahad-testsuite/E0053.rs:12:5: error: expected ‘fn<Bar> (x u16,) -> ()’ got ‘fn (x i16,) -> ()’
4 |     fn foo(x: u16);
|     ~~
......
12 |     fn foo(x: i16) { }
|     ^~
../mahad-testsuite/E0053.rs:12:5: error: method ‘foo’ has an incompatible type for trait ‘Foo’ [E0053]
4 |     fn foo(x: u16);
|     ~~
......
12 |     fn foo(x: i16) { } …
```
> [E0053] method 'x' has an incompatible type for trait 'y'

- gcc/rust/typecheck/rust-hir-type-check-struct.cc
- gcc/testsuite/rust/compile/missing_constructor_fields.rs
Added error code for Missing Field in
struct or struct-like enum variant.
---
```rust
// https://doc.rust-lang.org/error_codes/E0063.html
struct Foo {
x: i32,
y: i32,
z: i32,
}
fn main() {
let x = Foo { x: 0 , y:1 }; // { dg-error "constructor is missing fields" }
}
```
---
```rust
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/missing_constructor_fields.rs
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/missing_constructor_fields.rs:9:13: error: constructor is missing fields [E0063]
9 |     let x = Foo { x: 0 , y:1 }; // { dg-error "constructor is missing fields" }
|             ^~~
TOTAL                              : …
```
> [E0063] constructor is missing fields

- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/testsuite/rust/compile/break-rust2.rs
- gcc/testsuite/rust/compile/const_generics_3.rs
- gcc/testsuite/rust/compile/const_generics_4.rs
- gcc/testsuite/rust/compile/not_find_value_in_scope.rs
- Refactored error message similiar to rustc [`E0425`](https://doc.rust-lang.org/error_codes/E0425.html)
---
- [`rust/compile/break-rust2.rs`](https://github.com/Rust-GCC/gccrs/blob/962364f07687e378abd892fdcc46b41ae725214e/gcc/testsuite/rust/compile/break-rust2.rs)
- [`rust/compile/const_generics_3.rs`](https://github.com/Rust-GCC/gccrs/blob/962364f07687e378abd892fdcc46b41ae725214e/gcc/testsuite/rust/compile/const_generics_3.rs)
- [`rust/compile/const_generics_4.rs`](https://github.com/Rust-GCC/gccrs/blob/962364f07687e378abd892fdcc46b41ae725214e/gcc/testsuite/rust/compile/const_generics_4.rs)
- [`rust/compile/unresolved_name.rs:`](https://github.com/Rust-GCC/gccrs/blob/962364f07687e378abd892fdcc46b41ae725214e/gcc/testsuite/rust/compile/unresolved_name.rs)
```rust
// …
```
> [E0425] Use of unresolved name

- gcc/rust/util/expected.h
Directly taken from https://github.com/TartanLlama/expected and adapted
slightly for our use case.
* util/expected.h: New file.
This type offers a type similar to `std::expected`, which is only available since C++23. It will be useful for cleaning up our error handling, chaining errors together, and easier control flow in general.
This will be used for the upcoming experimental name resolution algorithm.
> util: Add tl::expected type

- gcc/testsuite/rust/compile/name_resolution1.rs
- gcc/testsuite/rust/compile/name_resolution2.rs
- gcc/testsuite/rust/compile/name_resolution3.rs
- gcc/testsuite/rust/compile/name_resolution4.rs
- gcc/testsuite/rust/compile/name_resolution5.rs
* rust/compile/name_resolution1.rs: New test.
* rust/compile/name_resolution2.rs: New test.
* rust/compile/name_resolution3.rs: New test.
* rust/compile/name_resolution4.rs: New test.
* rust/compile/name_resolution5.rs: New test.
Co-authored-by: @GuillaumeGomez
This PR adds some interesting test cases that our name resolution already handles properly, but that the reimplementation must handle too
> nr2.0: Add complex testcases

- gcc/rust/typecheck/rust-tyty-call.cc
- gcc/testsuite/rust/compile/func2.rs
- gcc/testsuite/rust/compile/tuple_struct2.rs
- gcc/testsuite/rust/compile/wrong_no_of_parameters.rs
- Refactored argument mismatch error into one function `emit_unexpected_argument_error`.
- Changed unexpected argument message to similiar to rustc.
- You can view the same on [`compiler-explorer`](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYSAHKUcAZPAZMADl3ACNMYhAANlIAB1QFQjsGFzcPb3jE5IEAoNCWCKjYq0wbFKECJmICNPdPLh9S8oFK6oI8kPDImMsqmrqMxr72zoKimIBKS1QTYmR2DioGAGoCTHMIJhAVvABmACZSFbCd/YPJlYBaAFI97F3DlZuAdgAhG40AQRXflaZngc3idPl9XgARUGg5YrFhMQIQS6vD7fP4regEf7PPbgtYbAiIu7AgD0xOe7xW6GAV0ixBIgIOBAQeAUKyoJgYLVWVQA1hsVgd/sRgO5GARWWETJiuEKRWxBKyAO5MVkKExxOK0PCYdA3A6CiFQl6Q74caa0TgAVl4ng4WlIqE4ACUzJiFLN5phAXseKQCJozdMeSADpaAHTRLxeDQvPZ7ACckkkia40Ut%2Bk4khtAYdnF4ChAGj9AemcFgMEQKFQLDidEi5EoaB …
> [E0061]  Refactored argument mismatch error function

- gcc/rust/resolve/rust-ast-verify-assignee.h
- gcc/testsuite/rust/compile/wrong_lhs_assignment.rs
-  Added error code support for an assignment operator which was used on a non-place expression.
---
```rust
fn foo() {
1 = 3; // { dg-error "invalid left-hand side of assignment" }
}
fn main() {
foo();
}
```
---
```rust
gccrs/gcc/testsuite/rust/compile/wrong_lhs_assignment.rs:4:5: error: invalid left-hand side of assignment [E0070]
compiler exited with status 1
PASS: rust/compile/wrong_lhs_assignment.rs  (test for errors, line 4)
```
---
* resolve/rust-ast-verify-assignee.h: called error function.
* rust/compile/wrong_lhs_assignment.rs: New test.
---
> [E0070] invalid left-hand side of assignment

- gcc/rust/rust-diagnostics.cc
- gcc/rust/rust-diagnostics.h
Assuming we want to get rid of the ```RichLocation``` wrapper along with the ```Location``` wrapper, this removes a dependency on ```RichLocation```'s converting constructor (which allows ```Location``` to be implicitly cast to ```RichLocation```).
> Add ```rust_error_at``` accepting ```location_t``` and ```ErrorCode```

- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-path.h
- gcc/rust/hir/tree/rust-hir-pattern.h
- gcc/rust/hir/tree/rust-hir.h
Add one more accessor and remove some rust_assert() in accessors for unique_ptr&.
* hir/tree/rust-hir-expr.h (TypeCastExpr::get_casted_expr): Remove
assert in accessor.
(TypeCastExpr::get_type_to_convert_to): Likewise.
(CompoundAssignmentExpr::get_left_expr): Likewise.
(CompoundAssignmentExpr::get_right_expr): Likewise.
(GroupedExpr::get_expr_in_parens): Likewise.
(TupleIndexExpr::get_tuple_expr): Likewise.
(FieldAccessExpr::get_receiver_expr): Likewise.
(ClosureParam::get_pattern): Likewise.
(ClosureParam::get_type): Likewise.
(ExprType::get_return_type): Likewise.
(IfLetExpr::get_scrutinee_expr): Likewise.
(MatchArm::get_guard_expr): Likewise.
(MatchExpr::get_scrutinee_expr): Likewise.
* hir/tree/rust-hir-item.h (TypeParam::get_type): Likewise.
(SelfParam::get_type): …
> gccrs: minor HIR cleanup

- gcc/rust/ast/rust-ast.h
- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/hir/tree/rust-hir-full-decls.h
- gcc/rust/rust-session-manager.h
Several lines add some warning, it clutters the compiler output, makes error message harder to find/read when compiling with a high number of cores.
> Fix several warnings

- contrib/mklog.py
- contrib/prepare-commit-msg
(Has been submitted for review upstream: https://inbox.sourceware.org/gcc-patches/20230707070727.658031-1-dkm@kataplop.net/)
Consider Signed-Off-By lines as part of the ending of the initial
commit to avoid having these in the middle of the log when the
changelog part is injected after.
This is particularly usefull with:
$ git gcc-commit-mklog --amend -s
that can be used to create the changelog and add the Signed-Off-By line.
Also applies most of the shellcheck suggestions on the
prepare-commit-msg hook.
> mklog: handle Signed-Off-By, minor cleanup

- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/testsuite/rust/compile/torture/intrinsics-3.rs
- Refactored Error Message similiar to rustc.
- See on [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYSupRwBk8DJgAcu4ARpjEIACcpAAOqAqEdgwubh5ecQlJAv6BISzhkTFWmDbJQgRMxASp7p5c3iVlAhVVBLnBYRHRlpXVtekNvW0d%2BYXRAJSWqCbEyOwcAKQATADMYGCLAKwAQlSYTASzmBABBMQBicgKE9sAIosaAIKPT5iqBBEMANQry6bmAC0ZwuDCuf1%2BAHYdq9vnDvlQfvxUBBbqsdt8APSY74RYgkEDfEwMYilVDABh4ABemHQ3xBlzwyARxOanl%2BADYNMjFlzXotIQ9nq9Ed8WEwAqioTDnvCiWCmPtpbC5fDkajFuiVXCBUKXoKOFNaJwtrxPBwtKRUJwAEpmAjfBQzOaYX5rHikAiaQ1TADWIGWAA4AHSQjmBjTLDRRDlRQNbLbSY0cSRm71Wzi8BQgDSe71TOCwGCIFCoFixOgRciUNDlyuRYDIZDEBSAhTMWIKBCoCxYABuTMwADU8JgAO4AeVijE4HpotE%2BLcooXToQCVQAnrPeGvmMQNxPQtpSl7uLxa2xBBOGLQtxbeFhQiZgE4xLRs2fSFhxUZxPev3gpJlH2mAfpa …
> [E0093] Declaration of unknown intrinsic function

- gcc/rust/checks/errors/rust-feature-gate.cc
- gcc/testsuite/rust/compile/changed_intrinsics.rs
- Added Errorcode Support for unstable features.
---
```rust
extern "rust-intrinsic" { // { dg-error "intrinsics are subject to change." "" { target *-*-* }  }
fn foo(); // { dg-error "unrecognized intrinsic function: .foo." }
}
fn main() {
unsafe {
foo(); // { dg-error "unrecognized intrinsic function: .foo." }
}
}
```
---
```rust
/gccrs/gcc/testsuite/rust/compile/feature_extern_types.rs:2:5: error: extern types are experimental. see issue 43467 <https://github.com/rust-lang/rust/issues/43467> for more information. add `#![feature(extern_types)]` to the crate attributes to enable. [E0658]
compiler exited with status 1
```
---
* checks/errors/rust-feature-gate.cc (FeatureGate::gate): called error function.
* rust/compile/changed_intrinsics.rs: …
> [E0658] Use of unstable feature

- gcc/rust/Make-lang.in
- gcc/rust/resolve/rust-rib.cc
- gcc/rust/resolve/rust-rib.h
This class adds a basic Rib class for the new name resolution algorithm.
It uses `optional` and `expected` return types in order to try and
improve error handling in these new passes.
* Make-lang.in: Add `rust-rib.cc` object.
* resolve/rust-rib.cc: New file.
* resolve/rust-rib.h: New file.
Needs #2317 and #2327
> nr2.0: Add basic Rib class

- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
This data structure replaces our existing scopes and allows for multiple
name resolution passes to insert definitions or look up names at different
stages of the pipeline. The documentation goes into detail about how the
data structure works, and how the source's hierarchy is preserved
throughout the pipeline.
The class is templated to enforce specific behavior based on the namespace
the scope map targets.
* resolve/rust-forever-stack.h: New file.
* resolve/rust-forever-stack.hxx: New file.
Needs #2327 and #2317
> nr2.0: Add `ForeverStack` data structure.

- gcc/rust/lang.opt
- gcc/rust/rust-session-manager.cc
- gcc/rust/rust-session-manager.h
Add a new option to crab1 cli to accept crate type. This version of the argument only accept a single crate type. Rustc accepts a comma separated list of crate types but this might require a litle more work for gcc.
> cli: Add frust-type option

- gcc/rust/expand/rust-proc-macro.cc
- libgrust/libproc_macro/proc_macro.cc
- libgrust/libproc_macro/proc_macro.h
- libgrust/libproc_macro/registration.h
- libgrust/libproc_macro/tokenstream.cc
Add a callback registration symbol into the proc macro library so the compiler can register it's own lexing/parsing functions on load. Register a conversion from string callback in order to implement the `FromStr` trait on `TokenStream`.
Fixes #973
> proc_macro: Add from string implementation

- gcc/rust/util/rust-token-converter.cc
- libgrust/libproc_macro/ident.cc
- libgrust/libproc_macro/ident.h
- libgrust/libproc_macro/rust/bridge/ident.rs
Use FFIString in Ident structure rather that a raw pointer and a length, this will reduce the size of the code dealing with raw pointers. Which should prevent some error.
Fixes #2246
> Change Ident structure

- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/compile/proc_macro_attribute_crate_type.rs
- gcc/testsuite/rust/compile/proc_macro_crate_type.rs
- gcc/testsuite/rust/compile/proc_macro_derive_crate_type.rs
- gcc/testsuite/rust/compile/proc_macro_derive_malformed.rs
Add attribute check for proc macros declarations.
Requires #2435 
Fixes #2437
> Proc macro attribute check

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/break1.rs
- gcc/testsuite/rust/compile/break_continue_outside_loop.rs
- gcc/testsuite/rust/compile/continue1.rs
- A loop keyword (break or continue) was used outside of a loop.
- Refactored error description similiar to rustc.
---
```rust
// https://doc.rust-lang.org/error_codes/E0268.html
fn boo() {
continue; // { dg-error ".continue. outside of a loop" }
break; // { dg-error ".break. outside of a loop or labeled block" }
}
fn main() {
boo()
}
```
---
```rust
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/break_continue_outside_loop.rs
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/break_continue_outside_loop.rs:4:5: error: ‘continue’ outside of a loop [E0268]
4 |     continue;       // { dg-error ".continue. outside of a loop"}
|     ^~~~~~~~
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/break_continue_outside_loop.rs: …
```
> [E0268] break or continue used outside of loop

- gcc/rust/parse/rust-parse-impl.h
Use ```token_id_is_keyword``` to shorten a large list of cases
> Improve keyword check while parsing a macro match

- libgrust/libproc_macro/literal.cc
- libgrust/libproc_macro/literal.h
- libgrust/libproc_macro/rust/bridge/literal.rs
- libgrust/libproc_macro/rust/bridge/token_stream.rs
- libgrust/libproc_macro/tokenstream.cc
- libgrust/libproc_macro/tokenstream.h
Two remaining structures in the rust interface were still using raw string pointer and length to communicate with the C++ library throught extern C functions. Using FFIString instead allow us to reduce the scope of potential errors using those raw pointers.
> Increase FFIString usage

- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/testsuite/rust/compile/non_member_const.rs
- Refactored Error message similiar to rustc.
---
```rust
// https://doc.rust-lang.org/error_codes/E0323.html
fn main() {
trait Foo {
type N;
}
struct Bar;
impl Foo for Bar {
const N : u32 = 0; // { dg-error "item .N. is an associated const, which does not match its trait .Foo." }
// error: item `N` is an associated const, which doesn't match its
//        trait `<Bar as Foo>`
}
}
```
---
```rust
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/non_member_const.rs:11:5: error: item 'N' is an associated const, which does not match its trait 'Foo' [E0323]
compiler exited with status 1
PASS: rust/compile/non_member_const.rs  (test for errors, line 11)
PASS: rust/compile/non_member_const.rs (test for excess errors)
```
---
* …
> [E0323] Implemented associated const, expected another trait

- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/testsuite/rust/compile/abi-vardaic.rs
- Added error code support for using variadic parameters used on Non-C ABI function.
- Fixes #2382
---
```rust
// https://doc.rust-lang.org/error_codes/E0045.html
fn main() {
extern "Rust" {
fn foo(x: u8, ...); // { dg-error "C-variadic function must have C or cdecl calling convention" }
}
}
```
---
```rust
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/abi-vardaic.rs                           
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/abi-vardaic.rs:5:9: error: C-variadic function must have C or cdecl calling convention [E0045]
5 |         fn foo(x: u8, ...); // { dg-error "C-variadic function must have C or cdecl calling convention" }
|         ^~
Time variable …
```
> [E0045] Variadic Parameters Used on Non-C ABI Function

- gcc/rust/ast/rust-ast.h
From various discussions we decided it would be better to remove the node id from identifiers since the latter is almost useless, it's sole usage was with proc macros but this has been circumvented.
Requires #2300 
Fixes #2458
> Remove NodeId from identifiers

- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/compile/proc_macro_attribute_non_function.rs
- gcc/testsuite/rust/compile/proc_macro_derive_non_function.rs
- gcc/testsuite/rust/compile/proc_macro_non_function.rs
Emit an error when a procedural macro attribute is placed on a non function item.
Fixes #2459
> Proc macro non function errors

- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/testsuite/rust/compile/proc_macro_attribute_crate_type.rs
- gcc/testsuite/rust/compile/proc_macro_attribute_private.rs
- gcc/testsuite/rust/compile/proc_macro_crate_type.rs
- gcc/testsuite/rust/compile/proc_macro_derive_crate_type.rs
- gcc/testsuite/rust/compile/proc_macro_derive_private.rs
- gcc/testsuite/rust/compile/proc_macro_private.rs
- gcc/testsuite/rust/compile/proc_macro_pub_function.rs
- gcc/testsuite/rust/compile/proc_macro_pub_module.rs
Proc macro crates cannot have any public function but proc macros. Proc macros should be public.
Requires #2435 
Fixes #2442
> Add privacy check to `proc_macro`, `proc_macro_derive` and `proc_macro_attribute` attributes.

- .github/workflows/bootstrap.yml
This should prevent the github-provided runners from spending all their time on bootstrap builds
> Prevent multiple bootstrap builds from running at once

- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/testsuite/rust/compile/issue-2478.rs
- gcc/testsuite/rust/compile/non_member_const.rs
When the resulting trait item is in an error state this means the underlying fields will be null.
Fixes #2478
> gccrs: fix ICE when we have unimplemented/invalid trait items

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/issue-2477.rs
> gccrs: fix ice when function is outside of context

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/testsuite/rust/compile/issue-2479.rs
> gccrs: Fix ICE by adding check for enum candidate's

- gcc/rust/ast/rust-ast-fragment.cc
- gcc/rust/ast/rust-ast-fragment.h
- gcc/rust/ast/rust-macro.h
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/expand/rust-macro-expand.cc
* ast/rust-ast-fragment.cc (Fragment::create_empty): New.
* ast/rust-ast-fragment.h (MacroTranscriberFunc): New.
* ast/rust-macro.h (MacroRulesDefinition): Use MacroTranscriberFunc.
* expand/rust-macro-builtins.cc
(MacroBuiltin::builtin_transcribers): likewise.
(MacroBuiltin::assert_handler): Return optional.
(MacroBuiltin::file_handler): Likewise.
(MacroBuiltin::column_handler): Likewise.
(MacroBuiltin::include_bytes_handler): Likewise.
(MacroBuiltin::include_str_handler): Likewise.
(MacroBuiltin::compile_error_handler): Likewise.
(MacroBuiltin::concat_handler): Likewise.
(MacroBuiltin::env_handler): Likewise.
(MacroBuiltin::cfg_handler): Likewise.
(MacroBuiltin::include_handler): Likewise.
(MacroBuiltin::line_handler): Likewise.
(MacroBuiltin::stringify_handler): …
> gccrs: use tl::optional for macro transcribers

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
---
```rust
const FOO: u32 = return 0; // error: return statement outside of function body
fn main() {}
```
---
```rust
➜  gccrs-build gcc/crab1  ../mahad-testsuite/E0572.rs
../mahad-testsuite/E0572.rs:1:18: error: return statement outside of function body [E0572]
1 | const FOO: u32 = return 0; // error: return statement outside of function body
|                  ^~~~~~
../mahad-testsuite/E0572.rs:1:1: error: expected ‘u32’ got ‘<tyty::error>’
1 | const FOO: u32 = return 0; // error: return statement outside of function body
| ^~~~~      ~~~   ~~~~~~
TOTAL                              :   0.00          0.00          0.00          146k
Extra diagnostic checks enabled; …
```
> [E0572] return is outside of function context

- gcc/rust/Make-lang.in
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-name-resolution-context.cc
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.h
- name resolution 2.0: Add base for Resolver data structure
- top-level: Add base `TopLevel` visitor
This commit adds a first simple `Resolver` data structure, which will
be used by all passes of the name resolution to store definitions and access
them. Namely, it contains a few instances of `ForeverStack`, for each
namespace we will be using.
The `TopLevel` pass takes care of collecting definitions, placing them
in the proper namespaces, and making them accessible for later resolution
passes like `Early` and `Late`. It is meant to be run in a fixed point
fashion, as import resolution, macro resolution and macro expansion
may generate multiple new definitions.
> name resolution 2.0: Add base Resolver and TopLevel pass

- gcc/rust/util/rust-unicode.cc
Addresses https://github.com/Rust-GCC/gccrs/issues/2379
depends on PR https://github.com/Rust-GCC/gccrs/pull/2425
```
gccrs: Normalize Hangul to NFC
* util/rust-unicode.cc (decomp_cano): Decompose Hangul.
(sort_cano): Fix bounds check.
(recomp): use `compose_hangul`.
(compose_hangul): Compose Hangul.
(rust_utf8_normalize_test): Add tests.
Signed-off-by: Raiki Tamura <tamaron1203@gmail.com>
```
More tests will be added in another PR.
See: Sample Code for Hangul Algorithms
https://www.unicode.org/versions/Unicode15.0.0/ch03.pdf
> Normalize Hangul

- gcc/rust/Make-lang.in
- gcc/rust/resolve/rust-default-resolver.cc
- gcc/rust/resolve/rust-default-resolver.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.h
- nr2.0: Add DefaultResolver visitor
- nr2.0: Use DefaultResolver for TopLevel
Needs #2456 so you can skip the first two commits
This PR adds a base visitor framework to the new name resolution framework which will serve all three of our resolving passes. It uses it in `TopLevel` and is also necessary for `Early`
> nr2.0: Add DefaultVisitor class

- gcc/rust/expand/rust-macro-builtins.cc
- gcc/testsuite/rust/compile/issue-2421_str.rs
When the load_file_bytes() fails to open the file, it emits an error but
returns an empty vector (as if the file is empty).
Instead, return a tl::optional nullopt in case of error and an empty
vector in case of an empty file.
fixes #2421
* expand/rust-macro-builtins.cc
(load_file_bytes): Return a tl::optional.
(MacroBuiltin::include_byte_handler): Adjust and check file was
correctly opened.
(MacroBuiltin::include_str_handler): Likewise.
* rust/compile/empty_file: New test.
* rust/compile/issue-2421_str.rs: New test.
> gccrs: better handling of incorrect file loading in include_* builtin macros

- gcc/rust/typecheck/rust-unify.cc
- gcc/testsuite/rust/compile/arrays1.rs
- gcc/testsuite/rust/compile/bad_type1.rs
- gcc/testsuite/rust/compile/bad_type2.rs
- gcc/testsuite/rust/compile/const_generics_6.rs
- gcc/testsuite/rust/compile/deadcode_err1.rs
- gcc/testsuite/rust/compile/deadcode_err2.rs
- gcc/testsuite/rust/compile/func1.rs
- gcc/testsuite/rust/compile/func3.rs
- gcc/testsuite/rust/compile/func4.rs
- gcc/testsuite/rust/compile/func5.rs
- gcc/testsuite/rust/compile/generics1.rs
- gcc/testsuite/rust/compile/generics2.rs
- gcc/testsuite/rust/compile/generics3.rs
- gcc/testsuite/rust/compile/implicit_returns_err1.rs
- gcc/testsuite/rust/compile/implicit_returns_err2.rs
- gcc/testsuite/rust/compile/implicit_returns_err3.rs
- gcc/testsuite/rust/compile/implicit_returns_err4.rs
- gcc/testsuite/rust/compile/issue-1152.rs
- gcc/testsuite/rust/compile/issue-2477.rs
- gcc/testsuite/rust/compile/mismatched-types.rs
- gcc/testsuite/rust/compile/reference1.rs
- gcc/testsuite/rust/compile/stmt_with_block_err1.rs
- gcc/testsuite/rust/compile/traits1.rs
- gcc/testsuite/rust/compile/traits2.rs
- gcc/testsuite/rust/compile/tuple_mismatch.rs
- gcc/testsuite/rust/compile/tuple_struct3.rs
- This errorcode emits when there are mismatch types between lhs & rhs of assignment operator & refactored message.
---
```rust
// ErrorCode::E0308
fn main() {
fn plus_one(x: i32) -> i32 { 
x + 1 
}
plus_one("Not a number");       // { dg-error "mismatched types, expected .i32. got .& str." }
let x: f32 = "Not a float";     // { dg-error "mismatched types, expected .f32. got .& str." }
}
```
---
```rust
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/mismatched-types.rs
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/mismatched-types.rs:7:14: error: mismatched types, expected ‘i32’ got ‘& str’ [E0308]
4 |     fn plus_one(x: i32) -> i32 {
|                 ~
......
7 |     plus_one("Not a number");       // { dg-error …
```
> [E0308] mismatch types on both sides of assignment Operator

- gcc/rust/checks/errors/rust-feature-gate.cc
- gcc/testsuite/rust/compile/feature.rs
Added ErrorCode support for use of unknown
feature.
---
```rust
// ErrorCode - E0635
#![feature(AA)] //{ dg-error "unknown feature .AA." }
#![feature(iamcrabby)] // { dg-error "unknown feature .iamcrabby." }
#![feature(nonexistent_gccrs_feature)] // { dg-error "unknown feature .nonexistent_gccrs_feature." }
fn main() {}
```
---
```rust
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/feature.rs
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/feature.rs:1:12: error: unknown feature ‘AA’ [E0635]
1 | #![feature(AA)] //{ dg-error "unknown feature .AA." }
|            ^~
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/feature.rs:2:12: error: unknown feature ‘iamcrabby’ [E0635]
2 | #![feature(iamcrabby)] // { dg-error "unknown feature …
```
> [E0635] Use of Unknown feature.

- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/testsuite/rust/compile/undeclared_label.rs
- Refactored error message to print more userfriendly message and added error code.
---
```rust
// ErrorCode::E0426
fn resolve_label_continue() -> () {
loop {
continue 'a; // { dg-error "use of undeclared label .a. in .continue." }
}
}
fn resolve_label_break() -> () {
loop {
break 'crabby; // { dg-error "use of undeclared label .crabby. in .break." }
}
}
fn main() {
resolve_label_continue();
resolve_label_break();
}
```
---
```rust
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/undeclared_label.rs:5:18: error: use of undeclared label ‘a’ in ‘continue’ [E0426]
5 |         continue 'a; // { dg-error "use of undeclared label .a. in .continue." }
|                  ^~
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/undeclared_label.rs:10:15: error: use …
```
> [E0426] Use of undeclared label

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-macro.h
- gcc/rust/resolve/rust-default-resolver.cc
- gcc/rust/resolve/rust-default-resolver.h
- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/rust/resolve/rust-early-name-resolver-2.0.h
- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-name-resolution-context.cc
- gcc/rust/resolve/rust-rib.cc
- gcc/rust/resolve/rust-rib.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/rust-session-manager.cc
- gcc/testsuite/rust/compile/name_resolution10.rs
- gcc/testsuite/rust/compile/name_resolution6.rs
- gcc/testsuite/rust/compile/name_resolution7.rs
- gcc/testsuite/rust/compile/name_resolution8.rs
- gcc/testsuite/rust/compile/name_resolution9.rs
This adds a base visitor for resolving macro invocations in the new name resolution 2.0 algorithm. Needs #2469 and #2456
> nr2.0: Add base for Early name resolution

- gcc/rust/typecheck/rust-tyty-subst.cc
- [`gcc/testsuite/rust/compile/expected_type_args2.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/expected_type_args2.rs)
- [`gcc/testsuite/rust/compile/expected_type_args3.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/expected_type_args3.rs)
- [`gcc/testsuite/rust/compile/traits12.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/traits12.rs)
* typecheck/rust-tyty-subst.cc (SubstitutionRef::get_mappings_from_generic_args): Added errorcode.
> [E0107] Wrong number of generic argument

- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-feature-gate.cc
- [`gcc/testsuite/rust/compile/const10.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/const10.rs)
- [`gcc/testsuite/rust/compile/changed_intrinsics.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/changed_intrinsics.rs)
- [`gcc/testsuite/rust/compile/feature_intrinsics.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/feature_intrinsics.rs)
- [`gcc/testsuite/rust/compile/feature_rust_attri1.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/feature_rust_attri1.rs)
- [`gcc/testsuite/rust/compile/feature_rust_attri0.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/feature_rust_attri0.rs)
```bash …
```
> [E0658] Use of mutable reference in constant functions.

- gcc/rust/checks/errors/rust-const-checker.cc
- [`gcc/testsuite/rust/compile/diagnostic_underline.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/diagnostic_underline.rs)
- [`gcc/testsuite/rust/compile/const-issue1440.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/const-issue1440.rs)
- [`gcc/testsuite/rust/compile/const1.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/const1.rs)
- [`gcc/testsuite/rust/compile/const3.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/const3.rs)
---
* checks/errors/rust-const-checker.cc (ConstChecker::check_function_call): Added errorcode.
> [E0015] Use of non-const inside const

- gcc/rust/util/rust-common.h
This semicolon produces several warning in each TU the header file is included in.
> Fix a warning about extra semicolon

- gcc/rust/typecheck/rust-hir-type-check.cc
---
```rust
fn main() {
let arr = [];
// { dg-error "type annotations needed" "" { target *-*-* } .-1 }
}
```
---
```bash
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/array_empty_list.rs
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/array_empty_list.rs:2:15: error: type annotations needed [E0282]
2 |     let arr = [];
|               ^
TOTAL                              :   0.00          0.00          0.00          146k
Extra diagnostic checks enabled; compiler may run slowly.
Configure with --enable-checking=release to disable checks.
```
---
- [`gcc/testsuite/rust/compile/array_empty_list.rs`](https://github.com/Rust- …
> [E0282] type annotations needed

- gcc/rust/backend/rust-compile.cc
- gcc/testsuite/rust/compile/arrays2.rs
- This error code was already added in this PR https://github.com/Rust-GCC/gccrs/pull/2494. But this error code is also valid for this mismatch array case.
---
```rust
// { dg-additional-options "-w" }
fn main() {
let array: [i32; 5] = [1, 2, 3];
// { dg-error "mismatched types, expected an array with a fixed size of 5 elements, found one with 3 elements" "" { target *-*-* } .-1 }
}
```
```bash
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/arrays2.rs
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/arrays2.rs:3:27: error: mismatched types, expected an array with a fixed size of 5 elements, found one with 3 elements [E0308]
3 |     let array: [i32; 5] = [1, 2, 3];
|                           ^
Time variable …
```
> [E0308] array misamatch types

- gcc/rust/Make-lang.in
- gcc/rust/rust-lang.cc
- gcc/rust/util/rust-punycode.cc
- gcc/rust/util/rust-punycode.h
Addresses https://github.com/Rust-GCC/gccrs/issues/2287 , https://github.com/Rust-GCC/gccrs/issues/305
Depends on https://github.com/Rust-GCC/gccrs/pull/2489
Added an punycode encoding function, which will be used in the v0 mangling scheme.
Decoder is not necessary because we do not need to demangle symbols.
```
* Make-lang.in: Add rust-punycode.o.
* rust-lang.cc (run_rust_tests): Add selftest.
* util/rust-punycode.cc: New file.
* util/rust-punycode.h: New file.
Signed-off-by: Raiki Tamura <tamaron1203@gmail.com>
```
> Implement punycode encoding

- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/testsuite/rust/compile/abi-options1.rs
```rust
extern "foobar" {
// { dg-error "invalid ABI: found .foobar." "" { target *-*-* } .-1 }
fn printf(s: *const i8, ...);
}
pub extern "baz" fn test() {}
// { dg-error "invalid ABI: found .baz." "" { target *-*-* } .-1 }
// extern "Rust" fn foo() {} // OK!
```
---
```bash
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/abi-options1.rs     
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/abi-options1.rs:1:1: error: invalid ABI: found ‘foobar’ [E0703]
1 | extern "foobar" {
| ^~~~~~
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/abi-options1.rs:6:5: error: invalid ABI: found ‘baz’ [E0703]
6 | pub extern "baz" fn test() {}
|     ^~~~~~
Time variable                                   usr           sys …
```
> [E0703] Use of Invalid ABI

- gcc/rust/backend/rust-compile-base.cc
- gcc/testsuite/rust/compile/attr_deprecated_2.rs
---
- [`gcc/testsuite/rust/compile/attr_deprecated_2.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/attr_deprecated_2.rs)
---
* backend/rust-compile-base.cc: Added ErrorCode.
* rust/compile/attr_deprecated_2.rs: Updated comment to pass the testcase.
> [E0541] Use of unknown meta item

- gcc/rust/typecheck/rust-casts.cc
- gcc/testsuite/rust/compile/all-cast.rs
- gcc/testsuite/rust/compile/bad_as_bool_char.rs
- gcc/testsuite/rust/compile/cast1.rs
- gcc/testsuite/rust/compile/cast4.rs
- gcc/testsuite/rust/compile/cast5.rs
- Added errorcodes according to different conditions and updated error message according to type casting type.
These are all the error codes related to casting in rustc.
- [`E0054`](https://doc.rust-lang.org/error_codes/E0054.html) to `bool`
- [`E0604`](https://doc.rust-lang.org/error_codes/E0604.html) to `char` other than `u8`
- [`E0605`](https://doc.rust-lang.org/error_codes/E0605.html) Invalid cast between standard data structures, needs rust `standard` library.
- [`E0606`](https://doc.rust-lang.org/error_codes/E0606.html)  incompatible cast - only `primitive` casts.
- [`E0607`](https://doc.rust-lang.org/error_codes/E0607.html) cast of `thin` & `fat pointers` - not supported in gccrs.
- [`E0620`](https://doc.rust-lang.org/error_codes/E0620.html) cast to `unsized` type.
- …
> `[E0054-E0604-E0620-E0606]` TypeCasting ErrorCodes

- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
Adjust the HIR dump for IfExpr and IfExprConseqElse
to use visit_field() and factor common part.
* hir/rust-hir-dump.h (do_ifexpr): New.
* hir/rust-hir-dump.cc (Dump::do_ifexpr): New.
(Dump::visit): Use do_ifexpr and visit_field
> gccrs: Adjust HIR dump for IfExpr and IfExprConseqElse

- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/rust-session-manager.cc
This avoids a use-after-free when reaching the recursion limit.
* expand/rust-macro-expand.h: Keep optional references for last_def
and last_invoc.
* expand/rust-macro-expand.cc (MacroExpander::expand_invoc): Store
optional references.
* rust-session-manager.cc (Session::expansion): Use tl::optional's APIs
for better checking.
> macro-expand: Keep optional references to last_{def, invoc}

- gcc/rust/backend/rust-mangle.cc
Fix https://github.com/Rust-GCC/gccrs/issues/2545
```
gccrs: Fix legacy mangling to use Unicode escape
* backend/rust-mangle.cc (legacy_mangle_name): Use Unicode escape
```
Result of mangling:
input:
```rust
pub fn あ() {}
mod Module {
pub fn function_日本語_русский() {}
}
fn main() {
あ();
Module::function_日本語_русский();
}
```
output:
```asm (AMD64)
...
_ZN1a7$u3042$17hae3ccdfa81d818e4E:
.cfi_startproc
...
_ZN1a6Module79function_$u65e5$$u672c$$u8a9e$_$u440$$u443$$u441$$u441$$u43a$$u438$$u438$$u439$17hae3ccdfa81d818e4E:
.cfi_startproc
...
main:
.LFB2:
.cfi_startproc
...
```
Demangle result:
```
_ZN1a6Module79function_$u65e5$$u672c$$u8a9e$_$u440$$u443$$u441$$u441$$u43a$$u438$$u438$$u439$17hae3ccdfa81d818e4E
=> a::Module::function_日本語_русскиий::hae3ccdfa81d818e4 …
```
> gccrs: Fix legacy mangling to use Unicode escape

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
We hit an assertion with range based iterators here. This code was used to solve complex generics such as:
struct Foo<X,Y>(X,Y);
impl<T> Foo<T, i32> {
fn test<Y>(self, a: Y) { }
}
The impl item will have the signiture of:
fn test<T,Y> (Foo<T, i32> self, a:Y)
So in the case where we have:
let a = Foo(123f32, 456);
a.test<bool>(true);
We need to solve the generic argument T from the impl block by infering the arguments there and applying them so that when we apply the generic argument bool we dont end up in the case of missing number of generics.
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): remove hack
> gccrs: remove horrible hack in solving complex generics on impl blocks

- gcc/rust/hir/rust-hir-dump.cc
visit_field() correctly handles empty unique_ptr<> and displays "none".
> gccrs: Cleanup HIR dump

- gcc/rust/backend/rust-compile-base.cc
We do extra checking after the fact here to ensure its a valid candidate and in the case there is only one candidate lets just go for it.
* backend/rust-compile-base.cc (HIRCompileBase::resolve_method_address): use the single candidate
> gccrs: simplify matching possible candidates

- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/rust/backend/rust-mangle.cc
- gcc/rust/typecheck/rust-tyty.h
We can endup with duplicate symbol names for different intrinsics with our current hash setup. This adds in the mappings and extra info to improve hash uniqueness.
* backend/rust-compile-intrinsic.cc (check_for_cached_intrinsic): simplify this cached intrinsic check
* backend/rust-mangle.cc (legacy_mangle_item): use new interface
* typecheck/rust-tyty.h: new managle helper
> gccrs: improve name mangling hash

- gcc/rust/util/make-rust-unicode.py
Addresses this comment by @CohenArthur 
> I think this is a very good first implementation of the script :) For future maintainability, I think it would be helpful to add types to the script so we can run it with mypy. But this is already very good, don't change it in this PR
https://github.com/Rust-GCC/gccrs/pull/2425#discussion_r1275951153
Python code was typechecked with mypy 1.4
```
gccrs: Type annotation for make-unicode-data.py
* util/make-rust-unicode.py: Add type annotation
```
> Add type annotation to make-rust-unicode-data.py

- gcc/rust/rust-diagnostics.cc
We cannot use `free` on a pointer allocated through `new[]`, and this
causes an ASAN failure. This fixes it by using `xcalloc` instead of
`new[]` when creating description buffers for our error codes.
* rust-diagnostics.cc: Switch from new[] to xcalloc
> diagnostics: Fix mismatch between new[] and free

- gcc/rust/backend/rust-compile-base.cc
- gcc/testsuite/rust/compile/inline_2.rs
Inline attribute takes one argument, but
more than one argument was found.
- [`gcc/testsuite/rust/compile/inline_2.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/inline_2.rs)
```rust
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/inline_2.rs:2:3: error: unknown inline option
2 | #[inline(A)] // { dg-error "unknown inline option" }
|   ^~~~~~
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/inline_2.rs:5:3: error: invalid number of arguments [E0534]
5 | #[inline(A, B)] // { dg-error "invalid number of arguments" }
|   ^~~~~~
|   expected one argument
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/inline_2.rs:8:3: error: invalid number of arguments [E0534]
8 | #[inline()] // { dg-error "invalid number of arguments" }
| …
```
> [E0534] inline attribute was malformed

- gcc/rust/rust-diagnostics.cc
- gcc/rust/rust-diagnostics.h
Added method of binding ErrorCode & rich location to parser and expansion errors.
- Fixes https://github.com/Rust-GCC/gccrs/issues/2385
- Depends on https://github.com/Rust-GCC/gccrs/pull/2531 & https://github.com/Rust-GCC/gccrs/pull/2527
Currently, the `Error` struct only supports simple location to `parser` and `expansion` errors. Updated the code to handle all cases for `errorcode` and `parsing` errors. Now, we can rich-loation to `Error` struct by using ampersand `&` operator.
The `rust_error_at` function immediately emits the error. But in some contexts we wish to collect them and discard them. Now, we can use errorcode and rich location in `Error` struct's context.
--- 
* rust-diagnostics.cc (va_constructor): Added constructor for all possible cases. …
> Support for `rich-loc` & `errorcode` in parser & expansion errors

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/bad_inner_doc.rs
---
- [`gcc/testsuite/rust/compile/bad_inner_doc.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/bad_inner_doc.rs)
```rust
// ErrorCode - E0753
pub fn main ()
{
//! inner doc allowed
let _x = 42;
// { dg-error "expected outer doc comment, inner doc" "" { target *-*-* } .+1 }
//! inner doc disallowed
mod module
{
/*! inner doc allowed */
/// outer doc allowed
// { dg-error "expected outer doc comment, inner doc" "" { target *-*-* } .+1 }
/*! but inner doc not here */
mod x { }
}
}
```
```bash
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/bad_inner_doc.rs:6:3: error: expected outer doc comment, inner doc ('//!' or '/*!') only allowed at start of item and before any outer attribute or doc ('#[', '///' or '/**') [E0753] …
```
> [E0753] Use of inner doc comment in invalid context

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/auto_trait_invalid.rs
- Updated `add_error` to `rust_error_at`
---
- [`gcc/testsuite/rust/compile/auto_trait_invalid.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/auto_trait_invalid.rs)
---
* parse/rust-parse-impl.h (Parser::parse_trait): added errorcode.
* rust/compile/auto_trait_invalid.rs: New comment.
---
> [E0380] Use of auto trait with method or associated item

- gcc/rust/backend/rust-compile-base.cc
- gcc/testsuite/rust/compile/inline_2.rs
The inline attribute only supports two arguments:
- `always`
- `never`
All other arguments given to the inline attribute will always return this error.
- [`gcc/testsuite/rust/compile/inline_2.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/inline_2.rs)
```rust
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/inline_2.rs
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/inline_2.rs:2:3: error: invalid argument, ‘inline’ attribute only accepts ‘always’ or ‘never’ [E0535]
2 | #[inline(A)] // { dg-error "unknown inline option" }
|   ^~~~~~
|   unknown inline option
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/inline_2.rs:5:3: error: invalid number of arguments
5 | #[inline(A, B)] // { dg-error "invalid …
```
> [E0535] Unknown argument given to inline attribute

- gcc/rust/ast/rust-pattern.h
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/match5.rs
- gcc/testsuite/rust/compile/pattern-struct.rs
Checking if pattern has items, before returing solves ICE. Added error code and rich location.
- Also, fixes https://github.com/Rust-GCC/gccrs/issues/2430
---
* ast/rust-pattern.h: No need of assertion, we are handling it.
* resolve/rust-early-name-resolver.cc (EarlyNameResolver::visit): Added check which emits error instead of using assertion.
* typecheck/rust-hir-type-check-pattern.cc (TypeCheckPattern::visit): Added rich location and error code.
* rust/compile/match5.rs: Updated comment for dejagnu.
* rust/compile/pattern-struct.rs: New test for ICE.
> [E0164] Neither tuple struct nor tuple variant used as a pattern

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/testsuite/rust/compile/issue-1589.rs
- gcc/testsuite/rust/compile/trait-cycle.rs
This errorcode & message emits when cycle
detected when computing the super predicates
of `x` which requires computing the super
predicates of `y`, which again requires
computing the super predicates of `x`,
completing the cycle.
- [`gcc/testsuite/rust/compile/issue-1589.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/issue-1589.rs)
```rust
~/gccrs/gcc/testsuite/rust/compile/trait-cycle.rs:1:5: error: cycle detected when computing the super predicates of ‘FirstTrait’ [E0391]
1 | pub trait FirstTrait: SecondTrait {}
|     ^~~~~
~/gccrs/gcc/testsuite/rust/compile/trait-cycle.rs:3:5: error: cycle detected when computing the super predicates of ‘SecondTrait’ [E0391]
3 | pub trait SecondTrait: FirstTrait {}
|     ^~~~~
```
---
* …
> [E0391] Detected type dependency cycle

- gcc/rust/backend/rust-mangle.cc
- gcc/rust/lex/rust-lex.cc
- gcc/rust/resolve/rust-ast-resolve-toplevel.h
- gcc/rust/rust-session-manager.cc
- gcc/rust/util/rust-canonical-path.h
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-mapping-common.h
~~Depends on https://github.com/Rust-GCC/gccrs/pull/2533~~
Please review the last commit
```
* backend/rust-mangle.cc (v0_add_identifier): Added punycode encoding
(v0_mangle_item): Likewise.
* resolve/rust-ast-resolve-toplevel.h: fix typo
* rust-session-manager.cc (Session::load_extern_crate): fix typo
* util/rust-canonical-path.h: fix typo
* util/rust-hir-map.cc (NodeMapping::get_error): fix typo
(Mappings::Mappings): fix typo
* util/rust-mapping-common.h (UNKNOWN_CREATENUM): fix typo
(UNKNOWN_CRATENUM): Change 0 to UINT32_MAX
```
I manually checked the following cases for `add_v0_identifier`:
```
_あ to u5___x7t
my_crate__ to 10my_crate__
6foobar
foobar to 6foobar
あ to u3l8j
_あいう to u7___x7tgi
ああああ to u6l8jaaa
```
> Add punycode encoding to v0 mangling

- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/testsuite/rust/compile/issue-2479.rs
- Added last variant name, errorcode & rich location. for enum candidates.
- Improved by this issue https://github.com/Rust-GCC/gccrs/issues/2479
---
- [`gcc/testsuite/rust/compile/issue-2479.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/issue-2479.rs)
```rust
test.rs:7:26: error: expected type, found variant of ‘Dragon::Born’ [E0573]
7 | fn oblivion() -> Dragon::Born { // error!
|                          ^~~~
|                          not a type
test.rs:7:1: error: failed to resolve return type
7 | fn oblivion() -> Dragon::Born { // error!
| ^~
test.rs:20:26: error: expected type, found variant of ‘Wizard::Saruman’ [E0573]
20 |     fn wizard(_: Wizard::Saruman); // error!
|                          ^~~~~~~
|                          not a type
```
--- …
> [E0573] Something other than type was used

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/generics13.rs
- Added more user-friendly message & hint for fixing ordering
- [`gcc/testsuite/rust/compile/generics13.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/generics13.rs)
```rust
➜  gccrs-build gcc/crab1 /home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/generics13.rs
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/generics13.rs:1:12: error: invalid order for generic parameters: lifetime parameters must be declared prior to type and const parameters
1 | struct Foo<A, 'a>; // { dg-error "invalid order for generic parameters: lifetimes should always come before types" }
|            ^
|            reorder the parameters: lifetimes, then consts and types
Time variable                                   usr           sys …
```
> Invalid order of generic parameters

- gcc/rust/backend/rust-compile-type.cc
- gcc/testsuite/rust/compile/iterators1.rs
There is a case where some generic types are holding onto inference variable pointers directly. So this gives the backend a chance to do one final lookup to resolve the type.
This now allows us to compile a full test case for iterators but there is still one miscompilation in here which results in a segv on O2 and bad result on -O0.
* backend/rust-compile-type.cc (TyTyResolveCompile::visit): do a final lookup
* rust/compile/iterators1.rs: New test.
> gccrs: Fix compilation of types which hold onto dangling infer vars

- gcc/rust/backend/rust-tree.cc
- gcc/rust/backend/rust-tree.h
This should help towards integrating ```backend/rust-tree.c``` and ```backend/rust-tree.h``` with gengtype, as an eventual step towards stripping down some of the data structures we have vestigially from the c++ frontend.
> Fork ```c++``` resorting methods

- gcc/rust/typecheck/rust-tyty.cc
- gcc/testsuite/rust/compile/issue-1725-2.rs
Added rich location and error code.
- [`gcc/testsuite/rust/compile/issue-1725-2.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/issue-1725-2.rs)
```rust
~/gccrs/gcc/testsuite/rust/compile/issue-1725-2.rs:28:9: error: type mismatch, expected ‘i32’ but got ‘f32’ [E0271]
16 |     type Output = f32;
|     ~~~~ 
......
23 | pub fn foo<T: core::ops::Add<Output = i32>>(a: T) -> i32 {
|               ~~~~
......
28 |     foo(123f32);
|         ^~~~~~
|         expected i32, found f32
~/gccrs/gcc/testsuite/rust/compile/issue-1725-2.rs:28:9: error: bounds not satisfied for f32 ‘Add’ is not satisfied [E0277]
23 | pub fn foo<T: core::ops::Add<Output = i32>>(a: T) -> i32 {
|               ~~~~
......
28 |     foo(123f32);
|         ^~~~~~
```
---
* …
> [E0271] Type mismatch between associated type trait.

- gcc/rust/rust-diagnostics.cc
- gcc/rust/rust-diagnostics.h
- gcc/rust/rust_error_codes.def
Currently, gccrs using the const `rich_location &`, and then using the cast to convert it to the functions which was used to emit the errors, having the overloaded is good, similiar to other frontends.
---
* rust-diagnostics.cc (rust_be_error_at): Added overload function. (rust_error_at): non-const `rich_location *` function.
* rust-diagnostics.h (rust_error_at): Implementation of overloaded function. (rust_be_error_at): likewise.
* rust_error_codes.def: Added GNU license.
---
> diagnostics: Added non-const `rich_location *` function

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/match4.rs
A tuple struct or tuple variant was used in a pattern as if it were a struct or struct variant.
- [`gcc/testsuite/rust/compile/match4.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/match4.rs)
```rust
/home/mahad/Desktop/mahad/gccrs/gcc/testsuite/rust/compile/match4.rs:12:9: error: tuple variant ‘C’ written as struct variant [E0769]
12 |         Foo::C { a } => {}
|         ^~~
|         use the tuple variant pattern syntax instead C(_)
```
---
* typecheck/rust-hir-type-check-pattern.cc (TypeCheckPattern::visit): Added error code and rich location.
* rust/compile/match4.rs: Updated new error commment.
> [E0769] Use of struct or tuple variant in struct or struct variant

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty.h
I included a ```TODO```, since I'm pretty sure ```TypeCheckExpr::resolve_fn_trait_call``` should be providing an implicit self argument.
> Fix invalid call to ```vector::front``` in ```TypeBoundPredicate``` constructors

- .github/workflows/docker.yml
This should get rid of some [docker build warnings](https://github.com/powerboat9/gccrs/actions/runs/6044879809)
> Bump ```docker/build-push-action``` to v4

- gcc/rust/hir/rust-ast-lower-pattern.cc
- gcc/testsuite/rust/compile/let_alt.rs
- This error code is emitted by `rustc 1.49.0`, but not emitted by `rustc -nightly`.
- I have updated according to `rustc 1.49.0`, as we are targeting `rustc 1.49.0` testsuite.
- See the difference here [`godbolt`](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYSAzKUcAZPAZMADl3ACNMYhAAJlIAB1QFQjsGFzcPb3jE5IEAoNCWCKjYq0wbFKECJmICNPdPLh9S8oFK6oI8kPDImMsqmrqMxr72zoKimIBKS1QTYmR2DioGAGoWJkCISZWAUgB2ACEdjQBBFfOV%2BgIVgH0mXb2nW/udrwARFa5o16PTi5WAPQAh4HFboYAAWkixBIu2i0SIcUumAAbphaCsxARIsxsSs4kwCNjiAwFJjiJgVgxUNcxLRUAB3TDoHbwuHfNn7UH9YCYa4AKghgv5Dw%2BADoIVxRccTvs3jKONNaJwAKy8TwcLSkVCcABKZmuClm80prK8PFIBE0iumAGsJNExZIAJxcPYADjd8JVKo00Xd7v0nEk6ut2s4vAUIA0lut0zgsBgiBQqBYcTokXIlDQaYzUWAyGQxAUEIU …
> Top level or-patterns are not allowed let binding

- gcc/rust/backend/rust-mangle.cc
- gcc/rust/lex/rust-input-source.h
- gcc/rust/lex/rust-lex.cc
- gcc/rust/util/rust-attributes.cc
- gcc/rust/util/rust-codepoint.h
- gcc/rust/util/rust-punycode.cc
- gcc/rust/util/rust-unicode.cc
- gcc/rust/util/rust-unicode.h
Fixes https://github.com/Rust-GCC/gccrs/issues/2548
```
gccrs: Check function names with no_mangle.
* backend/rust-compile-base.cc (HIRCompileBase::setup_fndecl): Add parameter.
* backend/rust-compile-base.h: Likewise.
* backend/rust-compile-implitem.cc (CompileTraitItem::visit): Change type of parameter.
* backend/rust-compile-item.cc (CompileItem::visit): Likewise.
* lex/rust-input-source.h: Move constants to rust-codepoint.h
* util/rust-codepoint.h (struct Codepoint): Add is_ascii method.
* util/rust-punycode.cc (extract_basic_string): Use it.
* lex/rust-lex.cc (Lexer::parse_byte_char): Likewise.
* backend/rust-mangle.cc (legacy_mangle_name): Likewise.
* util/rust-unicode.cc (is_ascii_only): New function.
* util/rust-unicode.h (is_ascii_only): Likewise.
```
Error …
> `#[no_mangle]` should not be applied to non-ASCII items

- Dockerfile
This *should* fix our docker builds. It looks like ```rust:latest``` [upgraded](https://github.com/docker-library/official-images/commit/10f7c0abd9f0f04360d30a83344ae7d8ea03bb86#diff-6591a398dd9843ff51ada710b7ff40291be32d8edd66a833f1a5de00d24d7640L16-R26) from debian 10 to debian 12 shortly before our docker builds started failing with ```cannot replace to directory /var/lib/buildkit/runc-overlayfs/cachemounts/buildkit596534011/usr/share/doc/libcrypt-dev with file```.
> Bump our docker build's debian base image version to match ```rust:latest```'s

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/type-if.rs
> Improve type checking for if expressions

- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/testsuite/rust/compile/privacy1.rs
- gcc/testsuite/rust/compile/privacy3.rs
- gcc/testsuite/rust/compile/privacy4.rs
- gcc/testsuite/rust/compile/privacy5.rs
- Use of private item outside scope
- Updated error message.
* checks/errors/privacy/rust-privacy-reporter.cc (PrivacyReporter::check_for_privacy_violation): Added errorcode & richlocation.
* rust/compile/privacy1.rs: Updated comment for dejagnu.
* rust/compile/privacy3.rs: likewise.
* rust/compile/privacy4.rs: likewise.
* rust/compile/privacy5.rs: likewise.
> [E0603] Use of private item outside scope

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/issue-2029.rs
- [`gcc/testsuite/rust/compile/issue-2029.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/issue-2029.rs)
```rust
~/gccrs/gcc/testsuite/rust/compile/issue-2029.rs:8:9: error: expected tuple struct or tuple variant, found function ‘fn (_ usize,) -> Foo{Foo (0:bool)}’ [E0532]
8 |         foo(x)
|         ^~~
|         a tuple struct with a similar name exists
```
---
* typecheck/rust-hir-type-check-pattern.cc (TypeCheckPattern::visit): Added rich location & error code.
* rust/compile/issue-2029.rs: Updated for dejagnu testcase.
---
> [E0532] Pattern arm did not match expected kind.

- gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/generics7.rs
- gcc/testsuite/rust/compile/generics8.rs
- gcc/testsuite/rust/compile/issue-925.rs
- Added errorcode & rich location.
- [`gcc/testsuite/rust/compile/generics7.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/generics7.rs)
- [`gcc/testsuite/rust/compile/issue-925.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/issue-925.rs)
```rust
../mahad-testsuite/E0592.rs:28:7: error: duplicate definitions with name ‘bar’ [E0592]
9 |     fn bar(self) -> isize {
|     ~~ 
|     duplicate definitions for bar
......
21 |     fn bar(self) -> T {
|     ~~ 
|     duplicate definitions for bar
......
28 |     a.bar();
|       ^~~
```
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): Added rich location and errorcode.
* rust/compile/generics7.rs: Updated comment.
* …
> [E0592] method or associated functions already defined with same names

- gcc/rust/backend/rust-compile-expr.cc
- gcc/testsuite/rust/execute/torture/iter1.rs
We were massing the match scruitinee expression as a way to access the result of the expression. This is wrong and needs to be stored in a temporary otherwise it will cause the code to be regnerated for each time it is used. This is not an issue in the case where the expression is only used once.
Fixes #1895
> Iterators WORKING

- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/expand/rust-proc-macro.cc
- gcc/rust/expand/rust-proc-macro.h
- gcc/rust/metadata/rust-extern-crate.cc
- gcc/rust/metadata/rust-extern-crate.h
- gcc/rust/metadata/rust-imports.cc
- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/rust/resolve/rust-early-name-resolver-2.0.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.h
- gcc/rust/rust-session-manager.cc
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
> Name resolve proc macros

- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/expand/rust-proc-macro.cc
- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
Proc macro are resolved but not expanded. This PR allows the code to properly retrieve the macro definition in order for it to be expanded.
Requires #2496
> Retrieve proc macro definition

- gcc/rust/ast/rust-ast.cc
- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/expand/rust-cfg-strip.cc
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.cc
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/rust-session-manager.cc
- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/rust/util/rust-attribute-values.h
- gcc/rust/util/rust-attributes.cc
- gcc/rust/util/rust-hir-map.cc
Maybe controversial changes, review carefully and consider all implications, this is meant to remove raw attribute values. Hopefully this will make the code less prone to typos.
> Unify raw attribute values

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/cfg2.rs
- gcc/testsuite/rust/compile/issue-2139.rs
- gcc/testsuite/rust/compile/issue-2190-1.rs
- gcc/testsuite/rust/compile/method1.rs
Added new error message, rich location and error code.
- [`gcc/testsuite/rust/compile/cfg2.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/cfg2.rs)
- [`gcc/testsuite/rust/compile/issue-2139.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/issue-2139.rs)
- [`gcc/testsuite/rust/compile/issue-2190-1.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/issue-2190-1.rs)
- [`gcc/testsuite/rust/compile/method1.rs`](https://github.com/Rust-GCC/gccrs/blob/master/gcc/testsuite/rust/compile/method1.rs)
---
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): Added new error message, rich location and error code.
* rust/compile/cfg2.rs: Updated according …
> [E0599] Failed to resovle method implementation

- gcc/rust/backend/rust-compile-intrinsic.cc
As discussed in https://github.com/Rust-GCC/gccrs/pull/2612. The `ctx` argument was unused so I removed it.
> Remove unused `ctx` argument in `make_unsigned_long_tree` function

- gcc/rust/backend/rust-builtins.cc
- gcc/rust/backend/rust-compile-intrinsic.cc
This pull request adds the `copy`, `likely` and `unlikely` intrinsics.
> Add intrinsics `copy` and `likely`

- gcc/rust/rust-backend.h
- gcc/rust/rust-gcc.cc
Since rust doesn't have complex types, these functions can be removed
> Remove unused complex number support

- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/testsuite/rust/compile/assume.rs
I've been having trouble getting this to work so far, optimizations don't seem to be taking the assumption into account. This *might* change after gcc upstream is merged in, but there's probably something off with my code.
> Add ```assume``` intrinsic

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-extern.h
- gcc/rust/backend/rust-compile-implitem.cc
- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/rust/backend/rust-compile-item.cc
- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/typecheck/rust-coercion.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
Fix subsititions -> substitutions
* backend/rust-compile-base.cc (HIRCompileBase::compile_function):
Fix typo in substitutions.
(HIRCompileBase::resolve_method_address): Likewise.
* backend/rust-compile-extern.h (CompileExternItem::visit):
Likewise.
* backend/rust-compile-implitem.cc (CompileTraitItem::visit):
Likewise.
* backend/rust-compile-intrinsic.cc (maybe_override_ctx):
Likewise.
* backend/rust-compile-item.cc (CompileItem::visit): Likewise.
* backend/rust-compile-resolve-path.cc
(HIRCompileBase::query_compile): Likewise.
* typecheck/rust-coercion.cc (TypeCoercionRules::do_coercion):
Likewise.
* typecheck/rust-hir-type-check-item.cc
(TypeCheckItem::ResolveImplBlockSelfWithInference): Likewise.
* typecheck/rust-hir-type-check-path.cc (TypeCheckExpr::visit): …
> gccrs: trivial typo fix.

- libgrust/libproc_macro/bridge.rs
- libgrust/libproc_macro/bridge/ffistring.rs
- libgrust/libproc_macro/bridge/group.rs
- libgrust/libproc_macro/bridge/ident.rs
- libgrust/libproc_macro/bridge/literal.rs
- libgrust/libproc_macro/bridge/punct.rs
- libgrust/libproc_macro/bridge/span.rs
- libgrust/libproc_macro/bridge/token_stream.rs
- libgrust/libproc_macro/group.rs
- libgrust/libproc_macro/ident.rs
- libgrust/libproc_macro/lib.rs
- libgrust/libproc_macro/literal.rs
- libgrust/libproc_macro/punct.rs
- libgrust/libproc_macro/span.rs
- libgrust/libproc_macro/token_stream.rs
The license text was missing in rust files producing the libproc_macro interface to the libproc_macro_internal library.
> Add license text to libproc_macro rust interface

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-type.cc
- gcc/rust/rust-backend.h
- gcc/rust/rust-gcc.cc
- gcc/rust/typecheck/rust-tyty-call.cc
- gcc/rust/typecheck/rust-tyty.h
Fix varadic -> variadic
* backend/rust-compile-expr.cc (CompileExpr::visit): Fix typo in varIadic.
* backend/rust-compile-type.cc (TyTyResolveCompile::visit): Likewise.
* rust-backend.h (function_type_varadic): Rename into ...
(function_type_variadic): ... this.
* rust-gcc.cc (function_type_varadic): Rename into ...
(function_type_variadic): ... this.
* typecheck/rust-tyty-call.cc (TypeCheckCallExpr::visit): Likewise.
* typecheck/rust-tyty.h (is_varadic): Renamed into ...
(is_variadic): ... this.
> gccrs: Minor typo fix

- gcc/rust/typecheck/rust-tyty-call.cc
- gcc/testsuite/rust/compile/variadic.rs
There are some certain rust types must be cast before passing them to a variadic function, because of arcane ABI rules dictated by the C standard. To fix the error, cast the value to the type specified by the error message.
---
* typecheck/rust-tyty-call.cc (TypeCheckCallExpr::visit): Added ErrorCode & more fixit hints.
* rust/compile/variadic.rs: Added new checks.
---
> [E0617] Attempt for invalid type variable in `variadic` function

- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
Add simple debug wrapper to dump HIR nodes on stderr.
Similar to what we already have for AST.
* hir/rust-hir-dump.cc (Dump::debug): New.
(debug): New.
* hir/rust-hir-dump.h (debug): New.
> gccrs: Add debug helper to dump HIR

- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-toplevel.h
- gcc/rust/util/rust-canonical-path.h
Fix #2631 
```
* util/rust-canonical-path.h: Add new segment kind for inherent impl.
* resolve/rust-ast-resolve-item.cc (ResolveItem::visit): Use it.
* resolve/rust-ast-resolve-toplevel.h: Use it.
```
> Fix CanonicalPath for impl

- gcc/rust/rust-session-manager.cc
When an error was emitted during the cfg strip pass by the crate loader, it was ignored and the error state propagated until another pass (name resolver).
Fixes #2638
> Fix ICE when emitting an error during cfg strip

- gcc/rust/expand/rust-macro-builtins.cc
Addresses #2358
* expand/rust-macro-builtins.cc (MacroBuiltin::include_str_handler): Comment removed
(MacroBuiltin::env_handler): Comment removed
(MacroBuiltin::cfg_handler): Comment removed
(MacroBuiltin::line_handler): Comment removed
- \[X] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[X] Read contributing guidlines
- \[X] `make check-rust` passes locally
- \[ ] Run `clang-format`
Removed unnecessary "empty vector" comments
> Remove unnecessary "empty vector" comments

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-extern.h
Fix a typo and merge 2 if clauses using the same condition.
* backend/rust-compile-expr.cc (CompileExpr::visit): Merge 2 if clauses.
* backend/rust-compile-extern.h: Fix typo in comment.
> gccrs: minor changes (typo and minor refactor)

- gcc/rust/backend/rust-compile-context.h
- gcc/rust/backend/rust-mangle.cc
- gcc/rust/backend/rust-mangle.h
- gcc/rust/hir/tree/rust-hir-item.h
Addresses https://github.com/Rust-GCC/gccrs/issues/2635
Depends on https://github.com/Rust-GCC/gccrs/pull/2633
Implemented mangling of basic paths.
Traits and generic ADTs cannot be mangled yet
I will add tests later.
```rust
#[lang = "sized"]
pub trait Sized {}
impl<T: Sized> T {}
struct S<T> {
a: T,
}
impl S<i32> {
fn a() {}
}
fn generic_func<T>(_: T) {}
fn main() {
generic_func::<S<usize>>(S { a: 1 });
}
```
```
...
crab1: note: Start mangling: <d::S::<i32>>::a
crab1: note: => _RNvMC5crateNtC1d1S1a
crab1: note: Start mangling: <d::S::<i32>>::a
crab1: note: => _RNvMC5crateNtC1d1S1a
crab1: note: Start mangling: d::main
crab1: note: => _RNvC1d4main
crab1: note: Added builtin lang_item: sized for S<usize>
crab1: note: Start mangling: d::generic_func
crab1: note: => …
```
> Initial implementation of v0 mangling

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/match_break.rs
Stop nullable expr parsing when there is a comma.
Fixes #2657
> Fix parse mut ref

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/parse_pub_unit_type.rs
Unit types could not be parsed correctly when made public.
Fixes #2648
> Fix pub unit type parsing

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/parse_generic_path_expr.rs
Fixes #2652 
Generic parsing failed due to some token that had not been split yet.
> Fix expression segment parsing

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/range_from_expr_for_loop.rs
- gcc/testsuite/rust/compile/while_break_expr.rs
`RangeFromExpr` were not parsed correctly in for loop.
Fixes #2660
Fixes #2658
> Fix RangeFromExpr parsing in for loop

- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/macro57.rs
- gcc/testsuite/rust/compile/macro_rules_macro_rules.rs
This fix allows the user to use the name `macro_rules` for it's macros.
Fixes #2651
> Accept `macro_rules` name for a macro rule.

- gcc/rust/ast/rust-macro.h
- gcc/testsuite/rust/compile/macro-issue2653.rs
A recent issue highlighted a bad behavior with macro match follow set rules, this PR fixes it.
Fixes #2653
> Fix macro fragment follow set

- gcc/rust/backend/rust-mangle.cc
- gcc/testsuite/rust/compile/v0-mangle1.rs
depends on https://github.com/Rust-GCC/gccrs/pull/2615
Added tests for v0 mangling.
I will continue implementing v0 later and will add more tests.
```
* backend/rust-mangle.cc (v0_identifier): Fix broken encoding.
(v0_scope_path): Modify paramter.
(v0_path): Fix namespace for modules.
* rust/compile/v0-mangle1.rs: New test.
```
> Add tests for v0 mangling

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/closure_in_closure.rs
Fix a the parsing of a closure in another closure without a space lead to the lexer creating an OR token.
Fixes #2656
> Fix closure in closure parsing

- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-item.h
- gcc/rust/ast/rust-macro.h
> Create base class ```AssociatedItem```

- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-expr.h
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/expand/rust-derive-clone.cc
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
Adds suport for labelled blocks up to compile (where it bails). Resolves  #2688
> 2688 labelled block

- MAINTAINERS
- contrib/gcc-changelog/git_commit.py
- contrib/gcc_update
- libgrust/ChangeLog
Asking for a review of the patch itself, but I will be sending it upstream in a later version of [this patchset](https://gcc.gnu.org/pipermail/gcc-rust/2023-September/001222.html)
> libgrust: Add changelog, maintainers

- gcc/rust/ast/rust-item.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/issue-2665.rs
> Parse const with no value

- gcc/rust/ast/rust-pattern.h
Overridden virtual methods were not marked as such.
> Fix overridden virtual method modifier

- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir.cc
> Remove obsolete HIR::BorrowExpr::double_borrow

- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-item.h
Refactoring some part of the AST.
> Ast refactor

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-item.h
- gcc/rust/expand/rust-cfg-strip.cc
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/hir/rust-ast-lower-extern.h
- gcc/rust/metadata/rust-export-metadata.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/testsuite/rust/compile/extern_c_named_variadic.rs
- gcc/testsuite/rust/compile/parse_variadic_function.rs
- gcc/testsuite/rust/compile/pattern_variadic.rs
- gcc/testsuite/rust/execute/torture/named_variadic.rs
Parse variadic functions.
This version of the PR modifies the way variadic are stored in the ast. Variadic were previously handled at function level, but this makes the parser a bit ugly. This PR suggest keeping variadic informations as a special parameter instead. It requires a lot of work to reflect this change at all level of the compiler. Many passes consider the number of arguments without checking for variadicity, therefore, this PR creates a big pile of ICE as of [c6d9843](https://github.com/Rust-GCC/gccrs/pull/2701/commits/c6d984301f88b315137b61cb91a0053d5e3e0f46).
Alternative to #2704
Fixes #2664 
Fixes #2700
> Parse variadic functions

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-mangle.cc
- gcc/rust/util/rust-mapping-common.h
- gcc/testsuite/rust/compile/v0-mangle2.rs
Addresses https://github.com/Rust-GCC/gccrs/issues/2635
Implement v0-mangling for closures with reference to RFC.
https://rust-lang.github.io/rfcs/2603-rust-symbol-name-mangling-v0.html#closures-and-closure-environments
After this PR is merged, I will work on mangling generic functions.
To do so, I will refactor `CanonicalPath`s to extract type info from them.
* backend/rust-compile-expr.cc (CompileExpr::generate_closure_function): Fix reference to node.
* backend/rust-mangle.cc (struct V0Path): Modified to accept closures.
(v0_crate_path): Modified to accept closures.
(v0_closure): New function to mangle closures.
(v0_path): Modified to accept closures
* util/rust-mapping-common.h (UNKNOWN_NODEID): Change to UINT32_MAX.
(UNKNOWN_HIRID): Change to UINT32_MAX. …
> v0-mangle closures

- gcc/rust/lex/rust-lex.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/tuple_float_index.rs
Fix a tricky case with lexer floating point disambiguation.
Requires #2694 
Fixes #2663
> Fix more tuple indices

- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-item.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/trait_pub_type.rs
We shall be able to parse public trait items even if those will be rejected during the AST validation pass later. This PR introduces some changes for associated trait types.
Fixes #2666
> Fix pub type parsing in trait

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-path.h
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-path.cc
- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-rib.h
- ast: Change *Path nodes API
- rib: Add Namespace enum
- forever-stack: Fix basic get logic
- foreverstack: Specialize `get` for Namespace::Labels
- forever stack: Fix resolve_path signature
- forever stack: Improve resolve_path implementation
- foreverstack: Add `to_canonical_path` method
- foreverstack: Add `to_rib` method
This PR introduces the necessary changes from #2620 in order to make late name resolution possible. Cherry-picked, cleaned up and all changelog'ed up.
> Add ForeverStack APIs for Name Resolution 2.0

- gcc/rust/expand/rust-proc-macro.cc
Bootstrap was failing because the vector did not allocate the internal buffer and was holding a null pointer.
Commit to fixup is b71fd2afa831
* expand/rust-proc-macro.cc (generate_proc_macro_decls_symbol): Resize the vector and initialize it with dummy data before changing it.
> fixup: Ensure buffer allocation for bootstrap

- gcc/rust/checks/errors/rust-ast-validation.cc
- gcc/rust/checks/errors/rust-ast-validation.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/auto_trait_invalid.rs
- gcc/testsuite/rust/compile/auto_trait_super_trait.rs
- gcc/testsuite/rust/compile/generic_auto_trait.rs
Some constructs are forbidden in rust with auto traits such as generic arguments and super traits. Rust code containing such construct should be rejected and the compiler should emit an error.
> Auto trait AST validation

- gcc/rust/checks/errors/rust-ast-validation.cc
- gcc/testsuite/rust/compile/non_foreign_variadic_function.rs
Variadic regular functions were recently added in the parser as they should be rejected in the ast validation pass. Those are now rejected in the ast validation pass.
Fixes #2712
> Reject regular variadic functions

- gcc/rust/checks/errors/rust-ast-validation.cc
- gcc/rust/checks/errors/rust-ast-validation.h
- gcc/testsuite/rust/compile/const_generics_8.rs
- gcc/testsuite/rust/compile/empty_union.rs
Unions with zero fields are forbidden.
> Add AST union validation

- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/issue-2650-1.rs
- gcc/testsuite/rust/compile/issue-2650-2.rs
Fixes issue #2650 
The parser now parses ASYNC functions.
* parse/rust-parse-impl.h (Parser::parse_item):Added ASYNC case.
(Parser::parse_vis_item):Added a switch case to handle ASYNC.
* rust/compile/issue-2650.rs: New test.
Signed-off-by : M V V S Manoj Kumar <mvvsmanojkumar@gmail.com>
> Added support to Parse ASYNC function

- gcc/rust/Make-lang.in
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
- gcc/rust/resolve/rust-name-resolution-context.cc
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- ctx: Add Labels ForeverStack to the resolver.
- nr2.0: Add base for late name resolution
- toplevel: Use DefaultResolver for Function
- nr2.0: Store mappings in NameResolutionContext
- late: Start setting up builtin types
- late: Start storing mappings properly in the resolver
Needs #2739
> Add base for late name resolution 2.0

- gcc/rust/ast/rust-item.h
- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/rust/resolve/rust-early-name-resolver-2.0.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.h
- early: Resolve paths properly
- toplevel: Add comment about running the collector twice
- ast: Add NodeId to UseTree base class
- early: Move `use` declaration resolving to TopLevel
- toplevel: Resolve `use` declarations
Needs #2740
Needs #2739
> Add `use` declaration resolution

- gcc/rust/ast/rust-item.h
- gcc/rust/checks/errors/rust-ast-validation.cc
- gcc/rust/checks/errors/rust-ast-validation.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/unsafe_module.rs
GCCRS does not allow unsafe module with it's parser even though the code shall be rejected at a later stage.
> Unsafe module

- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-item.h
- gcc/rust/checks/errors/rust-ast-validation.cc
- gcc/rust/checks/errors/rust-ast-validation.h
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/util/rust-common.h
- gcc/testsuite/rust/compile/const_async_function.rs
- gcc/testsuite/rust/compile/const_trait_fn.rs
> Ast validation trait const

- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/rust/resolve/rust-early-name-resolver.h
Many visit functions in the early name resolver are just plain old traversal visit functions like the ones from the default visitor. Makes early name visitor inherit from the default visitor in order to avoid traversal duplication.
> Make early name resolver inherit from default one

- gcc/testsuite/rust/compile/name_resolution11.rs
- gcc/testsuite/rust/compile/name_resolution12.rs
- gcc/testsuite/rust/compile/name_resolution13.rs
- gcc/testsuite/rust/execute/torture/name_resolution.rs
Local variables and functions or global variables have different resolution when binded to a variable. This was not covered before, even though it was handled by the new name resolution. This commit highlight this behavior from the new name resolution mechanism.
Fixes #2730
> Add test for binding name resolution scope

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-item.h
- gcc/rust/checks/errors/rust-ast-validation.cc
- gcc/rust/expand/rust-cfg-strip.cc
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/hir/rust-ast-lower-implitem.h
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-stmt.h
- gcc/rust/resolve/rust-default-resolver.cc
- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/compile/functions_without_body.rs
Change the function definition to have a clear optional body. Change the AST validation pass to check for free or associated functions without a body.
> Make function body optional and reject invalid functions during AST validation

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/util/rust-abi.cc
- gcc/rust/util/rust-abi.h
Fixes issue #2768
* backend/rust-compile-base.cc (HIRCompileBase::setup_abi_options): Renamed `WIN64` to `WIN_64`
* util/rust-abi.cc (get_abi_from_string): Likewise
(get_string_from_abi): Likewise
* util/rust-abi.h (enum ABI): Likewise
Thank you for making Rust GCC better!
If your PR fixes an issue, you can add "Fixes #issue_number" into this
PR description and the git commit message. This way the issue will be
automatically closed when your PR is merged. If your change addresses
an issue but does not fully fix it please mark it as "Addresses #issue_number"
in the git commit message.
Here is a checklist to help you with your PR.
- \[x] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see …
> Renamed `WIN64` to `WIN_64`

- gcc/rust/checks/errors/rust-feature.cc
- gcc/rust/checks/errors/rust-feature.h
- gcc/testsuite/rust/compile/sized-stub.rs
This should allow code such as
```rust
#![feature(lang_items)]
#![feature(no_core)]
#![no_core]
#[lang = "sized"]
trait Sized {}
```
to compile.
> Allow enabling ```lang_items``` and ```no_core``` features

- gcc/rust/resolve/rust-default-resolver.cc
- gcc/rust/resolve/rust-default-resolver.h
The default resolver put some scope in place but mostly has traversal functions similar to the default ast visitor, making it inherit from the default visitor allows us to avoid code duplication.
> Make default resolver inherit from default visitor

- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-expand-visitor.h
Many visit functions in the expand visitor simply visit their components like the default visitor. Making the expand visitor inherit from the default visitor allows us to keep all visitor in sync without having to change every visitor.
> Make expand visitor inherit from default visitor

- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/expand/rust-cfg-strip.cc
- gcc/rust/expand/rust-cfg-strip.h
Make cfg stripper inherit from the default visitor.
> Change cfg stripper to use default visitor

- gcc/rust/checks/errors/borrowck/rust-bir-builder-internal.h
- gcc/rust/checks/errors/borrowck/rust-bir-place.h
- gcc/rust/checks/errors/borrowck/rust-borrow-checker.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-path.h
- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-tyty.h
Sending them separatelly to not clutter the later bigger PRs.
For all commits:
> Minor changes needed for borrowck

- gcc/rust/checks/errors/rust-ast-validation.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/issue-2767.rs
Fixes #2778
* parse/rust-parse-impl.h (Parser::parse_trait_impl_item): Handled `async` similar to `const` (Parser::parse_pattern): clang-format.
Thank you for making Rust GCC better!
If your PR fixes an issue, you can add "Fixes #issue_number" into this
PR description and the git commit message. This way the issue will be
automatically closed when your PR is merged. If your change addresses
an issue but does not fully fix it please mark it as "Addresses #issue_number"
in the git commit message.
Here is a checklist to help you with your PR.
- \[x] `make …
> Handle `async` qualifier inside trait

- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-type.h
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-ast-lower-base.h
- gcc/rust/hir/rust-ast-lower-implitem.h
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/rust/hir/rust-ast-lower-type.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
> Borrowck ast lifetimes

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/typecheck/rust-tyty-call.cc
- gcc/rust/typecheck/rust-tyty-cmp.h
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/rust/typecheck/rust-unify.cc
#2770 folowup @CohenArthur requested (needs rebase)
> TyTy: Remove deprecated FnDef API

- gcc/rust/lex/rust-lex.cc
- gcc/testsuite/rust/compile/issue-2187.rs
- gcc/testsuite/rust/execute/torture/issue-2187.rs
If newline strings are encountered while lexing, the lexer now handles newline characters by incrementing current line number. This provides correct line number when displaying errors. If the lexer encounters end of file before string end, then it will use the start of the string as the location to an report error.
Fixes #2187
> Handle newlines during string parsing while lexing

- gcc/rust/checks/errors/rust-ast-validation.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/const_trait_fn.rs
- gcc/testsuite/rust/compile/issue-2785.rs
Fixes #2785 
I opened this pull request because I have some doubts.
So I created a switch-case for `async` keyword when reading trait items. I generate an error (I know its not the right way) and return nullptr.
The returning nullptr generates additional errors that results in the test case failing.
The correct way to generate error would be to add check in `ASTValidation::visit (AST::TraitFunctionDecl &decl)` function but it won't work right now because we never made the AST node.
To solve this problem I think we need to implement `parse_trait_async()` and to implement this function we need to make an AST node `AST::TraitItemAsync`.
But this node will be pretty much useless as `async` isn't allowed inside traits so I don't know if this is the right way to approach this problem …
> Handle `async` functions in traits

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/issue-2788.rs
Fixes #2788 
I am not sure how to test this as we don't have to check for error. I was reading up on `async` functions usage and I think Tokio is required to write small code snippets, which isn't supported by gccrs yet.
> Handle `async` keyword for regular implementations

- gcc/rust/typecheck/rust-hir-type-check-struct-field.h
- gcc/rust/typecheck/rust-hir-type-check-struct.cc
- gcc/testsuite/rust/compile/repeated_constructor_fields.rs
Fixes #2381
If a struct type is initialized with one of it's fields repeated it will currently issue an error at the use site. However we would like to give the rust error code and (like rustc) show both the specifications for the field to help the user diagnose the issue.
We move the check after the index for the field has been established so we can look up if the field has already been defined and get it's location.
We update the visit method to return if it has handled an error otherwise we then output a second fatal error as not all the field in the specification have been processed.
* gcc/rust/typecheck/rust-hir-type-check-struct-field.h: Allow visit to return a bool
* gcc/rust/typecheck/rust-hir-type-check-struct-field.cc: Improve check of respecification of …
> Add improved error when a field is redefined in a struct constructor

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-struct-field.h
- gcc/rust/typecheck/rust-hir-type-check-struct.cc
- gcc/testsuite/rust/compile/missing_constructor_fields.rs
Fixes #2389 
If a struct type with a variant that has fields is initialized with some fields the expression  HIR StructExprStructFields is checked that all the fields are assigned. However, if no fields are initialized the HIR StructExprStruct is generated. This doesn't check if the struct is a unit during typechekc and only fails at the compile stage with a ICE.
Add a check at the typecheck stage that makes sure the struct does not have a variant with fields and give an error message based on the rustc one.
We have also updated the message given in the case where one field was present to list the missing fields and match more closely the new message.
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit) Add additional check
* …
> Add improved error when no fields in initializer

- gcc/rust/ast/rust-ast-full-decls.h
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-item.h
- gcc/rust/expand/rust-derive-clone.cc
- gcc/rust/expand/rust-derive-clone.h
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
This moves us closer to unifying handling of associated items
> Remove ```TraitImplItem```

- gcc/testsuite/rust/execute/torture/builtin_macros1.rs
- gcc/testsuite/rust/execute/torture/coercion3.rs
- gcc/testsuite/rust/execute/torture/issue-2080.rs
- gcc/testsuite/rust/execute/torture/issue-2179.rs
- gcc/testsuite/rust/execute/torture/issue-2180.rs
- gcc/testsuite/rust/execute/torture/iter1.rs
* rust/execute/torture/builtin_macros1.rs: Fix output pattern.
* rust/execute/torture/coercion3.rs: Likewise.
* rust/execute/torture/issue-2080.rs: Likewise.
* rust/execute/torture/issue-2179.rs: Likewise.
* rust/execute/torture/issue-2180.rs: Likewise.
* rust/execute/torture/iter1.rs: Likewise.
> gccrs: Fix output line ending patterns for Windows platforms.

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/issue-2812.rs
Fixes #2812 
Might use same function to parse normal function and trait functions so should be a useful fix.
> Parse normal functions with `self` parameter correctly

- gcc/rust/hir/rust-ast-lower-base.cc
Previously, the default ABI was set to Rust, which is incorrect for extern blocks and extern functions. This patch changes the default ABI to C for these cases.
Reference: https://doc.rust-lang.org/reference/items/functions.html#extern-function-qualifier
Zulip discussion:  https://gcc-rust.zulipchat.com/#narrow/stream/266897-general/topic/extern.20blocks/near/346429045
* hir/rust-ast-lower-base.cc (ASTLoweringBase::lower_qualifiers): (ASTLoweringBase::lower_extern_block): Change ABI to C for extern
> Set the default ABI to C for extern blocks and extern functions

- gcc/testsuite/rust/compile/issue-1483.rs
Fixes #1483
* rust/compile/issue-1483.rs: New test.
> gccrs: add testcase to prove issue has already been fixed

- gcc/testsuite/rust/compile/issue-2772-1.rs
- gcc/testsuite/rust/compile/issue-2772-2.rs
Fixes #2772
* rust/compile/issue-2772-1.rs: New test.
* rust/compile/issue-2772-2.rs: New test.
> gccrs: add test cases to prove type inference is working

- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/testsuite/rust/compile/issue-2747.rs
Fixes #2747
* typecheck/rust-tyty-subst.cc (SubstitutionRef::get_mappings_from_generic_args): fix
* rust/compile/issue-2747.rs: New test.
> gccrs: Fix ICE accessing empty vector without check

- gcc/testsuite/rust/compile/issue-2782.rs
Fixes #2782
* rust/compile/issue-2782.rs: New test.
> gccrs: Add testcase to show issue is already fixed

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/issue-2775.rs
We can point to generic parent types which means we need to do the shallow resolve thing that rustc does. We have destructure which is similar to get what the parameter type points to.
Fixes #2775
* typecheck/rust-hir-type-check-pattern.cc (TypeCheckPattern::visit): use destructure
* rust/compile/issue-2775.rs: New test.
> gccrs: fix bug in pattern check for tuples

- gcc/testsuite/rust/execute/torture/matches_macro.rs
This adds a testcase for issue #2129.
* rust/execute/torture/matches_macro.rs: New test.
Fixes #2129
> gccrs: Add testcase for matches!() macro

- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-item.h
- gcc/testsuite/rust/compile/use_2.rs
This fixes rebinding imports, and should also get us closer to working glob imports.
> Fix rebinding imports

- gcc/rust/expand/rust-macro-expand.h
- gcc/testsuite/rust/compile/rustc_const_stable.rs
- expand: Fix formatting for "macro not found" error
- gccrs: Add testcase for #[rustc_const_stable]
> Add testcase for #2314, fix formatting in macro error

- gcc/rust/backend/rust-builtins.cc
- gcc/rust/backend/rust-builtins.h
- gcc/testsuite/rust/compile/torture/intrinsics-math.rs
```
* backend/rust-builtins.cc (BuiltinsContext::register_rust_mappings): Add powi and reformat.
* backend/rust-builtins.h: Add missing copyright header.
* rust/compile/torture/intrinsics-math.rs: Adjust pow test, add test for powi.
```
> gccrs: add powi intrinsics

- gcc/testsuite/rust/compile/issue-1773.rs
On Fri, Feb 09, 2024 at 11:03:38AM +0100, Jakub Jelinek wrote:
> On Wed, Feb 07, 2024 at 12:43:59PM +0100, arthur.cohen@embecosm.com wrote:
> > This patch introduces one regression because generics are getting better
> > understood over time. The code here used to apply generics with the same
> > symbol from previous segments which was a bit of a hack with out limited
> > inference variable support. The regression looks like it will be related
> > to another issue which needs to default integer inference variables much
> > more aggresivly to default integer.
> >
> > Fixes #2723
> >     * rust/compile/issue-1773.rs: Moved to...
> >     * rust/compile/issue-1773.rs.bak: ...here.
>
> Please don't use such suffixes in the testsuite.
> Either delete the testcase, or xfail it somehow until the …
> gccrs: Avoid *.bak suffixed tests - use dg-skip-if instead

- MAINTAINERS
- contrib/gcc-changelog/git_commit.py
- libgrust/ChangeLog
- libgrust: Add ChangeLog file
- libgrust: Add entry for maintainers
> libgrust: Add missed commits for Changelog creation

- gcc/testsuite/rust/compile/torture/intrinsics-math.rs
The signature was incorrectly using an i64 for the integer power,
instead of an i32.
> gccrs: fix powif64 intrinsic

- gcc/rust/rust-lang.cc
* rust-lang.cc (grs_langhook_type_for_mode): simplify code for
*Imode. Add missing long_double_type_node.
> gccrs: minor cleanup in langhook.type_for_mode

- gcc/testsuite/rust/compile/bad_stmt_enums.rs
- gcc/testsuite/rust/compile/bad_toplevel_enums.rs
- gcc/testsuite/rust/compile/redef_error1.rs
- gcc/testsuite/rust/compile/redef_error3.rs
- gcc/testsuite/rust/compile/redef_error4.rs
- gcc/testsuite/rust/compile/redef_error6.rs
The error messages produced during name resolution 2.0 are slightly different
> Adjust error checks to match name resolution 2.0

- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/resolve/rust-early-name-resolver.cc
```bash
=== rust Summary ===
```
---
I noticed a FixMe in `rust-macro-builtins.cc` that asks to change the return type of a function from BuiltInMacro to be wrapped in an optional so I changed it.
I then ran the codebase through `make -s -j16` to make sure there isn't any compiler error.
I then ran `make check-rust` to make sure there isn't any broken test-case. Results are as above.
I then run `clang-format`, add all the files edited and do a `git commit --signoff` and push them, creating a pull-request
> Fix FixMe in changing return type of builtin_macro_from_string() from BuiltinMacro to tl::optional<BuiltinMacro>

- gcc/rust/backend/rust-compile-extern.h
- gcc/rust/checks/errors/borrowck/rust-bir-builder-struct.h
- gcc/rust/checks/errors/borrowck/rust-function-collector.h
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-const-checker.h
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/checks/errors/rust-unsafe-checker.h
- gcc/rust/hir/rust-ast-lower-extern.h
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
- gcc/rust/hir/tree/rust-hir-full-decls.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-visitor.h
- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/resolve/rust-ast-resolve-implitem.h
- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.h
This PR adds the required HIR node and visitors for implementing extern types properly. The only step currently being performed is the lowering of AST extern types to their HIR counterpart.
> Add base for implementing extern types

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-collector.h
- gcc/rust/ast/rust-ast-full-decls.h
- gcc/rust/ast/rust-ast-full.h
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-builtin-ast-nodes.h
- gcc/rust/ast/rust-fmt.cc
- gcc/rust/ast/rust-fmt.h
- gcc/rust/expand/rust-derive.h
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-ast-lower-base.h
- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/hir/rust-ast-lower-expr.h
- gcc/rust/hir/rust-ast-lower-format-args.cc
- gcc/rust/hir/rust-ast-lower-format-args.h
- gcc/rust/parse/rust-parse.h
- gcc/rust/resolve/rust-ast-resolve-base.cc
- gcc/rust/resolve/rust-ast-resolve-base.h
- libgrust/libformat_parser/src/bin.rs
- libgrust/libformat_parser/src/lib.rs
Needs #2822
Fixes #2856 
This PR creates the `FormatArgs` AST node, and starts the process of building one as part of the `format_args!()` macro expansion. Having a dedicated AST node is what is being done in modern versions of `rustc` - it allows for certain optimizations like flattening and inlining of format_args arguments which reduce the generated code size.
This AST node should be converted into the proper function call as part of HIR lowering.
> Return proper AST nodes from format_args!() expansion

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
* resolve/rust-late-name-resolver-2.0.cc (Late::visit): Add error emitting
From  issue #2876 , I clone gcc locally, then run from build dir
```
../gcc_src/configure '--with-pkgversion=basepoints/gcc-14-9118-g3232ebd91ed, built at 1708915534' --prefix=/tmp/gcc-x86_64-linux --enable-werror-always --enable-languages=rust --disable-gcov --disable-shared --disable-threads --target=x86_64-linux --without-headers --disable-multilib
```
to verify the crash.
Then i edit in-place of the recently cloned gcc the file `rust-late-name-resolver-2.0.cc` until the problem regarding the file goes away after rebuilding. The rest of the errors are in gcc error itself
```
../../gcc_src/gcc/gcc.cc: In function ‘void read_specs(const char*, bool, bool)’:
../../gcc_src/gcc/gcc.cc:2413:32: …
```
> Add error emitting when we can't resolve id expr

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/ast/rust-builtin-ast-nodes.h
- gcc/rust/ast/rust-fmt.cc
- gcc/rust/ast/rust-fmt.h
- gcc/rust/expand/rust-derive.cc
- gcc/rust/expand/rust-derive.h
- gcc/rust/expand/rust-expand-format-args.cc
- gcc/rust/expand/rust-expand-format-args.h
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/resolve/rust-ast-resolve-base.cc
- gcc/testsuite/rust/compile/format_args_basic_expansion.rs
- libgrust/libformat_parser/src/lib.rs
Needs #2859
Needs #2917 for GCC 4.8 to have Rust 1.72 installed (for `String::leak`)
- ast: Add base nodes for FormatArgs
- macro-builtins: Add newline generic format_args!() handler
- parser: Add peek(n) method to parser
- format-args: Fix Rust interface and add input parsing.
- lower: Add base for lowering FormatArgs nodes
- format-args: Add base for expanding FormatArgs nodes
- format-args: Start storing string in Rust memory
- format-args: Add basic expansion of unnamed Display::fmt arguments.
- format-args: Add basic test case
> Expand FormatArgs node as AST pass

- gcc/rust/Make-lang.in
- gcc/rust/rust-session-manager.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-typecheck-context.cc
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty-variance-analysis-private.h
- gcc/rust/typecheck/rust-tyty-variance-analysis.cc
- gcc/rust/typecheck/rust-tyty-variance-analysis.h
> Borrowck: variance analysis

- gcc/rust/hir/rust-ast-lower-extern.h
- gcc/rust/hir/tree/rust-hir-item.h
Ran through git-clang-format, make check-rust passes as expected. 
Check-list:
(x) Make sure that visibility modifier are parsed for extern type nodes: I made sure that `parse_external_type_item` has AST::Visibility within its declaration
```c++
// in rust-parse-impl.h
template <typename ManagedTokenSource>
std::unique_ptr<AST::ExternalTypeItem>
Parser<ManagedTokenSource>::parse_external_type_item (AST::Visibility vis,
AST::AttrVec outer_attrs);
```
(x) Make sure that visibility is assigned to `ExternalTypeItem` I made sure that in in the function mentioned above, its constructor, ExternalTypeItem(), handled visibility correctly via its parent's constructor
```c++
// In rust-item.h
ExternalTypeItem (Identifier item_name, Visibility vis,
std::vector<Attribute> outer_attrs, location_t …
```
> Store visibility properly in ExternalTypeItem: Fixes #2897

- gcc/rust/util/rust-attribute-values.h
- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/compile/deprecated-fn.rs
Similar to #2929, allows us to compile code which uses ```rustc_deprecated``` but doesn't handle the proper diagnostics yet.
> Recognize rustc_deprecated as a builtin attribute

- gcc/rust/util/rust-attribute-values.h
- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/compile/unstable-fn.rs
In the future we'll have to produce [E0658](https://doc.rust-lang.org/error_codes/E0658.html), but this should allow us to compile code containing the ```unsafe``` attribute.
> Recognize unstable as a builtin attribute

- gcc/rust/typecheck/rust-unify.cc
- gcc/testsuite/rust/compile/match-never-ltype.rs
- gcc/testsuite/rust/compile/match-never-rtype.rs
Never can... never... exist, so it should always be coerced to the type
it is being matched against. This is useful for breaking off of a loop
from inside a match, or an if condition, for example.
* typecheck/rust-unify.cc (UnifyRules::go): Always unify to `ltype` if
we are matching against a `Never` in `rtype`.
(UnifyRules::expect_never): Always unify to the expected type.
* rust/compile/match-never-ltype.rs: New test.
* rust/compile/match-never-rtype.rs: New test.
Fixes #2908
This currently fails a bunch of tests, so leaving in draft. I'll revisit this tomorrow/later.
> unify: Always coerce `!` to the target type.

- gcc/testsuite/rust/compile/raw-byte-string-loc.rs
- gcc/testsuite/rust/compile/raw-string-loc.rs
The error is actually expected and uses the correct location.
* rust/compile/raw-byte-string-loc.rs: Use dg-error instead of
dg-excess-error.
* rust/compile/raw-string-loc.rs: Likewise.
@powerboat9 how do you feel about this?
> raw-strings: Remove dg-excess-error directive

- README.md
For #2937, I only add the alternative instead of also the build documentation on Rosetta since it is still failing on my local Mac M2.
> Add an alternative solution on MacOS

- gcc/rust/resolve/rust-default-resolver.cc
- gcc/testsuite/rust/compile/name_resolution25.rs
> Resolve impl block type with name resolution 2.0

- gcc/rust/backend/rust-tree.h
* backend/rust-tree.h: remove redundant macro definition.
> Remove redundant macro definition

- gcc/rust/Make-lang.in
- gcc/rust/checks/errors/borrowck/ffi-polonius/src/gccrs_ffi_generated.rs
- gcc/rust/checks/errors/borrowck/ffi-polonius/src/lib.rs
- gcc/rust/checks/errors/borrowck/polonius/rust-polonius-ffi.h
- gcc/rust/checks/errors/borrowck/polonius/rust-polonius.h
- gcc/rust/checks/errors/borrowck/rust-bir-builder-expr-stmt.cc
- gcc/rust/checks/errors/borrowck/rust-bir-dump.cc
- gcc/rust/checks/errors/borrowck/rust-borrow-checker.cc
- gcc/testsuite/rust/borrowck/borrowck.exp
- gcc/testsuite/rust/borrowck/position_dependant_outlives.rs
- gcc/testsuite/rust/borrowck/reference.rs
- gcc/testsuite/rust/borrowck/return_ref_to_local.rs
- gcc/testsuite/rust/borrowck/subset.rs
- gcc/testsuite/rust/borrowck/test_move.rs
- gcc/testsuite/rust/borrowck/test_move_behind_reference.rs
- gcc/testsuite/rust/borrowck/test_move_conditional.rs
- gcc/testsuite/rust/borrowck/tmp.rs
- gcc/testsuite/rust/borrowck/use_while_mut.rs
- gcc/testsuite/rust/borrowck/use_while_mut_fr.rs
- gcc/testsuite/rust/borrowck/well_formed_function_inputs.rs
All commits tested even with gcc48.
Depends on #2885
Related to #2716 
@CohenArthur 
@braw-lee
> Borrowck tests and build

- gcc/rust/rust-gcc.cc
Closes #2357
Remove unnecessary TREE_SIDE_EFFECTS and TREE_READONLY macros used in arithmetic overflow checks in rust-gcc.cc. Calls to abort are still generated when these are removed.
> Remove unnecessary SIDE_EFFECTS/READONLY macros

- libgrust/libformat_parser/Cargo.toml
- libgrust/libformat_parser/generic_format_parser/Cargo.toml
- libgrust/libformat_parser/generic_format_parser/src/lib.rs
- libgrust/libformat_parser/src/lib.rs
libgrust/ChangeLog:
* libformat_parser/Cargo.toml: Change Rust edition from 2021 to 2018.
* libformat_parser/generic_format_parser/Cargo.toml: Likewise.
* libformat_parser/generic_format_parser/src/lib.rs: Remove usage of
then-unstable std features and language constructs.
* libformat_parser/src/lib.rs: Likewise, plus provide extension trait
for String::leak.
While changing this does not feel great, it will enable us to compile our dependencies with gccrs as soon as possible.
> libformat_parser: Lower minimum Rust version to 1.49

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-base.h
- gcc/rust/backend/rust-compile-block.cc
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/backend/rust-compile-type.cc
- gcc/rust/backend/rust-compile-type.h
These were leftover from an earlier refactor
> Remove unused ```Context``` parameter for some backend methods

- gcc/rust/backend/rust-compile-expr.cc
- gcc/testsuite/rust/compile/issue-2906.rs
- gcc/testsuite/rust/execute/torture/issue-2906.rs
* backend/rust-compile-expr.cc (check_match_scrutinee): Handle structs
fixes #2906
We should now be able to use struct as scrutinee. I tested the code locally and it ran without issues but I was wondering if this patch also required a test case along with it.
> Handle structs as scrutinee for match expressions

- gcc/rust/resolve/rust-default-resolver.cc
This should improve handling of constant expressions for name resolution 2.0
> Visit constant items without expressions properly

- gcc/rust/rust-system.h
issue #2920
move system include to `rust-system.h` 
```c
#include <stack>
```
> Remove system include in `gcc/rust/typecheck/rust-hir-type-check.h`

- gcc/rust/ast/rust-expr.h
- gcc/rust/hir/tree/rust-hir-expr.h
`locus` should be private, we also have a getter for it
looks like the access specifier was misstyped
> Corrected access specifiers

- gcc/rust/resolve/rust-default-resolver.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
Removes a redundant function override and replaces usage of ```Rib::Kind::Item``` with ```Rib::Kind::ConstantItem```.
> Improve handling of ```ConstantItem``` during name resolution 2.0

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-item.h
- gcc/rust/ast/rust-path.h
- gcc/rust/checks/errors/rust-feature-gate.cc
- gcc/rust/checks/errors/rust-feature-gate.h
- gcc/rust/checks/errors/rust-feature.cc
- gcc/rust/checks/errors/rust-feature.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/util/rust-attribute-values.h
- gcc/testsuite/rust/compile/dropck_eyepatch_feature_gate.rs
- gcc/testsuite/rust/compile/may_dangle.rs
Outer attributes were not correctly parsed on generic parameter, this prevented the `#[may_dangle]` outer attribute from being used.
This feature also provides a new feature gate `dropck_eyepatch` to prevent `#[may_dangle]` attributes from being used in stable context.
Requires #3012
Content:
https://github.com/Rust-GCC/gccrs/compare/552c36c..3c311a9c33340382fd0ea043f365ddfef9068a8f
> Fix outer attribute parsing on generic parameters

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-expr.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/struct_expr_field_attributes.rs
Struct fields can have outer attributes on their field for various purpose, this behavior should be reflected upon struct expr fields.
Fixes #3018
> Add outer attributes to struct expr fields

- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/testsuite/rust/compile/issue-2725.rs
Fixes formatting issues from #2745
Addresses https://github.com/Rust-GCC/gccrs/issues/2725
> Emit error on optional supertraits

- gcc/rust/ast/rust-ast-fragment.h
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-macro.h
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-macro-builtins-asm.cc
- gcc/rust/expand/rust-macro-builtins-asm.h
- gcc/rust/expand/rust-macro-builtins-format-args.cc
- gcc/rust/expand/rust-macro-builtins-include.cc
- gcc/rust/expand/rust-macro-builtins-location.cc
- gcc/rust/expand/rust-macro-builtins-log-debug.cc
- gcc/rust/expand/rust-macro-builtins-utility.cc
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/hir/tree/rust-hir.cc
This is quite a rough fix (like a lot of the macro expansion code...) but it allows built-in macros to be treated as statements. I *think* asm!() might be the only one where it really matters, but also doing something like
```rust
{
line!();
}
```
will now work, whereas before the macro invocation would not get expanded properly and would be ignored.
```
* ast/rust-ast-fragment.h: Pass `is_semicolon` information to builtin macro transcribers.
* ast/rust-macro.h: Pass semicolon information to transcriber..
* expand/rust-macro-builtins-asm.cc (MacroBuiltin::asm_handler): Likewise. (parse_asm): Likewise.
* expand/rust-macro-builtins-asm.h (parse_asm): Likewise.
* expand/rust-macro-builtins-format-args.cc (MacroBuiltin::format_args_handler): Likewise.
* …
```
> expand: Keep track of semicoloned builtin macros

- gcc/testsuite/rust/compile/inline_asm_outside_unsafe.rs
I've added the unsafe guard check in #2982 but I haven't added it in since then
> Add test case for using asm! outside of unsafe {}

- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir.h
Addresses #3062
* hir/tree/rust-hir-expr.h: Added ExprType::InlineAsm
* hir/tree/rust-hir.h: Added ExprType::InlineAsm
> Added ExprType::InlineAsm

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-token.cc
- gcc/rust/lex/rust-token.h
- gcc/rust/parse/rust-parse-impl.h
Add RAW_STRING_LITERAL token variant and the LitType::RAW_STRING variant.
* ast/rust-ast-collector.cc (TokenCollector::visit): Handle RAW_STRING case in TokenCollection::visit
* ast/rust-ast.cc (AttributeParser::parse_meta_item_inner): Add RAW_STRING_LITERAL case to call parse_meta_item_lit() (AttributeParser::parse_literal): Add RAW_STRING_LITERAL case.
* ast/rust-ast.h: Add RAW_STRING_LITERAL to is_stirng_lit(). Add RAW_STRING enum variant to LitType enum.
* hir/rust-ast-lower-base.cc (ASTLoweringBase::lower_literal): Handle raw string literal type, falls back to rust_unreachable() for now.
* lex/rust-lex.cc (Lexer::parse_raw_string): Use make_raw_string instead of make_string.
* lex/rust-token.cc (Token::as_string): Handle case for RAW_STRING_LITERAL.
* …
> Add RAW_STRING_LITERAL

- gcc/rust/ast/rust-expr.h
- gcc/rust/expand/rust-macro-builtins-asm.cc
I fixed the parse result of parse_format_strings first. 
* ast/rust-expr.h (struct TupleTemplateStr): Store parse result of parse_format_string(s)
* expand/rust-macro-builtins-asm.cc (parse_format_strings): Likewise
I'm not sure how parse_asm_operand should be addressed for now (asm_codegen_il hasn't touched that part yet) so that would probably go into another PR)
Addresses #3069 (yes not fixed :) )
> Store parse result of parse_format_string(s)

- gcc/rust/ast/rust-expr.h
- gcc/rust/expand/rust-macro-builtins-asm.cc
Fixed #3050 by safeguarding constructors and using tl::optional in member of first layer's construction of InlineAsm
> Safe-guard InlineAsm structs

- gcc/rust/ast/rust-expr.h
Fixes #3051  
I deleted the two superfluous #include's from `gcc/rust/ast/rust-expr.h`.
* I ran the tests on aarch64 linux, producing the following results:
```
Native configuration is aarch64-unknown-linux-gnu
=== rust tests ===
Schedule of variations:
unix
Running target unix
Using /usr/share/dejagnu/baseboards/unix.exp as board description file for target.
Using /usr/share/dejagnu/config/unix.exp as generic interface file for target.
Using …
```
> Remove unnecessary #include from rust-expr.h

- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
The visitor was still using the as_string() method.
> rust: fix HIR dump for MatchExpr

- gcc/rust/Make-lang.in
- gcc/rust/checks/errors/borrowck/rust-borrow-checker-diagnostics.cc
- gcc/rust/checks/errors/borrowck/rust-borrow-checker-diagnostics.h
- gcc/rust/checks/errors/borrowck/rust-borrow-checker.cc
Will handle borrow-checking diagnostics inside this class
depends on #3058
> New class for bck diagnostics

- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/shadow1.rs
* hir/tree/rust-hir-expr.h: Add new get_operator_str method in
ArithmeticOrLogicalExpr and CompoundAssignmentExpr
* hir/tree/rust-hir.cc: Likewise
* typecheck/rust-hir-type-check-expr.cc: Improve error message for
operator expressions to display the correct operator symbol
* rust/compile/shadow1.rs: Fix test for new error message
Fixes #2030
- \[ X] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[ X] Read contributing guidlines
- \[X ] `make check-rust` passes locally
- \[X ] Run `clang-format`
- \[ X] Added any relevant test cases to `gcc/testsuite/rust/`
> Improve error messages for operator expressions

- gcc/testsuite/rust/execute/torture/issue-2187.rs
- gcc/testsuite/rust/execute/xfail/macro1.rs
Fixes #2817
For builtin_macro_includes_bytes & include.txt: Change `the_bytes` to b"hello, include!\r\n" 
For issue-2187.rs, change expected test output dg-output
to "L1\r\n\L2\r\nL3\r\nL4" and "a = "%s\n\0" to "a = "%s\r\n\0"
The rest is accomplished with 
```
#!/bin/bash
find . -type f | while read -r FILE; do
sed -i 's/$/\r/' "$FILE"
sed -i 's/\(.*\)\r\r\n/\r\n/g' "$FILE"
done
```
* rust/execute/same_field_name.rs: Likewise
* rust/execute/torture/arrays.rs: Likewise
* rust/execute/torture/atomic_load.rs: Likewise
* rust/execute/torture/atomic_store.rs: Likewise
* rust/execute/torture/block_expr1.rs: Likewise
* rust/execute/torture/builtin_abort.rs: Likewise
* rust/execute/torture/builtin_macro_cfg.rs: Likewise
* rust/execute/torture/builtin_macro_concat.rs: …
> Fix all tests in execute to be \r\n

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/issue-3046.rs
* typecheck/rust-hir-type-check-expr.cc: Fix ICE caused by not finding enum variant by adding new error message
* compile/issue-3046.rs: Add test for new error message
Fixes #3046
---
Adds a compile error, "expected function, tuple struct or tuple variant, found enum" when TypeCheckExpr::visit is called on a HIR::CallExpr, but that CallExpr's function is actually an enum.
> Add compile error to fix ICE when failing to find enum variants. 

- .github/workflows/bootstrap.yml
The CI failed to compile some new code that requires a nightly feature. This change allows the CI to use a nightly compiler instead.
> Fix CI bootstrap build with a nightly rust compiler

- gcc/rust/ast/rust-expr.h
Related to #3069, needed for asm generic il to work
I realized I was asserting expr instead of this->expr and the code kept failing from assertion for no reason ...
Change the assert of (expr != nullptr) to
(this->expr != nullptr) because we assigned (std::move(expr)) to this->expr, no need to assert expr
* ast/rust-expr.h (struct AnonConst): Change assertion of constructor 
* (struct InlineAsmOperand): Change assertion of constructor
> Change assertion of asm operand constructor

- gcc/rust/ast/rust-fmt.cc
- gcc/rust/ast/rust-fmt.h
- gcc/rust/expand/rust-macro-builtins-format-args.cc
- libgrust/libformat_parser/generic_format_parser/src/lib.rs
- libgrust/libformat_parser/src/bin.rs
- libgrust/libformat_parser/src/lib.rs
* ast/rust-fmt.cc (Pieces::collect): Added options for ParseMode
* ast/rust-fmt.h (collect_pieces): Likewise. (struct Pieces): Likewise.
* expand/rust-macro-builtins-format-args.cc (MacroBuiltin::format_args_handler): Likewise.
libgrust/ChangeLog:
* libformat_parser/generic_format_parser/src/lib.rs: Likewise.
* libformat_parser/src/bin.rs: Likewise.
* libformat_parser/src/lib.rs: Likewise.
> Added options for ParseMode

- gcc/rust/expand/rust-expand-visitor.cc
- gcc/testsuite/rust/compile/issue-2987.rs
```
* expand/rust-expand-visitor.cc: Fix ICE caused by unique_ptr UB and buggy iterator use
* rust/compile/issue-2987.rs: Add test for deriving Clone and Copy at the same time
```
Fixes #2987 
---
Fix an ICE caused by an improper use of iterators that prevented Clone and Copy from being applied to the same struct.
Fixes #2987
> [#2987] Patch ICE when deriving Clone and Copy

- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/testsuite/rust/compile/unknown-associated-item.rs
- Fixes subtask 1 of https://github.com/Rust-GCC/gccrs/issues/3079 (unable to create a subtask)
---
* typecheck/rust-hir-type-check-type.cc (TypeCheckType::visit): Add error message similiar to rustc with associaed type and trait name
* rust/compile/unknown-associated-item.rs: New test.
---
> gccrs: [E0576] Associated `item` not found in given `type`

- gcc/testsuite/rust/rustc/README.md
- gcc/testsuite/rust/rustc/rustc.exp
_Originally posted by @tschwinge in https://github.com/Rust-GCC/gccrs/issues/3071#issuecomment-2199788719_
---
* rust/external/README.md: information about external directory.
* rust/external/external.exp: New test.
> gccrs: Add external test directory for testsuite adaptor

- gcc/rust/expand/rust-cfg-strip.cc
- gcc/rust/expand/rust-cfg-strip.h
- gcc/testsuite/rust/compile/macro-issue2983_2984.rs
* expand/rust-cfg-strip.cc: Strip struct expr fields and strip fields in struct definition
* expand/rust-cfg-strip.h: Signatures for new function maybe_strip_struct_expr_fields
* rust/compile/macro-issue2983_2984.rs: Add test to check for correct stripped fields
Fixes #2983
Fixes #2984
- \[X] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[X] Read contributing guidlines
- \[X] `make check-rust` passes locally
- \[X] Run `clang-format`
- \[X] Added any relevant test cases to `gcc/testsuite/rust/`
---
@CohenArthur
> Properly striping struct fields when using attrs

- gcc/rust/ast/rust-ast.cc
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/hir/tree/rust-hir.h
- gcc/testsuite/rust/compile/issue-3045-1.rs
- gcc/testsuite/rust/compile/issue-3045-2.rs
```
* ast/rust-ast.cc:
Fix Attribute constructors to copy inner_attribute
* checks/errors/rust-unsafe-checker.cc:
Add pass for #[may_dangle] in safe impl's
* hir/rust-ast-lower-item.cc:
Add support for unsafe impl's
* hir/rust-ast-lower-type.cc:
Lower attributes in impl's from AST to HIR
* hir/rust-hir-dump.cc:
Change single attribute to AttrVec
* hir/tree/rust-hir-item.h:
Add unsafe support to Impl blocks in HIR
* hir/tree/rust-hir.cc:
Change single attribute to AttrVec
* hir/tree/rust-hir.h:
Add has/get_outer_attribute to GenericParam
* rust/compile/issue-3045-1.rs:
Add test for #[may_dangle] Generic Type triggering error
* rust/compile/issue-3045-2.rs:
Add test for #[may_dangle] Lifetime triggering error
```
Fixes #3045 
- \[x] GCC …
> #[may_dangle] in safe impl

- gcc/rust/checks/errors/borrowck/polonius/rust-polonius.h
1 << 16 gives : 10000000000000000
~(1 << 16) gives : 11111111111111101111111111111111
i think the assumption was output of ~(1 << 16) will be 1111111111111111, which results in extraction of wrong statement
this bug can be verified by checking nll_dump of this function
```rust
fn complex_cfg_subset<'a, 'b>(b: bool, x: &'a u32, y: &'b u32) -> &'a u32 {
if b { 
y
} else {
x
}   
}
```
> Fixed bitwise operation in `extract_stmt`

- gcc/rust/ast/rust-expr.h
- gcc/rust/expand/rust-macro-builtins-asm.cc
- gcc/rust/expand/rust-macro-builtins-asm.h
- gcc/testsuite/rust/compile/inline_asm_illegal_operands.rs
- gcc/testsuite/rust/compile/inline_asm_parse_operand.rs
Dependent: asm_generic_il
* ast/rust-expr.h (struct InlineAsmOperand): Add construction for register_type
* backend/rust-compile-asm.cc (CompileAsm::asm_construct_outputs): Set up counting to check
* expand/rust-macro-builtins-asm.cc (parse_reg_operand): Fix parsing logic & reassignment logic (parse_reg_operand_in): Fix parsing (parse_reg_operand_out): Fix parsing (parse_reg_operand_inout): Fix parsing (parse_reg_operand_unexpected): Remove rust_unreachable() (parse_asm_arg): Fix parsing logic
* expand/rust-macro-builtins-asm.h: Add = operator overloading
* rust/compile/inline_asm_illegal_operands.rs: Test now passing
* rust/compile/inline_asm_parse_operand.rs: Remove _, not supported right now
Draft first for warnings, failures
> Fix the parser's operand and flags storage

- gcc/rust/checks/errors/borrowck/ffi-polonius/src/lib.rs
- gcc/rust/checks/errors/borrowck/polonius/rust-polonius.h
fixes #3111
added some comments on both rust and cpp side
i am not sure about the terminology used in bit manipulation, pls suggest improvements if any
i didn't name the hard-coded constants (1 and 0x7FFF) yet
do we need to name them or the explanation in comments seems enough?
@P-E-P
> Improve compressed point bit manipulation

- gcc/rust/checks/errors/borrowck/rust-bir-builder-expr-stmt.cc
- gcc/rust/checks/errors/borrowck/rust-bir-builder-internal.h
- gcc/rust/checks/errors/borrowck/rust-bir-builder-lazyboolexpr.h
- gcc/rust/checks/errors/borrowck/rust-bir-builder-pattern.h
- gcc/rust/checks/errors/borrowck/rust-bir-builder.h
- gcc/rust/checks/errors/borrowck/rust-bir-place.h
- gcc/rust/checks/errors/borrowck/rust-bir.h
depends on #3076 
Added `location` field to BIR::Statement and BIR::Place, updated the BIR builders to take the source location from HIR and pass it to BIR node.
> borrowck: Added location support to BIR nodes

- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/resolve/rust-ast-resolve-expr.h
This should resolve InlineAsm through its operand, depends on https://github.com/Rust-GCC/gccrs/pull/3103
Relevant file for review is rust-ast-resolve-expr.h/cc
> Inline asm resolve expr

- configure
- configure.ac
Save LIBS around calls to AC_SEARCH_LIBS to avoid clobbering $LIBS.
> rust: avoid clobbering LIBS

- gcc/rust/checks/errors/borrowck/rust-bir-builder.h
- gcc/rust/checks/errors/borrowck/rust-bir-fact-collector.h
Fixes this bugzilla PR: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116192
We are once again hitting issues for formatting `size_t` values in our printf-like macros. We should think about having a 32bit build CI for cases like these. Also, on architectures where `size_t` is `unsigned int`, such as 32bit x86, we encounter an issue with `PlaceId` and `FreeRegion` being aliases to the same types. This poses an issue for overloading functions for these two types, such as `push_subset` in that case. This commit renames one of these `push_subset` functions to avoid the issue, but this should be fixed with a newtype pattern for these two types, as is currently being discussed on Zulip
> Fix 32-bits builds

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/issue-2324-1.rs
- gcc/testsuite/rust/compile/issue-2324-2.rs
I took the error message from rustc, but I *really* don't like it. Isn't the error message the direct opposite of the problem? 
Rustc error message: expected unit struct, unit variant or constant, found tuple variant
I want something like: referenced type is a non-unit enum variant, consider specifying the relevant variant fields
```
* typecheck/rust-hir-type-check-pattern.cc:
Emit E0532 when trying to reference a Tuple or Struct variant
using a non Tuple or Struct pattern.
* rust/compile/issue-2324-1.rs:
add test for E0532 with tuple enum variant
* rust/compile/issue-2324-1.rs:
add test for E0532 with struct enum variant
```
Fixes #2324 , addresses #2553
- \[x] GCC development requires copyright assignment or the Developer's Certificate of …
> Add error message for E0532

- gcc/rust/checks/errors/borrowck/rust-bir-builder.h
- gcc/rust/checks/errors/borrowck/rust-bir.h
- gcc/rust/checks/errors/borrowck/rust-borrow-checker-diagnostics.cc
- gcc/rust/checks/errors/borrowck/rust-borrow-checker-diagnostics.h
- gcc/testsuite/rust/borrowck/subset.rs
> Better subset errors

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/nonexistent-field.rs
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): Add error code and update error message
* rust/compile/nonexistent-field.rs: New test.
---
- Fixes: https://github.com/Rust-GCC/gccrs/issues/3123
- Addresses: https://github.com/Rust-GCC/gccrs/issues/2553
> Attempted to access a nonexistent field [`E0609`]

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-collector.h
- gcc/rust/ast/rust-ast-full-decls.h
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-path.cc
- gcc/rust/ast/rust-path.h
- gcc/rust/ast/rust-pattern.h
- gcc/rust/expand/rust-derive.h
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-ast-lower-base.h
- gcc/rust/resolve/rust-ast-resolve-base.cc
- gcc/rust/resolve/rust-ast-resolve-base.h
This PR cleans up the existing base `Path*` nodes and creates a new `Path` tagged union for representing lang items paths.
> Add `lang-item` paths

- gcc/rust/ast/rust-ast-full-decls.h
- gcc/rust/hir/tree/rust-hir-full-decls.h
* ast/rust-ast-full-decls.h (struct InlineAsmOperand): Change to class (class InlineAsmOperand): Change from struct
* hir/tree/rust-hir-full-decls.h (struct InlineAsmRegOrRegClass): Removed from decl, used from AST (struct AnonConst): new decl from rust-hir-expr.h (class InlineAsmOperand): new decl from rust-hir-expr.h
CI doesn't warn about ast decl having InlineAsmOperand as struct and in rust-expr.h having InlineAsmOperand as class.
Same for rust-hir-full-decls declaring HIR version of InlineAsmRegOrRegClass but doesn't define them in rust-hir-expr.h
> Fix the disorder struct and class in inline asm

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/match8.rs
Fixes https://github.com/Rust-GCC/gccrs/issues/3070
* typecheck/rust-hir-type-check-pattern.cc (TypeCheckPattern::visit): Add check for union patterns.
* rust/compile/match8.rs: New test.
> Add check for union patterns

- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/issue-2324-2.rs
- gcc/testsuite/rust/compile/match9.rs
Addresses #2553 #2094
Fix some incorrect error messages introduced in https://github.com/Rust-GCC/gccrs/pull/3118
```
* hir/tree/rust-hir.cc (Item::item_kind_string): New function.
* hir/tree/rust-hir.h: New function.
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit):
Modify to check all arms in match expressions even if some of them
has errors.
* typecheck/rust-hir-type-check-pattern.cc (TypeCheckPattern::visit):
Add and fix check for path patterns.
* rust/compile/issue-2324-2.rs: Fix error message.
* rust/compile/match8.rs: New test.
```
> Add check for path patterns.

- .github/workflows/clang-format.yml
Distutils module was missing, hence the required bump
> Fix clang-format CI

- gcc/rust/util/rust-canonical-path.h
- gcc/testsuite/rust/compile/v0-mangle1.rs
Fixes a bug with the test case itself, and one with `crate_num` initialization in `CanonicalPath`
> Fix `v0-mangle1.rs` test when run with ASAN

- gcc/rust/checks/errors/borrowck/rust-bir.h
This allows `std::unique_ptr<AbstractExpr>` to be properly destructed, discovered during development of #3142.
> Add virtual destructor to `AbstractExpr`

- gcc/rust/resolve/rust-ast-resolve-pattern.cc
[Indexing a map inserts an entry if one does not already exist](https://en.cppreference.com/w/cpp/container/map/operator_at). This should fix the issue with test `alt_patterns1.rs` in #3142
> Avoid accidental insertion into map

- gcc/rust/backend/rust-compile.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/testsuite/rust/compile/trait13.rs
- gcc/testsuite/rust/compile/trait14.rs
- gcc/testsuite/rust/execute/torture/trait14.rs
- gcc/testsuite/rust/execute/torture/trait15.rs
- gcc/testsuite/rust/execute/torture/trait16.rs
- gcc/testsuite/rust/execute/torture/trait17.rs
- gcc/testsuite/rust/execute/torture/trait18.rs
There was only one function that needed modification, the rest is testing for this new feature :)
```
* backend/rust-compile.cc:
Modify compute_address_for_trait_item to support supertraits
* typecheck/rust-tyty.cc:
Remove auto
* rust/compile/trait13.rs:
Add test for supertraits of supertraits
* rust/compile/trait14.rs:
Diamond problem with supertraits test
* rust/execute/torture/trait14.rs:
Add test for dynamic dispatch with supertraits
* rust/execute/torture/trait15.rs:
Add test for dynamic dispatch with generics
* rust/execute/torture/trait16.rs:
Add test for dynamic dispatch with lifetime params 1
* rust/execute/torture/trait17.rs:
Add test for dynamic dispatch with lifetime params 2
* rust/execute/torture/trait18.rs:
Add test for default …
```
> Dynamic dispatch with supertraits

- .github/no-bootstrap-asan.mk
- .github/workflows/ccpp.yml
This adds a job for running GCC with ASAN to the github CI
> Compile using ASAN on the github CI

- gcc/rust/Make-lang.in
- gcc/rust/checks/errors/rust-hir-pattern-analysis.cc
- gcc/rust/checks/errors/rust-hir-pattern-analysis.h
- gcc/rust/rust-session-manager.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/exhaustiveness1.rs
- gcc/testsuite/rust/compile/exhaustiveness2.rs
- gcc/testsuite/rust/compile/exhaustiveness3.rs
This patch adds a pattern analysis pass which detects non-exhaustive match patterns and finds witnesses (counterexamples).
The algorithm I implemented is based on one described in [rustc documents](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_pattern_analysis/usefulness/index.html). The current implementation lacks some patterns (OR, literals, ranges, etc.), which is handled by converting them into wildcard pattern.
```
gccrs: Implement initial pattern analysis pass.
* Make-lang.in: Add rust-hir-pattern-analysis.o.
* rust-session-manager.cc (Session::compile_crate):
Add pattern analysis pass.
* typecheck/rust-hir-type-check-pattern.cc (TypeCheckPattern::visit):
Do typecheck for subpatterns.
* checks/errors/rust-hir-pattern-analysis.cc: New file.
* …
```
> pattern analysis

- gcc/rust/checks/errors/rust-feature-gate.cc
- gcc/rust/checks/errors/rust-feature-gate.h
- gcc/rust/checks/errors/rust-feature.cc
- gcc/testsuite/rust/compile/auto_trait.rs
- gcc/testsuite/rust/compile/auto_trait_super_trait.rs
- gcc/testsuite/rust/compile/generic_auto_trait.rs
Throw an error when auto-traits used without feature attribute.
* checks/errors/rust-feature-gate.cc (FeatureGate::visit): Emit error on trait when auto field member true.
* checks/errors/rust-feature-gate.h: add prototype of trait visitor.
* checks/errors/rust-feature.cc (Feature::create): add optin_builtin_traits in match of feature.
* rust/compile/auto_trait_super_trait.rs: Add feature attribute.
* rust/compile/generic_auto_trait.rs: likewise.
fixes #2963
> Emit error on auto-traits

- gcc/rust/rust-session-manager.cc
* rust-session-manager.cc (Session::compile_crate): Use less repetition, fix a typo in `reports`, fix word order.
> session-manager: Fix typos in -frust-incomplete message

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/testsuite/rust/compile/issue-3141.rs
Fixes [#3141]
* backend/rust-compile-expr.cc: Fix range checking for both integers and floats.
* hir/tree/rust-hir-expr.h: Add "negative_number" boolean to LiteralExpr class.
* rust/compile/issue-3141.rs: New test.
This pull request aims to fix an incorrect handling of literal "overflows".
To fix the handling of integer literals I added a boolean attribute to the HIR LiteralExpr class to signal if the literal is negative, and compare it accordingly.
As for float literals, I added checks on the float exponent in order to check for overflows.
> [#3141] Fix incorrect handling of overflow in numeric types

- .github/workflows/commit-format.yml
Add the "Tested-by" prefix to the list of already matched footer prefixes.
This avoid warnings on commits using it.
> github: adjust footer detection for Tested-by

- .github/workflows/bootstrap.yml
Version 2 of this github action has been deprecated, we shall bump the version used in the CI.
> Change upload artifact github action version

- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/resolve/rust-ast-resolve-expr.h
add a resolve expr visitor on error propagation to avoid internal compiler error when used with generics
* resolve/rust-ast-resolve-expr.cc (ResolveExpr::visit): Add implementation of error propagation visitor
* resolve/rust-ast-resolve-expr.h: Add prototype of error propagation
fixes #3001
> Fix ICE on error propagation with generic

- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/testsuite/rust/compile/issue-3030.rs
- gcc/testsuite/rust/compile/nr2/exclude
Negative polarity means we can just ignore if any trait items are not implemented.
Fixes #3030
* hir/rust-ast-lower-item.cc (ASTLoweringItem::visit): the polarity was reversed
* typecheck/rust-hir-type-check-item.cc: check the polarity
* rust/compile/issue-3030.rs: New test.
> rust: negative polarity removes restrictions on validation of impl blocks

- gcc/rust/hir/rust-hir-dump.cc
Add tail_reachable and label fields to the dump.
> gccrs: adjust hir dump of BlockExpr

- gcc/rust/checks/errors/borrowck/rust-borrow-checker.cc
- gcc/rust/expand/rust-proc-macro.cc
- gcc/rust/parse/rust-parse.cc
This commit adds Liu Hao's patch from
https://github.com/lhmouse/MINGW-packages/blob/5859d27b2b6101204a08ad9702cb2937f8797be9/mingw-w64-gcc/0100-rust-fix.patch
* checks/errors/borrowck/rust-borrow-checker.cc (mkdir_wrapped): Remove.
(BorrowChecker::go): Use `mkdir` instead.
* expand/rust-proc-macro.cc (register_callback): Use Windows APIs to
open dynamic proc macro library.
(load_macros_array): Likewise.
* parse/rust-parse.cc (defined): Replace separators in paths using
std::replace.
This adds the patch from https://github.com/lhmouse/MINGW-packages/commit/16dad6ba10a5680ad3ca6304480210cef8366985 but reworked for our new changes.
@lhmouse could you check it looks okay and builds on your side?
Sidenote, this might not build on Linux either - I don't have access to my …
> mingw: Fix build with patch from Liu Hao

- gcc/rust/util/optional.h
This isn't producing any extra errors on my end, but the extra checks should at least be good to have.
> Add extra assertions to `tl:optional`

- gcc/rust/resolve/rust-ast-resolve-type.cc
- gcc/rust/resolve/rust-ast-resolve-type.h
- gcc/rust/resolve/rust-name-resolver.cc
- gcc/rust/resolve/rust-name-resolver.h
- gcc/testsuite/rust/compile/issue-3035.rs
- gcc/testsuite/rust/compile/nr2/exclude
We need to resolve the never type which is its own special AST node so it doesnt magically get handled like the regular builtin type paths such as i32.
Fixes #3035
* resolve/rust-ast-resolve-type.cc (ResolveType::visit): handle never type (ResolveTypeToCanonicalPath::visit): likewise
* resolve/rust-ast-resolve-type.h: missing never type
* resolve/rust-name-resolver.cc (Resolver::generate_builtins): track never type node_id (Resolver::setup_builtin): likewise
* resolve/rust-name-resolver.h: new never type getter
* rust/compile/issue-3035.rs: New test.
> rust: fix ICE when compiling impl block for !

- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/testsuite/rust/compile/issue-3082.rs
- gcc/testsuite/rust/compile/nr2/exclude
Qualified path expressions usually are <X as Y>::... but the as is optional this adds the extra checking in hir lowering to not hit that nullptr.
Fixes #3082
* hir/rust-ast-lower-type.cc (ASTLowerQualifiedPathInType::visit): check for valid as segment
* rust/compile/nr2/exclude:
* rust/compile/issue-3082.rs: New test.
> rust fix ICE when hir lowering qualified path expressions without an as

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast-builder-type.cc
- gcc/rust/ast/rust-ast-builder-type.h
- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-path.h
- gcc/rust/ast/rust-type.h
- gcc/rust/expand/rust-derive-clone.cc
- gcc/rust/expand/rust-derive-clone.h
- gcc/rust/expand/rust-derive-copy.cc
- gcc/rust/expand/rust-derive-copy.h
- gcc/testsuite/rust/compile/issue-3139-1.rs
- gcc/testsuite/rust/compile/issue-3139-2.rs
- gcc/testsuite/rust/compile/issue-3139-3.rs
- gcc/testsuite/rust/compile/nr2/exclude
When we generate derivations for Copy and Clone we need to make sure the associated impl block sets up the generic parameters and arguments correctly. This patch introduces the framework to copy chunks of the AST because we need to make sure these new AST nodes have their own associated id, calling clone on the nodes will just confuse name-resolution and subsequent mappings.
Fixes #3139
* Make-lang.in: new objects
* ast/rust-ast-builder.cc (Builder::generic_type_path_segment): new helper
(Builder::single_generic_type_path): likewise
(Builder::new_type): likewise
(Builder::new_lifetime_param): likewise
(Builder::new_type_param): likewise
(Builder::new_lifetime): likewise
(Builder::new_generic_args): likewise
* ast/rust-ast-builder.h: new helper decls
* ast/rust-ast.h: …
> rust: Add support for Clone and Copy derive on generic types

- gcc/rust/resolve/rust-ast-resolve-type.cc
- gcc/rust/resolve/rust-ast-resolve-type.h
- gcc/testsuite/rust/compile/issue-3036.rs
- gcc/testsuite/rust/compile/nr2/exclude
The canonical paths need to support unit-types which are technically a TupleType with no fields. This handles this case and adds an unreachable.
Fixes #3036
* resolve/rust-ast-resolve-type.cc (ResolveTypeToCanonicalPath::visit): add unit-type catch
* resolve/rust-ast-resolve-type.h: likewise
* rust/compile/issue-3036.rs: New test.
> rust: fix ICE during name resolution for impls on unit-types

- gcc/testsuite/rust/compile/issue-2951.rs
- gcc/testsuite/rust/compile/nr2/exclude
The resolution with ! was fixed in: 09cfe530f9c this adds a test case to show the other issue is also fixed.
Fixes #2951
* rust/compile/nr2/exclude: nr2 is crashing here
* rust/compile/issue-2951.rs: New test.
> gccrs: add test case to show impl block on ! works

- gcc/testsuite/rust/compile/issue-2203.rs
- gcc/testsuite/rust/compile/nr2/exclude
This was resolved in: 18422c9c386 which was missing the name resolution step for unit-types.
Fixes #2203
* rust/compile/nr2/exclude:
* rust/compile/issue-2203.rs: New test.
> gccrs: Add test case to show ICE is fixed

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-item.h
- gcc/testsuite/rust/compile/issue-2499.rs
- gcc/testsuite/rust/compile/nr2/exclude
We just had an assertion here for this case where we expect a trait. This changes the assertion into error handling producing the correct error code with fixit suggestion like rustc.
```
test.rs:7:6: error: Expected a trait found ‘Foo’ [E0404]
7 | impl Foo for Bar {}
|      ^~~
|      not a trait
test.rs:10:11: error: Expected a trait found ‘Foo’ [E0404]
10 | fn baz<T: Foo>(t: T) {}
|           ^~~
|           not a trait
```
Fixes #2499
* typecheck/rust-hir-trait-resolve.cc (TraitResolver::resolve_path_to_trait): use error handling instead of assertion
* typecheck/rust-hir-type-check-item.cc (TypeCheckItem::visit): reuse trait reference
* typecheck/rust-hir-type-check-item.h: update prototype
* …
> gccrs: Fix ICE when typechecking non-trait item when we expect one

- gcc/rust/resolve/rust-finalize-imports-2.0.cc
- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-name-resolution-context.cc
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/rust/resolve/rust-rib.cc
- gcc/rust/resolve/rust-rib.h
- gcc/testsuite/rust/compile/nr2/exclude
This modifies `Rib::Definition` in order to better handle shadowing. It splits shadowing declarations into `shadowing` and `globbed` declarations, as shadowing declarations must shadow non-shadowing declarations, but non-shadowing declarations must shadow "globbed" declarations.
> Improve `Rib::Definition` shadowing

- .github/workflows/ccpp.yml
I noticed that ```libgrust/libformat_parser/target``` was seemingly generated outside the build directory on my machine. This should detect similar issues, and confirm/deny the aforementioned issue.
> Check for writes outside of the build directory

- gcc/rust/ast/rust-expr.h
- gcc/rust/expand/rust-macro-builtins-asm.cc
While this adds a bit of boilerplate to the nested classes of `InlineAsmOperand`, it should be an improvement overall
> Improve `InlineAsmOperand`

- gcc/rust/resolve/rust-name-resolution-context.cc
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Also makes `NameResolutionContext::lookup` const qualified
> Use name resolver 2.0 during pattern typechecking

- gcc/rust/backend/rust-compile-asm.cc
- gcc/rust/expand/rust-macro-builtins-asm.cc
- gcc/testsuite/rust/compile/inline_asm_parse_operand.rs
- gcc/testsuite/rust/execute/torture/inline_asm_mov_x_5_ARM.rs
- gcc/testsuite/rust/execute/torture/inline_asm_mov_x_5_x86_64.rs
fixes #3149 
* backend/rust-compile-asm.cc (CompileAsm::asm_construct_inputs): Provide input operand for gccrs
* expand/rust-macro-builtins-asm.cc (parse_reg_operand_in): Move expr to In (expand_inline_asm_strings): Add comments to debug strings
* rust/compile/inline_asm_parse_operand.rs: Remove inout, functionality not supported. Remove redundant {}
* rust/execute/torture/inline_asm_mov_x_5_ARM.rs: Add operand in
* rust/execute/torture/inline_asm_mov_x_5_x86_64.rs: Likewise
> Provide input operand for gccrs

- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
Adds `const` qualified member function overloads to `ForeverStack`
> Make `const` references to `ForeverStack` more useful

- gcc/rust/typecheck/rust-hir-trait-reference.h
- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/issue-3032-1.rs
- gcc/testsuite/rust/compile/issue-3032-2.rs
- gcc/testsuite/rust/compile/nr2/exclude
When we are typechecking the impl block for DerefMut for &mut T the implementation follows the usual operator overload check but this ended up just resolving directly to the Trait definition which ends up being recursive which we usually handle. The issue we had is that a dereference call can be for either the DEREF or DEREF_MUT lang item here it was looking for a recurisve call to the DEREF lang item but we were in the DEREF_MUT lang item so this case was not accounted for.
Fixes #3032
* typecheck/rust-hir-trait-reference.h: new get locus helper
* typecheck/rust-hir-trait-resolve.cc (AssociatedImplTrait::get_locus): implemention
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::resolve_operator_overload): fix overload
* …
> gccrs: Fix bad recursive operator overload call

- gcc/testsuite/rust/compile/issue-3033.rs
- gcc/testsuite/rust/compile/nr2/exclude
The issue here was that the impl block for Cell<T> defines that T must have the bound of Copy implemented. But simultaneously if you do an deref you get direct access to the unsafe cell which also defines a get method so these are two valid ways of accessing the method in question but when Copy is implementet the simplest case is prefered so it does resolve to Cell<T>::get.
Fixes #3033
* rust/compile/nr2/exclude:
* rust/compile/issue-3033.rs: New test.
> gccrs: add test case to show method resolution is working

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-name-resolver.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-stmt.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-hir-type-check.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
This removes a call to `Resolver::get_unit_type_node_id`, which relies on the old resolver calling `Resolver::set_unit_type_node_id`
> Make `TyTy::TupleType::get_unit_type` cache its return value

- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/testsuite/rust/compile/issue-3009.rs
- gcc/testsuite/rust/compile/nr2/exclude
This catch to inject inference variables into generic paths was a catch all 'hack' that we needed before we handled generics correctly as we do now.
Fixes #3009
* typecheck/rust-hir-type-check-path.cc (TypeCheckExpr::resolve_segments): remove hack
* rust/compile/issue-3009.rs: New test.
> gccrs: fix bad type inferencing on path's

- gcc/rust/backend/rust-compile-context.cc
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-typecheck-context.cc
This simplifies `Context::setup_builtins` and removes a direct dependency on the old name resolver
> Remove usage of `Resolver::get_builtin_types`

- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/testsuite/rust/compile/issue-2323.rs
- gcc/testsuite/rust/compile/nr2/exclude
We do not need to inject inference variables on generic patterns with generic blocks. This will just cause unconstrained inference variables as they may not unify against something.
Fixes #2323
* typecheck/rust-hir-type-check-path.cc (TypeCheckExpr::resolve_root_path): dont infer here
* rust/compile/issue-2323.rs: New test.
> gccrs: fix bad type inference on local patterns

- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/testsuite/rust/compile/issue-2953-1.rs
- gcc/testsuite/rust/compile/issue-2953-2.rs
- gcc/testsuite/rust/compile/nr2/exclude
> Fix bad type checking on fn trait calls

- gcc/rust/ast/rust-item.h
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/nr2/exclude
- gcc/testsuite/rust/link/generic_function_0.rs
- gcc/testsuite/rust/link/trait_import_0.rs
- gcc/testsuite/rust/link/trait_import_1.rs
This should partially address #2349, although I'm not sure why `trait_import_*.rs` tests are still failing
> Improve handling of implicit `Self` parameter in AST

- gcc/testsuite/rust/compile/issue-1773.rs
- gcc/testsuite/rust/compile/issue-3242.rs
- gcc/testsuite/rust/compile/nr2/exclude
The original test case 1773 has been moved to a new issue 3242 which is still open and test-case is skipped. The original issue in 1773 is fixed so this will close out that issue
Fixes #1773
* rust/compile/issue-1773.rs: new test case
* rust/compile/issue-3242.rs: old test ranamed to match issue.
> gccrs: add test case to show issue is fixed

- gcc/rust/ast/rust-expr.h
- gcc/rust/backend/rust-compile-asm.cc
- gcc/rust/backend/rust-compile-asm.h
- gcc/rust/checks/errors/rust-unsafe-checker.h
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/typecheck/rust-tyty-call.h
- **hir: Mark AttrVec::get_outer_attrs as override**
- **typecheck: Remove unused parameter in TyTyCheckCallExpr**
- **asm: Fix clang warnings**
> Cleanup clang warnings

- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/testsuite/rust/compile/issue-2905-1.rs
- gcc/testsuite/rust/compile/issue-2905-2.rs
- gcc/testsuite/rust/compile/nr2/exclude
When resolving a type like this which is generic it causes the argument substitution to go through bounds checking which is expected. But this can call a type bounds probe which again calls a type query which will be on the Impl Type on an impl block which can result in a recursive type query which does eventually get caught and errors correctly. But this then triggers some old error diagnositcs which are not valid error codes but old error messages we used to catch simple errors very early on which do not apply for this senario.
Fixes #2905
* typecheck/rust-hir-type-check-item.cc (TypeCheckItem::resolve_impl_block_substitutions): dont check for unconstrained when the self is not resolved
* typecheck/rust-hir-type-check-type.cc (TypeCheckType::resolve_root_path): …
> gccrs: Fix bad handling for recursive type query

- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-name-resolution-context.cc
- gcc/rust/resolve/rust-name-resolution-context.h
Usually, calling these methods would involve an implicit construction of `Rib` from `Rib::Kind`, but just using a `Rib::Kind` as long as possible should work better.
> Push ribs by kind rather than by value

- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
Note that `DefaultResolver::visit` creates a rib of kind `Rib::Kind::ConstantItem` for static items, while before this change `TopLevel::visit` attempted to create a rib of kind `Rib::Kind::Item`
> Improve handling of static items in toplevel 2.0

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/testsuite/rust/compile/nr2/exclude
I probably missed a few spots, but this should cover most of the typechecker
> Use nr2.0 in typechecker

- .github/workflows/commit-format.yml
Issue references shall now be used with the Rust GCC prefix in order to avoid mixing gccrs issues and GCC bugzilla PRs.
Fixes #3213.
> Add a new CI step to detect raw issue references in commit messages

- gcc/rust/ast/rust-stmt.h
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-mangle-legacy.cc
- gcc/rust/backend/rust-mangle-v0.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/rust/util/rust-common.h
- gcc/rust/util/rust-token-converter.cc
- gcc/rust/util/rust-token-converter.h
System includes shall use rust-system header instead.
> Clean up some system includes

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/checks/errors/rust-hir-pattern-analysis.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/exhaustiveness1.rs
- gcc/testsuite/rust/compile/issue-2567-1.rs
- gcc/testsuite/rust/compile/issue-2567-2.rs
- gcc/testsuite/rust/compile/issue-2567-3.rs
- gcc/testsuite/rust/compile/issue-3231.rs
This is a special case in Rust and the ! type can unify with pretty much
anything its almost a inference variable and a unit-type for special cases.
Fixes #3231
Fixes #2567
>  gccrs: empty match expressions should resolve to !

- gcc/rust/resolve/rust-name-resolver.cc
This should make some common dependencies on the old resolver easier to debug
> Prevent execution of some nr1.0 functions with nr2.0

- .github/workflows/ccpp.yml
GCC's baseline was changed from C++11 -> C++14 and GCC 4.8 -> GCC 5.4
in r15-4719-ga9ec1bc06bd3cc, so adjust the baseline CI job accordingly.
One quirk here is that the Ubuntu image we're using in CI has 5.5.0
rather than 5.4.0. But I think we can eat that difference.
ChangeLog:
* .github/workflows/ccpp.yml: Use GCC 5.5 instead of GCC 4.8.
* .github/bors.toml: Update CI job name.
> CI: upgrade GCC baseline from 4.8 -> 5.4 (5.5)

- gcc/rust/hir/rust-hir-dump.cc
* hir/rust-hir-dump.cc (Dump::visit): add missing null checks
> gccrs: fix crash in hir dump with missing guards

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-hir-type-check-type.h
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-typecheck-context.cc
- gcc/testsuite/rust/compile/issue-2907.rs
- gcc/testsuite/rust/compile/nr2/exclude
TypePaths have special handling for Self where we can look at the current ctx for more acurate TypeAlias information if required. We cant do this for Impl contexts but not for Traits as we might as well fall back to the TypePathProbe.
The other issue was the dyn type comming in because Foo::foo and Foo is a trait reference we represent this as a dyn type as the root resolved path but then find the associated impl block for this but we cannot do this when we have resolved to a Dyn because this is just a representation that we know we are talking about a trait not because we are actually working with a real Dyn type.
Fixes #2907
* typecheck/rust-hir-trait-resolve.cc (TraitResolver::resolve_trait): track trait
* typecheck/rust-hir-type-check-implitem.cc: trait block
* …
> gccrs: improve handling of Self Type paths

- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
- gcc/rust/util/rust-lang-item.h
Small cleanup of the lang item mappings in preparation for the remaining lang item patches
> Cleanup lang items mappings

- gcc/rust/backend/rust-compile-implitem.cc
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-hir-pattern-analysis.cc
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/typecheck/rust-hir-trait-resolve.cc
Both TraitItemFunc::has_definition() and TraitItemFunc::has_block_defined() were exactly the same implementation, so remove one.
* hir/tree/rust-hir-item.h: Remove TraitItemFunc::has_block_defined()
* backend/rust-compile-implitem.cc (CompileTraitItem::visit): Call TraitItemFunc::has_definition() instead.
* checks/errors/rust-const-checker.cc (ConstChecker::visit): Likewise.
* checks/errors/rust-hir-pattern-analysis.cc (PatternChecker::visit): Likewise.
* checks/errors/rust-unsafe-checker.cc (UnsafeChecker::visit): Likewise.
* typecheck/rust-hir-trait-resolve.cc (ResolveTraitItemToRef::visit): Likewise.
> hir: Remove duplicate function in TraitItemFunc

- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/checks/errors/rust-ast-validation.cc
- gcc/rust/util/rust-stacked-contexts.h
As part of my cleanups for lang-items, which should land soon...
This uses the `StackedContexts` API which is safer than a simple vector for keeping track of context
> Cleanup `ContextualASTVisitor`

- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/testsuite/rust/compile/issue-2423.rs
- gcc/testsuite/rust/compile/nr2/exclude
This was a handy debug assertion but only works for valid rust code. This needs to handle the case where the type is not resolved which is a valid case.
Fixes #2423
* resolve/rust-ast-resolve-item.cc (ResolveItem::visit): remove assertions
* rust/compile/nr2/exclude: nr2 can't handle this
* rust/compile/issue-2423.rs: New test.
> gccrs: Remove bad assertion in name resolution

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-base.h
- gcc/rust/backend/rust-compile-implitem.cc
- gcc/rust/backend/rust-compile-item.cc
- gcc/testsuite/rust/compile/issue-1525.rs
The code here was wrongly assuming the decl type from the folding of the expression would be the type of the constant decl. This is not the case for unsized coercions for slices, where the expression here is a reference to an array then we require the coercion to fix the result up to the expected type.
Fixes Rust-GCC#1525
* backend/rust-compile-base.cc: apply coercion site to result
* backend/rust-compile-base.h: update prototype
* backend/rust-compile-implitem.cc (CompileTraitItem::visit): send in coercion info
* backend/rust-compile-item.cc (CompileItem::visit): likewise
* rust/compile/issue-1525.rs: New test.
> gccrs: constant evaluation like these are coercion sites

- gcc/rust/backend/rust-constexpr.cc
- gcc/rust/rust-gcc.cc
- gcc/testsuite/rust/compile/issue-2394.rs
These are ported from the c-family code c-warn.cc and c-typchk.cc
Fixes Rust-GCC#2394
* backend/rust-constexpr.cc (eval_store_expression): check for null
(eval_call_expression): formatting
(eval_loop_expr): formatting
* rust-gcc.cc (arithmetic_or_logical_expression): add warnings
* rust/compile/issue-2394.rs: New test.
> gccrs: add checks for division by zero and left shift overflow

- gcc/rust/hir/rust-hir-dump.cc
* hir/rust-hir-dump.cc (Dump::visit): add missing check for no return value
> gccrs: fix crash in hir dump

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-collect-lang-items.cc
- gcc/rust/ast/rust-collect-lang-items.h
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/rust-session-manager.cc
- gcc/rust/util/rust-attributes.cc
- gcc/rust/util/rust-attributes.h
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
In order to have lang items paths, we need to be able to resolve these lang items to their definition point which is impossible in the current system, as lang items are only saved in the mappings during lowering (and thus after name resolution). This small visitor collects lang items and stores their NodeIds in the mappings for an easy resolution.
> Collect lang items in the AST

- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-item.h
- gcc/rust/ast/rust-path.cc
- gcc/rust/ast/rust-path.h
- gcc/rust/expand/rust-derive-copy.cc
- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/rust/hir/rust-ast-lower-type.h
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-type.h
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
This PR makes it possible to use lang items as paths, for example when generating code for derives or for-loops. Instead of generating a complex path to something like `core::marker::Copy`, we can just use a `LangItemPath` to `LangItem::COPY`. This way, the code generation does not need to care about name resolution, about std's module hierarchy changing, or about duplicate definitions with the same module structure (e.g. if a user defines a copy trait in their own source file with their own `core` and `marker` module).
This is not going to build until #3289 is merged as it depends on those mappings - but it should still be reviewable
> Use lang items as paths

- .github/glibcxx_ubuntu64b_log_expected_warnings
- .github/log_expected_warnings
- configure
- configure.ac
- gcc/doc/install.texi
We moved to a bootstrap requirement of C++11 in GCC 11, 8 years after support was stable in GCC 4.8.
It is now 8 years since C++14 was the default mode in GCC 6 (and 9 years since support was complete in GCC 5), and we have a few bits of optional C++14 code in the compiler, so it seems a good time to update the bootstrap requirement again.
The big benefit of the change is the greater constexpr power, but C++14 also added variable templates, generic lambdas, lambda init-capture, binary literals, and numeric literal digit separators.
C++14 was feature-complete in GCC 5, and became the default in GCC 6.  5.4.0 bootstraps trunk correctly; trunk stage1 built with 5.3.0 breaks in eh_data_format_name due to PR69995.
gcc/ChangeLog:
* doc/install.texi (Prerequisites): Update to C++14.
ChangeLog:
* …
> build: update bootstrap req to C++14

- gcc/rust/backend/rust-compile-fnparam.cc
- gcc/rust/backend/rust-compile-fnparam.h
- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-pattern.h
- gcc/testsuite/rust/compile/issue-2847.rs
In order to handle the tuple pattern of: ````fn test ((x _) : (i32, i32)) -> i32 { x }``` we need to recognize that ABI wise this function still takes a tuple as the parameter to this function its just how we can address the "pattern" of the tuple changes.
So reall if this was C it would look like:
```c
void test (struct tuple_type __prameter)
{
return __parameter.0
}
```
The code here reuses our existing pattern code so that we generate these implicit bindings of the paramter with a field access so any time x is referenced it's really just emplacing __parameter.0 for the field access into the struct which is a tuple.
Fixes Rust-GCC#2847
* backend/rust-compile-fnparam.cc (CompileFnParam::visit): compile tuple patterns
(CompileFnParam::create_tmp_param_var): return …
> gccrs: implement the TuplePattern and use it for function patterns

- gcc/rust/ast/rust-item.h
* ast/rust-item.h: I have changed helper constructor for typepath to be a delegating constructor.
Fixes #3296
> gccrs: Made changes to AST::TraitImpl constructor for TypePath

- .github/workflows/ccpp.yml
> gccrs: disable macos github workflow

- gcc/rust/typecheck/rust-hir-path-probe.cc
- gcc/rust/typecheck/rust-hir-path-probe.h
- gcc/rust/typecheck/rust-hir-type-check-path.cc
* typecheck/rust-hir-path-probe.cc: Fix typos.
* typecheck/rust-hir-path-probe.h: Likewise.
* typecheck/rust-hir-type-check-path.cc: Likewise.
> typecheck-path: Fix typo (reciever -> receiver)

- gcc/testsuite/rust/compile/multiline-string.rs
- gcc/testsuite/rust/execute/torture/multiline-string.rs
Regression checks for Rust-GCC#1399. Fixes #1399
> parser: Add testcases for multiline strings

- gcc/rust/resolve/rust-ast-resolve-type.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/util/rust-lang-item.cc
- gcc/rust/util/rust-lang-item.h
- gcc/testsuite/rust/compile/additional-trait-bounds1.rs
- gcc/testsuite/rust/compile/additional-trait-bounds2.rs
- gcc/testsuite/rust/compile/additional-trait-bounds2nr2.rs
- gcc/testsuite/rust/compile/nr2/exclude
> Add resolution for additional trait bounds

- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/ast/rust-path.h
This commit adds new methods for building pattern nodes, match expressions and more precise call expressions.
> ast-builder: Add more methods

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/issue-3304.rs
Fixes #3304
Here is a checklist to help you with your PR.
Note that you can skip the above if you are just opening a WIP PR in
order to get feedback.
---
*Please write a comment explaining your change. This is the message
that will be part of the merge commit.
> Fix name resolution for enums with generics

- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/rust/hir/rust-ast-lower-type.h
- gcc/rust/resolve/rust-ast-resolve-type.cc
- gcc/rust/resolve/rust-ast-resolve-type.h
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-hir-type-check-type.h
- gcc/testsuite/rust/compile/auto_traits1.rs
- gcc/testsuite/rust/compile/auto_traits2.rs
- gcc/testsuite/rust/compile/auto_traits3.rs
- gcc/testsuite/rust/compile/nr2/exclude
Needs #3324 
This allows us to start looking at more handling for auto traits and multiple trait bounds, as they are always represented as parenthesized types when used in function parameters
> Resolve and lower parenthesized types

- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.h
- gcc/testsuite/rust/compile/nr2/exclude
> nr2.0: Resolve type aliases inside trait definitions

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-typecheck-context.cc
Replaces the DIY vector stack with a StackedContexts object for block
scopes in the type checker context.
Fixes #3284.
* typecheck/rust-hir-type-check.h (class TypeCheckContext): add
header file and use StackedContexts for blocks
* typecheck/rust-typecheck-context.cc: update methods
* typecheck/rust-hir-trait-resolve.cc: refactor function calls
* typecheck/rust-hir-type-check-implitem.cc: refactor function calls
* typecheck/rust-hir-type-check-type.cc: refactor function calls
Signed-off-by: Prajwal S N <prajwalnadig21@gmail.com>
> refactor(typecheck): StackedContexts for blocks

- gcc/rust/hir/rust-hir-dump.cc
These hir nodes have optional expressions which need guarded
* hir/rust-hir-dump.cc (Dump::do_qualifiedpathtype): add guard
(Dump::do_traitfunctiondecl): likewise
(Dump::visit): likewise
> gccrs: fix ICE during HIR dump

- gcc/rust/resolve/rust-default-resolver.cc
- gcc/rust/resolve/rust-default-resolver.h
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.h
- gcc/testsuite/rust/compile/nr2/exclude
May overlap with #3307, apologies to @liamnaddell
> nr2.0: Improve default and top-level resolvers

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-tyty-call.cc
- gcc/testsuite/rust/compile/issue-3046.rs
- gcc/testsuite/rust/compile/issue-3140.rs
- gcc/testsuite/rust/compile/nr2/exclude
We need to check if the borrowed value is valid before creating the reference type. Otherwise this will lead to an ICE.
Fixes Rust-GCC#3140
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): check for error
* typecheck/rust-tyty-call.cc (TypeCheckCallExpr::visit): likewise and remove debug error
* rust/compile/issue-3046.rs: remove old error message
* rust/compile/issue-3140.rs: New test.
> gccrs: fix ICE in borrows to invalid expressions

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-expr.h
- gcc/rust/hir/tree/rust-hir-expr.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/rust/util/rust-lang-item.cc
- gcc/rust/util/rust-lang-item.h
- gcc/rust/util/rust-operators.h
- gcc/testsuite/rust/compile/cmp1.rs
- gcc/testsuite/rust/compile/nr2/exclude
The Eq and Partial Ord are very similar to the operator overloads we support for add/sub/etc... but they differ in that usually the function call name matches the name of the lang item. This time we need to have support to send in a new path for the method call on the lang item we want instead of just the name of the lang item.
NOTE: this test case doesnt work correctly yet we need to support the derive of partial eq on enums to generate the correct comparison code for that.
Fixes Rust-GCC#3302
* backend/rust-compile-expr.cc (CompileExpr::visit): handle partial_eq possible call
* backend/rust-compile-expr.h: handle case where lang item calls differ from name
* hir/tree/rust-hir-expr.cc (OperatorExprMeta::OperatorExprMeta): new helper
* hir/tree/rust-hir-expr.h: …
> gccrs: add support for lang_item eq and PartialEq trait

- gcc/rust/hir/rust-hir-dump.cc
Return type and parameter types are optional on closures.
* hir/rust-hir-dump.cc (Dump::visit): add null guard
> gccrs: fix ICE with hir dump on closure

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/backend/rust-compile-type.cc
- gcc/rust/rust-gcc.cc
This changes our enum type layout so for example:
```rust
enum Foo {
A,
B,
C(char),
D { x: i32, y: i32 },
}
```
Used to get layed out like this in gccrs:
```c
union {
struct A { int RUST$ENUM$DISR; };
struct B { int RUST$ENUM$DISR; };
struct C { int RUST$ENUM$DISR; char __0; };
struct D { int RUST$ENUM$DISR; i64 x; i64 y; };
}
```
This has some issues notably with the constexpr because this is just a giant union it means its not simple to constify what enum variant we are looking at because the discriminant is a mess.
This now gets layed out as:
```c
struct {
int RUST$ENUM$DISR;
union {
struct A { };
struct B { };
struct C { char __0; };
struct D { i64 x; i64 y; };
} payload;
}
```
This layout is much cleaner and allows for our constexpr to work properly.
* …
> gccrs: cleanup our enum type layout to be closer to rustc

- gcc/rust/typecheck/rust-casts.cc
- gcc/testsuite/rust/compile/cast_float_as_integer.rs
#3270 added rules for `int -> float` casts but not the opposite .
This PR should add  support for `float -> int` casts and fully fix #3261.
> Allow float type to be casted as integer type

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-unify.cc
Unify rules are not the same as coercion rules. The coercion of ! is allowed to any type but not for a unify site which is different.
* backend/rust-compile-expr.cc (CompileExpr::visit): implement coercion
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): this is a least upper bound coercion
* typecheck/rust-unify.cc (UnifyRules::go): remove unify ! coercion
> gccrs: match arms are a LUB

- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/rust/lang.opt
- gcc/rust/rust-lang.cc
- gcc/rust/rust-session-manager.cc
- gcc/rust/rust-session-manager.h
- gcc/testsuite/rust/compile/try-catch-unwind-new.rs
- gcc/testsuite/rust/compile/try-catch-unwind-old.rs
This pull request adds the `try` intrinsic, making it possible to handle `panic`s.
A new option, `-frust-panic` is added to specify the panic handling strategy.
Note that currently, only `try`-`catch` mechanism is added in this pull request.
To correctly handle the `panic` structures, an unwinder must also be implemented (in the runtime library).
> Add `try` intrinsics

- gcc/rust/checks/errors/rust-readonly-check.cc
- gcc/testsuite/rust/compile/mutability_checks1.rs
- gcc/testsuite/rust/execute/torture/builtin_macro_include_bytes.rs
This ensures that we handle var decls readonly checks much better
Addresses: Rust-GCC#807 Rust-GCC#3287
* checks/errors/rust-readonly-check.cc (check_decl): improve mut check
(emit_error): helper
(check_modify_expr): likewise
(readonly_walk_fn): reuse helper
(ReadonlyCheck::Lint): cleanup context each run
* rust/execute/torture/builtin_macro_include_bytes.rs: missing mut
> gccrs: improve mutability checks

- gcc/rust/Make-lang.in
- gcc/rust/resolve/rust-forever-stack.cc
- gcc/rust/resolve/rust-forever-stack.h
`ForeverStackStore` is meant to partially unify the internal states of per-namespace `ForeverStack` instances. This PR doesn't contain modifications to `ForeverStack` which would allow it to rely on a `ForeverStackStore` to store nodes, but a future PR should address this.
> Add `ForeverStackStore`

- gcc/testsuite/rust/compile/issue-1446.rs
- gcc/testsuite/rust/compile/iterators1.rs
- gcc/testsuite/rust/compile/macros/builtin/eager1.rs
- gcc/testsuite/rust/compile/macros/builtin/recurse2.rs
Some failures occur in the testsuite because we
did not account for the big-endian case.
* rust/compile/issue-1446.rs: Add swap_bytes function.
* rust/compile/iterators1.rs: Remove unused {to, from}_le functions.
Before merging this I would like to run our testsuite on the compile farm on a SPARC machine to see that they're really fixed. Will report here once it's done.
> testsuite: Fix missing handling of little endian.

- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/expand/rust-derive-clone.cc
- gcc/rust/expand/rust-derive-clone.h
- gcc/rust/expand/rust-derive-copy.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/derive_clone_enum1.rs
- gcc/testsuite/rust/compile/derive_clone_enum2.rs
- gcc/testsuite/rust/compile/derive_clone_enum3.rs
- gcc/testsuite/rust/compile/derive_macro1.rs
- gcc/testsuite/rust/compile/derive_macro3.rs
- gcc/testsuite/rust/compile/derive_macro4.rs
- gcc/testsuite/rust/compile/derive_macro6.rs
- gcc/testsuite/rust/compile/nr2/exclude
- gcc/testsuite/rust/execute/torture/derive_clone_enum1.rs
- gcc/testsuite/rust/execute/torture/derive_macro3.rs
- gcc/testsuite/rust/execute/torture/derive_macro4.rs
This PR changes how lang item paths are handled and subsequently finishes the implementation of `derive(Clone)` for enums and their variants. Putting it as a draft since it's a mess and needs cleaning up. Addresses #2996, but we still need to properly implement generic Clone I think?
I might instead split this up in multiple PRs to first refactor the lang item paths and then finish implementing `derive(Clone)` on top of it - next week.
Needs #3366
> Finish `derive(Clone)` for enums

- gcc/rust/util/rust-lang-item.cc
- gcc/rust/util/rust-lang-item.h
- gcc/testsuite/rust/compile/issue-2954.rs
Add and implement a lang item (receiver) in source code.
Fix [#2954](https://github.com/Rust-GCC/gccrs/issues/2954)
* util/rust-lang-item.cc: Add receiver to map.
* util/rust-lang-item.h: Define LangItem::Kind::RECEIVER.
* rust/compile/issue-2954.rs: New test.
> Add receiver lang item

- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/expand/rust-derive-clone.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/testsuite/rust/compile/derive_macro6.rs
When deriving `Clone` for a type with generic, we need to bound the impl's generic to be `: Clone`. e.g. the derive of `struct Foo<T>` should always be `impl<T: Clone> Clone for Foo<T>` even if `T` isn't necessarily bound by `Clone` in the struct's definition. Requires #3343 and thus #3366 so only review the last 3 commits
> Improve `derive(Clone)` for generic types

- gcc/rust/expand/rust-derive-copy.cc
> derive(Copy): Improve bounds when deriving Copy

- gcc/rust/Make-lang.in
- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/resolve/rust-ice-finalizer.cc
- gcc/rust/resolve/rust-ice-finalizer.h
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
- gcc/testsuite/rust/compile/nr2/exclude
Nr2 did not emit the correct error message for break identifier "rust".
> Fix rust breakage with nr2

- gcc/rust/util/rust-lang-item.cc
- gcc/rust/util/rust-lang-item.h
- gcc/testsuite/rust/compile/try-trait.rs
This is a necessary step for starting to handle the desugar of `<expr>?`. In Rust 1.49, the desugar looks like this:
```rust
/// match Try::into_result(<expr>) {
///     Ok(val) => #[allow(unreachable_code)] val,
///     Err(err) => #[allow(unreachable_code)]
///                 return Try::from_error(From::from(err)),
/// }
```
which uses 4 out of the 5 lang items added in this PR. the remaining lang item is used for try blocks, an unstable feature which I'm not sure we need to support at first for `std`
> lang-items: Add Result and Try lang items

- gcc/rust/backend/rust-compile-expr.cc
This commit is required for this type of pattern, which isn't really pattern matching:
```rust
match something {
new_binding => { ... }
}
```
This is required for desugaring for-loops and error propagation expressions.
> backend: Allow anything as a match scrutinee

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/nr2/exclude
Some of our tests only work with name resolution 2.0 because the latter misinterprets type paths. This change should cause the compiler to error out if it would otherwise misinterpret a type path. A fix for type path resolution isn't included in this comment, since doing so would make it harder to track the meaningfulness of test regressions.
> Check for type paths nr2.0 can't handle yet

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
- gcc/rust/resolve/rust-name-resolver.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
Remove usage of nr1 resolver with closure captures.
> Nr2 closure captures

- gcc/rust/rust-session-manager.cc
- gcc/rust/rust-session-manager.h
```
* rust-session-manager.cc (Session::handle_crate_name): Remove                    
crate name inference                                                              
(Session::compile_crate): Add crate name inference and error if                   
inferred name is empty. Remove CompileOptions::get_instance ()                    
that returned a local copy of the options. Rename                                 
crate_name_changed to crate_name_found to match semantics.                        
(rust_crate_name_validation_test): Test inferring ".rs" name                      
* rust-session-manager.h: Modify handle_crate_name definition to                  
include filename.
```
Fixes #3129. Also fixes an issue where filenames such as ".rs" provided cause an ICE. …
> Infer crate name after file opening

- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/testsuite/rust/compile/nr2/exclude
When we lookup here it returns an optional which can lead to a crash because it needs a guard if it has a value.
* backend/rust-compile-resolve-path.cc (HIRCompileBase::query_compile): add guard
* rust/compile/nr2/exclude: these tests now work it seems
> gccrs: catch missing guard for optional result

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/lang.opt
This will be crucial for more complex gimple debugging to make it easier to follow the code vs the original rust code.
* backend/rust-compile-expr.cc (CompileExpr::visit): disable overflow checks
* lang.opt: new flag
> gccrs: add new -frust-overflow-checks to control overflow checks

- gcc/rust/util/rust-lang-item.cc
- gcc/rust/util/rust-lang-item.h
In Rust 1.49, `From::from` is a lang item as it is used in the `<expr>?` desugar
> lang-items: Add From::from

- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/issue-3174.rs
- gcc/testsuite/rust/compile/nr2/exclude
> gccrs: add support for ref literal patterns

- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-expr.h
Collapses all of the OperatorExprs into Expr instead of first having to check for OperatorExpr and then check for each OperatorExpr::Kind.
> ast: Add new Expr::Kinds

- gcc/rust/expand/rust-macro-builtins-utility.cc
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/macros/builtin/option_env1.rs
- gcc/testsuite/rust/compile/macros/builtin/option_env2.rs
- gcc/testsuite/rust/compile/macros/builtin/option_env3.rs
- gcc/testsuite/rust/execute/torture/builtin_macro_option_env.rs
```
* expand/rust-macro-builtins-utility.cc: Add macro expansion for
option_env with eager expansion
* expand/rust-macro-builtins.cc: Add option_env to builtin list
* expand/rust-macro-builtins.h: Add option_env handler to header
file
* rust/compile/macros/builtin/option_env1.rs: Add success case for option_env
* rust/compile/macros/builtin/option_env2.rs: Add failure case for option_env
* rust/execute/torture/builtin_macro_option_env.rs: Add
execution case for option_env
* rust/compile/nr2/exclude: Some issues with nr2 need to be
resolved before allowing option_env with NR2.0.
```
Fixes #1806 
Addresses #927, #1791 
Here is a checklist to help you with your PR.
- \[x] GCC development requires copyright assignment or the Developer's Certificate …
> Add option_env support

- gcc/rust/util/rust-lang-item.cc
- gcc/rust/util/rust-lang-item.h
- gcc/testsuite/rust/compile/structural-eq-peq.rs
These lang items are used when deriving Eq and PartialEq, and will be checked when compiling pattern matching.
* util/rust-lang-item.cc: New items.
* util/rust-lang-item.h: Likewise.
* rust/compile/structural-eq-peq.rs: New test.
> lang-items: Add structural_{peq, teq}

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
Needs #3094 so only review the last commit
@liamnaddell @powerboat9 how does that look to you?
> Resolve lang-item PathInExpressions in nr2.0 late resolver

- gcc/rust/checks/lints/rust-lint-scan-deadcode.h
* checks/lints/rust-lint-scan-deadcode.h: Check if the field name starts with an underscore before warning.
> Do not warn about unused fields if they start with '_'

- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
Add new methods for building `return <x>;` expressions/statements in our AST.
> ast: builder: Add Return expression builder

- gcc/rust/typecheck/rust-tyty.cc
We needed to check for the optional has a value here or not it leads to an ICE.
* typecheck/rust-tyty.cc (ClosureType::setup_fn_once_output): add checks for lang items
> gccrs: Fix ICE when fn_once and fn_once_output lang item is not defined

- gcc/rust/typecheck/rust-hir-path-probe.cc
It is valid for the query to fail here so its valid to not assert here.
* typecheck/rust-hir-path-probe.cc (PathProbeType::visit): remove assertion
> gccrs: Fix ICE during path probe

- gcc/rust/typecheck/rust-type-util.cc
- gcc/testsuite/rust/compile/reference1.rs
Addresses Rust-GCC #3381 Rust-GCC #3382 
* typecheck/rust-type-util.cc (coercion_site): allow inference vars
* rust/compile/reference1.rs: fix error message
> gccrs: coercion sites allow for type inference as well.

- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
This guards against a crash but i think this should actually be treated as if its a generic type like below. But for now this addresses a crash which can occur.
* checks/errors/privacy/rust-privacy-reporter.cc (PrivacyReporter::check_base_type_privacy): Add guard for placeholder
> gccrs: Fix crash in privay reporter for placeholder types

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-item.cc
- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-typecheck-context.cc
- gcc/testsuite/rust/execute/torture/issue-3381.rs
When we have paths such as Try::from_error the Try references the Trait and then from_error references the from_error trait item. So this resolves directly to a trait implementation which has the type:
fn <Self> (v: placeholder) -> Self
Remember that a path such as: Try::from_error gets handled by doing a
clever substitution: <T? as Try>::from_error
The main piece here is that we resolve this function type and for monomoprhization we know this is a trait call but we know that all trait's have an implicit Self type param which in this case is Result<i32, i32> so when it comes to knowing which impl block this is we got rid of the old bad insert/lookup receiver hack and use the specified type to know which impl block we are talking about to generate the function.
The hard part here is inside …
> gccrs: Fix compilation of trait-items which map to impl items

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/expand/rust-derive-debug.cc
- gcc/rust/expand/rust-derive-default.cc
- gcc/rust/expand/rust-derive-default.h
- gcc/rust/expand/rust-derive.cc
- gcc/testsuite/rust/compile/derive-default1.rs
- gcc/testsuite/rust/compile/nr2/exclude
- gcc/testsuite/rust/execute/torture/derive-default1.rs
Needs #3398 for the builder methods and #3400
Fixes #2993
> Add `derive(Default)`

- gcc/rust/Make-lang.in
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/rust/util/rust-unwrap-segment.cc
- gcc/rust/util/rust-unwrap-segment.h
- gcc/testsuite/rust/compile/nr2/exclude
> Resolve instances of `TypePath` more accurately

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/ast/rust-desugar-for-loops.cc
- gcc/rust/ast/rust-desugar-for-loops.h
- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/rust-session-manager.cc
- gcc/testsuite/rust/compile/for-loop1.rs
- gcc/testsuite/rust/compile/for-loop2.rs
- gcc/testsuite/rust/compile/nr2/exclude
- gcc/testsuite/rust/execute/torture/for-loop1.rs
- gcc/testsuite/rust/execute/torture/for-loop2.rs
I'm not a big fan of mutating the AST to do this, however this enables us to desugar for-loops easily. The alternative is desugaring during the lowering phase, which has the issue of not inserting any information about the generated nodes into our name resolver. This leads to failures during typechecking which is annoying.
The best thing would be to figure out a way to insert resolved nodes when we do the Desugar, but it's a bit tricky.
> Desugar for-loops in the AST

- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/testsuite/rust/compile/issue-3403.rs
- gcc/testsuite/rust/compile/nr2/exclude
This was a bad diagnostic added when I was working on slices and iterators also the name of the function is also bad. This is all about setting up associated types based on the current context of the bounds assocated with the associated trait bounds on this function.
The tell tale is that this didnt have an associated rust error code so this is most definetly not the correct error diagnostic.
Fixes Rust-GCC#3403
* typecheck/rust-tyty-subst.cc (SubstitutionRef::monomorphize): remove diagnostic
* rust/compile/issue-3403.rs: New test.
> gccrs: remove bad type checking diagnostic

- gcc/rust/typecheck/rust-autoderef.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-typecheck-context.cc
- Updated single-parameter calls to pass an explicit HirId alongside the type.
- This refactor ensures that all calls to insert_implicit_type consistently use the two-parameter version, improving clarity and maintainability of type mapping tracking.
Fixes https://github.com/Rust-GCC/gccrs/issues/3396
Signed-off-by: Guransh Singh <guransh766@gmail.com>
> Get rid of duplicate interface #3396

- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/rust/util/rust-lang-item.cc
- gcc/rust/util/rust-lang-item.h
- gcc/testsuite/rust/execute/torture/enum_intrinsics1.rs
This is pretty nasty piece of rust in my opinion the return type of this intrinsic results into a lang item associated type:
```<T as DiscriminantKind>::Discriminant```
This is a special case which needs to support mapping onto the repr type of the associated ADT that is passed in, but defaults to isize otherwise.
This patch assumes we only come accross this case in a HIR::CALL_EXPR, so and makes assumutions that its always of this function signiture. I will do some checking in libcore to verify that assumption. More work is needed to parse the repr type on enums but the code is there to support this when its in to change the types etc.
Addresses Rust-GCC#3348
* backend/rust-compile-intrinsic.cc (discriminant_value_handler): new handler
* …
> gccrs: add discriminant value intrinsic

- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/testsuite/rust/execute/torture/enum_intrinsics2.rs
Addresses Rust-GCC#3348
* backend/rust-compile-intrinsic.cc (variant_count_handler): new intrinsic
* rust/execute/torture/enum_intrinsics2.rs: New test.
> gccrs: add variant_count intrinsic

- gcc/rust/backend/rust-compile-type.cc
- gcc/rust/backend/rust-compile-type.h
Addresses Rust-GCC#3352
* backend/rust-compile-type.cc (TyTyResolveCompile::get_implicit_enumeral_node_type): use repr (TyTyResolveCompile::visit): update prototype
* backend/rust-compile-type.h: likewise
> gccrs: enum type layout needs to respect the enum repr type

- gcc/rust/typecheck/rust-hir-type-check-base.h
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-hir-type-check-type.h
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/testsuite/rust/compile/issue-2369.rs
gccrs: add diagnostic for E0229 no associated type arguments allowed here
It seems bounds in qualified paths are not allowed to specify associated
type bindings because its going to be associated with the impl block
anyway.
Fixes Rust-GCC#2369
* typecheck/rust-hir-type-check-base.h: add flag
* typecheck/rust-hir-type-check-type.cc (TypeCheckType::visit): likewise
* typecheck/rust-tyty-bounds.cc: new diagnostic
* rust/compile/issue-2369.rs: New test.
> gccrs: add diagnostic for E0229 no associated type arguments allowed here

- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-stmt.h
- gcc/rust/resolve/rust-ast-resolve-type.h
Rust allows you to use generics within type bounds when they are declared later on. This changes the name resolution to walk the genric params in two passes to ensure the type parameters are setup before drilling down into the type parameters
This issue has exposed another type checking issue which needs fixed in a subseqent patch.
Addresses Rust-GCC#3022
* resolve/rust-ast-resolve-item.cc (ResolveTraitItems::visit): use new api
(ResolveItem::visit): likewise
(ResolveExternItem::visit): likewise
* resolve/rust-ast-resolve-stmt.h: likewise
* resolve/rust-ast-resolve-type.h (class ResolveGenericParam): remove
(class ResolveGenericParams): added new api
> gccrs: fix name resolution for generics where type param is declared later

- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/testsuite/rust/compile/issue-3022.rs
With simple patterns we dont introduce any more inference varaibles as
they are already declared in a specific way. This would only lead to
more unconstrained inference varaibles than is required.
Fixes Rust-GCC#3022
Depends on https://github.com/Rust-GCC/gccrs/pull/3435
> gccrs: self paths are patterns but we dont have mappings for it

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/generics4.rs
- gcc/testsuite/rust/compile/generics6.rs
- gcc/testsuite/rust/compile/issue-2035.rs
- gcc/testsuite/rust/compile/type-bindings1.rs
- gcc/testsuite/rust/compile/unconstrained_type_param.rs
We have the type information for the resolved call lets tell the user about it in the diagnostic and apply the correct error code.
Fixes Rust-GCC#2035
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): improve error diag
* rust/compile/generics4.rs: cleanup
* rust/compile/generics6.rs: likewise
* rust/compile/type-bindings1.rs: likewise
* rust/compile/unconstrained_type_param.rs: likewise
* rust/compile/issue-2035.rs: New test.
> gccrs: improve error diagnostic for bad type-resolution in CallExpr

- gcc/rust/checks/errors/borrowck/rust-bir-builder-struct.h
- gcc/rust/checks/errors/borrowck/rust-function-collector.h
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-const-checker.h
- gcc/rust/checks/errors/rust-hir-pattern-analysis.cc
- gcc/rust/checks/errors/rust-hir-pattern-analysis.h
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/checks/errors/rust-unsafe-checker.h
- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/rust/hir/rust-ast-lower-type.h
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
- gcc/rust/hir/tree/rust-hir-full-decls.h
- gcc/rust/hir/tree/rust-hir-type.h
- gcc/rust/hir/tree/rust-hir-visitor.h
- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/resolve/rust-ast-resolve-type.cc
- gcc/rust/resolve/rust-ast-resolve-type.h
- gcc/rust/typecheck/rust-hir-type-check-type.h
Our AST has ImplTraitType for multiple bounds and a singular ImplTraitTypeOneBound, this patch desugars these into a simple HIR::ImplTraitType. It also does the name resolution for this.
* checks/errors/borrowck/rust-bir-builder-struct.h: remove HIR::ImplTraitTypeOneBound
* checks/errors/borrowck/rust-function-collector.h: likewise
* checks/errors/rust-const-checker.cc (ConstChecker::visit): likewise
* checks/errors/rust-const-checker.h: likewise
* checks/errors/rust-hir-pattern-analysis.cc (PatternChecker::visit): likewise
* checks/errors/rust-hir-pattern-analysis.h: likewise
* checks/errors/rust-unsafe-checker.cc (UnsafeChecker::visit): likewise
* checks/errors/rust-unsafe-checker.h: likewise
* hir/rust-ast-lower-type.cc (ASTLoweringType::translate): likewise …
> gccrs: Add name resolution and HIR lowering for ImplTraitType's

- gcc/rust/backend/rust-compile-type.cc
- gcc/rust/backend/rust-compile-type.h
- gcc/rust/checks/errors/borrowck/rust-bir-fact-collector.h
- gcc/rust/checks/errors/borrowck/rust-bir-place.h
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-hir-type-check-type.h
- gcc/rust/typecheck/rust-substitution-mapper.cc
- gcc/rust/typecheck/rust-substitution-mapper.h
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty-call.h
- gcc/rust/typecheck/rust-tyty-cmp.h
- gcc/rust/typecheck/rust-tyty-variance-analysis-private.h
- gcc/rust/typecheck/rust-tyty-visitor.h
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/rust/typecheck/rust-unify.cc
- gcc/rust/typecheck/rust-unify.h
This completes the initial setup and boilerplate for the new type in the
typesystem. This is not functional yet but its a big patch already.
> gccrs: initial setup for new OpaqueType to represent Impl types

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/if-without-else.rs
- gcc/testsuite/rust/compile/implicit_returns_err3.rs
- gcc/testsuite/rust/compile/torture/if.rs
Check if an if-expr return void type.
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): Add check on if-expr.
* rust/compile/implicit_returns_err3.rs: Change test to be valid.
* rust/compile/torture/if.rs: Likewise.
* rust/compile/if-without-else.rs: New test.
Fixes: #3230
> Add type check on if-expr

- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/nr2/exclude
When visiting an external crate declaration, handle failed crate name lookups. This can happen when `Session::load_extern_crate` fails to load a crate during the `CfgStrip` phase.
> nr2.0: Fix issue with external crates

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/expand/rust-derive-clone.cc
- gcc/rust/expand/rust-derive-clone.h
- gcc/rust/expand/rust-derive-eq.cc
- gcc/rust/expand/rust-derive-eq.h
- gcc/rust/expand/rust-derive-partial-eq.cc
- gcc/rust/expand/rust-derive-partial-eq.h
- gcc/rust/expand/rust-derive.cc
- gcc/rust/expand/rust-derive.h
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/testsuite/rust/compile/derive-eq-invalid.rs
- gcc/testsuite/rust/compile/derive-partialeq1.rs
- gcc/testsuite/rust/compile/nr2/exclude
- gcc/testsuite/rust/execute/torture/derive-partialeq1.rs
Fixes #2992 
This adds a base for deriving `PartialEq` and `Eq` but misses some more complex stuff like struct enum items, as we need to add more to our nameres and codegen to handle these rebinding patterns.
~~We also need to rework this part of the expansion pass as `derive(Eq)` and `derive(PartialEq)` should both create *two* impls: one of their trait, and one of the associated `Structural*` trait~~ this is now done in this PR.
This is ready for reviewing and merging IMO as a first basic implementation of `derive(PartialEq)` even if it does not support all types of Rust enums
> derive(PartialEq): Add partial implementation (hehe)

- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-expand-visitor.h
- gcc/testsuite/rust/compile/macros/mbe/macro-expand-module.rs
> Fix expansion of macros inside modules

- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/tree/rust-hir-path.h
* hir/rust-hir-dump.cc: Check unique_ptr members are present before visiting them.
* hir/tree/rust-hir-path.h: Add `has_{type, trait}` methods to QualifiedPathInType.
> hir-dump: Fix more segfaults in the HIR dump

- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/rust/resolve/rust-early-name-resolver.h
- gcc/testsuite/rust/compile/issue-2015.rs
> Fix macro invocation in impl trait type bound

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-pattern.cc
- gcc/rust/checks/errors/rust-feature.h
- gcc/rust/expand/rust-macro-builtins-helpers.h
- gcc/rust/expand/rust-macro-builtins-include.cc
- gcc/rust/expand/rust-macro-builtins-utility.cc
- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/lex/rust-lex.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/util/rust-edition.cc
- gcc/rust/util/rust-edition.h
I ran into some issues getting edition information in `rust-forever-stack.hxx`, created `rust-edition.h` and `rust-edition.cc`, and realized this would make sense as a separate patch
> Reduce usage of `rust-session-manager.h`

- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/expand/rust-macro-substitute-ctx.cc
- gcc/rust/expand/rust-macro-substitute-ctx.h
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
- gcc/testsuite/rust/compile/crate-metavar1.rs
- gcc/testsuite/rust/execute/crate-metavar1.rs
This is better than what we currently do but it is missing a test for checking that we can properly call macros from external crates. I might add it later but it's a bit of a pain. Fixes #2833
> expansion: Correctly expand `$crate` metavar

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-trait-resolve.h
- gcc/rust/typecheck/rust-type-util.cc
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/testsuite/rust/execute/torture/issue-3126.rs
We need to be careful when doing bounds check as to not create a recusive trait resolution. This patch checks for that case and fixes a bad type is equal check on ADT Types which was caught with a regression here.
Fixes Rust-GCC#3126
* typecheck/rust-hir-trait-resolve.cc (TraitResolver::ResolveHirItem): new helper
* typecheck/rust-hir-trait-resolve.h: add helper prototype
* typecheck/rust-type-util.cc (query_type): add debug
* typecheck/rust-tyty-bounds.cc (TypeBoundsProbe::scan): check for recursion
* typecheck/rust-tyty.cc (VariantDef::is_equal): fix is equal check
* rust/execute/torture/issue-3126.rs: New test.
> gccrs: check for recursion trait cycle with bounds checks

- gcc/rust/expand/rust-derive-clone.cc
- gcc/rust/expand/rust-derive-copy.cc
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-path.cc
- gcc/rust/resolve/rust-ast-resolve-type.cc
- gcc/rust/resolve/rust-name-resolver.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/nr2/exclude
The 1.0 name resolver allows insertions of resolutions to duplicate (or even overwrite) past resolutions. This PR as-is introduces assertions to prevent duplicate resolution insertions. Allowing duplicate-but-identical resolution insertions (inserting `(a, b)` and `(a, c)` is allowed iff `b == c`) would be an alternative approach.
> Prevent duplicate resolution insertions

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
- gcc/testsuite/rust/compile/nr2/exclude
> nr2.0: Fix `StructExprFieldIdentifier` handling

- gcc/rust/typecheck/rust-hir-path-probe.cc
- gcc/rust/typecheck/rust-hir-trait-reference.cc
- gcc/rust/typecheck/rust-hir-trait-reference.h
- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty-bounds.h
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty-subst.h
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/execute/torture/issue-3502.rs
In order to handle generic super traits on any trait bound we need to ensure we track the TypeBoundPredicate as part of the TraitReference instead of just the raw TraitReferences because these will have any applied generics enplace.
Then for any TypeBoundPredicate it takes a copy of the super traits because this is the usage of a TraitBound and we can apply generics which then need to be recursively applied up the chain of super predicates.
The main tweak is around TypeBoundPredicate::lookup_associated_item because we need to associate the predicate with the item we are looking up so the caller can respect the generics correctly as well.
Fixes Rust-GCC#3502
* typecheck/rust-hir-path-probe.cc: update call
* typecheck/rust-hir-trait-reference.cc …
> gccrs: support generic super traits recursively

- .github/workflows/bootstrap.yml
- .github/workflows/ccpp.yml
```
Disable network access via 'unshare' in two CI workflows to catch issues
like PR119333 where importing polonius meant bootstrap tried to pull crates
from the internet.
ChangeLog:
PR rust/119333
* .github/workflows/bootstrap.yml: Disable network via 'unshare'.
* .github/workflows/ccpp.yml: Ditto.
```
> ci: disable network

- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-stmt.h
- gcc/rust/hir/rust-ast-lower-stmt.cc
- gcc/rust/hir/tree/rust-hir-stmt.cc
- gcc/rust/hir/tree/rust-hir-stmt.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/resolve/rust-ast-resolve-stmt.h
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
> Parse and lower `let-else` statements

- gcc/testsuite/rust/compile/issue-2905-2.rs
Import from core library was wrong, it misses several crate directives since we're no longer dealing with multiple files.
> Fix core library test's canonical path

- gcc/rust/backend/rust-compile-expr.cc
- gcc/testsuite/rust/compile/issue-3567.rs
We need to check for error_mark_node when doing adjustments from coercion sites otherwise we hit assetions as part of the coercion. That fixes the ICE but the reason for the error_mark_node is because the array element value.
Fixes Rust-GCC#3567
* backend/rust-compile-expr.cc (CompileExpr::array_value_expr): add value chk for array expr
* rust/compile/issue-3567.rs: New test.
> gccrs: Fix ICE when array elements are not a value

- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/compile/issue-3553.rs
We need to recursively check the super traits of the predicate the Self type is trying to implement. Otherwise its cannot implement it.
This now outputs an error thats super close to rustc which looks like: compare to https://godbolt.org/z/3eM4YYG7j
```
test.rs:13:6: error: the trait bound ‘A: Foo’ is not satisfied [E0277]
5 | trait Bar: Foo {
|               required by this bound in: Bar
......
13 | impl Bar for A {
|      ^~~
|         the trait Foo is not implemented for A
```
Fixes Rust-GCC#3553
* typecheck/rust-hir-type-check-item.cc (TypeCheckItem::resolve_impl_block_substitutions): Track the polarity
* typecheck/rust-tyty-bounds.cc (TypeBoundPredicate::validate_type_implements_this): new validator
* typecheck/rust-tyty.h: new prototypes …
> gccrs: Add check for super traits being implemented by Self

- gcc/rust/resolve/rust-ast-resolve-path.cc
- gcc/testsuite/rust/compile/issue-3568.rs
- gcc/testsuite/rust/compile/nr2/exclude
Fixes Rust-GCC#3568
* resolve/rust-ast-resolve-path.cc (ResolvePath::resolve_path): check for super mid path
* rust/compile/nr2/exclude: nr2 puts out a different error multiple times
* rust/compile/issue-3568.rs: New test.
> gccrs: Fix ICE when using super mid way though path

- gcc/rust/typecheck/rust-hir-dot-operator.cc
- gcc/testsuite/rust/compile/issue-3554-1.rs
- gcc/testsuite/rust/compile/issue-3554-2.rs
We need to ensure we are adding methods to the possible candidates.
Fixes Rust-GCC#3554
* typecheck/rust-hir-dot-operator.cc:
* rust/compile/issue-3554-1.rs: New test.
* rust/compile/issue-3554-2.rs: New test.
> gccrs: Fix ICE when doing method resolution on trait predicates

- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/testsuite/rust/compile/issue-3552.rs
Fixes Rust-GCC#3552
* backend/rust-compile-resolve-path.cc (HIRCompileBase::query_compile): check for Expr trait item
* hir/rust-hir-dump.cc (Dump::visit): expr is optional
* rust/compile/issue-3552.rs: New test.
> gccrs: Fix ICE when compiling path which resolves to trait constant

- gcc/rust/backend/rust-compile-context.h
- gcc/rust/backend/rust-compile-type.cc
- gcc/testsuite/rust/compile/issue-3588.rs
Array expressions are still getting turned into VIEW_CONVERT_EXPR's becuase TYPE_MAIN_VARIANT is not set so then we might as well reuse the type-hasher to sort this out.
Fixes Rust-GCC#3588
* backend/rust-compile-context.h: only push named types
* backend/rust-compile-type.cc (TyTyResolveCompile::visit): run the type hasher
* rust/compile/issue-3588.rs: New test.
> gccrs: Fix ICE during const expr eval on array expressions

- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
> nr2.0: Rename `prelude` to `lang_prelude`

- gcc/rust/backend/rust-constexpr.cc
- gcc/testsuite/rust/compile/issue-3563.rs
Since 898d55ad7e2 was fixed to remove the VIEW_CONVERT_EXPR from array expressions we can now turn on the array element access const expr.
Fixes Rust-GCC#3563
* backend/rust-constexpr.cc (eval_store_expression): turn this back on
* rust/compile/issue-3563.rs: New test.
> gccrs: Fix ICE in array ref constexpr

- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/tree/rust-hir-type.cc
- gcc/testsuite/rust/compile/issue-3615.rs
Fixes Rust-GCC#3615
* hir/rust-hir-dump.cc (Dump::visit): check has type
* hir/tree/rust-hir-type.cc (BareFunctionType::BareFunctionType): likewise
* rust/compile/issue-3615.rs: New test.
> gccrs: FIX ICE when working with HIR::BareFunctionType

- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/testsuite/rust/compile/issue-3614.rs
Fixes Rust-GCC#3614
* typecheck/rust-hir-type-check-base.cc (TypeCheckBase::parse_repr_options): check for input
* rust/compile/issue-3614.rs: New test.
> gccrs: FIX ICE for malformed repr attribute

- gcc/rust/typecheck/rust-tyty-subst.h
- gcc/testsuite/rust/compile/issue-3605.rs
num regions is based on the used arguments of regions which can be less than the substutions requirements. So lets check for that and allow anon regions to be created for them.
Fixes Rust-GCC#3605
* typecheck/rust-tyty-subst.h: check for min range
* rust/compile/issue-3605.rs: New test.
> gccrs: fix ice when setting up regions

- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/testsuite/rust/compile/issue-3606.rs
Fixes Rust-GCC#3606
* typecheck/rust-hir-type-check-base.cc (TypeCheckBase::parse_repr_options): check for null and empty and add missing delete call
* rust/compile/issue-3606.rs: New test.
> gccrs: fix crash in parse repr options and missing delete call

- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/testsuite/rust/compile/enum_discriminant1.rs
Addresses https://github.com/Rust-GCC/gccrs/issues/3636
```
* backend/rust-compile-resolve-path.cc: Evaluate the enum's discriminant in a const context
* rust/compile/enum_discriminant1.rs: New test.
```
> Fix error when evaluating an enum discriminant containing arithmetic operations

- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/testsuite/rust/compile/nr2/exclude
I think there may be a few more spots where we disregard opening scope resolution operators, but unless anyone objects I think I'll leave it for another PR (would be nice to pass paths directly to `NameResolutionContext::resolve_path`, rather than the properties of a given path).
> nr2.0: Handle global paths

- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/testsuite/rust/compile/issue-3657.rs
We dont need to assert here the lifetime code already supports this case.
Fixes Rust-GCC#3657
* typecheck/rust-hir-type-check-base.cc: remove assertion
* rust/compile/issue-3657.rs: New test.
> gccrs: Fix ICE when resolving lifetimes without name

- gcc/rust/rust-gcc.cc
- gcc/testsuite/rust/compile/issue-3665.rs
Const decls are just delcarations wrapping the value into the DECL_INITIAL and the shift checks we have assume no decls are involved and its just flat values. This patch simply unwraps the constant values if they exist.
Fixes Rust-GCC#3665
* rust-gcc.cc (arithmetic_or_logical_expression): unwrap const decls
* rust/compile/issue-3665.rs: New test.
> gccrs: Fix ICE when doing shift checks on const decl

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/issue-3656.rs
We hit assertions on empty enum or unknown variant, this catches the error and emits a new diagnostic.
Fixes Rust-GCC#3656
* typecheck/rust-hir-type-check-pattern.cc (TypeCheckPattern::visit): emit error
* rust/compile/issue-3656.rs: New test.
> gccrs: Fix ICE on invalid match arms

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-base.h
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-extern.h
- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/hir/tree/rust-hir-expr.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/issue-3667.rs
This patch adds support for raw references which enforce the pointer type away from a reference type.
Fixes Rust-GCC#3667
* backend/rust-compile-base.cc (HIRCompileBase::address_expression): allow optional type
* backend/rust-compile-base.h: update prototype
* backend/rust-compile-expr.cc (CompileExpr::visit): update borrow expr
* backend/rust-compile-extern.h: remove unused debug
* backend/rust-compile-resolve-path.cc (HIRCompileBase::query_compile): update usage
* hir/rust-ast-lower-expr.cc (ASTLoweringExpr::visit): lower raw ref
* hir/tree/rust-hir-expr.cc (BorrowExpr::BorrowExpr): add flag for raw ref
* hir/tree/rust-hir-expr.h (class BorrowExpr): add new raw ref field
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): add handle for raw ref …
> gccrs: Fix ICE on raw reference

- gcc/rust/resolve/rust-ast-resolve-type.cc
- gcc/rust/typecheck/rust-substitution-mapper.cc
- gcc/rust/typecheck/rust-substitution-mapper.h
- gcc/testsuite/rust/compile/issue-3643.rs
- gcc/testsuite/rust/compile/issue-3646.rs
- gcc/testsuite/rust/compile/issue-3654.rs
- gcc/testsuite/rust/compile/issue-3663.rs
- gcc/testsuite/rust/compile/issue-3671.rs
- gcc/testsuite/rust/compile/nr2/exclude
We need to check upfront if the type is valid or not. Then error with a decent message.
Fixes Rust-GCC#3643
Fixes Rust-GCC#3646
Fixes Rust-GCC#3654
Fixes Rust-GCC#3663
Fixes Rust-GCC#3671
* resolve/rust-ast-resolve-type.cc (ResolveRelativeTypePath::go): fix error msg
* typecheck/rust-substitution-mapper.cc (SubstMapper::Resolve): add validation
(SubstMapper::valid_type): new check
(SubstMapper::visit): check if can resolve
* typecheck/rust-substitution-mapper.h: new prototype
* rust/compile/nr2/exclude: nr2 is missing type path error
* rust/compile/issue-3643.rs: New test.
* rust/compile/issue-3646.rs: New test.
* rust/compile/issue-3654.rs: New test.
* rust/compile/issue-3663.rs: New test.
* rust/compile/issue-3671.rs: New test.
> gccrs: Fix ICE when hitting invalid types for generics

- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-item.h
- gcc/rust/checks/errors/rust-feature.cc
- gcc/rust/checks/errors/rust-feature.h
- gcc/rust/hir/rust-ast-lower-implitem.cc
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/hir/tree/rust-hir-item.cc
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/testsuite/rust/compile/min_specialization1.rs
This paves the way for properly stubbing out `min_specialization`, but does not properly handle these functions in later passes like method resolution or typechecking.
> Add base for handling `#![feature(min_specialization)]`

- gcc/rust/resolve/rust-ast-resolve-base.h
- gcc/rust/resolve/rust-ast-resolve-implitem.h
- gcc/rust/resolve/rust-ast-resolve-stmt.cc
- gcc/rust/resolve/rust-ast-resolve-stmt.h
- gcc/rust/resolve/rust-ast-resolve-toplevel.h
* resolve/rust-ast-resolve-base.h (redefined_error): created a function for rust_error_at for redefined at multiple times.
* resolve/rust-ast-resolve-implitem.h: changed rust_error_at to redefined_error.
* resolve/rust-ast-resolve-stmt.cc (ResolveStmt::visit): changed rust_error_at to redefined_error.
* resolve/rust-ast-resolve-stmt.h: changed rust_error_at to redefined_error.
* resolve/rust-ast-resolve-toplevel.h: changed rust_error_at to redefined_error.
- Fixes #2436
> chore: refactoring rust_error_at "redefined multiple times"

- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
Instead, mark the visitor as dirty and wait for the next round of the fixed point to take care of them. This avoids issues with module items being loaded while not being stripped yet.
* resolve/rust-toplevel-name-resolver-2.0.cc (TopLevel::visit): Return if module is unloaded.
This fixes some issues with `cfg` expansion we were getting when compiling `core` 1.49
> nr2.0: Do not resolve modules this run if they are unloaded

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-token-tree-desugar.cc
- gcc/rust/expand/rust-token-tree-desugar.h
- gcc/rust/rust-session-manager.cc
- gcc/testsuite/rust/compile/macros/mbe/macro-issue3693.rs
- gcc/testsuite/rust/compile/macros/mbe/macro-issue3708.rs
- gcc/testsuite/rust/compile/macros/mbe/macro-issue3709-1.rs
- gcc/testsuite/rust/compile/macros/mbe/macro-issue3709-2.rs
Fixes #3709 
Fixes #3708 
Fixes #3693
> Handle doc comments in macros + fixes for invalid macro expansions in `core`

- gcc/rust/expand/rust-macro-builtins-format-args.cc
- gcc/testsuite/rust/compile/format_args_extra_comma.rs
* expand/rust-macro-builtins-format-args.cc (format_args_parse_arguments): Improve safety, allow extra commas after end of argument list.
* rust/compile/format_args_extra_comma.rs: New test.
This fixes some uses of `format_args!()` within `core`
> format_args: Allow extraneous commas, improve safety

- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/util/rust-attribute-values.h
- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/compile/track_caller.rs
Fixes #3026 by adding `#[track_caller]` as a recognizable builtin macro.
```
* expand/rust-macro-builtins.cc (MacroBuiltin::builtin_transcribers): Add entry for track_caller.
* util/rust-attribute-values.h: add `TRACK_CALLER` attribute.
* util/rust-attributes.cc: add `track_caller` attribute definition.
```
```
* rust/compile/track_caller.rs: New test.
```
Signed-off-by: Bhavesh Mandalapu <mandalapubhavesh@gmail.com>
> Recognize `#[track_caller]`

- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/testsuite/rust/compile/issue-3612.rs
Trait constants were missing type resolution step, this adds that as if it was a normal constant. The unsafe checker was missing a null check.
Fixes Rust-GCC#3612
* checks/errors/rust-unsafe-checker.cc (UnsafeChecker::visit): add null check
* hir/tree/rust-hir-item.h: add has_type helper
* typecheck/rust-hir-trait-resolve.cc (TraitItemReference::resolve_item): add missing type checking
* rust/compile/issue-3612.rs: New test.
> gccrs: Fix segv in unsafe chcker

- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/compile/issue-3530-1.rs
- gcc/testsuite/rust/compile/issue-3530-2.rs
Fixes #3530
This quick fix is kind of an ugly one, since [parsing of `repr` types is not fully implemented yet](https://github.com/Rust-GCC/gccrs/blob/20c8539a23e0a0462e3763c3983ffb3ca9b7e709/gcc/rust/typecheck/rust-hir-type-check-base.cc#L301-L302). This merely adds a new `ReprKind` type similar to [Rust's `ReprFlags`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_abi/src/lib.rs#L81-L101).
I'm open to suggestions for improvements, or any …
> gccrs: Implement typecheck for zero-variant enums

- gcc/rust/hir/rust-hir-dump.cc
* hir/rust-hir-dump.cc (Dump::visit): add guard for optional label
> gccrs: Fix crash in hir dump as labels are optional

- gcc/rust/rust-gcc.cc
- gcc/testsuite/rust/compile/issue-3664.rs
I copied a bad form of this check from the c front-end this updates it to ensure the rhs is an INTEGER_CST and the lhs needs checked in the first place.
Fixes Rust-GCC#3664
* rust-gcc.cc (arithmetic_or_logical_expression): Ensure this is an integer
* rust/compile/issue-3664.rs: New test.
> gccrs: Fix ICE when checking shift's which are behind array refs

- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/compile/issue-402.rs
It is not allowed to have a declared inference variable in the return position of a function as this may never get infered you need good points of truth.
Ideally if we get a student for GSoC 25 we will get the Default Hir Visitor so that we can grab the HIR::InferredType locus instead of using the ref location lookups.
Fixes Rust-GCC#402
* typecheck/rust-hir-type-check-item.cc (TypeCheckItem::visit): add diagnostic
* typecheck/rust-tyty.cc (BaseType::contains_infer): new helper to grab first infer var
* typecheck/rust-tyty.h: prototype
* rust/compile/issue-402.rs: New test.
> gccrs: Add check for placeholder (infer) type in return position

- gcc/rust/typecheck/rust-hir-type-check-struct-field.h
- gcc/rust/typecheck/rust-hir-type-check-struct.cc
- gcc/testsuite/rust/compile/issue-3628.rs
- gcc/testsuite/rust/compile/macros/mbe/macro-issue2983_2984.rs
- gcc/testsuite/rust/compile/struct_init1.rs
The error handling here was done long ago when we didnt know how to do any error handling very well. This removed bad fatal_errors and adds in some nice rich_location error diagnostics instead.
Fixes Rust-GCC#3628
* typecheck/rust-hir-type-check-struct-field.h: keep reference to parent expression
* typecheck/rust-hir-type-check-struct.cc (TypeCheckStructExpr::TypeCheckStructExpr): update ctor
(TypeCheckStructExpr::resolve): remove bad rust_fatal_errors
(TypeCheckStructExpr::visit): cleanup errors
* rust/compile/macros/mbe/macro-issue2983_2984.rs: cleanup error diagnotics
* rust/compile/struct_init1.rs: likewise
* rust/compile/issue-3628.rs: New test.
> gccrs: Fix ICE in struct expressions

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/issue-3581-1.rs
- gcc/testsuite/rust/compile/issue-3581-2.rs
- gcc/testsuite/rust/compile/nonexistent-field.rs
We were wrongly adding the assertion that this must not be an enum but this is a pointless assertion we only care that there are variant in the ADT and if the field exists in the first variant.
Fixes Rust-GCC#3581
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): fix bad assertion
* rust/compile/nonexistent-field.rs: fix error message
* rust/compile/issue-3581.rs: New test.
> gccrs: Fix ICE when handling case of unknown field in HIR::FieldAccess

- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/testsuite/rust/compile/issue-3649.rs
- gcc/testsuite/rust/compile/nr2/exclude
We have an assertion when accessing generic args if there are any which is really useful so this adds the missing guards for the case where they are specified but empty.
Fixes Rust-GCC#3649
* ast/rust-ast-visitor.cc (DefaultASTVisitor::visit): add guard
* expand/rust-expand-visitor.cc (ExpandVisitor::visit): add guard
* rust/compile/nr2/exclude: nr2 is missing error for this
* rust/compile/issue-3649.rs: New test.
> gccrs: Fix ICE with empty generic arguments

- gcc/rust/backend/rust-compile-expr.cc
There are two cases when initilizing an array, this is the const context which means we need to build the array ctor, which means using lots of memory, its super inefficient because we are using a big wrapper over the GCC internals here but preallocating the vectors here causes a:
terminate called after throwing an instance of 'std::bad_alloc'
So this is a handy error condition to rely on for this senario.
Fixes Rust-GCC#3713
Fixes Rust-GCC#3727
* backend/rust-compile-expr.cc (CompileExpr::array_copied_expr): prealloc the vector
> gccrs: prealloc the initilizer vector

- gcc/testsuite/rust/compile/nr2/compile.exp
..., using the standard idiom.  This '*.exp' file doesn't adhere to the parallel testing protocol as defined in 'gcc/testsuite/lib/gcc-defs.exp'.
This also restores proper behavior for '*.exp' files executing after (!) this one, which erroneously caused hundreds or even thousands of individual test cases get duplicated vs. skipped, randomly, depending on the '-jN' level.
PR testsuite/119508
gcc/testsuite/
* rust/compile/nr2/compile.exp: Disable parallel testing.
(cherry picked from commit 79d2c3089f480738613b7d338d86d8be710f8158)
Resolves Rust-GCC/gccrs#3740.
> Disable parallel testing for 'rust/compile/nr2/compile.exp' [PR119508]

- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/rust/resolve/rust-early-name-resolver-2.0.h
- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/testsuite/rust/compile/nr2/exclude
This should allow errors produced directly or indirectly by `ForeverStack::resolve_path` to be intelligently emitted or discarded. This can be used to avoid duplicate error messages, and in the near future for better language prelude and `pub(in <path>)` handling.
> nr2.0: Improve error handling

- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/ast/rust-ast.h
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
- gcc/rust/resolve/rust-name-resolution-context.cc
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/rust/util/rust-stacked-contexts.h
- gcc/testsuite/rust/compile/multiple_bindings1.rs
- gcc/testsuite/rust/compile/nr2/exclude
> nr2.0: Fix multiple bindings

- gcc/rust/expand/rust-derive-clone.cc
- gcc/testsuite/rust/compile/nr2/exclude
Both nodes had the same id, this led to a resolution conflict.
Fixes #3474
> Completely duplicate path node

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
* resolve/rust-late-name-resolver-2.0.cc (Late::Late): False initialize the
funny_error field.
> nr2.0: late: Correctly initialize funny_error member

- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-pattern.h
- gcc/testsuite/rust/execute/torture/struct_pattern1.rs
This PR adds support for basic struct ident patterns, specifically in the case of rebinding struct fields to new names:
```rust
match instance {
Foo { field_name: new_name } => { do_something(new_name) }
}
```
This is required for finish support for `derive(PartialEq)` and `derive(PartialOrd)`
> Add basic struct pattern rebinding

- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/expand/rust-derive-partial-eq.cc
- gcc/testsuite/rust/execute/torture/derive-partialeq2.rs
Fixes #2989 
Needs to be rebased on #3741 once it is merged
> Finish `derive(PartialEq)`

- gcc/rust/hir/rust-ast-lower-implitem.cc
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/rust/hir/rust-ast-lower-type.h
- gcc/testsuite/rust/compile/impl_trait_diag.rs
- gcc/testsuite/rust/compile/issue-1485.rs
Rust only allows impl traits to be used in the return position of functions.
Fixes Rust-GCC#1485
* hir/rust-ast-lower-implitem.cc (ASTLowerImplItem::visit): allow impl type
* hir/rust-ast-lower-item.cc (ASTLoweringItem::visit): likewise
* hir/rust-ast-lower-type.cc (ASTLoweringType::ASTLoweringType): new flag for impl trait
(ASTLoweringType::translate): pass flag
(ASTLoweringType::visit): track impl trait tag
(ASTLoweringType::emit_impl_trait_error): new diagnostic
* hir/rust-ast-lower-type.h: add new field
* rust/compile/impl_trait_diag.rs: New test.
* rust/compile/issue-1485.rs: New test.
> gccrs: Emit error diagnostic for bad impl type usage

- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-collect-lang-items.cc
- gcc/rust/ast/rust-collect-lang-items.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
This should make the visitation of `EnumItem` instances more straightforward, as well as add some missing calls to base class visitors
> nr2.0: Adjust enum item visitors

- gcc/rust/ast/rust-desugar-apit.cc
- gcc/rust/ast/rust-item.h
- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/rust/hir/tree/rust-hir-item.cc
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty-subst.h
- gcc/testsuite/rust/compile/impl_trait_generic_arg.rs
- gcc/testsuite/rust/compile/nr2/exclude
When using impl traits in argument position (APIT), they are desugared into generics, and supplying explicit generic arguments is not allowed. This commit adds the error diagnostic E0632 for attempting to pass generic arguments to impl traits, completing the implementation of the APIT feature.
* ast/rust-desugar-apit.cc: track if this is a impl-trait generic
* ast/rust-item.h (class TypeParam): add field to track if from impl trait
* hir/rust-ast-lower-type.cc (ASTLowerGenericParam::visit): likewise
* hir/tree/rust-hir-item.cc (TypeParam::TypeParam): upate hir as well
(TypeParam::operator=): likewise
* hir/tree/rust-hir-item.h (class TypeParam): likewise
* typecheck/rust-tyty-subst.cc (SubstitutionParamMapping::get_generic_param): add error
* …
> gccrs: Prevent passing generic arguments to impl traits in argument position

- gcc/rust/backend/rust-constexpr.cc
- gcc/testsuite/rust/compile/issue-3618.rs
This PR addresses #3618. With this change, the expected error of reaching the iteration limit is reported:
```
test.rs:1:17: error: ‘constexpr’ loop iteration count exceeds limit of 262144 (use ‘-fconstexpr-loop-limit=’ to increase the limit)
1 | static _X: () = loop {};
|                 ^~~~
```
My handling of `t` being a `NULL_TREE` may not be appropriate in `eval_constant_expression`, seeking guidance there.
Fixes #3618
> Fix ICE segfault on empty static loops

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-full-decls.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/expand/rust-macro-builtins-asm.cc
- gcc/rust/expand/rust-macro-builtins-asm.h
- gcc/rust/hir/tree/rust-hir-expr.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
Visit `InlineAsm` in ast-collector. Move `AST::InlineAsmOption` to `AST::InlineAsm::Option`.
Fixes https://github.com/Rust-GCC/gccrs/issues/3746.
> ast: collect InlineAsm node dump

- gcc/rust/rust-attribs.cc
- gcc/rust/rust-lang.cc
Since r14-6076, the LANG_HOOKS_COMMON_ATTRIBUTE_TABLE should not be used and LANG_HOOKS_ATTRIBUTE_TABLE replaces it.
Add the "cold" attribute to fix PR120018 (and the matching "hot" attribute).
Replace some gcc_assert() by explicit warnings (same as D frontend).
Add some clang-format off/on comment around code that's not correctly
formatted.
> Adapt attribute lang hook and do some cleanup

- gcc/rust/expand/rust-derive-default.cc
- gcc/rust/expand/rust-derive-eq.cc
- gcc/testsuite/rust/compile/nr2/exclude
This patch ensuers we reuse the Builder for new type to ensure we create a new type from scratch ensuring consistent new node-ids.
* expand/rust-derive-default.cc (DeriveDefault::visit_struct): use builder
(DeriveDefault::visit_tuple): likewise
* expand/rust-derive-eq.cc (DeriveEq::visit_tuple): likewise
(DeriveEq::visit_struct): likewise
(DeriveEq::visit_enum): likewise
(DeriveEq::visit_union): likewise
* rust/compile/nr2/exclude: these are fixed now
> gccrs: We cant clone types as it will dup the node-id

- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/testsuite/rust/compile/same_field_name.rs
As far as I can tell, this test should have been a compile test. Also, it seems like execute tests don't interact well with `dg-error` directives.
> Fix test `same_field_name.rs`

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/macros/mbe/meta-param.rs
> Fix `Attr` metavariable binding

- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/rust/resolve/rust-forever-stack.hxx
Most of these changes are required for #3785
> Small improvements to `DefaultASTVisitor` and nr2.0

- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/issue-3661.rs
Undefined attribute macros have no proc macro definition, which results in a failing `rust_assert`. This changes that assert to an if statement, that returns early if there is no proc macro definition. Fixes #3661.
I chose not to add an error in the if statement, because NR1 does not throw an additional error. Adding this return avoids the failing assert, and results in `error: macro not found` to be reported, exact same behavior as NR1.
Unsure if I placed the test file in the correct directory. Might be better placed in /macros.
- \[X] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[X] Read contributing guidlines
- \[X] `make check-rust` passes locally
- \[X] Run …
> gccrs: Fix NR2 ICE in visit_attributes

- gcc/testsuite/rust/execute/torture/for-loop1.rs
- gcc/testsuite/rust/execute/torture/for-loop2.rs
- gcc/testsuite/rust/execute/torture/iter1.rs
This is similar to 9faba024ef18b9c4d67f22bd3b020b5e445fad0a, but it applies to execute tests
> nr2.0: Fix some paths in test files

- gcc/rust/backend/rust-compile-type.cc
- gcc/rust/typecheck/rust-substitution-mapper.cc
- gcc/rust/typecheck/rust-tyty-call.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/rust/typecheck/rust-unify.cc
- gcc/testsuite/rust/compile/bad-rpit1.rs
- gcc/testsuite/rust/execute/torture/impl_rpit1.rs
- gcc/testsuite/rust/execute/torture/impl_rpit2.rs
- gcc/testsuite/rust/execute/torture/impl_rpit3.rs
This is the initial patch for RPIT, we can build on this to handle the more complex cases but there are enough distinct changes going on here that it should just get merged now.
RPIT is really a sneaky generic so for example:
```rust
fn foo() -> impl Bar {
Baz
}
```
This is represented as: fn () -> OpaqueType Bar. But when we handle the coercion site for Baz on impl Bar when we type resolve the function we know that the underlying type  is Baz. Note this function is _not_ generic so its using this special OpaqueType and keeping track of the underlying type in its ty_ref reference hir-id which will resolve to Baz.
This also means if we have a case where maybe this was in an if statement:
```rust
fn foo(a: i32) -> impl Bar {
if a > 10 {
Baz
} else {
Qux
}
}
```
The rules of impl Bar is that …
> gccrs: Initial support for Return Position Impl Trait

- gcc/rust/typecheck/rust-coercion.cc
- gcc/rust/typecheck/rust-unify.cc
- gcc/rust/typecheck/rust-unify.h
- gcc/testsuite/rust/compile/traits9.rs
- gcc/testsuite/rust/compile/unify-errors1.rs
The unify code was a bit dumb here where we always set emit_error to false for any subtypes for example in comparing tuples we always emitted the whole tuple didnt match the other tuple but really its much better to say expected bool got i32 because the element types didn't match.
* typecheck/rust-coercion.cc (TypeCoercionRules::coerce_unsized): dont emit error here
* typecheck/rust-unify.cc (UnifyRules::resolve_subtype): new helper to handle emit error
(UnifyRules::expect_adt): call resolve_subtype
(UnifyRules::expect_reference): likewise
(UnifyRules::expect_pointer): likewise
(UnifyRules::expect_array): likewise
(UnifyRules::expect_slice): likewise
(UnifyRules::expect_fndef): likewise
(UnifyRules::expect_fnptr): likewise
(UnifyRules::expect_tuple): likewise …
> gccrs: Always emit the error highest in the type hierarchy

- gcc/rust/parse/rust-parse.cc
- gcc/testsuite/rust/compile/torture/extern_mod2.rs
Stops an ICE from occuring when path attribute is empty
Fixes Rust-GCC#3607
gcc/rust/Changelog:
* parse/rust-parse.cc (Rust::extract_module_path): Handle a case where the path is empty / has only whitespaces.
gcc/testsuite/Changelog:
* rust/compile/torture/extern_mod2.rs: New tests to verify an error is thrown if the path is empty.
Signed-off by: vishruth-thimmaiah <vishruththimmaiah@gmail.com>
> parser: fix ICE std::out_of_range with path attrs to nonexisting path

- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/testsuite/rust/compile/nr2/exclude
May have some overlap with #3770. ~~Depends on #3784.~~
> nr2.0: Improve visibility path handling

- gcc/rust/lex/rust-lex.cc
- gcc/testsuite/rust/compile/torture/unended-raw-byte-string.rs
Fixes an ICE when a raw byte string is not terminated
Fixes Rust-GCC#3731
* lex/rust-lex.cc (Lexer::parse_raw_byte_string): Fix infinite looping when a raw byte string is not terminated.
* rust/compile/torture/unended-raw-byte-string.rs: New test to ensure correct error message for unended raw byte string.
> fix: ICE when parsing unterminated raw byte strings

- gcc/rust/hir/rust-ast-lower-pattern.cc
- gcc/rust/hir/rust-hir-dump.cc
This is part of making compilation of subpatterns (called `to_bind` in the code) of [IdentifierPattern](https://doc.rust-lang.org/reference/patterns.html#r-patterns.ident) work.
- \[x] Read contributing guidelines
May be off-topic for this PR, but to those who have more experience with project, I'm currently having issues with `Resolver::TypeCheckContext` not storing the type of the lowered subpattern, which does not allow me to make changes to successfully compile the subpattern. Any …
> gccrs: Lower IdentifierPattern's to_bind to HIR

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-implitem.cc
- gcc/rust/backend/rust-compile-item.cc
- gcc/rust/resolve/rust-default-resolver.cc
- gcc/rust/resolve/rust-default-resolver.h
- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-name-resolution-context.cc
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/typecheck/rust-hir-type-check-enumitem.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check.cc
- gcc/rust/util/rust-canonical-path.h
- gcc/testsuite/rust/compile/nr2/exclude
~~Depends on a few other PRs~~
> nr2.0: Separate out canonical path handling

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-expr.h
- gcc/rust/expand/rust-cfg-strip.cc
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
I have another commit in the pipeline which depends on this and fixes test `execute/torture/closure4.rs` under name resolution 2.0
> Add new function `ClosureExpr::get_definition_expr`

- gcc/rust/typecheck/rust-type-util.cc
- gcc/testsuite/rust/execute/torture/basic_partial_ord1.rs
- gcc/testsuite/rust/execute/torture/basic_partial_ord2.rs
There was a complex recurisve type query hierarchy here but the type was resolved so we can just do an early return here
* typecheck/rust-type-util.cc (query_type): early return.
* rust/execute/torture/basic_partial_ord1.rs: New test.
* rust/execute/torture/basic_partial_ord2.rs: New test.
> gccrs: Fix bug in query type stopping PartialOrd

- gcc/rust/hir/rust-hir-dump.cc
Small one to improve HIR debugging for patterns.
- \[x] Read contributing guidelines
> gccrs: Improve HIR dumps for patterns

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
Addresses [this comment](https://github.com/Rust-GCC/gccrs/pull/3822#discussion_r2149932447), thanks to @P-E-P for explaining the rationale for this change over meeting :)
- \[x] Read contributing guidelines
> nr2.0: Update IdentifierPattern's subpattern name resolution

- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/hir/rust-ast-lower-item.h
- gcc/rust/rust-session-manager.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-item.h
Name resolution 2.0 doesn't like crates being typechecked before the initialization of `ImmutableNameResolutionContext`
> Adjust external crate lowering and type checking

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.h
When type checking expressions that involve references, we need to examine the bounds of the referenced type to properly resolve traits and methods.
* typecheck/rust-hir-type-check-expr.cc: Look at bounds behind references.
* typecheck/rust-hir-type-check-expr.h: Add helper method.
> gccrs: Ensure we look at the bounds behind a reference

- gcc/rust/typecheck/rust-hir-type-bounds.h
- gcc/rust/typecheck/rust-tyty-bounds.cc
Rename assemble_sized_builtin to assemble_marker_builtins and reorganize the type matching to properly handle function pointers and closures with their associated traits (Fn, FnMut, FnOnce).
* typecheck/rust-hir-type-bounds.h: Rename method.
* typecheck/rust-tyty-bounds.cc: Refactor marker trait assembly and add proper Fn trait handling for function types.
> gccrs: Refactor marker builtin trait assembly

- gcc/rust/typecheck/rust-hir-dot-operator.cc
- gcc/rust/typecheck/rust-hir-dot-operator.h
Refactor the dot operator implementation to improve code organization and maintainability while preserving existing functionality.
* typecheck/rust-hir-dot-operator.cc: Major refactoring and cleanup.
* typecheck/rust-hir-dot-operator.h: Add new helper methods.
> gccrs: Cleanup and refactor method resolution

- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty.h
When resolving type bounds, we need to examine super traits to properly determine if type bindings are valid in the current context.
* typecheck/rust-tyty-bounds.cc: Check super traits for type bindings.
* typecheck/rust-tyty.h: Add helper methods for bound checking.
> gccrs: Fix bug with bad type bindings not looking at super traits

- gcc/rust/typecheck/rust-unify.cc
Its valid to unify a closure to an fnptr as we are working on the fn traits. There are still other issues but this is part of the patch set.
* typecheck/rust-unify.cc (UnifyRules::expect_fnptr): add unify rules
> gccrs: Add unify rules for fnptr and closures

- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/testsuite/rust/compile/issue-3525.rs
There was a sily bug where if you reorder this test case to declare A before B this test would work but its meant to work in any order. So this fixes the bug during code gen to fall back to our query compile system if this is needed.
Fixes Rust-GCC#3525
* backend/rust-compile-resolve-path.cc: if this fails fall back to query compile
* rust/compile/issue-3525.rs: New test.
> gccrs: Fix bug with non compiled const decl

- gcc/rust/hir/tree/rust-hir-expr.h
MatchArm has outer attributions as private member, but there was no way to get it, so I added a getter function.
```
* hir/tree/rust-hir-expr.h (MatchArm::get_outer_attrs): Add getter for outer attributions
```
> Add getter for outer attributions

- gcc/rust/rust-lang.cc
I don't know if this version check is redundant, but it probably shouldn't be *this* redundant
> Update C++ version check in rust-lang.cc

- gcc/rust/ast/rust-expr.h
- gcc/rust/ast/rust-pattern.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-visibility.h
Missing locus getters create additional warning with clang. This PR will reduce the amount of warnings emitted by clang with clang-filter enabled.
> Add locus getters

- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/nr2/exclude
This prioritizes resolution in the language prelude over resolution as a module.
> nr2.0: Adjust resolution of modules

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
`DefaultResolver` already handles `StructStruct` in a more correct fashion.
> Remove `Late` visitor override for `StructStruct`

- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/rust/resolve/rust-late-name-resolver-2.0.h
- gcc/rust/resolve/rust-name-resolution-context.h
- gcc/testsuite/rust/compile/while_let_without_label.rs
* ast/rust-ast-visitor.cc (DefaultASTVisitor::visit): Check that the WhileLet has a label
before visiting it.
* rust/compile/while_let_without_label.rs: New test.
> ast: Check before visiting a while-let's label

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-expr.h
- gcc/testsuite/rust/compile/issue-3874.rs
This is an invalid test case but we just need a guard for the missing borrow expression.
Fixes Rust-GCC#3874
* ast/rust-ast-collector.cc (TokenCollector::visit): check for missing borrow
* ast/rust-expr.h: add helper
* rust/compile/issue-3874.rs: New test.
> gccrs: Fix ice with invalid borrow expression

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
**Edit: Resolved the previous problem.**
Type checking for LiteralPattern is also updated to resolve the following edge case:
```rust
fn main() {
let arr = [0, 0];
match arr {
// Should fail as `LiteralPattern`-s in the `SlicePattern` should be type checked
// against element type of `arr`
[0, 0.0] => {}
_ => {}
}
}
```
[Link to the code in Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=5664a23df0102b376f1ec74ad7d7bff1)
~~However, the draft commit causes `gccrs/gcc/testsuite/rust/compile/if_let_expr.rs` to fail, specifically `if_let_expr.rs:12:33: error: type annotations needed [E0282]`.~~
> Basic SlicePattern type checking

- .github/glibcxx_ubuntu64b_log_expected_warnings
- .github/log_expected_warnings
- gcc/rust/checks/errors/borrowck/rust-bir-place.h
Fix narrowing:
```
-../../gcc/rust/checks/errors/borrowck/rust-borrow-checker-diagnostics.cc:145:46:
warning: narrowing conversion of ‘loan’ from ‘Rust::Polonius::Loan’ {aka
‘long unsigned int’} to ‘uint32_t’ {aka ‘unsigned int’} [-Wnarrowing]
```
> Fix narrowing of Loan (size_t) into LoanId (uint32)

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-bounds.h
- gcc/rust/typecheck/rust-hir-type-check-base.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty-subst.h
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/compile/issue-3836.rs
- gcc/testsuite/rust/execute/torture/basic_partial_ord1.rs
- gcc/testsuite/rust/execute/torture/basic_partial_ord2.rs
- gcc/testsuite/rust/execute/torture/issue-3836.rs
- gcc/testsuite/rust/execute/torture/partial-ord-6.rs
This was a nasty issue to debug, the issue was very eager type bounds checking. So for example:
pub trait PartialOrd<Rhs: ?Sized = Self>: PartialEq<Rhs>
The super trait of PartialEq<Rhs> is a generic substitution and we reuse our bounds code here for normal generic bounds and generics an invalid bounds check was occuring when PartialEq<Rhs> was getting substituted becase this is a trait doing proper bounds checking is not valid here because this is telling us about the bounds in this case.
Fixes Rust-GCC#3836
* typecheck/rust-hir-trait-resolve.cc (TraitResolver::resolve_trait): track is super trait
* typecheck/rust-hir-type-bounds.h: refactor bounds scan
* typecheck/rust-hir-type-check-base.h: track from super trait
* typecheck/rust-hir-type-check-expr.cc …
> gccrs: Fix bad bounds checking for PartialOrd

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
* resolve/rust-late-name-resolver-2.0.cc (Late::visit): Check for a label
before visiting it.
> nr2.0: Check before visiting a for-loop's label

- gcc/rust/typecheck/rust-casts.cc
- gcc/rust/typecheck/rust-casts.h
- gcc/testsuite/rust/compile/issue-2680.rs
This case:
let i = 1;
let j = i as i64;
'i' is meant to default to i32 but the inference was making both of these i64 because the code was prefering coercion logic which can end up with a default unify which causes the ?integer to unify with i64 making them both i64.
But all we need to do is allow the simple cast rules to run first then fallback to coercions but special consideration has to be made to ensure that if there are dyn objects needed then this needs a unsize coercion, but also we need to ensure the underlying types are a valid simple cast too otherwise these also need to fallback to the coercion code.
Fixes Rust-GCC#2680
* typecheck/rust-casts.cc (TypeCastRules::resolve): optional emit_error flag
(TypeCastRules::check): try the simple cast rules then …
> gccrs: Fix cast rules logic to try simple casts then fall back to coercions

- gcc/testsuite/rust/compile/issue-3144.rs
Fixes Rust-GCC#3144
* rust/compile/issue-3144.rs: New test.
> gccrs: Add test case to show we emit better errors now

- gcc/rust/util/rust-attribute-values.h
- gcc/rust/util/rust-attributes.cc
* util/rust-attribute-values.h: Add declarations for them.
* util/rust-attributes.cc: Add definitions.
> attributes: Add #[test] and #[simd_test]

- gcc/rust/backend/rust-compile-base.cc
- gcc/testsuite/rust/compile/issue-3978.rs
Rust seems to allow duplicate HIR::Item 'main' functions but it needs to be a root item to be the true main entry point. This means we can use the canonical path to determine if this is a root one where its CrateName::main or CrateName::Module::main.
Fixes Rust-GCC#3978
* backend/rust-compile-base.cc: check the canonical path
* rust/compile/issue-3978.rs: New test.
> gccrs: Fix ICE with duplicate root item main function

- gcc/rust/hir/tree/rust-hir-expr.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-path.h
- gcc/rust/typecheck/rust-hir-trait-reference.cc
- gcc/rust/typecheck/rust-hir-trait-reference.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-typecheck-context.cc
- gcc/testsuite/rust/compile/issue-3916.rs
In the test case:
```rust
fn test (len: usize) -> u64 {
let mut i = 0;
let mut out = 0;
if i + 3 < len {
out = 123;
}
out
}
```
The issue is to determine the correct type of 'i', out is simple because it hits a coercion site in the resturn position for u64. But 'i + 3', 'i' is an integer infer variable and the same for the literal '3'. So when it comes to resolving the type for the Add expression we hit the resolve the operator overload code and because of this:
```rust
macro_rules! add_impl {
($($t:ty)*) => ($(
impl Add for $t {
type Output = $t;
#[inline]
#[rustc_inherit_overflow_checks]
fn add(self, other: $t) -> $t { self + other }
}
)*)
}
add_impl! { usize u8 u16 u32 u64 u128 isize i8 i16 i32 i64 i128 f32 f64 }
```
This means the resolution for 'i + 3' is ambigious because it could …
> gccrs: Add initial support for deffered operator overload resolution

- gcc/rust/backend/rust-compile-resolve-path.cc
Not adding the test case here we emit more errors than rustc for the error type node so its just noisy and dejagnu is being a pain.
Fixes Rust-GCC#3933
* backend/rust-compile-resolve-path.cc (ResolvePathRef::resolve): return error_mark_node
> gccrs: return error node when this fails during constexpr case

- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/testsuite/rust/compile/issue-3915.rs
- gcc/testsuite/rust/execute/torture/sip-hasher.rs
When we have generic paths like T::foobar during codegen sometimes we need to enforce an extra lookup for this generic parameter type to the mono morphized underlying type.
Fixes Rust-GCC#3915
Fixes Rust-GCC#1247
* backend/rust-compile-resolve-path.cc (HIRCompileBase::query_compile): do another lookup
* rust/compile/issue-3915.rs: New test.
* rust/execute/torture/sip-hasher.rs: New test.
> gccrs: fix bad monomophization of generic paths - GOAL TEST CASE SIP HASHER WORKS!

- gcc/rust/expand/rust-cfg-strip.cc
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
`TopLevel` would ignore just-loaded modules but `Early` and `ExpandVisitor` wouldn't. The latter would produce errors when it hit attributes which should have been indirectly `CfgStrip`'d away.
> Load modules during `CfgStrip` phase

- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-expr.h
- gcc/rust/ast/rust-type.h
- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/hir/tree/rust-hir-expr.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-visitor.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/deferred_const_inference.rs
- **ast: Use AnonConst for array type sizes**
- **hir: Handle deferred const inference variables**
> Parse deferred const generics

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-desugar-question-mark.cc
- gcc/rust/ast/rust-desugar-question-mark.h
- gcc/rust/ast/rust-expression-yeast.cc
- gcc/rust/ast/rust-expression-yeast.h
- gcc/rust/rust-session-manager.cc
Since we are doing more and more "external" desugars, as in desugars
that take a pointer and replace it with another one, rather than
modifying it from within, having an external visitor dispatch to the
proper desugar helps with code clarity.
* Make-lang.in:
* ast/rust-desugar-question-mark.cc: Rework class
API.
* ast/rust-desugar-question-mark.h: Likewise.
* ast/rust-expression-yeast.cc: New file.
* ast/rust-expression-yeast.h: New file.
> desugar: Add desugar dispatch for all desugars

- gcc/rust/resolve/rust-default-resolver.cc
- gcc/rust/resolve/rust-default-resolver.h
This should fix the CI failure in #3995
> Handle `IfLetExprConseqElse` in `DefaultResolver`

- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/rust-backend.h
- gcc/rust/rust-gcc.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/match-slicepattern-slice.rs
- gcc/testsuite/rust/execute/torture/match-slicepattern-slice-1.rs
Figured out how to use the `debug` function in `rust.gcc.cc`.
Looking for feedback on my implementation for `slice_data_index_expression`, I am unsure whether it's the best way to do so. (should I make it such that the 1st parameter is the actual slice tree and not the data field?)
Supporting rest patterns `[..]` in slice patterns will be my next task.
> gccrs: Implement compilation for SlicePattern matching against SliceType scrutinee

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/rust/typecheck/rust-hir-type-check-base.h
- gcc/rust/typecheck/rust-hir-type-check-enumitem.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-hir-type-check.cc
- gcc/rust/typecheck/rust-type-util.cc
> nr1.0: Remove `rust/typecheck` support

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-desugar-while-let.cc
- gcc/rust/ast/rust-desugar-while-let.h
- gcc/rust/ast/rust-expression-yeast.cc
- gcc/testsuite/rust/compile/while_let1.rs
Needs #3999 - only review the last commit here
> Desugar while-let loops

- gcc/rust/checks/lints/rust-lint-unused-var.cc
- gcc/testsuite/rust/compile/auto_traits2.rs
- gcc/testsuite/rust/compile/derive-debug1.rs
- gcc/testsuite/rust/compile/derive_macro1.rs
- gcc/testsuite/rust/compile/format_args_basic_expansion.rs
- gcc/testsuite/rust/compile/format_args_extra_comma.rs
- gcc/testsuite/rust/compile/issue-2043.rs
- gcc/testsuite/rust/compile/issue-2166.rs
- gcc/testsuite/rust/compile/issue-2238.rs
- gcc/testsuite/rust/compile/issue-2907.rs
- gcc/testsuite/rust/compile/min_specialization1.rs
- gcc/testsuite/rust/compile/name_resolution2.rs
- gcc/testsuite/rust/compile/name_resolution4.rs
- gcc/testsuite/rust/compile/torture/generics29.rs
- gcc/testsuite/rust/compile/torture/generics30.rs
- gcc/testsuite/rust/compile/torture/traits3.rs
- gcc/testsuite/rust/compile/torture/traits7.rs
- gcc/testsuite/rust/execute/torture/impl_trait3.rs
- gcc/testsuite/rust/execute/torture/min_specialization2.rs
- gcc/testsuite/rust/execute/torture/trait10.rs
- gcc/testsuite/rust/execute/torture/trait11.rs
- gcc/testsuite/rust/execute/torture/trait12.rs
- gcc/testsuite/rust/execute/torture/trait13.rs
- gcc/testsuite/rust/execute/torture/trait9.rs
This PR addresses https://github.com/Rust-GCC/gccrs/issues/4022
> Remove warning for unused self parameter

- gcc/rust/backend/rust-compile-expr.cc
- gcc/testsuite/rust/compile/issue-3960.rs
We assert that struct expressions during code-gen must be of TyTy::ADTType but we can simply just check for this and return error_mark_node to make this safe.
Fixes Rust-GCC#3960
* backend/rust-compile-expr.cc (CompileExpr::visit): check for ADTType instead of assert
* rust/compile/issue-3960.rs: New test.
> gccrs: Fix ICE during const eval of const capacity

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-collector.h
- gcc/rust/ast/rust-ast-full-decls.h
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/ast/rust-pattern.cc
- gcc/rust/ast/rust-pattern.h
- gcc/rust/expand/rust-cfg-strip.cc
- gcc/rust/expand/rust-cfg-strip.h
- gcc/rust/expand/rust-derive.h
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-ast-lower-base.h
- gcc/rust/hir/rust-ast-lower-pattern.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/resolve/rust-ast-resolve-base.cc
- gcc/rust/resolve/rust-ast-resolve-base.h
- gcc/rust/resolve/rust-ast-resolve-pattern.cc
Most changes are made to implement 2 new item types for `AST::SlicePattern`. Currently only `SlicePatternItemsNoRest` can be lowered as I have not made changes to the `HIR::SlicePattern` to support `SlicePatternItemsHasRest`. HIR changes will be made in a follow-up PR.
Question directed to @philberty: seems like after this PR, there will be 3 base abstract classes that have identical functions:
- `SlicePatternItems`
- `TuplePatternItems`
- `TupeStructItems`
Wondering whether it would be wise to combine all these 3 base abstract classes into a common `PatternItems` class to handle storing of multi-patterns? This could be a item for my backlog once I'm done with the stuff on my original GSoC proposal.
> gccrs: Add rest pattern support for AST::SlicePattern

- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty.cc
* typecheck/rust-tyty-subst.cc: track the const generic
* typecheck/rust-tyty.cc (ConstType::is_equal): finish the is_equal
> gccrs: Ensure we track the const generic substitution on the param mappings

- gcc/rust/typecheck/rust-autoderef.cc
- gcc/rust/typecheck/rust-coercion.cc
- gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
- gcc/rust/typecheck/rust-hir-path-probe.cc
- gcc/rust/typecheck/rust-hir-path-probe.h
- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/rust/typecheck/rust-hir-type-check-base.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-typecheck-context.cc
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty-subst.h
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/compile/generics8.rs
This old can_eq interface was an old method to try and check if types can match up by taking into account generics but its not maintained properly and we already have a new wrapper Resolver::types_compatable (type, type, locus, emit_errors) which just calls unify_site_and infer with commit false. There are only a few places left to update.
One minor downside is that i need to remove const in some places because the unify interface is non const. Ideally we would want to avoid writing a seperate const unify anyway so i think this is not ideal but fine for us.
* typecheck/rust-autoderef.cc: remove useless assertion
* typecheck/rust-coercion.cc (TypeCoercionRules::coerce_unsafe_ptr): refactor (TypeCoercionRules::coerce_borrowed_pointer): remove FIXME this is fine
* …
> gccrs: Remove more calls to the old TyTy::BaseType::can_eq interface

- gcc/rust/Make-lang.in
- gcc/rust/parse/rust-parse-impl-lexer.cc
- gcc/rust/parse/rust-parse-impl-macro.cc
- gcc/rust/parse/rust-parse-impl-proc-macro.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
This should reduce incremental compile times when modifying `rust-parse-impl.h` and not `rust-parse.h`
> Avoid including `rust-parse-impl.h` in `rust-parse.h`

- gcc/rust/ast/rust-ast.cc
I missed this while reviewing #4016
> Catch parse failure in `parse_path_meta_item`

- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-macro.h
- gcc/rust/parse/rust-parse.h
This probably introduces conflicts with #4016
> Make `AttributeParser` rely more on `Parser`

- .github/workflows/ccpp.yml
https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/#macos-13-is-closing-down
> ci: Bump from `macos-13` to `macos-15`

- gcc/testsuite/rust/execute/inline_asm_inout_ident.rs
- gcc/testsuite/rust/execute/inline_asm_inout_var.rs
Those test are failing on the macos CI runner. (expected)
> Exclude some inline assembly test

- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/hir/rust-ast-lower-pattern.cc
- gcc/rust/hir/tree/rust-hir-pattern.h
- gcc/testsuite/rust/compile/issue-3928.rs
Fixes #3928 
Add support to AST lowering of exclusive range pattern.
* backend/rust-compile-pattern.cc (CompilePatternCheckExpr::visit):
Check upper compare operator.
* hir/rust-ast-lower-pattern.cc (ASTLoweringPattern::visit):
Handle lowering of exclusive range pattern.
* hir/tree/rust-hir-pattern.h (class RangePattern):
Add support for exclusive ranges in HIR representation.
* rust/compile/issue-3928.rs: New test.
> gccrs: Fix ICE on exclusive_range_pattern lowering

- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/ast/rust-item.h
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-expand-visitor.h
- gcc/testsuite/rust/compile/macros/mbe/macro49.rs
This should help detect issues like #3444
> Add checks to `ExpandVisitor`

- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/import_wildcards.rs
Avoid abort on wildcard use declaration.
Fixes #3953.
> Wildcard use declaration

- gcc/rust/resolve/rust-ast-resolve-stmt.h
- gcc/testsuite/rust/compile/enum_discriminant3.rs
addresses https://github.com/Rust-GCC/gccrs/issues/3635
> Fix ICE when trying to compile enums with non-const discriminants.

- gcc/rust/ast/rust-ast.cc
- gcc/testsuite/rust/compile/issue-3966.rs
> Reject empty cfg_attr

- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-var-decl.h
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/execute/torture/let-identifierpattern-subpattern.rs
Implements `let` statement binding support for identifier patterns' subpatterns, together with closure param bindings as well (albeit untested because of #4071)
> Finish up subpattern codegen support for identifier patterns

- gcc/rust/util/rust-attribute-values.h
- gcc/rust/util/rust-attributes.cc
This attribute is a procedural macro defined by the crate `simd-test-macro`, not a built-in macro.
> Remove `#[simd_test]` support

- gcc/rust/expand/rust-macro-builtins-format-args.cc
- gcc/testsuite/rust/compile/format_args_concat.rs
This is a simpler version of #4064. I think I'll probably revisit this latter, to try to improve eager expansion -- it seems like we do a lot of unnecessary `tokens -> AST -> tokens -> AST` conversions.
> Eagerly expand `format_args` macro

- gcc/rust/ast/rust-expr.h
Fixes #3944
When using a null pointer for strip information it produces an error when trying to access the structure's child within a visitor.
Either we need to make the default visitor aware of the strip state or avoid relying on the internal state to store the strip information.
A third way would be to consider every strippable item as truly optional but this doesn't feel right, as we wouldn't be able to easily tell optional branches from strip-optional ones apart.
> Separate strip information from internal state

- gcc/rust/backend/rust-compile-context.h
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/issue-3965-1.rs
- gcc/testsuite/rust/compile/issue-3965-2.rs
- gcc/testsuite/rust/compile/issue-3969.rs
We need to catch the error node for the array capacity and return early. Otherwise we try to const evaluate something thats just silly. Also when compiling array expressions we can simply reuse the array capacity expression we already have cons folded.
Fixes Rust-GCC#3965
Fixes Rust-GCC#3969
* backend/rust-compile-context.h: add assertions for context peeks
* backend/rust-compile-expr.cc (CompileExpr::visit): check for valid loop context
(CompileExpr::array_copied_expr): just reuse array tyty capacity value
* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): catch error
* rust/compile/issue-3965-1.rs: New test.
* rust/compile/issue-3965-2.rs: New test.
> gccrs: Fix segv when handling invalid array capacities

- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/rust/typecheck/rust-unify.cc
We need to distinguish between abi's and unsafety on fnptrs. There is a commented out check because there is a regression in:
rust/compile/try-catch-unwind-{new/old}.rs
But i think this is because the test case should be taking an FnOnce from reading std::panic in rust 1.49. Where as we are passing an fnptr which is probably because we didnt support fnonce at all then.
Addresses #4090
* hir/tree/rust-hir-item.h: add unsafe helper
* typecheck/rust-hir-type-check-type.cc (TypeCheckType::visit): pass in abi and unsafe
* typecheck/rust-tyty.cc (BaseType::monomorphized_clone): likewise
(FnPtr::as_string): emit more info
(FnPtr::clone): update ctor call
* typecheck/rust-tyty.h: new ctor params
* typecheck/rust-unify.cc (UnifyRules::expect_fnptr): check abi and unsafe
> gccrs: track abi and unsafety on fnptrs for proper type checking

- gcc/rust/backend/rust-constexpr.cc
- gcc/testsuite/rust/compile/issue-2394.rs
- gcc/testsuite/rust/compile/issue-4146.rs
This pulls over more constexpr support from C++ front-end.
Fixes Rust-GCC#4146
* backend/rust-constexpr.cc (eval_constant_expression): port over missing bits
(eval_store_expression): likewise
(eval_call_expression): likewise
(eval_binary_expression): likewise
(eval_bit_field_ref): likewise
(eval_check_shift_p): likewise
(fold_pointer_plus_expression): likewise
(maybe_fold_addr_pointer_plus): likewise
(fold_expr): likewise
(union_active_member): likewise
(fold_indirect_ref_1): likewise
(rs_fold_indirect_ref): likewise
(rs_eval_indirect_ref): likewise
(eval_logical_expression): likewise
(eval_vector_conditional_expression): likewise
(eval_bare_aggregate): likewise
(cxx_eval_trinary_expression): likewise
(eval_and_check_array_index): likewise
(eval_array_reference): …
> gccrs: Fix ICE handling division by zero in const eval

- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/testsuite/rust/compile/issue-4168.rs
When we have an invalid capacity expression we can't try to then also const fold it as GCC will assert on invalid conversions.
Fixes Rust-GCC#4168
* typecheck/rust-hir-type-check-type.cc (TypeCheckType::visit): check for invalid capacity
* rust/compile/issue-4168.rs: New test.
> gccrs: Fix ICE for invalid const capacity expression handling

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-builtin-ast-nodes.h
Replace rust_sorry_at() stub with basic implementation that outputs format_args!() macro syntax.
Related to Issue - #4004 
This is WIP so let me know if this is ok for now or need changes.
> Implement `TokenCollector::visit(AST::FormatArgs&)` 

- gcc/rust/typecheck/rust-substitution-mapper.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/compile/issue-4090-1.rs
- gcc/testsuite/rust/compile/issue-4090-2.rs
This patch adds support to recursively walk fnptr types to do generic substitutions.
Fixes #4090
* typecheck/rust-substitution-mapper.cc (SubstMapperInternal::visit): handle fnptr
* typecheck/rust-tyty.cc (FnPtr::handle_substitions): new
* typecheck/rust-tyty.h: likewise
* rust/compile/issue-4090-1.rs: New test.
* rust/compile/issue-4090-2.rs: New test.
> gccrs: fnptr types can hold onto generic params so it needs to handle substs

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
This was an old chunk of code to try and sort out the Self type on resolving methods for impl blocks. But this is not required when our unify code works properly.
* typecheck/rust-hir-type-check-expr.cc: remove old hack
> gccrs: Remove old hack from resolve operator overload

- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-substitute-ctx.cc
- gcc/rust/expand/rust-macro-substitute-ctx.h
- gcc/testsuite/rust/compile/macros/mbe/macro58.rs
Fix segfault on builtin metavars as well as location on substituted tokens.
> Metavar segfault

- .github/workflows/send-emails.yml
The workflow doesn't know what are the new commits in the target branch. It does now which PR has been merged, but it only has the original revisions, before the merge queue rebased them... So instead of looking at the target branch, craft the emails from the original commits.
> ci: adjust again the workflow for sending emails

- .github/workflows/send-emails.yml
And add more log output to help with possible after the fact debugging...
> ci: handle empty commit list

- .github/workflows/send-emails.yml
Not very nice, but at least it should not blow up.
> ci: fix early exit

- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/checks/errors/rust-hir-pattern-analysis.cc
- gcc/rust/hir/rust-ast-lower-pattern.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/testsuite/rust/compile/match-tuplestructpattern-err.rs
- gcc/testsuite/rust/compile/match-tuplestructpattern-rest.rs
- gcc/testsuite/rust/execute/torture/match-tuplestructpattern-rest-1.rs
- gcc/testsuite/rust/execute/torture/match-tuplestructpattern-rest-2.rs
Can't believe I forgot about it until now :skull:
> Implement compilation support for rest patterns in tuple struct patterns

- .github/workflows/send-emails.yml
hashFiles() only works with files in $GITHUB_WORKSPACE, not /tmp. Probably cleaner to use the "outputs" machinery anyway.
> ci: yet another fix for the conditionnal steps

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-type.cc
- gcc/rust/backend/rust-compile-type.h
- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-substitution-mapper.cc
- gcc/rust/typecheck/rust-substitution-mapper.h
- gcc/rust/typecheck/rust-type-util.cc
- gcc/rust/typecheck/rust-tyty-call.h
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty-util.cc
- gcc/rust/typecheck/rust-tyty-util.h
- gcc/rust/typecheck/rust-tyty-variance-analysis-private.h
- gcc/rust/typecheck/rust-tyty-visitor.h
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/rust/typecheck/rust-unify.cc
- gcc/rust/typecheck/rust-unify.h
This patch refactors the const generic type system to follow the same pattern as regular type parameters. The monolithic ConstType is split into four distinct types:
ConstParamType (generic parameter placeholder)
ConstValueType (resolved constant value)
ConstInferType (inference variable)
ConstErrorType (error sentinel)
* backend/rust-compile-expr.cc (CompileExpr::array_copied_expr): refactor to new classes
* backend/rust-compile-pattern.cc (CompilePatternCheckExpr::visit): likewise
(CompilePatternBindings::visit): likewise
* backend/rust-compile-type.cc (TyTyResolveCompile::visit): likewise
* backend/rust-compile-type.h: likewise
* typecheck/rust-hir-type-check-base.cc (TypeCheckBase::resolve_literal): likewise
* typecheck/rust-hir-type-check-expr.cc …
> gccrs: Refactor TyTy::ConstType into separate types
