Rust-GCC/gccrs

- gcc/rust/backend/rust-compile.cc
-fdump-tree-gimple should provide output of the skeleton function
Addresses #19
> This will now compile a void function declaration to gimple

- gcc/rust/analysis/rust-resolution.cc
- gcc/rust/analysis/rust-resolution.h
- gcc/rust/ast/rust-stmt.h
This gives us errors such as:
```started name resolution
INSIDE FUNCTION: main                                                                                                      
IdentifierPattern: logical                                                                                                 
IdentifierPattern: a_float                                                                                                 
LiteralExpr: 5                                           
test1.rs:6:24: error: unable to determine type for declaration from init expr
6 |     let an_integer   = 5i32; // Suffix annotation
|                        ^                             
LiteralExpr: 3.0
test1.rs:9:27: error: unable to determine type for declaration from init expr
9 |     let default_float   = …
```
> WIP type infer error handling in LetStmt

- gcc/rust/analysis/rust-resolution.h
- gcc/rust/analysis/rust-scan.cc
- gcc/rust/analysis/rust-scan.h
- gcc/rust/analysis/rust-type-resolution.cc
- gcc/rust/analysis/rust-type-resolution.h
More work will be added here but there is enough to start working
on the initial AST -> Gimple transformations now.
> Add type resolution to CallExpr

- gcc/rust/analysis/rust-name-resolution.cc
- gcc/rust/analysis/rust-resolution.h
- gcc/rust/analysis/rust-type-resolution.cc
Reduce the redundant scoping code.
> Move scoping to Resolution class

- gcc/rust/analysis/rust-type-resolution.cc
- gcc/rust/analysis/rust-type-resolution.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/ast/rust-path.h
- gcc/rust/backend/rust-compile.cc
- gcc/rust/rust-session-manager.cc
this is more WIP to compile the parameters and return type to a function
> WIP Compiler parameters and return type and setup body

- gcc/rust/ast/rust-expr.h
- gcc/rust/backend/rust-compile.cc
This is giving us the basics of gimple so far.
```
$ cat test.rs.005t.gimple
test (signed int x)
{
return;
}
main ()
{
signed int an_integer;
signed int call_test;
<unnamed type> logical;
signed int default_integer;
logical = 1;
an_integer = 5;
default_integer = 7;
default_integer = default_integer + 3;
test (1);
}
```
> AST conversion of pimritives

- gcc/rust/analysis/rust-type-resolution.cc
- gcc/rust/ast/rust-expr.h
- gcc/rust/backend/cscope.h
- gcc/rust/backend/rust-compile.cc
- gcc/rust/rust-gcc.cc
This is more WIP for the gimple conversion pass
> WIP gimple conversions for calls and returns

- gcc/rust/ast/rust-ast-full-test.cc
- gcc/rust/ast/rust-expr.h
- gcc/rust/backend/rust-compile.cc
- gcc/rust/backend/rust-compile.h
```
test (i32 x)
{           
i32 D.198;
D.198 = x + 1;
return D.198;
}           
main ()
{
i32 an_integer;
i32 call_test;
bool logical;                                                                                                                                                                                                                                        
i32 default_integer;                                                                                                                                                                                                                                 
i32 x;    
logical = 1;
an_integer = 5;
default_integer = 7;
default_integer = default_integer + 3;
call_test = test (1);
x = 5;
{
if (x == 5) goto <D.200>; else goto <D.201>; …
```
> Compile conditional expressions if/if-else/if-elif-else

- .gitignore
- gcc/rust/lex/rust-codepoint.h
- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-lex.h
- gcc/rust/lex/rust-token.h
- gcc/rust/rust-linemap.cc
- gcc/rust/rust-session-manager.cc
This PR improves code quality in the lexer. 
Notably, the giant `build_token` method had many aspects split off into separate methods. 
I also fixed some location tracking issues in the lexer.
> Lexer cleanup

- Makefile.def
- Makefile.in
- gcc/rust/Make-lang.in
- gcc/rust/analysis/rust-type-resolution.cc
- gcc/rust/backend/rust-compile.cc
- gcc/testsuite/lib/rust-dg.exp
- gcc/testsuite/lib/rust.exp
- gcc/testsuite/rust.test/compilable/conditional.rs
- gcc/testsuite/rust.test/compilable/impl_block.rs
- gcc/testsuite/rust.test/compilable/static_function.rs
- gcc/testsuite/rust.test/compilable/struct_init.rs
- gcc/testsuite/rust.test/compilable/type_infer1.rs
- gcc/testsuite/rust.test/rust-test.exp
This PR adds the boiler plate for dejagnu testsuite for rust. make check-rust should invoke this.
> Testsuite PR

- .github/workflows/ccpp.yml
- README.md
> Add missing Dejagnu dependancy to run test suite.

- .github/workflows/ccpp.yml
This will make viewing the tests overview in builds easier
> Seperate build and Test steps in the build

- gcc/rust/ast/clone-test.h
- gcc/rust/ast/rust-ast-containers.h
- gcc/rust/ast/rust-ast-full.h
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/ast/rust-cond-compilation.h
- gcc/rust/ast/rust-macro.h
- gcc/rust/ast/rust-path.h
- gcc/rust/ast/rust-pattern.h
- gcc/rust/ast/rust-stmt.h
- gcc/rust/ast/rust-type.h
- gcc/rust/backend/cscope.h
- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/lex/rust-codepoint.h
- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-token.cc
- gcc/rust/lex/rust-token.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.cc
- gcc/rust/parse/rust-parse.h
- gcc/rust/rust-backend.h
- gcc/rust/rust-buffered-queue.h
- gcc/rust/rust-diagnostics.h
- gcc/rust/rust-gcc-diagnostics.cc
- gcc/rust/rust-lang.cc
- gcc/rust/rust-linemap.cc
- gcc/rust/rust-location.h
- gcc/rust/rust-object-export.h
Add GPL license text to files without the header
Resolves #66
> Add missing license text

- gcc/rust/ast/rust-item.h
- gcc/rust/backend/rust-compile-context.h
- gcc/rust/backend/rust-compile-expr.h
- gcc/rust/backend/rust-compile-item.h
- gcc/rust/hir/rust-ast-lower-item.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/resolve/rust-ast-resolve-item.h
- gcc/rust/resolve/rust-ast-resolve-toplevel.h
- gcc/rust/typecheck/rust-hir-type-check-toplevel.h
- gcc/rust/typecheck/rust-hir-type-check-type.h
- gcc/testsuite/rust.test/compilable/constant1.rs
Adds resolution and named readonly constant GIMPLE node for the constant.
Fixes #81
> Implement constant expressions

- .github/workflows/greetings.yml
This should make sure people are aware about copyright assignment on their first PR.
> Create new Greetings automation on github

- gcc/rust/backend/rust-compile-expr.h
- gcc/rust/hir/rust-ast-lower-expr.h
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/resolve/rust-ast-resolve-expr.h
- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust.test/compilable/struct_access1.rs
This adds in struct field expressions and should be generic enough for
tuples later on.
> Add struct_field_expression support

- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/testsuite/rust.test/compilable/arithmetic_expressions1.rs
This adds test cases and enforces the type rules for ArithmeticOrLogical
Operators.
> Enforce the rules for arithmetic operations

- .github/workflows/clang-format.yml
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-path.h
- gcc/rust/lang-specs.h
- gcc/rust/lex/rust-codepoint.h
- gcc/rust/lex/rust-token.h
- gcc/rust/operator.h
- gcc/rust/rust-backend.c
- gcc/rust/rust-buffered-queue.h
- gcc/rust/rust-diagnostics.cc
- gcc/rust/rust-gcc-diagnostics.cc
- gcc/rust/rust-lang.cc
- gcc/rust/rust-linemap.cc
- gcc/rust/rust-object-export.c
- gcc/rust/rust-object-export.h
- gcc/rust/rust-target.h
Signed-off-by: Akshat Agarwal <humancalico@disroot.org>
> Format all files in gcc/rust/ using clang-format and add clang format GitHub Action

- .github/workflows/clang-format.yml
- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/rust/typecheck/rust-hir-type-check-implitem.h
- gcc/rust/typecheck/rust-hir-type-check-toplevel.h
- gcc/rust/typecheck/rust-hir-type-check-type.h
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-tyty-call.h
- gcc/rust/typecheck/rust-tyty-rules.h
The CI didn't run on #238 probably because it was opened before the #242 so some files were left unformatted so I have reformatted those as well in the first commit
Closes: #240
> Run clang-format CI on every push on master branch

- gcc/rust/parse/rust-parse-impl.h
This patch fixes the inner attribute parsing. And throw errors properly.
Here's a test code:
```rust
// sum.rs
#![recursion_limit="128"]
macro_rules! sum {
($base:expr) => { $base };
($a:expr, $($rest:expr),+) => { $a + sum!($($rest),+) };
}
fn main() {
println!("{}", sum!(1,2,3,4,5));
```
Compile:
```bash
gccrs -frust-dump-parse sum.rs -c | less gccrs.ast.dump
```
We can get:
```rust
Crate: 
inner attributes: 
recursion_limit = 128
items: 
......
```
BTW, `rustc` lacks of necessary checks, but we make it better, for example, if we write some bad code:
```rust
#!,recursion_limit="128"]
...
```
`rustc` doesn't complain at all. But in patched `gccrs`:
```bash
sum.rs:1:3: error: Expect `['
1 | #!,recursion_limit="128"]
|   ^
sum.rs:1:3: error: unrecognised token ‘,’ for start of item …
```
> Fix to parse inner attribute correctly

- gcc/rust/backend/rust-compile-implitem.h
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/typecheck/rust-hir-type-check-toplevel.h
- gcc/rust/typecheck/rust-hir-type-check.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
This is a PR to fix the test suite failures
> Test suite failures

- .github/workflows/ccpp.yml
issue #270 resolved, added make -j $(nproc) to CI workflow.
> CI workflow make -j commit

- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/rust/typecheck/rust-hir-type-check-type.h
- gcc/rust/typecheck/rust-tyty-rules.h
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
resolves #272 ,  renamed class TyCtx to TyVar according to the PR #268
> refactored class TyCtx to TyVar

- README.md
Resolves #279 . Document how to use docker gccrs to build full rust .exe
> Documentation for issue #279

- gcc/rust/typecheck/rust-hir-type-check.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
I'm not sure that my default_type is ok or not.   #263
> Refactoring TypeResolution Resolve with new InferType::default_type and defaulting float to f64

- gcc/rust/backend/rust-compile-context.h
- gcc/rust/backend/rust-compile-implitem.h
- gcc/rust/backend/rust-compile-item.h
- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/backend/rust-compile-tyty.h
- gcc/rust/rust-backend.h
- gcc/rust/rust-gcc.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/rust/typecheck/rust-hir-type-check-implitem.h
- gcc/rust/typecheck/rust-hir-type-check-item.h
- gcc/rust/typecheck/rust-hir-type-check-stmt.h
- gcc/rust/typecheck/rust-hir-type-check-toplevel.h
- gcc/rust/typecheck/rust-hir-type-check-type.h
- gcc/rust/typecheck/rust-hir-type-check.cc
- gcc/rust/typecheck/rust-substitution-mapper.h
- gcc/rust/typecheck/rust-tyty-rules.h
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust.test/compilable/generics3.rs
- gcc/testsuite/rust.test/compilable/generics4.rs
- gcc/testsuite/rust.test/compilable/generics5.rs
- gcc/testsuite/rust.test/compilable/generics6.rs
- gcc/testsuite/rust.test/compilable/generics7.rs
Recursive function substution is not supported here with this patch. As the
patch was getting bigger it seems better to merge sooner than later to
avoid conflicts.
#235 #234 #236
> Generics continued this adds more type resolution to ADT and Functions

- .github/bors.toml
- .github/workflows/ccpp.yml
- .github/workflows/clang-format.yml
Github Action only triggered on bors-ng controlled branches (trying/staging).
Fixes #324
> Initial bors-ng integration

- gcc/rust/analysis/rust-hir-liveness.cc
- gcc/rust/analysis/rust-hir-liveness.h
- gcc/rust/analysis/rust-hir-scan-deadcode.h
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/testsuite/rust.test/compile/unused.rs
> add more path to collect live symbols

- gcc/testsuite/rust.test/xfail_compile/issue-407-2.rs
- gcc/testsuite/rust.test/xfail_compile/issue-407.rs
@teromene, for your information/learning.  ;-D
> Fix #407, #409 testcases

- gcc/rust/resolve/rust-ast-resolve-unused.h
- gcc/rust/resolve/rust-name-resolver.h
- gcc/testsuite/rust.test/compile/loop5.rs
- gcc/testsuite/rust.test/compile/loop7.rs
- gcc/testsuite/rust.test/compile/struct_base_init_1.rs
- gcc/testsuite/rust.test/compile/underscore_id.rs
> Allow unused underscore identifiers

- gcc/rust/ast/rust-ast.h
- gcc/rust/hir/rust-ast-lower-block.h
- gcc/rust/hir/rust-ast-lower-expr.h
- gcc/rust/hir/rust-ast-lower-implitem.h
- gcc/rust/hir/rust-ast-lower-item.h
- gcc/rust/hir/rust-ast-lower-stmt.h
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/hir/tree/rust-hir.h
lowering attribute by copying attribute from AST to HIR directly.
Addresses #459
> lowering attribute by copying attribute from AST to HIR directly

- gcc/config/arm/arm-rust.c
> Build fixes for 32-bit ARM

- gcc/rust/Make-lang.in
- gcc/rust/lint/rust-lint-marklive-base.h
- gcc/rust/lint/rust-lint-marklive.cc
- gcc/rust/lint/rust-lint-marklive.h
- gcc/rust/lint/rust-lint-scan-deadcode.h
- gcc/rust/rust-session-manager.cc
replace analysis dir with lint dir and rename liveness to marklive
> replace analysis dir with lint dir and rename liveness to marklive

- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-token.h
This series implements a couple of small changes to improve the handling
of strings attached to Token.
> Token strings

- gcc/rust/lint/rust-lint-marklive.cc
- gcc/rust/lint/rust-lint-marklive.h
- gcc/rust/lint/rust-lint-scan-deadcode.h
- gcc/rust/resolve/rust-ast-resolve-unused.h
- gcc/testsuite/rust/compile/torture/cfg_attr.rs
- gcc/testsuite/rust/compile/torture/unused1.rs
- gcc/testsuite/rust/compile/torture/unused_struct.rs
Marking live symbol for struct construction.
> Marking live symbol for struct construction.

- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/rust/typecheck/rust-hir-type-check-type.h
Pushing 2 commit for Mark, cleaning up some warning.
> Minor warning cleanup

- gcc/rust/ast/rust-item.h
- gcc/rust/backend/rust-compile-base.h
- gcc/rust/backend/rust-compile-implitem.h
- gcc/rust/hir/rust-ast-lower-implitem.h
- gcc/rust/hir/rust-ast-lower-item.h
- gcc/rust/hir/rust-ast-lower-stmt.h
- gcc/rust/hir/tree/rust-hir-full-decls.h
- gcc/rust/hir/tree/rust-hir-full-test.cc
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-visitor.h
- gcc/rust/lint/rust-lint-marklive-base.h
- gcc/rust/lint/rust-lint-marklive.h
- gcc/rust/resolve/rust-ast-resolve-item.h
- gcc/rust/resolve/rust-ast-resolve-type.h
- gcc/rust/typecheck/rust-hir-const-fold-base.h
- gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
- gcc/rust/typecheck/rust-hir-path-probe.h
- gcc/rust/typecheck/rust-hir-trait-resolve.h
- gcc/rust/typecheck/rust-hir-type-check-base.h
- gcc/rust/typecheck/rust-hir-type-check-implitem.h
- gcc/rust/typecheck/rust-tycheck-dump.h
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/compile/torture/traits3.rs
This PR strips HIR::Method and reuses the HIR::Function with a HIR::SelfParam.
It reduces complexity in type checking and GENERIC generation.
> Add trait-impl support for methods

- gcc/rust/ast/rust-item.h
- gcc/rust/hir/rust-ast-lower-item.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/lint/rust-lint-marklive.cc
- gcc/rust/lint/rust-lint-marklive.h
- gcc/rust/lint/rust-lint-scan-deadcode.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/torture/forward_decl_3.rs
- gcc/testsuite/rust/compile/torture/generics10.rs
- gcc/testsuite/rust/compile/torture/generics13.rs
- gcc/testsuite/rust/compile/torture/generics14.rs
- gcc/testsuite/rust/compile/torture/generics4.rs
- gcc/testsuite/rust/compile/torture/generics6.rs
- gcc/testsuite/rust/compile/torture/generics7.rs
- gcc/testsuite/rust/compile/torture/impl_block3.rs
- gcc/testsuite/rust/compile/torture/methods1.rs
- gcc/testsuite/rust/compile/torture/methods2.rs
- gcc/testsuite/rust/compile/torture/methods3.rs
- gcc/testsuite/rust/compile/torture/nested_struct1.rs
- gcc/testsuite/rust/compile/torture/struct_base_init_1.rs
- gcc/testsuite/rust/compile/torture/struct_init.rs
- gcc/testsuite/rust/compile/torture/struct_init_3.rs
- gcc/testsuite/rust/compile/torture/struct_init_4.rs
- gcc/testsuite/rust/compile/torture/struct_init_5.rs
- gcc/testsuite/rust/compile/torture/struct_init_6.rs
- gcc/testsuite/rust/compile/torture/struct_init_7.rs
- gcc/testsuite/rust/compile/torture/type_infer1.rs
- gcc/testsuite/rust/compile/torture/type_infer5.rs
- gcc/testsuite/rust/compile/torture/unused_struct_field.rs
1. make struct field carry the location info. Fixed #533 
2. detect unused struct field.
> Unused struct fields

- gcc/rust/lint/rust-lint-marklive.h
- gcc/testsuite/rust/compile/torture/if.rs
- gcc/testsuite/rust/compile/torture/if_elif.rs
- gcc/testsuite/rust/compile/torture/if_else.rs
mark live symbol in if expr family except if let expr
> mark live symbol in if expr family except if let expr

- gcc/rust/lint/rust-lint-marklive.cc
- gcc/rust/lint/rust-lint-marklive.h
- gcc/rust/lint/rust-lint-scan-deadcode.h
- gcc/testsuite/rust/compile/torture/struct_base_init_1.rs
- gcc/testsuite/rust/compile/torture/struct_init_5.rs
- gcc/testsuite/rust/compile/torture/struct_init_6.rs
- gcc/testsuite/rust/compile/torture/struct_init_7.rs
- gcc/testsuite/rust/compile/torture/tuple_struct_unused.rs
mark live symbol support type alias and tuple struct
> mark live symbol support type alias and tuple struct

- gcc/rust/lint/rust-lint-scan-deadcode.h
make the warning msg be searched easier.
Fixed #545
> make the warning msg be searched easier

- gcc/rust/ast/rust-ast.h
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-pattern.h
- gcc/rust/hir/tree/rust-hir-type.h
- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-token.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/bad_inner_doc.rs
- gcc/testsuite/rust/compile/doc_isolated_cr_block_comment.rs
- gcc/testsuite/rust/compile/doc_isolated_cr_inner_block_comment.rs
- gcc/testsuite/rust/compile/doc_isolated_cr_inner_line_comment.rs
- gcc/testsuite/rust/compile/doc_isolated_cr_line_comment.rs
- gcc/testsuite/rust/compile/torture/all_doc_comment_line_blocks.rs
- gcc/testsuite/rust/compile/torture/all_doc_comment_line_blocks_crlf.rs
- gcc/testsuite/rust/compile/torture/isolated_cr_block_comment.rs
- gcc/testsuite/rust/compile/torture/isolated_cr_line_comment.rs
This adds support for inner and outer doc comments within the parser.
> Handle doc comments strings

- gcc/rust/lint/rust-lint-marklive.cc
Add some comments about how scan dead code pass handles PathInExpression and PathExprSegment.
> add some comments about how scan dead code pass handle PathInExpression and PathExprSegment

- gcc/rust/lint/rust-lint-scan-deadcode.h
Add some comments about what's kind of unused item will be warned
> Add some comments about what's kind of unused item will be warned

- gcc/rust/lint/rust-lint-marklive.cc
- gcc/rust/lint/rust-lint-marklive.h
- gcc/rust/lint/rust-lint-scan-deadcode.h
- gcc/rust/util/rust-hir-map.h
- gcc/testsuite/rust/compile/torture/generics13.rs
- gcc/testsuite/rust/compile/torture/generics14.rs
- gcc/testsuite/rust/compile/torture/generics18.rs
- gcc/testsuite/rust/compile/torture/generics24.rs
- gcc/testsuite/rust/compile/torture/impl_block_unused.rs
warn the unused associated functions
> warn the unused associated functions

- gcc/rust/backend/rust-compile-context.h
- gcc/rust/backend/rust-compile-tyty.h
- gcc/rust/hir/rust-ast-lower-type.h
- gcc/rust/hir/tree/rust-hir-full-test.cc
- gcc/rust/hir/tree/rust-hir-type.h
- gcc/rust/resolve/rust-ast-resolve-type.h
- gcc/rust/typecheck/rust-hir-const-fold.h
- gcc/rust/typecheck/rust-hir-type-check-type.h
- gcc/rust/typecheck/rust-substitution-mapper.h
- gcc/rust/typecheck/rust-tyty-call.h
- gcc/rust/typecheck/rust-tyty-cmp.h
- gcc/rust/typecheck/rust-tyty-coercion.h
- gcc/rust/typecheck/rust-tyty-rules.h
- gcc/rust/typecheck/rust-tyty-visitor.h
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/compile/torture/coercion2.rs
We will need to add the remaining coercion calls for the relevant sites
to get the full support we need but this will serve as the initial support.
Fixes #124
> Raw pointer support

- gcc/rust/hir/rust-ast-lower-implitem.h
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
Add mappings for trait items that can be used for
query-based compilation and type checking
> Add mappings for trait items

- gcc/rust/parse/rust-parse-impl.h
Parsing the .. (DOT_DOT) operator to get a range had two
issues. Trying to compile:
let block = [1,2,3,4,5];
let _rf = &block[1..];
let _rt = &block[..3];
let _rft = &block[2..4];
range.rs:4:23: error: found unexpected token ‘]’ in null denotation
4 |   let _rf = &block[1..];
|                       ^
range.rs:4:24: error: expecting ‘]’ but ‘;’ found
4 |   let _rf = &block[1..];
|                        ^
Since .. can represent either a range from or a range from-to it can
be followed by an expression or not. We do have a hack in our
pratt-parser so that it is allowed to return a nullptr. But even in
that case it will have swallowed the next token. Add another hack to
the pratt-parser so that if the next token is one that cannot start an
expression and the caller allows a nullptr return …
> Support RangeFrom ([x..]) and RangeFromTo ([x..y]) in the parser

- gcc/rust/backend/rust-compile-expr.h
- gcc/rust/hir/rust-ast-lower-base.h
- gcc/rust/hir/rust-ast-lower-expr.h
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/resolve/rust-ast-resolve-expr.h
- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/rust/typecheck/rust-tyty-cast.h
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/compile/cast1.rs
- gcc/testsuite/rust/compile/torture/cast1.rs
- gcc/testsuite/rust/compile/torture/cast2.rs
- gcc/testsuite/rust/compile/torture/cast3.rs
This is the initial type casting rules more test cases will be added over time. To find gaps.
Fixes #158
> TypeCastExpr

- gcc/rust/hir/rust-ast-lower-stmt.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
From Mark Wieelard: https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000160.html
> Here are a couple of little patches to improve or simplify locations a
> bit
> A few more location patches 

- gcc/rust/hir/rust-ast-lower-item.h
- gcc/rust/resolve/rust-ast-resolve-item.h
- gcc/rust/typecheck/rust-hir-trait-resolve.h
Add name resolution and HIR lowering to trait-bounds
> Add building blocks for super-traits

- gcc/rust/backend/rust-mangle.cc
This PR adds the generation of type prefixes for simple types, which are numeric types, booleans, chars, strings, empty tuples/unit types and placeholder types.
I'm unsure as to how to test this, even in the long run. There might be some shenanigans we can pull using an elf reader and regexes in order to compare ABI names with rustc.
The entire implementation of v0 name mangling is very large, so I thought I'd split it up in multiple PRs.
> Add v0 type mangling prefixing for simple types

- gcc/rust/typecheck/rust-hir-const-fold.h
Add some more missing constant-folding operations
> Add missing const folding

- gcc/rust/resolve/rust-ast-resolve-item.h
- gcc/testsuite/rust/compile/torture/issue-808.rs
- gcc/testsuite/rust/compile/torture/traits11.rs
- gcc/testsuite/rust/compile/torture/traits4.rs
- gcc/testsuite/rust/compile/torture/traits5.rs
- gcc/testsuite/rust/compile/torture/traits6.rs
- gcc/testsuite/rust/execute/torture/operator_overload_1.rs
- gcc/testsuite/rust/execute/torture/operator_overload_2.rs
- gcc/testsuite/rust/execute/torture/operator_overload_3.rs
- gcc/testsuite/rust/execute/torture/operator_overload_4.rs
- gcc/testsuite/rust/execute/torture/operator_overload_5.rs
There is still another hack I am working through to remove before fixing the issue.
Addresses: #739
> Remove implicit name hack for trait associated types

- gcc/rust/typecheck/rust-hir-type-check-expr.h
This ports over some code from the method-call expr to try and infer the
arguments in the function definition when required.
Addresses #809
> Support generics on operator overlads.

- gcc/rust/gource-gccrs.sh
This script tries to isolate our changes to GCC minus the changes to
gcc/config so that we can visualize our development history.
I will be uploading a video output to youtube shortly, it also includes our cargo-integration project too :D
> Add script to generate gource

- gcc/rust/monthly-diff.py
This script was used to get metrics and a graph for the 2021 end year report
> add script to graph the changes over time

- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
This helper is part of a larger PR into fixing our implementation of MethodResolution
> Add Mappings::iterate_trait_items helper

- .github/workflows/ccpp.yml
- gcc/testsuite/rust/compile/inline_1.rs
> Forbid unresolved test cases

- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-lex.h
- gcc/rust/parse/rust-cfg-parser.cc
- gcc/rust/parse/rust-cfg-parser.h
- gcc/rust/rust-session-manager.cc
- gcc/rust/rust-session-manager.h
- gcc/rust/util/rust-hir-map.cc
> Parse proper cfg values

- gcc/rust/lex/rust-lex.h
Fixes the -fself-test invalid memory accesses and adds documentation
regarding a possible future fix.
Co-authored-by: tschwinge <thomas@schwinge.name>
Co-authored-by: philberty <philip.herron@embecosm.com>
Closes #987
> lexer: Add reference and warning documentation

- gcc/rust/expand/rust-macro-expand.cc
- gcc/testsuite/rust/compile/macro10.rs
> macros: Allow any delimiters for invocation

- gcc/rust/hir/rust-ast-lower-type.h
> Add missing HIR lowering for SliceTypes

- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/rust-linemap.cc
- gcc/rust/rust-linemap.h
- gcc/rust/util/rust-hir-map.cc
- gcc/testsuite/rust/execute/torture/builtin_macros3.rs
Fixes issue #979 
1) Added the column!() macro using the LOCATION_COLUMN() from gcc_linemap
2) To-Do: add relevant test cases.
Signed-off-by : M V V S Manoj Kumar <mvvsmanojkumar@gmail.com>
The test case I added always fails, I can't figure out whether there is a problem in my test case or there is something wrong with my implementation of the column!() macro. Do let me know where I am going wrong and also if I missed something . :)
> Added column!() macro

- gcc/rust/parse/rust-parse.cc
- gcc/testsuite/rust/compile/macro27.rs
- gcc/testsuite/rust/compile/macro28.rs
- gcc/testsuite/rust/compile/macro29.rs
- gcc/testsuite/rust/compile/macro30.rs
- gcc/testsuite/rust/compile/macro31.rs
- gcc/testsuite/rust/compile/macro35.rs
This PR adds hints about the allowed tokens after a certain fragment, and fixes tests to uphold the new error message
> Add hints for valid follow tokens

- gcc/rust/parse/rust-parse.cc
- gcc/testsuite/rust/compile/macro39.rs
> Properly perform follow set checking on matcher

- .github/workflows/ccpp.yml
- gcc/rust/typecheck/rust-hir-path-probe.h
> Add base for build job using older GCC version

- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/util/rust-hir-map.cc
- gcc/testsuite/rust/compile/builtin_macro_compile_error.rs
> macros: add compile_error! macro

- gcc/rust/lang.opt
- gcc/rust/rust-session-manager.cc
- gcc/rust/rust-session-manager.h
> Add -frust-edition flag and possible values

- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/rust-session-manager.h
- gcc/rust/util/rust-hir-map.cc
> macros: add include! macro

- .github/workflows/docker.yml
- ci: skip docker image push when in a fork
> CI: do not push Docker image in a fork

- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-ast-lower-base.h
- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/compile/torture/doc_comment.rs
- hir: improve doc attribute handling
Addresses #1140
> hir: improve doc attribute handling

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-base.h
- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/compile/attr_cold.rs
> backend: handle cold attribute

- gcc/rust/Make-lang.in
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/privacy/rust-privacy-check.cc
- gcc/rust/privacy/rust-privacy-common.h
- gcc/rust/privacy/rust-visibility-resolver.cc
- gcc/rust/privacy/rust-visibility-resolver.h
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
This adds a new visitor whose aim is to resolve the visibility of each VisItem in a crate. The crux of the implementation will be resolving `pub restricted` items, whose module needs to be resolved using name resolution/path resolution. On top of that, we will need to add a new visitor building a "tree" of modules, with a `accessible_from` or `is_child_of` method: All children of a module get to access its items whose visibility is inherited.
> Add base for visibility resolving

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-base.h
- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/debug/custom_link_section.rs
- handle the `link_section` attribute
> backend: handle link_section attribute

- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
> Keep `SimplePath{Segment}`s in mappings

- gcc/rust/rust-session-manager.cc
- gcc/rust/rust-session-manager.h
- gcc/rust/util/rust-hir-map.h
- gcc/testsuite/rust/compile/attr-mismatch-crate-name.rs
- gcc/testsuite/rust/compile/mismatch-crate-name.rs
- rust-session-manager: handle `crate_name` attribute
Fix #789 properly
> rust-session-manager: handle `crate_name` attribute

- gcc/rust/ast/rust-ast-full-test.cc
- gcc/rust/ast/rust-item.h
- gcc/rust/ast/rust-macro.h
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/parse/rust-parse-impl.h
Sorry to new contributors but I think I've taken all the good first issues we opened yesterday... 
Closes #1179 
Closes #1180
Closes #1181
Closes #1182
Necessary for #1172 
Addresses #1159
> Add missing `SimplePath`s location

- gcc/rust/backend/rust-compile-intrinsic.cc
- intrinsic: add breakpoint intrinsic
Addresses #658
> intrinsic: add breakpoint intrinsic

- gcc/rust/backend/rust-compile-intrinsic.cc
- intrinsic: add rotate_left and rotate_right intrinsic
Address #658
> intrinsic: add rotate_left and rotate_right intrinsic

- gcc/rust/Make-lang.in
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/hir/rust-ast-lower-item.h
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/hir/tree/rust-hir-full-test.cc
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-path.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/privacy/rust-privacy-check.cc
- gcc/rust/privacy/rust-privacy-common.h
- gcc/rust/privacy/rust-visibility-resolver.cc
- gcc/rust/privacy/rust-visibility-resolver.h
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
- gcc/testsuite/rust/compile/pub_restricted_1.rs
> Resolve module visibility properly

- gcc/rust/Make-lang.in
- gcc/rust/privacy/rust-privacy-check.cc
- gcc/rust/privacy/rust-privacy-common.h
- gcc/rust/privacy/rust-privacy-reporter.cc
- gcc/rust/privacy/rust-privacy-reporter.h
- gcc/rust/privacy/rust-pub-restricted-visitor.cc
- gcc/rust/privacy/rust-pub-restricted-visitor.h
- gcc/rust/privacy/rust-visibility-resolver.cc
- gcc/rust/privacy/rust-visibility-resolver.h
- gcc/rust/resolve/rust-ast-resolve-base.h
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-toplevel.h
- gcc/rust/resolve/rust-ast-resolve.cc
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
- gcc/rust/util/rust-optional-test.cc
- gcc/rust/util/rust-optional.h
- gcc/testsuite/rust/compile/privacy1.rs
- gcc/testsuite/rust/compile/pub_restricted_3.rs
This adds a base visitor for reporting basic privacy violations. For now, only function calls are implemented.
> Report simple privacy violations

- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/privacy/rust-privacy-check.cc
- gcc/rust/privacy/rust-privacy-reporter.cc
- gcc/rust/privacy/rust-privacy-reporter.h
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
- gcc/testsuite/rust/compile/privacy5.rs
- gcc/testsuite/rust/compile/privacy6.rs
~~Needs #1255, so skip reviewing the first commit or wait for it to be merged~~ Done and rebased :)
> Report privacy errors on explicit types

- README.md
> Add build badges for marks build-farm

- Dockerfile
> docker: Add commit information to Docker image

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/const_generics_1.rs
- gcc/testsuite/rust/compile/const_generics_2.rs
Closes #1301 
~~Needs #1312, so only review the last commit~~
> Parse const generics properly

- gcc/rust/ast/rust-path.h
- gcc/rust/parse/rust-parse-impl.h
Closes #1320 
Sorry for taking a good-first-pr but this is starting to be needed :)
> ast: Add location to ConstGenericArg

- gcc/rust/ast/rust-ast-full-test.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-macro.h
- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-base.h
- gcc/rust/rust-gcc.cc
- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/compile/attr_deprecated.rs
- gcc/testsuite/rust/compile/attr_deprecated_2.rs
- handle the `deprecated` attribute
> backend: handle deprecated attribute

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/util/rust-abi.cc
- gcc/rust/util/rust-abi.h
- gcc/testsuite/rust/debug/win64-abi.rs
- Properly handles foreign (`extern` functions) ABIs
> backend: properly handles foreign ABIs

- gcc/rust/expand/rust-attribute-visitor.cc
- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/testsuite/rust/compile/macro_return.rs
- gcc/testsuite/rust/compile/torture/macro_as_expr.rs
- macros: properly handles recursive macros
Fixes #1084
> macros: properly handles recursive macros

- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/expand/rust-macro-substitute-ctx.cc
- gcc/testsuite/rust/compile/macro-issue1400-2.rs
- gcc/testsuite/rust/compile/macro-issue1400.rs
> Allow repeating metavars alongside repetitions

- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/testsuite/rust/compile/unsafe9.rs
> unsafe: Add checks for union field accesses

- gcc/rust/util/rust-hir-map.cc
- gcc/testsuite/rust/compile/builtin_macro_compile_error.rs
- gcc/testsuite/rust/compile/builtin_macro_concat.rs
- gcc/testsuite/rust/compile/builtin_macro_env.rs
- gcc/testsuite/rust/compile/builtin_macro_include_bytes.rs
- gcc/testsuite/rust/compile/builtin_macro_include_str.rs
- gcc/testsuite/rust/compile/macro42.rs
- gcc/testsuite/rust/execute/torture/builtin_macro_cfg.rs
- gcc/testsuite/rust/execute/torture/builtin_macro_concat.rs
- gcc/testsuite/rust/execute/torture/builtin_macro_env.rs
- gcc/testsuite/rust/execute/torture/builtin_macro_include_bytes.rs
- gcc/testsuite/rust/execute/torture/builtin_macro_include_str.rs
- gcc/testsuite/rust/execute/torture/builtin_macro_line.rs
- gcc/testsuite/rust/execute/torture/builtin_macros1.rs
- gcc/testsuite/rust/execute/torture/builtin_macros3.rs
- gcc/testsuite/rust/execute/torture/macros29.rs
- gcc/testsuite/rust/execute/torture/macros30.rs
- gcc/testsuite/rust/execute/torture/macros31.rs
- hir: more conformant builtin macro detection
Fixes #971
> hir: more conformant builtin macro detection

- gcc/rust/rust-backend.h
- gcc/rust/rust-gcc.cc
This removes the unused switch statement wrapper
> Remove unused backend wrapper

- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/testsuite/rust/compile/unsafe10.rs
> unsafe: Allow calls to safe intrinsics

- gcc/rust/backend/rust-constexpr.cc
NOP_EXPR should fall through into convert and view_convert_exprs.
> Fix port of NOP_EXPR

- gcc/rust/backend/rust-constexpr.cc
> constexpr: Fix warning in sorry fmt string

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty.h
> Fix generic substitution on unit structs

- gcc/rust/typecheck/rust-hir-type-check-stmt.cc
- gcc/testsuite/rust/compile/const6.rs
- gcc/testsuite/rust/compile/const7.rs
The fix is a bit of guess so do have a careful look :)
> Add testcases to test folding

- gcc/testsuite/rust/compile/const_generics_7.rs
> const generics: Make sure const generic types are visited properly in all contexts

- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-const-checker.h
- gcc/testsuite/rust/compile/const_generics_8.rs
> const generics: Forbid default values in Functions, Traits and Impls

- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-expand.cc
- gcc/testsuite/rust/compile/builtin_macro_concat.rs
- gcc/testsuite/rust/compile/builtin_macro_env.rs
- gcc/testsuite/rust/compile/builtin_macro_recurse.rs
- expand: eagerly evaluate the macros inside some of the builtin macros
> expand: eager evaluate macros inside builtin macros

- gcc/rust/lang.opt
- gcc/rust/rust-lang.cc
Same as #1560, but in a single more descriptive commit. I'll hold on doing the other fixes until you're okay with the process @philberty
> Apply #1560 master

- gcc/rust/ast/rust-ast-dump.cc
Implements ast dump for TypeAlias
> ast: dump TypeAlias

- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
> [25/37] rust-privacy-reporter: Add copyright header

- gcc/rust/parse/rust-cfg-parser.cc
> [10/37] rust-cfg-parser: Add copyright header

- gcc/rust/lang-specs.h
> [33/37] lang-specs: Rename language spec @rs -> @rust

- gcc/rust/ast/rust-ast-dump.cc
- gcc/rust/ast/rust-ast-dump.h
- gcc/rust/ast/rust-macro.h
> Dump macro declarations properly

- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/parse/rust-cfg-parser.cc
> Add missing copyright headers

- gcc/rust/ast/rust-ast-full-test.cc
- gcc/rust/ast/rust-macro.h
- gcc/rust/lex/rust-codepoint.h
- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-token.cc
- gcc/rust/lex/rust-token.h
- gcc/rust/parse/rust-cfg-parser.h
- gcc/rust/rust-object-export.cc
- gcc/rust/util/rust-attributes.cc
- gcc/rust/util/rust-make-unique.h
- gcc/rust/util/rust-optional-test.cc
> Apply 1559 master (remove system includes)

- gcc/rust/Make-lang.in
- gcc/rust/lang-specs.h
Co-authored-by: ibuclaw <ibuclaw@gdcproject.org>
Let's still do this while we haven't resolved #1540 :)
Closes #1609
> Apply #1605 on master (fix lang spec)

- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/testsuite/rust/compile/torture/intrinsics-6.rs
- gcc/testsuite/rust/compile/torture/intrinsics-7.rs
> Intrinsics unchecked ops

- .github/workflows/bootstrap.yml
This should fix the CI job for bootstrapping
> ci: Use same CXXFLAGS in bootstrap workflow

- gcc/rust/ast/rust-ast-dump.cc
Adds dump for unit struct
Depends on #1624
> Ast dump unit struct

- gcc/rust/util/rust-lang-item.h
- gcc/testsuite/rust/compile/torture/phantom_data.rs
Fixes #1127 
Added `phantom_data` lang item
> Implement PhantomData

- gcc/rust/ast/rust-item.h
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/parse/rust-parse-impl.h
Hi. I've added location to AST::Visibility, but it's possible I may have missed some steps here.
Fixes #1183.
> Add location to AST::Visibility

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/rust-gcc.cc
> Release `mpz_t` values properly

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/rust-gcc.cc
- gcc/rust/rust-lang.cc
> No fold after convert to

- gcc/rust/backend/rust-compile-expr.cc
Issue created by the subsequent merges
> 8e52e414f40b: Fix merge issue

- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-lex.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/rust/rust-session-manager.cc
- gcc/rust/util/rust-optional.h
> Improve dump lex

- gcc/rust/backend/rust-builtins.cc
Merging #1630 broke the bootstrap build
> builtins: Remove unused parameter

- README.md
I love https://justforfunnoreally.dev/
> just for fun

- gcc/rust/Make-lang.in
- gcc/rust/lang.opt
- gcc/rust/rust-session-manager.cc
- gcc/testsuite/lib/rust.exp
Remember to change your `./configure` line :)
This is obviously up for discussion and I would be happy to get some more input.
> Implement `-frust-incomplete-and-experimental-compiler-do-not-use` flag

- gcc/rust/backend/rust-compile-type.cc
- gcc/rust/backend/rust-constexpr.cc
- gcc/rust/backend/rust-tree.cc
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/checks/errors/privacy/rust-reachability.cc
- gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/checks/lints/rust-lint-marklive.cc
- gcc/rust/checks/lints/rust-lint-unused-var.cc
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/tree/rust-hir-full-test.cc
- gcc/rust/lex/rust-lex.cc
- gcc/rust/lex/rust-lex.h
- gcc/rust/metadata/rust-export-metadata.cc
- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/resolve/rust-ast-resolve-type.cc
- gcc/rust/resolve/rust-ast-verify-assignee.h
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/rust/typecheck/rust-hir-type-check-item.h
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/rust/typecheck/rust-tyty-rules.h
- gcc/rust/util/rust-attributes.cc
This starts removing some of the unused parameters within the codebase
> Cleanup unused parameters

- gcc/rust/CONTRIBUTING.md
- gcc/rust/README.md
- gcc/rust/ast/rust-item.h
- gcc/rust/lang.opt
- gcc/rust/lex/rust-token.h
- gcc/rust/parse/rust-parse-impl.h
Will need to be backported to master
> Fix whitespace errors

- gcc/rust/backend/rust-builtins.cc
- gcc/testsuite/rust/compile/torture/intrinsics-math.rs
Addresses https://github.com/Rust-GCC/gccrs/issues/658
Added math intrinsic functions.
> Add math intrinsics

- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/testsuite/rust/compile/const10.rs
> Check const functions for mutable references

- gcc/rust/rust-session-manager.cc
> Fix frust very long typo

- gcc/rust/ast/rust-ast-full-decls.h
- gcc/rust/ast/rust-ast-full-test.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-item.h
- gcc/rust/ast/rust-macro.h
- gcc/rust/lex/rust-token.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/decl_macro1.rs
- gcc/testsuite/rust/compile/decl_macro2.rs
- gcc/testsuite/rust/compile/decl_macro3.rs
- gcc/testsuite/rust/compile/decl_macro4.rs
- gcc/testsuite/rust/compile/decl_macro5.rs
- gcc/testsuite/rust/compile/decl_macro6.rs
- gcc/testsuite/rust/compile/decl_macro7.rs
- gcc/testsuite/rust/execute/torture/decl_macro1.rs
- gcc/testsuite/rust/execute/torture/decl_macro2.rs
- gcc/testsuite/rust/execute/torture/decl_macro3.rs
- gcc/testsuite/rust/execute/torture/decl_macro4.rs
This PR is currentry wip.
Opinions and advices are welcome!
> Parse declarative macro (decl_macro 2.0)

- gcc/rust/typecheck/rust-hir-type-check-stmt.cc
---
Improves the typechecking of patterns in let statements.
> Improve type checking on let statements

- gcc/rust/checks/lints/rust-lint-scan-deadcode.h
- gcc/testsuite/rust/compile/issue-1031.rs
- gcc/testsuite/rust/compile/issue-1289.rs
- gcc/testsuite/rust/compile/privacy7.rs
- gcc/testsuite/rust/compile/test_mod.rs
- gcc/testsuite/rust/compile/torture/raw_identifiers.rs
- gcc/testsuite/rust/compile/torture/raw_identifiers_keywords.rs
> [CL] do not lint public items

- gcc/rust/ast/rust-ast-dump.h
- gcc/rust/ast/rust-ast.h
- gcc/rust/expand/rust-attribute-visitor.cc
- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/macro43.rs
- gcc/testsuite/rust/compile/parse_range.rs
> [CL] cleanup macro expansion and parsing

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-item.cc
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-const-checker.h
- gcc/rust/hir/rust-ast-lower-item.cc
- gcc/rust/typecheck/rust-hir-type-check-toplevel.cc
- gcc/rust/util/rust-attributes.cc
- gcc/testsuite/rust/compile/const7.rs
- gcc/testsuite/rust/compile/const8.rs
- gcc/testsuite/rust/compile/const_generics_7.rs
- gcc/testsuite/rust/compile/const_generics_8.rs
- gcc/testsuite/rust/compile/macro44.rs
- gcc/testsuite/rust/compile/macro_export_1.rs
- gcc/testsuite/rust/execute/torture/loop-condition-eval.rs
@liushuyu @abbasfaisal @philberty I've added Changelogs to some of your commits again :)
Addresses #1705.
> [CL] const test cases, const generics, various fixes

- gcc/rust/hir/rust-ast-lower-pattern.cc
- gcc/rust/hir/rust-ast-lower-pattern.h
Implements HIR lowering for grouped patterns.
> Add HIR lowering for GroupedPattern

- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-pattern.h
- gcc/rust/backend/rust-compile-stmt.cc
Implements and utilizes CompilePatternLet to compile let statements
> Create and use CompilePatternLet visitor for compiling let statments

- gcc/rust/backend/rust-compile-expr.cc
> Removed comment copy-pasted from gcc/tree.def

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast-dump.cc
- gcc/rust/ast/rust-ast-dump.h
- gcc/rust/ast/rust-item.h
- gcc/rust/backend/rust-builtins.cc
- gcc/rust/backend/rust-builtins.h
- gcc/rust/checks/lints/rust-lint-marklive.cc
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/resolve/rust-name-resolver.cc
- gcc/rust/resolve/rust-name-resolver.h
- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/testsuite/rust/compile/const9.rs
- gcc/testsuite/rust/compile/issue-1272.rs
@dafaust @philberty if you'd like to review some of the Changelogs :)
> [CL] ast dump and refactor

- gcc/rust/typecheck/rust-tyty-call.cc
- gcc/testsuite/rust/compile/variadic.rs
- gcc/testsuite/rust/execute/torture/overflow1.rs
Fixes #1495, still need to add tests.
> Add variadic argument type checking

- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-var-decl.h
- gcc/rust/resolve/rust-ast-resolve-pattern.h
Improves handling of WildcardPattern in let statements.
> Improve WildcardPattern let statement handling

- gcc/testsuite/rust/compile/issue-1361.rs
Fixes #1361
* rust/compile/issue-1361.rs: New test.
> gccrs: add test case to show our query-type system is working

- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/pattern-or.rs
> Parse AltPattern

- gcc/rust/ast/rust-ast-dump.cc
- gcc/rust/ast/rust-ast-dump.h
- gcc/rust/ast/rust-ast-full-decls.h
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-item.h
- gcc/rust/checks/errors/rust-feature-gate.h
- gcc/rust/expand/rust-attribute-visitor.cc
- gcc/rust/expand/rust-attribute-visitor.h
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-ast-lower-base.h
- gcc/rust/resolve/rust-ast-resolve-base.cc
- gcc/rust/resolve/rust-ast-resolve-base.h
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/rust/resolve/rust-early-name-resolver.h
- gcc/rust/util/rust-attributes.cc
- gcc/rust/util/rust-attributes.h
> Add AST node for extern types

- gcc/rust/expand/rust-macro-builtins.cc
- gcc/testsuite/rust/compile/builtin_macro_eager3.rs
> builtins: Implement eager expansion for include_str!()

- gcc/rust/ast/rust-pattern.h
- gcc/rust/hir/tree/rust-hir-pattern.h
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
Some small code formatting and error message tweaks, formerly part of #1888.
> Basic Code Cleanup

- gcc/rust/ast/rust-pattern.h
- gcc/rust/hir/tree/rust-hir-pattern.h
Fixes bug pointed out in https://github.com/Rust-GCC/gccrs/pull/1888#discussion_r1112855910.
> Fix assignment operator overloads for AST and HIR patterns

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/closure_no_type_anno.rs
> parser: Fix parsing closure parameter

- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/testsuite/rust/compile/closure_no_type_anno.rs
> Resolve closure parameters without given type

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/complex_qualified_path_in_expr.rs
> parser: Fix handling of multiple left angles in null denotation

- gcc/rust/backend/rust-compile-fnparam.h
- gcc/rust/backend/rust-compile-pattern.h
- gcc/rust/backend/rust-compile-resolve-path.h
- gcc/rust/backend/rust-compile-var-decl.h
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-const-checker.h
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/checks/errors/rust-unsafe-checker.h
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
- gcc/rust/hir/tree/rust-hir-full-decls.h
- gcc/rust/hir/tree/rust-hir-pattern.h
- gcc/rust/hir/tree/rust-hir-visitor.h
- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.h
Adds a HIR node for alternate patterns
> Add AltPattern HIR node

- gcc/rust/backend/rust-compile-expr.cc
- gcc/testsuite/rust/execute/torture/closure4.rs
- gcc/testsuite/rust/execute/torture/ref-pattern2.rs
> hir: Improve pattern bindings handling in closure parameters

- gcc/rust/resolve/rust-ast-resolve-pattern.h
Remove `ResolvePattern` visitor class.
> Remove unused ResolvePattern visitor

- gcc/rust/hir/rust-ast-lower-pattern.cc
- gcc/rust/hir/rust-ast-lower-pattern.h
- gcc/rust/resolve/rust-ast-resolve-pattern.cc
- gcc/rust/resolve/rust-ast-resolve-pattern.h
Implement ast lowering and name resolution for `SlicePattern`
> Add name resolution and ast lowering for SlicePattern

- gcc/rust/hir/rust-ast-lower-pattern.cc
- gcc/rust/hir/rust-ast-lower-pattern.h
> Lower AltPattern

- .github/workflows/commit-format.yml
Check Signed-off-by/Reviewed-by/Co-authored-by lines are all grouped and last in commit log.
> ci: check Signed-off-by lines (and others) are at the end

- gcc/rust/util/rust-lang-item.h
> Handle "fn" and "fn_mut" lang items

- gcc/rust/ast/rust-ast-tokenstream.cc
- gcc/rust/ast/rust-ast-tokenstream.h
Fix some issues with tokenstream export.
Fixes #2095
> Tokenstream fixes

- gcc/rust/ast/rust-ast.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
Add a boolean to tell inner and outer attributes ast nodes appart.
Fixes #2096
> ast: Add difference between attributes

- gcc/rust/hir/rust-ast-lower-block.h
- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/hir/rust-ast-lower-expr.h
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/resolve/rust-ast-resolve-expr.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.h
- gcc/testsuite/rust/compile/if_let_expr.rs
> Lower ```if let```

- libgrust/libproc_macro/Makefile.am
- libgrust/libproc_macro/Makefile.in
- libgrust/libproc_macro/punct.cc
- libgrust/libproc_macro/punct.h
Add Punct structure matching the rust definition.
Needs #2117
> libproc_macro: Add Punct type

- gcc/rust/resolve/rust-ast-resolve-pattern.cc
> Resolve identifier-pattern struct pattern fields

- gcc/testsuite/rust/execute/torture/issue-1852-1.rs
- gcc/testsuite/rust/execute/torture/issue-1852.rs
These testcases are similar to the ones added in #2072 but regarding
execution. One more issue was opened from them - #2144
* rust/execute/torture/issue-1852-1.rs: New test.
* rust/execute/torture/issue-1852.rs: New test.
> patterns: Add execution testcases to verify proper pattern matching

- gcc/rust/typecheck/rust-unify.cc
- gcc/rust/typecheck/rust-unify.h
- gcc/rust/util/rust-abi.cc
> Add missing ABI mappings and check

- gcc/rust/hir/rust-ast-lower-implitem.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/testsuite/rust/compile/issue-1524.rs
- gcc/testsuite/rust/compile/issue-2106.rs
> Add missing where clause lowering for Impl functions

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
This is a case in #2019 where you have the default Add impl for i32 for example which has:
impl Add for i32 {
fn add(self, other:i32) { self + other }
}
This function will do a check for operator overload which then is able to find multiple candidates such as:
impl<'a> Add<i32> for &'a i32 {
type Output = <i32 as Add<i32>>::Output;
fn add(self, other: i32) -> <i32 as Add<i32>>::Output {
Add::add(*self, other)
}
}
This initial operator overload will resolve to this as it looks like a valid candidate. This patch adds another level of checks to ensure the candidate does not equal the current context DefId.
Addresses #2019
* typecheck/rust-hir-type-check-expr.cc: update for op overload
> gccrs: Improve operator overload check for recursive overload

- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/ast/rust-stmt.h
- gcc/testsuite/rust/compile/issue-1446.rs
- gcc/testsuite/rust/execute/torture/cfg-tail.rs
> Fix tail expression stripping

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-context.h
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-type.cc
- gcc/rust/backend/rust-compile-type.h
- gcc/rust/backend/rust-compile.cc
- gcc/rust/backend/rust-tree.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/testsuite/rust/execute/torture/coercion3.rs
- gcc/testsuite/rust/execute/torture/issue-2179.rs
- gcc/testsuite/rust/execute/torture/issue-2180.rs
> Add missing coercion site logic

- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/lex/rust-token.cc
- gcc/rust/lex/rust-token.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/macro-issue2192.rs
> Handle keywords in macro fragments

- gcc/rust/util/rust-optional.h
This uses ```T*``` to represent the ```T&```, allowing ```nullptr``` to be used as a ```None``` equivalent.
> Improve Optional<T&> implementation

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-collector.h
- gcc/rust/ast/rust-ast-dump.cc
- gcc/rust/ast/rust-ast-dump.h
- gcc/rust/ast/rust-ast-full-decls.h
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/ast/rust-macro.h
- gcc/rust/checks/errors/rust-feature-gate.h
- gcc/rust/expand/rust-cfg-strip.cc
- gcc/rust/expand/rust-cfg-strip.h
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-expand-visitor.h
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-ast-lower-base.h
- gcc/rust/resolve/rust-ast-resolve-base.cc
- gcc/rust/resolve/rust-ast-resolve-base.h
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/rust/resolve/rust-early-name-resolver.h
- gcc/rust/util/rust-attributes.cc
- gcc/rust/util/rust-attributes.h
Addresses #1412 by adding a new AttrInput
> Add AST::AttrInputMacro

- gcc/rust/util/rust-optional.h
This should improve usage of ```Optional<T>``` with non-trivial types.
> Improve Optional<T> implementation

- gcc/rust/ast/rust-ast.cc
- gcc/testsuite/rust/compile/cfg-attr.rs
> Only check first item of cfg_attr attribute as predicate

- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/testsuite/rust/compile/nested_macro_use3.rs
> Fix macro resolutions in middle of multiple nested macro_use modules

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-base.h
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/typecheck/rust-autoderef.cc
- gcc/rust/typecheck/rust-autoderef.h
- gcc/rust/typecheck/rust-hir-dot-operator.cc
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/rust/typecheck/rust-unify.cc
- gcc/testsuite/rust/compile/issue-2190-1.rs
- gcc/testsuite/rust/compile/issue-2190-2.rs
- gcc/testsuite/rust/execute/torture/issue-2236.rs
> Bug fixes autoderef cycles using derefs

- gcc/rust/expand/rust-macro-substitute-ctx.cc
- gcc/rust/expand/rust-macro-substitute-ctx.h
- gcc/testsuite/rust/compile/issue-2225.rs
Fixes #2225 by improving metavariable substitution
> Avoid invalid metavariable substitutions

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/hir/rust-ast-lower-stmt.cc
- gcc/rust/hir/rust-ast-lower-stmt.h
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/rust/resolve/rust-ast-resolve-pattern.cc
- gcc/rust/resolve/rust-ast-resolve-stmt.cc
- gcc/rust/resolve/rust-ast-resolve-stmt.h
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/compile/issue-2238.rs
> Add missing name-resolution and hir lowering to Stmts

- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/macro-delim.rs
This fixes an ICE with the provided test
> Properly match delimiters

- gcc/rust/lex/rust-lex.h
- gcc/rust/lex/rust-token.h
- gcc/rust/util/rust-token-converter.cc
- libgrust/libproc_macro/Makefile.am
- libgrust/libproc_macro/Makefile.in
- libgrust/libproc_macro/group.cc
- libgrust/libproc_macro/group.h
- libgrust/libproc_macro/literal.cc
- libgrust/libproc_macro/literal.h
- libgrust/libproc_macro/punct.cc
- libgrust/libproc_macro/punct.h
- libgrust/libproc_macro/rust/bridge/group.rs
- libgrust/libproc_macro/rust/bridge/ident.rs
- libgrust/libproc_macro/rust/bridge/literal.rs
- libgrust/libproc_macro/rust/bridge/punct.rs
- libgrust/libproc_macro/rust/bridge/span.rs
- libgrust/libproc_macro/span.cc
- libgrust/libproc_macro/span.h
Add Spans to proc macros.
Fixes #1892
> Add Spans to procedural macros

- gcc/rust/expand/rust-macro-substitute-ctx.cc
Addresses #1078 for the time being
> Handle crate metavariable

- Makefile.def
- Makefile.in
- configure
- configure.ac
Fix the missing dependency between gcc and libgrust.
> fixup: Fix build dependency

- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/rust/expand/rust-macro-substitute-ctx.cc
- gcc/rust/expand/rust-macro-substitute-ctx.h
This should be useful for improving/introducing proper nested-repetition handling.
> Make MatchedFragmentContainer a tree-like structure

- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-expr.h
- gcc/rust/ast/rust-item.h
- gcc/rust/ast/rust-macro.h
- gcc/rust/ast/rust-stmt.h
- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-expand-visitor.h
> Proc macro statements

- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/resolve/rust-early-name-resolver.cc
- gcc/testsuite/rust/compile/macro54.rs
- gcc/testsuite/rust/compile/macro55.rs
> Expand expressions/types correctly in more contexts.

- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/testsuite/rust/compile/macro-issue2268.rs
> Fix empty nested repetitions

- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/expand/rust-macro-expand.h
- gcc/testsuite/rust/compile/macro56.rs
> Fix macro nested repetitions

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/rust-diagnostics.cc
- gcc/rust/rust-diagnostics.h
- gcc/rust/rust-gcc.cc
- gcc/rust/rust-linemap.cc
- gcc/rust/rust-location.h
- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-stmt.cc
- gcc/rust/util/rust-token-converter.cc
> Change class Location into typedef

- gcc/rust/rust-linemap.cc
- gcc/rust/rust-linemap.h
> Reduce Linemap/Gcc_linemap abstraction

- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/rust-linemap.cc
- gcc/rust/rust-linemap.h
> Reduce Linemap/Gcc_linemap abstraction further

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-dump.cc
- gcc/testsuite/rust/link/trait_import_0.rs
Fixes several issues with current ast collector.
Requires #2313 
Fixes #7
> Ast collector fixes

- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-path.cc
- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/metadata/rust-imports.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/rust/rust-backend.h
- gcc/rust/rust-diagnostics.cc
- gcc/rust/rust-linemap.h
- gcc/rust/rust-session-manager.cc
- gcc/rust/typecheck/rust-tyty.cc
> Replace ```Linemap::unknown_location``` with ```UNKNOWN_LOCATION```

- gcc/rust/rust-linemap.cc
- gcc/rust/rust-linemap.h
> Merge ```Linemap``` and ```Gcc_linemap```

- gcc/rust/lex/rust-lex.cc
- gcc/rust/rust-linemap.cc
- gcc/rust/rust-linemap.h
> Merge ```Linemap::to_string``` into ```Linemap::location_to_string```

- gcc/rust/lex/rust-token.cc
Output escaped character values instead of their raw values in string.
Fixes #2398
> dump: Output escaped character values

- gcc/rust/lex/rust-lex.cc
- gcc/rust/rust-linemap.cc
- gcc/rust/rust-linemap.h
- gcc/rust/rust-session-manager.cc
> Remove ```Linemap::get_location```

- gcc/rust/lex/rust-lex.cc
- gcc/rust/rust-linemap.cc
- gcc/rust/rust-linemap.h
> Remove ```Linemap::start_line```

- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/rust-hir-dump.h
- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/hir/tree/rust-hir-type.h
- gcc/rust/hir/tree/rust-hir.cc
- gcc/rust/util/rust-common.h
Nearly complete rewrite of the HIR dump pass.
fixes #693
> Rework the HIR dump pass

- gcc/rust/util/rust-unicode.cc
> fix bootstrap build

- gcc/rust/expand/rust-proc-macro-invoc-lexer.cc
- gcc/rust/expand/rust-proc-macro-invoc-lexer.h
> Use ```MacroInvocLexerBase``` in ```ProcMacroInvocLexer```

- gcc/rust/lex/rust-lex.cc
- gcc/testsuite/rust/compile/issue-2514.rs
> Fix lexer exponential on tuple

- gcc/rust/backend/rust-tree.cc
- gcc/rust/backend/rust-tree.h
- gcc/rust/config-lang.in
- gcc/rust/rust-lang.cc
> Handle remaining unhandled gengtype annotations

- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/rust/resolve/rust-early-name-resolver-2.0.h
- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
- gcc/rust/rust-diagnostics.h
- gcc/rust/rust-session-manager.cc
- gcc/testsuite/rust/compile/nested_macro_definition.rs
Fixes #2233 
This PR clashes with #2537 we need to decide which one get merged. Per
> // now do we need to keep mappings or something? or insert "uses" into our
> // ForeverStack? can we do that? are mappings simpler?
> Handle nested macro definition (mappings)

- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/testsuite/rust/compile/iterators1.rs
- gcc/testsuite/rust/execute/torture/issue-2583.rs
This patch set it to fix the bad intrinsic's causing issues with the iterator code.
Fixes https://github.com/Rust-GCC/gccrs/issues/2583
> Fix iterator intrinsics

- gcc/rust/backend/rust-constexpr.cc
This *should* fix bootstrap builds
> Fix ODR violations

- gcc/rust/rust-backend.h
- gcc/rust/rust-gcc.cc
> Move remaining expression-related methods into base class ```Backend```

- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-block.cc
- gcc/rust/backend/rust-compile-context.cc
- gcc/rust/backend/rust-compile-context.h
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-extern.h
- gcc/rust/backend/rust-compile-fnparam.cc
- gcc/rust/backend/rust-compile-intrinsic.cc
- gcc/rust/backend/rust-compile-item.cc
- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/backend/rust-compile-type.cc
- gcc/rust/backend/rust-compile-var-decl.h
- gcc/rust/backend/rust-compile.cc
- gcc/rust/rust-backend.h
- gcc/rust/rust-gcc.cc
- gcc/rust/rust-session-manager.cc
- gcc/rust/rust-session-manager.h
> Convert class ```Backend``` into namespace

- gcc/rust/rust-gcc.cc
This should make refactoring along the lines of https://github.com/Rust-GCC/gccrs/pull/2609#pullrequestreview-1616222052 easier
> Use namespace definition to simplify function declarations

- gcc/rust/hir/rust-ast-lower-implitem.h
> Make lowering of ```AssociatedItem``` instances polymorphic

- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-expr.h
- gcc/rust/backend/rust-compile-base.cc
- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-stmt.cc
- gcc/rust/backend/rust-compile-var-decl.h
- gcc/rust/checks/errors/privacy/rust-privacy-reporter.cc
- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/checks/errors/rust-unsafe-checker.cc
- gcc/rust/expand/rust-derive-clone.cc
- gcc/rust/hir/rust-ast-lower-pattern.cc
- gcc/rust/hir/rust-ast-lower.cc
- gcc/rust/hir/rust-hir-dump.cc
- gcc/rust/hir/tree/rust-hir-expr.h
- gcc/rust/hir/tree/rust-hir-path.h
- gcc/rust/hir/tree/rust-hir-pattern.h
- gcc/rust/hir/tree/rust-hir.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/rust/resolve/rust-ast-resolve-expr.cc
- gcc/rust/resolve/rust-ast-resolve-pattern.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
- gcc/rust/typecheck/rust-hir-type-check-stmt.cc
- gcc/rust/typecheck/rust-tyty.h
- gcc/rust/util/rust-hir-map.cc
- gcc/testsuite/rust/compile/tupple_struct_pattern_tuple.rs
Minor changed done during the borrowck work. Tested after each  commit (but before the last rebase).
> HIR cleanup and refactor

- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/self_const_ptr.rs
- gcc/testsuite/rust/compile/self_mut_ptr.rs
- gcc/testsuite/rust/compile/self_ptr.rs
Fix self pointer rejection during parsing.
> Prevent const self ptr

- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/testsuite/rust/compile/for_lifetimes.rs
- gcc/testsuite/rust/compile/torture/utf8_identifiers.rs
Tested all commits check-rust + format + commit message.
@P-E-P
> Improved `for lifetime` handling

- gcc/rust/hir/tree/rust-hir-item.h
- gcc/rust/typecheck/rust-hir-trait-resolve.cc
- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.h
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-hir-type-check-item.h
- gcc/rust/typecheck/rust-hir-type-check-path.cc
- gcc/rust/typecheck/rust-hir-type-check-type.cc
- gcc/rust/typecheck/rust-hir-type-check-type.h
- gcc/rust/typecheck/rust-hir-type-check.cc
- gcc/rust/typecheck/rust-hir-type-check.h
- gcc/rust/typecheck/rust-substitution-mapper.cc
- gcc/rust/typecheck/rust-substitution-mapper.h
- gcc/rust/typecheck/rust-typecheck-context.cc
- gcc/rust/typecheck/rust-tyty-bounds.cc
- gcc/rust/typecheck/rust-tyty-region.h
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-tyty-subst.h
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
> Borrowck: add support for regions (lifetimes) in TyTy

- gcc/rust/checks/errors/rust-ast-validation.cc
- gcc/testsuite/rust/compile/issue-2850.rs
> Fix variadic check on all function parameters

- .github/workflows/ccpp.yml
ChangeLog:
* .github/workflows/ccpp.yml: Install Rust manually.
> ci: Install Rust directly from rustup instead of apt

- README.md
> fixed README.md , dump ast using correct option

- gcc/rust/lex/rust-lex.cc
- gcc/testsuite/rust/compile/raw-byte-string-loc.rs
- gcc/testsuite/rust/compile/raw-string-loc.rs
Intended to follow up on #2930 -- could be merged before #2930, but the commit message wouldn't make sense.
> Improve parsing of raw string literals

- CONTRIBUTING.md
- README.md
ChangeLog:
* CONTRIBUTING.md: Fix invalid line length.
* README.md: Likewise.
> chore: Fix Remark CI

- .github/workflows/ccpp.yml
Change macos version from "latest" to "13".
> Pin macos CI to version 13

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-collector.h
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-expr.h
- gcc/rust/checks/errors/rust-feature-gate.cc
- gcc/rust/checks/errors/rust-feature-gate.h
- gcc/rust/checks/errors/rust-feature.cc
- gcc/rust/checks/errors/rust-feature.h
- gcc/rust/expand/rust-derive.h
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-ast-lower-base.h
- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/hir/rust-ast-lower-expr.h
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/rust/resolve/rust-ast-resolve-base.cc
- gcc/rust/resolve/rust-ast-resolve-base.h
- gcc/testsuite/rust/compile/box_syntax.rs
- gcc/testsuite/rust/compile/box_syntax_feature_gate.rs
Add ability to parse the box syntax but this PR does not lower it. Add the corresponding feature gate as well as two tests.
> Parse box keyword

- gcc/rust/ast/rust-expr.h
- gcc/rust/expand/rust-macro-builtins-asm.cc
- gcc/rust/expand/rust-macro-builtins-asm.h
- gcc/testsuite/rust/compile/inline_asm_illegal_operands.rs
- gcc/testsuite/rust/compile/inline_asm_illegal_options.rs
Draft issue for my mentors, relates to #3052
> incorporate tl::expected into InlineAsm parsing

- .github/workflows/ccpp.yml
Issues being reported and fixes are here.
https://github.com/actions/checkout/issues/1487
https://github.com/actions/checkout/issues/1809
> Pin node16 by allowing old version

- .github/workflows/ccpp.yml
- gcc/rust/Make-lang.in
- gcc/rust/checks/errors/borrowck/ffi-polonius/src/gccrs_ffi.rs
- gcc/rust/checks/errors/borrowck/ffi-polonius/src/gccrs_ffi_generated.rs
- gcc/rust/checks/errors/borrowck/ffi-polonius/src/lib.rs
- gcc/rust/checks/errors/borrowck/polonius/rust-polonius-ffi.h
- gcc/rust/checks/errors/borrowck/polonius/rust-polonius.cc
- gcc/rust/checks/errors/borrowck/polonius/rust-polonius.h
- gcc/rust/checks/errors/borrowck/rust-borrow-checker.cc
- libgrust/libformat_parser/Cargo.toml
- libgrust/libformat_parser/generic_format_parser/src/lib.rs
- libgrust/libformat_parser/src/lib.rs
Alternate implementation of PR #3044
this one uses std::vector and FFIVector acts as a wrapper around it
> Added FFIVector to get Polonius output on C++ side

- .github/workflows/bootstrap.yml
- .github/workflows/ccpp.yml
- gcc/rust/checks/errors/borrowck/ffi-polonius/src/gccrs_ffi.rs
- gcc/rust/checks/errors/borrowck/ffi-polonius/src/lib.rs
- **ffi-polonius: Remove usage of extern types.**
- **github: Remove nightly Rust installation**
@dkm sorry for not making this earlier!
> Remove dependency on nightly Rust

- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/hir/tree/rust-hir-expr.h
For https://github.com/Rust-GCC/gccrs/issues/3102
> Inline asm hir pipeline

- gcc/rust/checks/errors/borrowck/rust-bir-builder-expr-stmt.cc
- gcc/rust/checks/errors/borrowck/rust-bir-builder-internal.h
- gcc/rust/checks/errors/borrowck/rust-bir-builder.h
- gcc/rust/checks/errors/borrowck/rust-bir.h
- gcc/rust/checks/errors/borrowck/rust-borrow-checker-diagnostics.cc
- gcc/rust/checks/errors/borrowck/rust-borrow-checker-diagnostics.h
- gcc/testsuite/rust/borrowck/reference.rs
- gcc/testsuite/rust/borrowck/return_ref_to_local.rs
- gcc/testsuite/rust/borrowck/tmp.rs
- gcc/testsuite/rust/borrowck/use_while_mut.rs
- gcc/testsuite/rust/borrowck/use_while_mut_fr.rs
- gcc/testsuite/rust/borrowck/well_formed_function_inputs.rs
> Better loan errors

- gcc/rust/checks/errors/borrowck/rust-borrow-checker-diagnostics.cc
- gcc/testsuite/rust/borrowck/test_move.rs
- gcc/testsuite/rust/borrowck/test_move_conditional.rs
> Better move errors

- gcc/rust/typecheck/rust-hir-type-check-enumitem.cc
- gcc/rust/typecheck/rust-hir-type-check-implitem.cc
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/testsuite/rust/compile/nr2/exclude
> Fix some issues with canonical path fetching in name resolution 2.0

- gcc/rust/checks/lints/rust-lint-marklive.cc
Depends on #3198, which makes `NameResolutionContext::lookup` const qualified
> Use name resolver 2.0 in `MarkLive`

- gcc/rust/ast/rust-item.h
* ast/rust-item.h: Add EnumItem::Kind for differentiating all variants that may be used inside an enum declaration.
This is necessary for implementing `derive(Clone)` on enums
> ast: Add EnumItem::Kind

- gcc/rust/ast/rust-collect-lang-items.cc
- gcc/rust/util/rust-attributes.cc
- gcc/rust/util/rust-attributes.h
Reverts Rust-GCC/gccrs#3338
@saeitoshi-10 the PR's content is not bad but we need to fix the commit message. Can you reopen a PR?
> Revert "refactor all attribute functions in rust-collect-lang-items.cc"

- gcc/rust/resolve/rust-toplevel-name-resolver-2.0.cc
We already lost some time on this unusual pattern, a comment will hopefully prevent this from happening again.
> Add warning about default visitor usage

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast-builder.cc
- gcc/rust/ast/rust-ast-builder.h
- gcc/rust/expand/rust-derive-debug.cc
- gcc/rust/expand/rust-derive-hash.cc
- gcc/rust/expand/rust-derive-hash.h
- gcc/rust/expand/rust-derive.cc
- gcc/testsuite/rust/compile/derive-hash1.rs
- gcc/testsuite/rust/compile/nr2/exclude
> Add `derive(Hash)` expansion

- gcc/rust/backend/rust-compile-resolve-path.cc
- gcc/rust/backend/rust-compile-resolve-path.h
- gcc/rust/typecheck/rust-hir-type-check-item.cc
- gcc/rust/typecheck/rust-tyty.cc
- gcc/rust/typecheck/rust-tyty.h
Track DefId on FnTypes and cleanup
> gccrs: Track defid on fntypes and cleanup

- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/rust/util/rust-hir-map.cc
- gcc/rust/util/rust-hir-map.h
- gcc/testsuite/rust/compile/nr2/exclude
> Fix nr2 as string ice (within foreverstack)

- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/testsuite/rust/compile/nr2/exclude
- gcc/testsuite/rust/compile/self_import_namespace.rs
> Fix unresolved imports

- gcc/testsuite/rust/compile/nr2/compile.exp
This should fix https://gcc.gnu.org/bugzilla/show_bug.cgi?id=119508
> nr2.0: Improve test script

- gcc/rust/rust-gcc.cc
This PR corresponds to the patchset sent by @pinskia on the 20th of March 2025, which you can find [here](https://gcc.gnu.org/pipermail/gcc-rust/2025-March/002382.html).
> Cleanup rust-gcc.cc by Andrew Pinski (20-03-2025)

- gcc/rust/typecheck/rust-hir-type-check-expr.cc
- gcc/testsuite/rust/execute/torture/min_specialization2.rs
- gcc/testsuite/rust/execute/torture/min_specialization3.rs
Needs #3678 so only review the last commit. Pinging @bjorn3 since we discussed it on Zulip but if you're swamped or don't want to review C++ don't feel obligated to :)
> Implement proper method resolution for min_specialization

- .github/glibcxx_ubuntu64b_log_expected_warnings
- .github/log_expected_warnings
- gcc/doc/install.texi
Addresses PR#117869
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117869
gcc/ChangeLog:
* doc/install.texi: Add requirements for building gccrs.
> install.texi: Mention Rust requirement for building gccrs

- gcc/rust/checks/errors/rust-const-checker.cc
- gcc/rust/resolve/rust-ast-resolve-item.cc
- gcc/testsuite/rust/compile/enum_discriminant2.rs
> Fix const checking of enum discriminants

- gcc/rust/resolve/rust-ast-resolve-path.cc
- gcc/rust/resolve/rust-ast-resolve-type.cc
- gcc/rust/resolve/rust-forever-stack.hxx
- gcc/testsuite/rust/compile/issue-3568.rs
- gcc/testsuite/rust/compile/name_resolution9.rs
- gcc/testsuite/rust/compile/self-path2.rs
This should help with making `issue-3568.rs` pass with name resolution 2.0.
> Adjust segment start position errors

- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/nr2/exclude
> NR2: Change error message to match expected test output

- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-path.cc
- gcc/rust/ast/rust-path.h
- gcc/rust/hir/rust-ast-lower-type.cc
- gcc/rust/parse/rust-parse-impl.h
- gcc/rust/parse/rust-parse.h
- gcc/rust/resolve/rust-ast-resolve-type.h
- gcc/rust/resolve/rust-default-resolver.cc
- gcc/rust/resolve/rust-default-resolver.h
- gcc/rust/resolve/rust-forever-stack.h
- gcc/rust/resolve/rust-late-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/generics9.rs
- gcc/testsuite/rust/compile/nr2/exclude
We lacked forward parameter type ban
Fixes #3477
> Nr2 fix generic9

- gcc/testsuite/rust/compile/nr2/exclude
- gcc/testsuite/rust/compile/use_1.rs
> Change expected error output to match nr2

- gcc/rust/ast/rust-ast-visitor.cc
Default visitor should visit every members.
> Visit visibility in UseDeclaration

- gcc/rust/backend/rust-compile-pattern.cc
- gcc/rust/backend/rust-compile-pattern.h
- gcc/testsuite/rust/execute/torture/struct-pattern-match.rs
> Improve struct pattern compilation

- gcc/rust/typecheck/rust-hir-trait-resolve.cc
Prevent infinite loops when projecting associated types by properly handling cyclical references with placeholder types.
* typecheck/rust-hir-trait-resolve.cc: Add cyclical projection protection.
> gccrs: Fix cyclical projection to placeholder

- gcc/rust/typecheck/rust-hir-type-check-pattern.cc
This PR is to pave way for implementing RestPattern compilation - tests will be added when that is completed.
> gccrs: Implement type checking for ItemType::RANGED in TuplePattern

- gcc/testsuite/rust/compile/issue-3524.rs
Fixes Rust-GCC#3524
* rust/compile/issue-3524.rs: New test.
> gccrs: Add test case to show issue is fixed

- gcc/rust/expand/rust-expand-visitor.cc
- gcc/rust/expand/rust-expand-visitor.h
This seems like some low-lying fruit, while I try to fix `ExpandVisitor`
> Specialize `ExpandVisitor::expand_macro_children`

- gcc/rust/Make-lang.in
- gcc/rust/ast/rust-ast-collector.cc
- gcc/rust/ast/rust-ast-collector.h
- gcc/rust/ast/rust-ast-visitor.cc
- gcc/rust/ast/rust-ast-visitor.h
- gcc/rust/ast/rust-ast.cc
- gcc/rust/ast/rust-ast.h
- gcc/rust/ast/rust-builtin-ast-nodes.h
- gcc/rust/expand/rust-derive.h
- gcc/rust/expand/rust-macro-builtins-offset-of.cc
- gcc/rust/expand/rust-macro-builtins.cc
- gcc/rust/expand/rust-macro-builtins.h
- gcc/rust/expand/rust-macro-expand.cc
- gcc/rust/hir/rust-ast-lower-base.cc
- gcc/rust/hir/rust-ast-lower-base.h
- gcc/rust/hir/rust-ast-lower-expr.cc
- gcc/rust/hir/rust-ast-lower-expr.h
- gcc/rust/lang.opt
- gcc/rust/resolve/rust-ast-resolve-base.cc
- gcc/rust/resolve/rust-ast-resolve-base.h
- gcc/rust/resolve/rust-early-name-resolver-2.0.cc
- gcc/testsuite/rust/compile/offset_of1.rs
- **ast: Add OffsetOf node**
- **expand: Add parser for offset_of!() and builtin resolution.**
> Add OffsetOf AST node and offset_of!() parsing

- gcc/rust/backend/rust-compile-expr.cc
- gcc/rust/rust-backend.h
- gcc/rust/rust-gcc.cc
- gcc/testsuite/rust/execute/torture/offset_of1.rs
- **ast: Add OffsetOf node**
- **expand: Add parser for offset_of!() and builtin resolution.**
- **hir: Add OffsetOf node**
- **offset_of: Compile the offset properly**
> Add offset_of!() evaluation

- gcc/rust/ChangeLog
"options.txt" was supposed to be "options.h".
> nr2.0: Fix ChangeLog entry

- gcc/rust/parse/rust-parse-impl.h
- gcc/testsuite/rust/compile/parse_closure_bind.rs
Fixes https://github.com/Rust-GCC/gccrs/issues/4071.
> Expect identifier subpatterns to be non-alt

- gcc/rust/typecheck/rust-hir-type-check-base.cc
- gcc/rust/typecheck/rust-tyty-subst.cc
- gcc/rust/typecheck/rust-unify.cc
This is an initial patch set to improve const generics which *isn't* finished but these are foundational patches for now.
> More const generics development

- .github/workflows/ccpp.yml
This *should* fix the arm CI in #4105
> ci: Bump commit to merge in arm64 ci
