Rust-GCC/gccrs

gcc/rust/Make-lang.in
gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-cond-compilation.h
gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-item.h
gcc/rust/ast/rust-macro.h
gcc/rust/ast/rust-path.h
gcc/rust/ast/rust-type.h
gcc/rust/backend.h
gcc/rust/lex/rust-lex.cc
gcc/rust/lex/rust-lex.h
gcc/rust/operator.h
gcc/rust/parse/rust-parse.cc
gcc/rust/rust-backend.c
gcc/rust/rust-gcc.cc
gcc/rust/rust-lang.cc
gcc/rust/rust-linemap.h
gcc/rust/rust-location.h
gcc/rust/rust-object-export.c
gcc/rust/rust-object-export.h
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h
gcc/rust/rust-system.h
gcc/rust/rustspec.cc

Changes consist of some rebase issue fixes and some cleanup of code.
The more important fixes are:
- actually allows the gccrs compiler driver to run something (fixes the mismatch between the old "grs1" and new "rust1" compiler names) - otherwise the gccrs compiler driver fails to work 
- readded the location adjustments when parsing (i.e. the "locus - 2" instead of just "locus")
- minor changes to satisfy intellisense (and other static analysis) via adding header includes
Also, this is the first test for new PR-based contributing system - we can set a precedent on standards or best practices or whatever.

Minor rebase fixes and some cleanup

---

gcc/rust/Make-lang.in

The Makefile of gcc directory will iterate `lang_OBJS` variable for detecting language frontend objects, so the standard way is to define this variable with all related object filenames.
Besides, the missing of `lang_OBJS` may cause the unwilling issue, say, you can't run `make -j n` otherwise the compiler complains `insn_modes.h` is missing. Now we can use `make -j n`.
BTW, could you authorize me to push the branch directly? That's better than maintaining forks. And you can protect the master branch.

Add rust_OBJS to fix compiling error

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-item.h
gcc/rust/lex/rust-lex.cc
gcc/rust/parse/rust-parse.cc

Enhance AST dump

---

gcc/rust/Make-lang.in
gcc/rust/backend/rust-compile.cc
gcc/rust/backend/rust-compile.h
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/rust-lang.cc
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h

It will crash when compiling but its the code setup i want to get in sooner
than later.
Addresses #15

This sets up the conversion from AST to GCC

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast.h

This PR contains 3 changes:
- Enhance let statement dump
- Fix string literal printing
- Fix params printing in DelimTokenTree
Here's an example:
```rust
fn abc(x:u32, y:u32) -> u32 {
return x+y;
}
fn main() {
type T = u32;
let x: T = 1;
let y: T = 2;
println!("Hello World!");
println!("{}", abc(x, y));
}
```
The dump result:
```rust
Crate: 
inner attributes: none
items: 
u32 abc(x : u32, y : u32)
BlockExpr:
{
outer attributes: none
inner attributes: none
statements: 
ExprStmtWithoutBlock:
return ArithmeticOrLogicalExpr: x + y
final expression: none
}
void main()
BlockExpr:
{
outer attributes: none
inner attributes: none
statements: 
T
Generic params: none
Where clause: none
Type: u32
Outer attributes: none
let x : T = 1
Outer attributes: none
let y : T = 2
ExprStmtWithoutBlock: …
```

Update AST dump

---

gcc/rust/analysis/rust-resolution.cc
gcc/rust/analysis/rust-resolution.h
gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-expr.h

More type inferencing code.
Also adds the error:
```
test.rs:8:5: error: E0282: type annotations or init expression needed
8 |     let x;
|     ^
```

WIP more type inferencing

---

gcc/rust/parse/rust-parse.cc
gcc/rust/parse/rust-parse.h

This is a hack to get the AST to become a CallExpr more changes might
occur later to cleanup this side of the AST.

For tuple structs the constructor is just a regular function call

---

gcc/rust/analysis/rust-type-resolution.cc
gcc/rust/analysis/rust-type-resolution.h
gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-item.h
gcc/rust/ast/rust-stmt.h
gcc/rust/backend/cscope.h
gcc/rust/backend/rust-compile.cc
gcc/rust/backend/rust-compile.h

This is the initial setup for the pass to convert to GIMPLE. On thing that needed done in type resolution was to find all locals per block as these must be setup up front for GIMPLE but this was easy enough with our visitor pattern.
Note the creation of a cscope.h (needs a better name) but something like this might be useful for our static analysis passes to be more unified.

WIP more GIMPLE conversion

---

gcc/rust/analysis/rust-type-resolution.cc
gcc/rust/analysis/rust-type-resolution.h
gcc/rust/ast/rust-expr.h

Adds the type resolution for struct initialization such as:
```
struct Foo {
one: i32,
two: i32,
}
let struct_test = Foo { one: 1, two: 2 };
```

Type Resolve Struct initializtion of their fields

---

gcc/rust/backend/cscope.h
gcc/rust/backend/rust-compile.cc
gcc/rust/backend/rust-compile.h

This still requires more type resolution work to ensure field ordering
on the initilizer and defaults if required.
struct Foo struct_test;
try
{
struct_test.one = 1;
struct_test.two = 2;
}
finally
{
struct_test = {CLOBBER};
}

Compile AST::StructExprStructFields into a constructor tree.

---

Dockerfile

This allows for easy testing via docker:
```
sudo docker build . -t gccrs-dev
sudo docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp gccrs-dev:latest gccrs -g -O2 -c gcc/testsuite/rust.test/compilable/type_infer1.rs -o type_infer1.o
```

Add Docker file for automated images to allow for easier testing

---

.github/workflows/ccpp.yml

This will turn on the test-suite which does have a currently failing test
lets see what happens the workflow in github.
Eventually it would be ideal to have a junit.xml or equivalent archive artefact to compare with each PR.

Turn on make check-rust

---

README.md
gcc/rust/analysis/rust-type-resolution.cc
gcc/rust/analysis/rust-type-resolution.h
gcc/rust/analysis/rust-type-visitor.h
gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-type.h
gcc/rust/backend/rust-compile.cc
gcc/rust/backend/rust-compile.h
gcc/testsuite/rust.test/compilable/arrays1.rs

This adds type inferencing and validation for arrays such as:
let x: [i32, 5] = [1,2,3,4,5]
ley y = [1,2,3];
It checks that each element is of a valid type and they line up correctly.
There needs to be some refactoring of the type resolution to handle the
array index expressions so this is a good save point for now.
Addresses: #27 #55

Add Type resolution to Array expressions

---

gcc/rust/analysis/rust-type-resolution.cc

to how struct AST Types. We need to move to HIR to avoid this issue via
name resolution.
This was a regression from the arrays work breaking inferencing of structs we need the move to hir to handle this better.

We cannot lookup types to ensure they are known as AST::Type differs

---

gcc/rust/analysis/rust-type-resolution.cc
gcc/rust/analysis/rust-type-resolution.h
gcc/rust/ast/rust-expr.h
gcc/rust/backend/rust-compile.cc

This an implementation to check return types for functions it needs work
to handle structs and other data structures later on.

Type Resolve ReturnExpr's to ensure they match the function type.

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/hir/tree/rust-hir-stmt.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/resolve/rust-name-resolver.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-tyctx.cc
gcc/rust/typecheck/rust-tyty-resolver.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/testsuite/rust.test/compilable/type_infer3.rs
gcc/testsuite/rust.test/fail_compilation/bad_type2.rs

Rust must examine each usage of a name and unify their types. For example:
let mut x;
x = 1
This means the declaration is determined to be an inference variable then
the assignment can be resolved to an Integer TyTy which can be combined
as part of the rules to now make the let x decl be an i32.
#12

Add type unification as part of typecheck.

---

gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/testsuite/rust.test/compilable/forward_decl_1.rs

resolved yet. Such as:
fn main() -> i32 { call() }
fn call() -> i32 { return 1; }
The compilation pass acts on the first function main and detects the other
node call is not compiled yet we can go resolve it. This is a toplevel
item since it has a local_def_id and therefore it has a NULL enclosing
scope for the block.
Fixes #72

When compiling a block it might reference a GIMPLE node that is not

---

gcc/rust/typecheck/rust-tyty-resolver.h
gcc/testsuite/rust.test/compilable/shadow1.rs
gcc/testsuite/rust.test/fail_compilation/shadow1.rs

When a new name is defined the name resolver freezes the previous
declartion such that all new references point to the latest decl.
This patch fixes a crash when we shadow and get a type mismatch and the
combination of types fails. See the failure test case for the crash.
Fixes #82

Shadowing rules are done as part of name resolution.

---

gcc/rust/ast/rust-expr.h
gcc/rust/backend/rust-compile-block.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-stmt.h
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower-block.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-stmt.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/util/rust-hir-map.cc

Example:
```
fn main() {
let mut x = 5;
if x == 5 {
x = 1;
} else if x == 3 {
x = 2;
} else {
x = 3;
}
}
```
GIMPLE
```
void main ()
{
i32 mut x;
mut x = 5;
if (mut x == 5) goto <D.188>; else goto <D.189>;
<D.188>:
{
mut x = 1;
}
goto <D.190>;
<D.189>:
{
if (mut x == 3) goto <D.191>; else goto <D.192>;
<D.191>:
{
mut x = 2;
}
goto <D.193>;
<D.192>:
{
mut x = 3;
}
<D.193>:
}
<D.190>:
}
```

Bring conditionals back since the HIR change.

---

gcc/rust/ast/rust-expr.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/rust-backend.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-tyty-resolver.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty-visitor.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compilable/arrays2.rs
gcc/testsuite/rust.test/compilable/arrays_index1.rs
gcc/testsuite/rust.test/compilable/type_infer4.rs

ArrayExpr, ArrayExprElems and ArrayIndexExpr. Still need to do
ArrayElemsCopied.
I expect there to be some changes to cleanup the rust-tyty-resolver
this code is to resolve all ribs within a scope but its getting a bit
hairy in there now.

This brings arrays back into the new framework. It resolves ArrayType

---

gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-item.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile-resolve-path.h
gcc/rust/backend/rust-compile-struct-field-expr.h
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-struct-field-expr.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-struct-expr-field.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-struct-field.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

It supports structs where no base struct is referenced and the constructor is in order.
This is a big change to get the basic ADT type implemented. More smaller changes are to come in subsequent PRs to support tuples and base struct references.
With this change the test suite should be fully passing. Such that we can start failing builds if failing tests are popping up in PRs.

This brings structs back in post HIR changes. 

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-pattern.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/rust-session-manager.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compilable/integer_types.rs

This change propagates the PrimitiveCoreType to AST and HIR so the suffix can be examined.
```
fn main() {
let a1: i8 = 1i8;
let a2: i16 = 2i16;
let a3: i32 = 3i32;
let a4: i64 = 4i64;
let a5: i128 = 5i128;
let b1 = 1i8;
let b2 = 2i16;
let b3 = 3i32;
let b4 = 4i64;
let b5 = 5i128;
let c1: u8 = 1u8;
let c2: u16 = 2u16;
let c3: u32 = 3u32;
let c4: u64 = 4u64;
let c5: u128 = 5u128;
let d1 = 1u8;
let d2 = 2u16;
let d3 = 3u32;
let d4 = 4u64;
let d5 = 5u128;
}
```
```
void main ()
{
i8 a1;
i16 a2;
i32 a3;
i64 a4;
i128 a5;
i8 b1;
i16 b2;
i32 b3;
i64 b4;
i128 b5;
i8 c1;
i16 c2;
i32 c3;
u64 c4;
u128 c5;
i8 d1;
i16 d2;
i32 d3;
u64 d4;
u128 d5;
a1 = 1;
a2 = 2;
a3 = 3;
a4 = 4;
a5 = 5;
b1 = 1;
b2 = 2;
b3 = 3;
b4 = 4;
b5 = 5;
c1 = 1;
c2 = 2;
c3 = 3;
c4 = 4;
c5 = 5;
d1 = 1;
d2 = 2;
d3 = 3;
d4 = 4;
d5 = …
```

Examine the Suffix hint on integers to apply apropriate TyTy type.

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty-visitor.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compilable/float1.rs

We need to ensure all suffix of literals are handled in a subsequent PR.
```
f32 test (f32 x)
{
f32 D.199;
D.199 = x + 1.0e+0;
return D.199;
}
void main ()
{
f32 a_float;
f32 call_test;
a_float = 5.12300014495849609375e+0;
_1 = a_float + 1.0e+0;
call_test = test (_1);
}
```

Add in F32 and F64 types builtin types.

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-item.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/testsuite/rust.test/compilable/static_var1.rs
gcc/testsuite/rust.test/fail_compilation/static_var1.rs

Still requires name mangling for the ASM name similar to functions.
```
static x:i32 = 3;
fn main() {
let y = x +1;
}
```
```
.file   "test.rs"
.text
.globl  __x
.section        .data.__x,"aw"
.align 4
.type   __x, @object
.size   __x, 4
__x:
.long   3
.text
.type   main, @function
main:
.LFB0:
.cfi_startproc
pushq   %rbp
.cfi_def_cfa_offset 16
.cfi_offset 6, -16
movq    %rsp, %rbp
.cfi_def_cfa_register 6
movl    __x(%rip), %eax
addl    $1, %eax
movl    %eax, -4(%rbp)
popq    %rbp
.cfi_def_cfa 7, 8
ret
.cfi_endproc
.LFE0:
.size   main, .-main
.ident  "GCC: (GNU) 11.0.0 20201127 (experimental)"
.section        .note.GNU-stack,"",@progbits
```

Add in support to compile static variables.

---

.github/workflows/ccpp.yml

This should fail until the struct PR has been merged. Lets see if it works.

Change CI to look for any unexpected failures to fail the build.

---

gcc/rust/backend/rust-compile-tyty.h
gcc/testsuite/rust.test/compilable/literals1.rs

This also ensure the type suffix is respected against the number.

Add test to cover handling hex, binary and octal number literals.

---

gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-stmt.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower-block.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty-resolver.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compilable/deadcode1.rs
gcc/testsuite/rust.test/compilable/implicit_returns1.rs
gcc/testsuite/rust.test/fail_compilation/missing_return1.rs

For implict returns we must consider cases with a block having multiple
returns:
HIR::BlockExpr Stmts {
...
return x
}
HIR::BlockExpr final_expression {
x + 1
}
Although the code above is bad this is valid rust code and the rust
compiler correctly identifies the final_expression as unreachable.
This dead code eliminiation is done as part of AST to HIR lowering.
Type resolution examines all blocks to identifiy if they terminate
a function with a return/final expression it must correspond accordngly.
If the block is the final block the resulting termination of the block
must match the return type of the function, else the block must conform
to unit type.

Implicit Returns support.

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/lex/rust-lex.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust.test/compilable/float_types.rs

Rust is permissive for integers being marked as floats so the check in the lexer can be removed here.

Respect the f32 and f64 suffix on literals

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-tyctx.cc
gcc/rust/typecheck/rust-tyty-call.h
gcc/rust/typecheck/rust-tyty-resolver.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty-visitor.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

This is a code cleanup as there are some inconsistencies with type inferencing rules and making the class force implementing the visitors will help fix these later on.

Make TyTyVisitor a pure abstract class

---

gcc/rust/hir/rust-ast-lower-block.h
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/testsuite/rust.test/compilable/scoping1.rs
gcc/testsuite/rust.test/compilable/shadow2.rs

There was a bug with LetStmts where we name resolved the identifier
pattern first before the init expression. This lead to a situation
where shadowing rules were broken.
Example:
let x = 1;
let x = x + 1;
In this example the code was referencing the 2nd LetStmt as the resolved
name for the Identifier reference.
Fixes #80

Ensure scoping rules are enforced correctly for BlockExpr's

---

gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve.cc

This means that parameters are scoped and shadowed correctly. Currently the resolver is treating all parameters are shadowing each other if they have the same name which is incorrect.
#80

Functions with parameters must receive their own scoping Rib

---

gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile.cc
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-pattern.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve-unused.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/resolve/rust-name-resolver.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty-resolver.h
gcc/rust/util/rust-hir-map.cc
gcc/testsuite/rust.test/compilable/unused1.rs

This lead to cleanup of the name resolver as the usage of mappings means that in a given rib if there are no references to a decl NodeId that means it was not used.
To get on par with the offical rust compiler it should be allowed to have a reference where the name was assigned but not used but this might be a separate pass.
This gives us warnings for example:
```
test.rs:10:9: warning: unused name
10 |     let a = 1;
|         ^
test.rs:11:9: warning: unused name
11 |     let b = test();
|         ^
test.rs:5:1: warning: unused name
5 | fn unused() -> i32 {
| ^
```
test
```
fn test() -> i32 {
1
}
fn unused() -> i32 {
2
}
fn main() {
let a = 1;
let b = test();
}
```
The check is very generic since it is based on node id mappings so it should work as more rust is supported over time.

Add in a check for unused decls within ribs.

---

gcc/rust/backend/rust-compile-item.h

This will change when we implement visibility but the main method will be reserved case that will always be DECL_PUBLC.
Fixes #136

Mark all functions as DECL_PUBLIC such that they can be linked against.

---

README.md

The repository was moved into the Rust-GCC organization from philberty

Fix link to build status shield

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/fail_compilation/implicit_returns_err1.rs
gcc/testsuite/rust.test/fail_compilation/implicit_returns_err2.rs
gcc/testsuite/rust.test/fail_compilation/implicit_returns_err3.rs

This change enforces strict type checkon on all ExprWithBlock. This includes unreachable tail expressions. Specific test cases have been added for context to ensure the failure cases are hit accordingly.
This change also improves the diagnostic errors for mismatched types where the reference HirId was lost leading to default locations.
There is a general hardening of the typechecker in this patch which will be used for further changes later on.

Enforce type checking on implicit returns

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust.test/compilable/parens1.rs

This makes the expression handling support exprs within parens. Such as:
x = (2*a) + 3;

Expressions within parentheses

---

gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile.cc
gcc/testsuite/rust.test/compilable/forward_decl_2.rs
gcc/testsuite/rust.test/compilable/forward_decl_3.rs
gcc/testsuite/rust.test/compilable/forward_decl_4.rs

We must ensure the backend can support compilation of things declared
lexically after they are referenced. This scans the toplevel except
functions which are handled as we reference them. To make that generic
enough for all toplevel items will be a move to query based compilation
which still needs planning.

Handle forward references in backend compilation

---

gcc/rust/backend/rust-compile-var-decl.h

This was using LetStmt->Pattern.as_string which included mut in the string
dump. This makes the gimple nodes harder to debug as the name is (mut a)
instead of a for example.
Addresses: #77

Fix the naming of VAR_DECLS within gimple nodes.

---

gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.cc
gcc/rust/rust-system.h

GCC doesn't like that:
In file included from [...]
./mm_malloc.h:42:12: error: attempt to use poisoned "malloc"
return malloc (__size);
^
See commit e7b3f654f2ab0400c95c0517387a9ad645a5c4cd, for example.

Fix '#include <algorithm>'

---

gcc/rust/parse/rust-parse-impl.h

... as used otherwise, in this file.  And, this avoids:
[...]/source-gcc/gcc/rust/parse/rust-parse-impl.h:12243:72: error: could not convert '{false, true}' from '<brace-enclosed initializer list>' to 'Rust::ParseRestrictions'
= {/* can_be_struct_expr = */ false, /* entered_from_unary = */ true};
^

Turn brace-enclosed initializer list into actual assignments

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust.test/compilable/type_infer5.rs

The type resolver must ensure LHS for assignments where the LHS was
infered to be ? and the node mappings have a definition ID we know
the declaration id and can reassign the TyTy so further references know
its type.

Delcare first case for ADT types field access fail to type resolve.

---

gcc/rust/lex/rust-lex.cc

The input needed to be skipped once the operator was parsed to ensure
the lexer did not duplicate the operator. |= still fails but this looks
to be a parser problem.
The output for |= shows:
```
beginning null denotation identifier handling
current peek token when starting path pratt parse: '|='
current token (just about to return path to null denotation): '|='
finished null denotation identifier path parsing - next is branching 
test.rs:24:7: error: expecting ‘}’ but ‘|=’ found
24 |     g |= 7;
|       ^
test.rs:24:5: error: error may be from having an expression (as opposed to statement) in the body of the function but not last
24 |     g |= 7;
|     ^
```
I am unsure what the bug is there yet
Addresses #173

Fixes the ^= and %= compound expression parsing.

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust.test/compilable/comparison_expr1.rs

This fixes the expression type resolution to coerce these into bools. For
LazyBoolExprs && and || the lhs and rhs are bools.
Fixes: #172 #171

ComparisonExprs and LazyBoolExprs are bools

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust.test/compilable/unary_operators.rs
gcc/testsuite/rust.test/fail_compilation/unary_negation.rs
gcc/testsuite/rust.test/fail_compilation/unary_not.rs

This is an example of a unary expression in gimple. The rules for enforcing
the types are observed in the type resolver here too.
Unary negate cannot be applied to bools but only integers and floats.
Unary not cannot be applied to floating points but can be applied to
integers and bools.
Fixes: #167

Implement NegationExpression

---

gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc

GCC uses qualified types to create const immutability.
This is a building block for #77

Add backend support to create immutable types

---

gcc/rust/ast/rust-type.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/tree/rust-hir-type.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/rust-session-manager.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/testsuite/rust.test/compilable/function_reference1.rs
gcc/testsuite/rust.test/compilable/function_reference2.rs

This supports basic function pointers in rust most of the code was already
there to infer this but this has now helped tidy it up and make it work.
Fixes #184

Support binding functions to LetStmts.

---

gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/resolve/rust-name-resolver.h
gcc/testsuite/rust.test/compilable/name_resolve1.rs
gcc/testsuite/rust.test/fail_compilation/redef_error1.rs
gcc/testsuite/rust.test/fail_compilation/redef_error2.rs
gcc/testsuite/rust.test/fail_compilation/redef_error3.rs
gcc/testsuite/rust.test/fail_compilation/redef_error4.rs
gcc/testsuite/rust.test/fail_compilation/redef_error5.rs

Rust does not allow functions/methods/constants/static definitions to
shadow otherwise you end up with unusable items.
Fixes #208

Enforce Duplicate definition rules

---

gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-block.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile-stmt.h
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/testsuite/rust.test/compilable/block_expr1.rs

We keep temporary's for each block in order for the result to be
referenced. For example:
let x = { test() + 1 };
This can be resolved into:
{
let x:i32;
_tmp1:i32;
{
_tmp2:i32 = test();
_tmp1 = _tmp2 + 1;
}
x = _tmp1;
}
Fixes #189
Depending on the order of merging PRs the method resolution one will need an amendment to use this shared function block code.

This adds support for basic BlockExpressions

---

gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-unused.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/resolve/rust-name-resolver.h
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h

Methods are resolved as part of type resolution so scanning ribs early
on will results in false warnings about unused methods.

Move scan for unused names to be after type resolution

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/testsuite/rust.test/compilable/block_expr2.rs

Further testing found regressions with implicit returns and type
resolution.
This unifies the type resolution in block expressions to be more strict
and ensure everything bar the final statement should be UnitType.
It also gets rid of the is_final_expr hack used for implicit returns before
#212 if fixed would have picked this up

With the merge of BlockExprs

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust.test/compilable/block_expr3.rs
gcc/testsuite/rust.test/compilable/if_elif_else_expr1.rs

When we compile if blocks the else gives us a final branch that can
resolve. Single IfExpr cannot resolve as there is no final branch.
This also fixes a small regression in compiling elif blocks where the
gimple body was empty.
Fixes #213

Conditional blocks with else can resolve into a non unit type expression

---

gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust.test/compilable/block_expr_parser_bug.rs

This allows for rust style ternery expressions.
Fixes #214

Fixes parsing if expressions as part of an expression.

---

gcc/rust/backend/rust-compile.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust.test/compilable/function_reference3.rs

When we have a test case that is, for example, a FieldAccessExpression the
compiler must resolve and compile that field into a reference which can be
called. This is not a simple direct call to a function in that scenario.
Fixes #217

Fix bad type resolution for CallExpr when fn is not simply PathInExpression

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust.test/compilable/compound_assignment_expr1.rs

Fix parsing |= as a compound assignment expression.

---

gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h
gcc/rust/typecheck/rust-tycheck-dump.h

We output each debug IR to file which makes it easier to debug larger
test cases. Be aware not all dumps are complete such as name resolution
is not implemented yet, HIR is badly formatted and type resolution dump is
not finished.
We get the following outputs:
```
-rw-rw-r--  1 philbert philbert    4012 Feb  9 14:04 gccrs.ast.dump
-rw-rw-r--  1 philbert philbert    4082 Feb  9 14:04 gccrs.ast-expanded.dump
-rw-rw-r--  1 philbert philbert    5445 Feb  9 14:04 gccrs.hir.dump
-rw-rw-r--  1 philbert philbert       0 Feb  9 14:04 gccrs.lex.dump
-rw-rw-r--  1 philbert philbert     604 Feb  9 14:04 gccrs.target-options.dump
-rw-rw-r--  1 philbert philbert    1214 Feb  9 14:04 gccrs.type-resolution.dump
```

Enable -frust-dump-all option for debugging

---

gcc/rust/ast/rust-expr.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-stmt.h
gcc/rust/hir/rust-ast-lower-block.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-hir-type-check.h
gcc/testsuite/rust.test/compilable/loop6.rs
gcc/testsuite/rust.test/compilable/loop7.rs
gcc/testsuite/rust.test/fail_compilation/break2.rs
gcc/testsuite/rust.test/fail_compilation/continue1.rs

commit 3b7ce5b850414596e2317db1ecee1ba43dc506a6 (HEAD -> phil/while-loops, origin/phil/while-loops)
Author: Philip Herron <philip.herron@embecosm.com>
Date:   Thu Feb 11 13:42:07 2021 +0000
Add in ContinueExpr support
We made an implicit loop begin label that can be referenced in a goto to
restart the loop.
Fixes #188
commit 37992873fefe69a37398b8b29b45950653cf2434
Author: Philip Herron <philip.herron@embecosm.com>
Date:   Thu Feb 11 12:07:19 2021 +0000
Add in while loop support
We create a LoopExpr comprising of:
LOOP_EXPR {
EXIT_EXPR (while loop predicate)
{
<LOOP_BODY>
}
}
Fixes #109

While Loops and ContinueExpr

---

gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-type.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-type.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyctx.cc
gcc/rust/typecheck/rust-tyty-call.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty-visitor.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compilable/borrow1.rs
gcc/testsuite/rust.test/compilable/deref1.rs

This also adds in the mising InferenceType _ which was mostly implemented
before as part of Data Structures 1.
We create GENERIC REFERENCE_TYPES for these this is the building block
to finish work on mutability rules and pointers.
Fixes: #196
Addresses: #169 #170
Note more work is needed here for mutable references and double references.

Add ReferenceType with BorrowExpr and DereferenceExpr

---

gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc

This adds in a debugging interface for the backend IR to help diagnose
issues with the tree.

Add debug interface to GCC debug_tree on GENERIC graphs

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile-stmt.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/backend/rust-compile-var-decl.h
gcc/rust/backend/rust-compile.cc
gcc/rust/typecheck/rust-hir-method-resolve.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-struct-field.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-tycheck-dump.h
gcc/rust/typecheck/rust-tyctx.cc
gcc/rust/typecheck/rust-tyty-call.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

Cleanup tyty

---

gcc/rust/expand/rust-macro-expand.h

Keep ExpansionCfg configs complying with `librustc_expand`.

Update default configs in ExpansionCfg

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-expr.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/operator.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h

This pull request extracts and combines the operator enums in the AST and HIR namespace. The new enums are in `operator.h` and the old `enum Operator` is removed.
Fixes issue #228.

Cleanup operator

---

gcc/testsuite/rust.test/rust-test.exp

As mentioned in issue #212, some tests in fail_compliation are passing when they shouldn't. The reason is that `{ dg-do run { xfail *-*-* } }` will be successful if the compilation failed _or_ if the resulting executable returns a non-zero value.
This PR fixes this by replacing it with `{ dg-do compile }`, which detects if the compiler crashed or not, followed by `{ dg-final { output-exists-not } }`, which ensures the compilation actually failed.
Now the failing tests are `fail_compilation/implicit_returns_err1.rs` and `fail_compilation/tuple_struct1.rs`.

Make failing tests actually fail

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-tyty-call.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty-visitor.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compilable/str1.rs

This gives the apropriate reference type over const char *.
Fixes #85

Add in support for string literals

---

gcc/rust/rust-lang.cc

Both headers are not used and trigger warning on DEFHOOK macros redefinitions.

Remove unused header inclusions.

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

Replace all occurences of [Ss]ubstition[s] by [Ss]ubstition[s].
Looks like a common typo, there are some more occurrence in other parts of GCC :)

Typo fix in substition

---

gcc/rust/rust-backend.h

virtual `loop_expression` and `exit_expression` were not marked pure and do not have
a default impl, causing error during linking when optimisation are disabled.
This fixes this error:
```
/usr/bin/ld: rust/rust-gcc.o: in function `Backend::~Backend()':
...gccrs/build/gcc/../../gcc/rust/rust-backend.h:67: undefined reference to `vtable for Backend'
/usr/bin/ld: rust/rust-gcc.o: in function `Backend::Backend()':
...gccrs/build/gcc/../../gcc/rust/rust-backend.h:64: undefined reference to `vtable for Backend'
collect2: error: ld returned 1 exit status
make: *** [../../gcc/rust/Make-lang.in:92: rust1] Error 1
```

Fix Backend:: mark 2 methods pure

---

gcc/rust/Make-lang.in
gcc/rust/typecheck/rust-tyty-rules.h

Add using clause for UnitRules.
Add -Werror=overloaded-virtual to avoid regressing on this warning.

Fix last remaining Woverloaded-virtual

---

gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compilable/block_expr4.rs

Fix type unification for Inference Variables and return types
When we resolve the type of an expression such as a LiteralExpr with HIR id
10, but is the final expression in a BlockExpr of HirId 11. The same type
is infered for the entire BlockExpr as well as the final Expr but we
override the reference id on the TyTy::Type. This means if there is a
change in reference id the old ID must be added to the combined reference
chain for type inference to take place.
Fixes #293

Fix type unification for return types

---

gcc/rust/typecheck/rust-tyty.h

resolves #280 , this PR adds to_string() to TyTy::TypeKind. The method is implemented using switch case to map enum to string.

added to_string() for TypeKind

---

gcc/rust/parse/rust-parse-impl.h

This improves errors messages with the source location info for the error.

Add missing location info into TypePath

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-stmt.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty-call.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty-visitor.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

This is WIP for #252 and awaits copyright assignment.
Removed TyTy::UnitType and TyTy::TypeKind::UNIT.
Replaced by TyTy::TupleType with an empty list of fields.
Added default empty vector for fields in ctor for TyTy::TypeType.

Remove TyTy::UnitType

---

gcc/rust/lex/rust-lex.cc
gcc/testsuite/rust.test/fail_compilation/unterminated_c_comment.rs

Emit an error when EOF is reached before end of C-style comment.
fix #300

Fix error while unexpected EOF when scanning for end of comment

---

gcc/rust/ast/rust-path.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower-base.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-method-resolve.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty-call.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-hir-map.h
gcc/testsuite/rust.test/compile/generics8.rs
gcc/testsuite/rust.test/compile/generics9.rs
gcc/testsuite/rust.test/compile/methods3.rs

ommit 6c0fb08c3b84f4de8236ed80f3485381b42f9d4b (HEAD -> phil/generics3, origin/phil/generics3)
Author: Philip Herron <philip.herron@embecosm.com>
Date:   Fri Mar 26 15:23:57 2021 +0000
Add Generic Impl block support
This extends the support from #237 to extend this to MethodCallExpr, this
now follows a similar path to normal CallExprs and ensures the used
arguments in substitution are preserved during unification of types. Part
of method resolution is fixed here by taking advantage if is_equal instead
of unify calls which could result in bad errors which are just part of the
probe process to lookup possible candidates for method resolution.
Fixes #306
commit 97d4ad5114f7f25875a66b290ec6b4f82af25e58
Author: Philip Herron <philip.herron@embecosm.com>
Date:   Sat Mar 27 16:28:45 2021 +0000 …

Generics on Impl Blocks WIP

---

gcc/testsuite/rust.test/xfail_compile/continue1.rs
gcc/testsuite/rust.test/xfail_compile/fail_compilation/unterminated_c_comment.rs
gcc/testsuite/rust.test/xfail_compile/unterminated_c_comment.rs

the PR #302 and #301 were conflicting because they are both modifying the tests.
Move the conflicting test and add correct dg-error directive.

Fix test after several PR were merged

---

gcc/rust/ast/rust-item.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compile/generics11.rs
gcc/testsuite/rust.test/compile/type-alias1.rs
gcc/testsuite/rust.test/compile/type-alias2.rs
gcc/testsuite/rust.test/xfail_compile/type-alias1.rs

commit 42e13fb08b14f638ca1becd3ca9386972648f372 (HEAD -> phil/generics4, origin/phil/generics4)
Author: Philip Herron <philip.herron@embecosm.com>
Date:   Tue Mar 30 17:53:09 2021 +0100
Add support for TypeAlias
This allows for a typedef style alias of any type in rust code, as the
types are abstracted behind the TyTy interface this falls out quite nicely.
In order to support TypeAliases we needed to be able to supported already
substituted types in #311.
More testing is needed here the GenericParameters on TypeAlias are not
being used in the type resolution pass here.
Fixes #312
Addresses #311
commit 52e63128c5491c5432960b62e664d7ac479d140a
Author: Philip Herron <philip.herron@embecosm.com>
Date:   Tue Mar 30 18:23:53 2021 +0100
Fix bad tracking on used substitutions on generic types. …

Initial TypeAlias support

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compile/generics12.rs

When we have Types capable of type substitution it only needs substituted
if it was not already substituted and it actually has substitutions defined
Fixes #311

Fixed bug TyTy::SubstitutionRef::needs_substitution

---

.github/workflows/ccpp.yml

Checking for 'unexpected' will also catch XFAIL tests being PASS.

Fix CI checks

---

gcc/testsuite/rust.test/xfail_compile/generics4.rs

Having at least one dg-error and not only dg-excess-error should avoid silent
regression.

Add dg-error to generics4.rs xfail test

---

gcc/rust/rust-session-manager.cc

Address '[...]/gcc/rust/rust-session-manager.cc:124:15: error: unused variable ‘target’ [-Werror=unused-variable]' diagnostic [#336]

---

gcc/rust/hir/rust-ast-lower-expr.h

#336
In file included from [...]/gcc/rust/hir/tree/rust-hir-full.h:24,
from [...]/gcc/rust/hir/rust-ast-lower.h:25,
from [...]/gcc/rust/hir/rust-ast-lower.cc:19:
[...]/gcc/rust/hir/tree/rust-hir-expr.h: In member function ‘virtual void Rust::HIR::ASTLoweringExpr::visit(Rust::AST::CompoundAssignmentExpr&)’:
[...]/gcc/rust/hir/tree/rust-hir-expr.h:426:7: error: ‘op’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
426 |       expr_type (expr_kind), right_expr (std::move (right_value))
|       ^~~~~~~~~~~~~~~~~~~~~
In file included from [...]/gcc/rust/hir/rust-ast-lower-type.h:24,
from [...]/gcc/rust/hir/rust-ast-lower-item.h:25,
from [...]/gcc/rust/hir/rust-ast-lower.cc:20:
[...]/gcc/rust/hir/rust-ast-lower-expr.h:471:33: note: ‘op’ was declared here
471 | …

Address 'error: ‘op’ may be used uninitialized in this function [-Werror=maybe-uninitialized]' diagnostic [#336]

---

gcc/rust/lex/rust-lex.cc

Address '[...]/gcc/rust/lex/rust-lex.cc:433:30: error: too many arguments for format [-Werror=format-extra-args]' diagnostic [#336]

---

gcc/rust/hir/rust-ast-lower-type.h

#336
In file included from [...]/gcc/rust/hir/tree/rust-hir-full.h:29,
from [...]/gcc/rust/hir/rust-ast-lower.h:25,
from [...]/gcc/rust/hir/rust-ast-lower.cc:19:
[...]/gcc/rust/hir/tree/rust-hir-type.h: In member function ‘virtual void Rust::HIR::ASTLoweringType::visit(Rust::AST::BareFunctionType&)’:
[...]/gcc/rust/hir/tree/rust-hir-type.h:785:3: error: ‘kind’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
785 |   MaybeNamedParam (MaybeNamedParam &&other) = default;
|   ^~~~~~~~~~~~~~~
In file included from [...]/gcc/rust/hir/rust-ast-lower-item.h:25,
from [...]/gcc/rust/hir/rust-ast-lower.cc:20:
[...]/gcc/rust/hir/rust-ast-lower-type.h:58:41: note: ‘kind’ was declared here
58 |         HIR::MaybeNamedParam::ParamKind kind;
| …

Address 'error: ‘kind’ may be used uninitialized in this function [-Werror=maybe-uninitialized]' diagnostic [#336]

---

gcc/rust/parse/rust-parse-impl.h

(Sorry, but at this point) I didn't (have time to) try to understand the C++ class hierarchy etc. -- but these changes do placate GCC 4.8, and don't cause any testsuite regressions.  But somebody please review, who knows this code!
---
In file included from [...]/gcc/rust/parse/rust-parse.h:645:0,
from [...]/gcc/rust/rust-session-manager.cc:34:
[...]/gcc/rust/parse/rust-parse-impl.h: In instantiation of 'std::unique_ptr<Rust::AST::AttrInput> Rust::Parser<ManagedTokenSource>::parse_attr_input() [with ManagedTokenSource = Rust::Lexer]':
[...]/gcc/rust/parse/rust-parse-impl.h:522:66:   required from 'Rust::AST::Attribute Rust::Parser<ManagedTokenSource>::parse_attribute_body() [with ManagedTokenSource = Rust::Lexer]'
[...]/gcc/rust/parse/rust-parse-impl.h:493:59:   required from …

Placate GCC 4.8

---

gcc/rust/expand/rust-macro-expand.cc

#336
The only caller is currently `#if 0`ed, too.

Address '[...]/gcc/rust/expand/rust-macro-expand.cc:3228:1: error: control reaches end of non-void function [-Werror=return-type]' diagnostic [#336]

---

gcc/rust/typecheck/rust-tyty.h

#336
In file included from [...]/gcc/rust/typecheck/rust-hir-type-check.h:24,
from [...]/gcc/rust/resolve/rust-name-resolver.h:24,
from [...]/gcc/rust/resolve/rust-ast-resolve.h:22,
from [...]/gcc/rust/rust-session-manager.cc:36:
[...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::USizeType::USizeType(Rust::HirId, std::set<unsigned int>)’:
[...]/gcc/rust/typecheck/rust-tyty.h:972:41: error: unused parameter ‘refs’ [-Werror=unused-parameter]
972 |   USizeType (HirId ref, std::set<HirId> refs = std::set<HirId> ())
|                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
[...]/gcc/rust/typecheck/rust-tyty.h: In constructor ‘Rust::TyTy::USizeType::USizeType(Rust::HirId, Rust::HirId, std::set<unsigned int>)’:
[...]/gcc/rust/typecheck/rust-tyty.h:976:55: error: unused …

Address 'gcc/rust/typecheck/rust-tyty.h' '-Werror=unused-parameter' diagnostics [#336]

---

gcc/rust/rust-session-manager.cc

#336
I haven't quickly been able to understand the target hooks handling here -- seems to be WIP?
My proposed changed doesn't change any behavior.

Address '[...]/gcc/rust/rust-target.h:23: error: "DEFHOOK" redefined' diagnostic [#336]

---

gcc/rust/Make-lang.in
gcc/rust/analysis/rust-hir-liveness-base.h
gcc/rust/analysis/rust-hir-liveness.cc
gcc/rust/analysis/rust-hir-liveness.h
gcc/rust/analysis/rust-hir-scan-deadcode.h
gcc/rust/rust-session-manager.cc
gcc/testsuite/rust.test/compile/unused.rs

This is the very beginning work for dead code detection. #330 
1. create a new test for this feature.
2. handle an extremely simple case.
After compiling the rust1, and feed "testsuite/rust.test/xfail_compile/unused.rs" to it.
``` rust
fn bar() { // {dg-warning "function is never used: `bar`"}
foo();
}
fn foo() { // {dg-warning "function is never used: `foo`"}
bar();
}
fn f() {
}
fn main() {
f();
}
```
we will get some warnings.
``` bash
../gccrs/gcc/testsuite/rust.test/xfail_compile/unused.rs:2:1: warning: function is never used: `[bar]`
2 | fn bar() { // {dg-warning "function is never used: `bar`"}
| ^
../gccrs/gcc/testsuite/rust.test/xfail_compile/unused.rs:6:1: warning: function is never used: `[foo]`
6 | fn foo() { // {dg-warning "function is never used: `foo`"}
| ^
```

Create liveness analysis for dead code detection

---

gcc/rust/ast/rust-expr.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/rust-gcc.cc
gcc/rust/rust-lang.cc

#336
In file included from [...]/gcc/rust/ast/rust-ast-full.h:23,
from [...]/gcc/rust/parse/rust-parse.h:21,
from [...]/gcc/rust/rust-session-manager.cc:34:
[...]/gcc/rust/ast/rust-expr.h: In member function ‘virtual void Rust::AST::RangeExpr::set_outer_attrs(std::vector<Rust::AST::Attribute>)’:
[...]/gcc/rust/ast/rust-expr.h:3220:48: error: unused parameter ‘new_attrs’ [-Werror=unused-parameter]
3220 |   void set_outer_attrs (std::vector<Attribute> new_attrs) override
|                         ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
[...]/gcc/rust/ast/rust-expr.h: In constructor ‘Rust::AST::IfLetExpr::IfLetExpr(std::vector<std::unique_ptr<Rust::AST::Pattern> >, std::unique_ptr<Rust::AST::Expr>, std::unique_ptr<Rust::AST::BlockExpr>, std::vector<Rust::AST::Attribute>, Location)’: …

Address miscellaneous '-Werror=unused-parameter' diagnostics [#336]

---

gcc/rust/util/rust-inline-visitor.h

This is a clean implementation of the inline visitor. Should be useful for various cleanups such as #366.

Implement the inline visitor

---

gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compile/generics17.rs
gcc/testsuite/rust.test/compile/generics18.rs

When we have a struct Foo <T>(T) but the fntype in impl block is different
fn <X> Bar(a:X) -> Foo<X>(X) { } we must take advantage of the adjustment
code in the substitution mapper.
This affects MethodCallExpr and PathInExpressions where it used to resolve
the root segment and leave the arguments as inference variables when we
lack a segement with generic arguments.
This also fixes a bug in name resolution where the Self keyword resolved
to the struct/type the impl block resolves to but it needed to resolve
to the impl block type explicitly which ensures the parameter mappings
reflect what the parent impl block is.
Fixes: #376

Fix crash when mapping of Generic argument changes.

---

gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/testsuite/rust.test/xfail_compile/unconstrained_type_param.rs

When we have an impl<X,Y> Foo<X>, the type parameter Y is unconstrained
so that we cannot be sure how Y should be substituted later on.
Fixes #354

Add Check for unconstrained type parameters

---

gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/rust-diagnostics.cc
gcc/rust/rust-diagnostics.h
gcc/rust/rust-gcc-diagnostics.cc
gcc/rust/rust-linemap.cc
gcc/rust/rust-location.h
gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
gcc/rust/typecheck/rust-hir-path-probe.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/testsuite/rust.test/xfail_compile/arrays1.rs
gcc/testsuite/rust.test/xfail_compile/arrays2.rs
gcc/testsuite/rust.test/xfail_compile/bad_type1.rs
gcc/testsuite/rust.test/xfail_compile/bad_type2.rs
gcc/testsuite/rust.test/xfail_compile/generics1.rs
gcc/testsuite/rust.test/xfail_compile/generics2.rs
gcc/testsuite/rust.test/xfail_compile/generics3.rs
gcc/testsuite/rust.test/xfail_compile/generics7.rs
gcc/testsuite/rust.test/xfail_compile/redef_error1.rs
gcc/testsuite/rust.test/xfail_compile/redef_error2.rs
gcc/testsuite/rust.test/xfail_compile/redef_error3.rs
gcc/testsuite/rust.test/xfail_compile/redef_error4.rs
gcc/testsuite/rust.test/xfail_compile/redef_error5.rs
gcc/testsuite/rust.test/xfail_compile/redef_error6.rs
gcc/testsuite/rust.test/xfail_compile/tuple1.rs
gcc/testsuite/rust.test/xfail_compile/type-alias1.rs

Adding rich location will improve our error message diagnostics, this is
an initial building block to keep a wrapper over the GCC stuff we call.
Addresses: #97 
Fixes: #327

Add basic wrapper over gcc rich_location

---

gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/testsuite/rust.test/xfail_compile/expected_type_args2.rs
gcc/testsuite/rust.test/xfail_compile/expected_type_args3.rs
gcc/testsuite/rust.test/xfail_compile/generics8.rs

When no parameters are passed to generic data types we cannot properly
infer the usage of the generic block.
This brings in a canonicalized check for `rustc --explain E0107`
Fixes #379

Fix crash on empty parameters to generic data type

---

gcc/testsuite/lib/rust.exp
gcc/testsuite/rust.test/xfail_compile/unsafe.rs

Fix the pruning regex to also match ICE message and allow for dg-ice use.
Add the test from #382 as a sample example.
Should help #308

Fix dg-ice handling in rust testsuite

---

gcc/rust/Make-lang.in
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/rust-session-manager.cc
gcc/rust/typecheck/rust-hir-const-fold-base.h
gcc/rust/typecheck/rust-hir-const-fold-ctx.h
gcc/rust/typecheck/rust-hir-const-fold.cc
gcc/rust/typecheck/rust-hir-const-fold.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compile/arrays3.rs
gcc/testsuite/rust.test/compile/arrays4.rs
gcc/testsuite/rust.test/xfail_compile/arrays2.rs

Rust allows for constant eval for cases like array capacity, the initial
version of this code forced the programmer to only use literals which was
not correct but got the type system off the ground.
This now takes advantage of the GCC backend object to offer 3 helprs.
1. check for constant Bexpression* are equal
2. extract a size_t constant value from the Bexpression*
3. to string the Bexpression constant
We can get away with the extraction of the value here because we know its going to be a usize for array capacity but some thought is needed if these methods are to be reused in other cases.
There is a new ConstFold namespace which should be extensible for const
functions later on and const generics.
Fixes: #296

Reuse fold-const.c from GCC to enforce const array capacities

---

gcc/rust/ast/rust-stmt.h
gcc/rust/hir/rust-ast-lower.cc
gcc/testsuite/rust.test/compile/deadcode2.rs
gcc/testsuite/rust.test/xfail_compile/deadcode_err1.rs
gcc/testsuite/rust.test/xfail_compile/deadcode_err2.rs

This is a legal code segment:
```rust
fn foo() -> i32 {
return 1;
let a = 1;
a
}
```
And this is illegal:
```rust
fn foo() -> i32 {
return 1;
let a = 1.5;
a
}
```
So we shouldn't remove unreachable statements at HIR lowering. We can issue warnings for them, but they need to be kept so that their types can be checked.
*(Original in https://github.com/Rust-GCC/gccrs/pull/364)*

Don't remove unreachable statements at HIR lowering

---

gcc/rust/ast/rust-expr.h

Closes #360 
This fixes IfLetExpr's behavior and removes the previous unused warning as well

Assign outer_attrs in IfLetExpr constructor

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compile/generics19.rs
gcc/testsuite/rust.test/compile/generics20.rs

Handle the case where we have a generic type:
```rust
struct Foo<A,B>(A,B);
impl<T> Foo<i32, T> { ... }
```
In this case the impl block only defines 1 type parameter but the generic datatype has two type parameters.
Fixes #386

Partial substitions of generic data types

---

gcc/rust/resolve/rust-ast-resolve-type.h
gcc/testsuite/rust.test/xfail_compile/generic-default1.rs

Type parameters can have defaults these need to be name resolved.
Addresses: #307

Name resolve any specified types in TypeParams

---

gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compile/generics21.rs
gcc/testsuite/rust.test/compile/generics22.rs

We need to perform internal substitutions on Reference and Tuple Types in order to type check them.
These types cannot hold substitution parameters so they need to be performed with the internal substitution mapper.
Fixes #396

ReferenceTypes and Tuple can hold Type Parameters

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-path.h
gcc/rust/hir/rust-ast-lower-base.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/compile/generics23.rs
gcc/testsuite/rust.test/compile/generics24.rs
gcc/testsuite/rust.test/compile/lifetime1.rs
gcc/testsuite/rust.test/xfail_compile/expected_type_args2.rs
gcc/testsuite/rust.test/xfail_compile/expected_type_args3.rs
gcc/testsuite/rust.test/xfail_compile/generics4.rs
gcc/testsuite/rust.test/xfail_compile/type-bindings1.rs

When we get GenericBindings such as ::<A=...> this is not allowed
in this context. We can also improve the unexpected number of argument
errors to print the number of expected vs received arguments
An example error message looks like:
```
test.rs:4:12: error: generic item takes at least 1 type arguments but 0 were supplied
1 | struct Foo<A>(A);
|            ~
......
4 |     let a: Foo = Foo::<i32>(123);
|            ^
```

Improve error diagnostics in generic argument handling

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust.test/xfail_compile/array_empty_list.rs
gcc/testsuite/rust.test/xfail_compile/generics11.rs

When we have expression paths to generic functions we need to resolve all
type parameters to something otherwise we are left with orphaned inference
variables.
This adds the same checks from rustc back in, previously the
PathInExpression resolver abused inference variables as it was implemented
incorrectly since this is fixed in previous PRs we can bring this back in
to make typing more strict again.
Fixes #375

Add locations to implicit inference variables

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust.test/xfail_compile/issue-407.rs

This should fix #407 
The output now looks like:
```
test1.rs:9:17: error: found unexpected token ‘=’ in null denotation
9 |             a + = 1;
|                 ^
test1.rs:9:13: error: failed to parse expression for expression without block (pratt-parsed expression is null)
9 |             a + = 1;
|             ^
test1.rs:9:13: error: failed to parse statement or expression without block in block expression
test1.rs:9:19: error: failed to parse if body block expression in if expression
9 |             a + = 1;
|                   ^
test1.rs:8:9: error: failed to parse expr with block in parsing expr statement
8 |         if a < 40 {
|         ^
test1.rs:8:9: error: failed to parse statement or expression without block in block expression
test1.rs:10:11: error: could not parse loop …
```

Fix crashing in assignment operation

---

gcc/rust/backend/rust-compile-context.h
gcc/testsuite/rust.test/compile/generics26.rs
gcc/testsuite/rust.test/compile/generics27.rs

When we have generic data types or types that can contain type parameters
we need to make sure to avoid duplicating record types and abusing
structural equality rules in GCC. We do this by looking for already
compiled types that the item is equal to so they refer to the canoncial
record type.
Fixes #415

We need to monomorphize tuples as well as ADT's

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/rust-diagnostics.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

Fix duplicated function generation for generics
When emitting the backend IR we need to check if we have already compiled
one already. This is all due to the fact when we do generic substitutions
in type resolution its only upon usage of a function the function is
substituted it gains a new unique ty_ref HIR ID to make sure new
substituted versions of a type have unique ids.
Fixes #403

Fix duplicate function generation in the backend

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile.cc
gcc/rust/util/fnv-hash.h

Rustc uses a SIP128 hash for the legacy symbol mangling but an FNV hash is
simpler to implement. This is a port of the implementation from golang
stdlib hash package.
The fingerprint for the hash is simply the function signature for now.
Rustc takes into account options such as -Cmetadata to generate uniqueness.
We still need to implement a SIP128 hasher and the V0 symbol mangling but this
will do in the interim.
Addresses: #305
Fixes: #428

Add FNV-128 hash for legacy symbol mangling

---

gcc/testsuite/rust.test/unsupported/lifetime_param.rs
gcc/testsuite/rust.test/unsupported/slice1.rs
gcc/testsuite/rust.test/unsupported/struct_field_vis.rs
gcc/testsuite/rust.test/unsupported/unsupported.exp

Add support for 'unsupported' test cases in testsuite
Introduce an 'unsupported/' directory in the testsuite. It should contains tests
case for which the compiler currently has an incorrect behavior:
- its accepts invalid input
- it rejects valid input
Some basic guidelines are provided in unsupported.exp.

Add support for 'unsupported' test cases in testsuite

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust.test/compile/top_attr.rs

Fixed #419
only parse inner_attributes if it starts with "#!" not only "#"

Fixed #419: only parse inner_attributes if it starts with "#!" not only "#"

---

gcc/rust/util/rust-hir-map.cc

The DefId was being constructed wrongly by not fully shifting the CrateNum
over to be masked correctly.
Addresses #437
I am not sure if this fixes #437 but this definitely was not correct.

DefId is a bit mask of CrateNum & LocalDefId

---

gcc/rust/rust-buffered-queue.h

When end + num_items_to_read > buffer.size the buffer is extended to make sure it
can hold at least the extra num_items_to_read. The assert at the end of this block
however checks against end + num_queued_items. Fix the assert. This makes check-rust
zero fail on arm64.

Fix assert in rust-buffered-queue peek

---

gcc/config/aarch64/aarch64-protos.h
gcc/config/aarch64/aarch64-rust.c

Define aarch64_rust_target_cpu_info in aarch64-protos.h.
AARCH64_ISA_V8_1 isn't defined directly, check aarch64_isa_flags.

Fix aarch64 config for rust

---

gcc/rust/lex/rust-lex.cc
gcc/testsuite/rust.test/compile/raw_identifiers.rs
gcc/testsuite/rust.test/compile/raw_identifiers_keywords.rs
gcc/testsuite/rust.test/xfail_compile/raw_identifiers_bad_keywords.rs
gcc/testsuite/rust.test/xfail_compile/raw_identifiers_underscore.rs

Lexer::parse_raw_identifier added the first character twice.
Adds tests for a simple raw identifier, a keyword as raw identifier and
xfail tests for a single underscore and forbidden keyword (crate) as raw
identifier.
To help error diagnostics continue after parse_raw_identifier failed in
Lexer::build_token.
Fixes: https://github.com/Rust-GCC/gccrs/issues/426

Fix raw identifier parsing.

---

gcc/rust/util/rust-hir-map.h

valgrind complains whenever a crate number is used because they are all
derived from the initial crateNumItr in the rust-hir-map Mapping which
is never initialized. This isn't technically a bug because all that is
required is for crate numbers to be unique. But it could cause
non-deterministic behaviour when crate numbers are used for sorting.
And it makes the valgrind output really noisy.
With this patch and configure --enable-valgrind-annotations running
rust1 should not give any valgrind errors.

Initialize crateNumItr in rust-hir-map to zero.

---

gcc/rust/resolve/rust-ast-resolve-unused.h

The ScanUnused class would only mention some name was unused.
Add the actual identifier name that is unused to help the user.
Note that this warning might produce a similar warning as the
ScanDeadcode class produces if the indentifier is a function.

Mention the identifier that was unused in ScanUnused.

---

gcc/config/aarch64/aarch64-rust.c

commit dcb3a7b62 "Fix aarch64 config for rust" fixed the build
on arm64, but introduced a typo in the aarch64_isa_flags check.
AARCH64_FL_V8_2 should have been AARCH64_FL_V8_1 for "v8.1a".

Fix v8.1a typo in gcc/config/aarch64/aarch64-rust.c

---

gcc/config/rs6000/linux64.h
gcc/config/rs6000/rs6000-logue.c

Applying 2 patches sent on GCC mailing-list.
These changes fix errors in the current Rust testsuite.

Fix rs6000

---

gcc/rust/analysis/rust-hir-liveness-base.h
gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast.h
gcc/rust/backend/rust-compile-base.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/rust/hir/rust-ast-lower-block.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-cond-compilation.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-full-decls.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir-macro.h
gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/hir/tree/rust-hir-stmt.h
gcc/rust/hir/tree/rust-hir-visitor.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/rust/rust-session-manager.cc
gcc/rust/typecheck/rust-hir-const-fold-base.h
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-hir-type-check.cc

Deleting HIR::Attribute and reusing AST::Attribute. 
Some relative reusing classes below:
1. DelimTokenTree
2. AttrInputMetaItemContainer
3. AttrInputLiteral
4. MetaItemLitExpr
5. MetaItemPathLit
6. MetaItemPath
7. MetaItemSeq
8. MetaWord
9. MetaNameValueStr
10. MetaListPath
11. MetaListNameValueStr
12. Attrbute
13. AttrInput
14. MacroParser

reusing AST::Attribute and remove HIR::Attribute

---

gcc/rust/lex/rust-lex.h

Fixes #457 
I'm not really sure how to test it with `dejagnu` or if it is even possible.
This PR adds a check for the `-` filename in the `RAIIFile` class. In that case, the inner pointer should simply be `stdin`. We also have to be careful not to `fclose(stdin)` upon deallocation.

stdin: Allow compilation from standard input

---

gcc/rust/lex/rust-lex.h

Thanks to @tschwinge for finding the bug.
I added a test case, but not a lot of programs know how to handle this file. Unless there is some specific option, `gcc` complains about no input files, and `cat` does not understand it either. So I'm not sure the test case is actually useful.

raiifile: Allow dash-prefixed files to be parsed

---

gcc/rust/rust-session-manager.cc
gcc/rust/typecheck/rust-tyty.h

I am starting my work on cargo-gccrs, and the output from the compiler messes with what cargo expects as output. Since much of the debug prints are already done on `stderr` instead of `stdout`, this PR fixes what I believe to be the few remaining cases using `stdout`.
I used the following regexes (with ripgrep) to find all remaining instances of debug prints on `stdout`: `[^f]printf` and `fprintf \(stdout`

Always print compiler debug info on stderr

---

README.md

GCC Rust now has an associated mailing list and irc channel on the usual GCC locations.

Update README.md with GCC mailing list

---

gcc/config/rs6000/linux.h

Like 64-bit PowerPC, 32-bit PowerPC has the issue that
TARGET_RUST_OS_INFO is defined in both config/rs6000/sysv4.h
and config/rs6000/linux.h which triggers an error directive.
Thus, apply the same fix which undefines TARGET_RUST_OS_INFO
in linux.h first before redefining it, eliminating the error
directive.
gcc/ChangeLog:
2021-06-02  John Paul Adrian Glaubitz <glaubitz@physik.fu-berlin.de>
* config/rs6000/linux.h: Undefine TARGET_RUST_OS_INFO before
defining it.
Fixes #468

rs6000: Override TARGET_RUST_OS_INFO in linux.h

---

gcc/config/mips/mips-rust.c

mips: Fix incorrect name for target feature flag TARGET_ODD_SPREG

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir.h
gcc/rust/lex/rust-lex.cc
gcc/rust/parse/rust-parse-impl.h
gcc/rust/rust-diagnostics.cc
gcc/rust/rust-diagnostics.h
gcc/rust/rust-lang.cc
gcc/rust/rust-session-manager.cc
gcc/rust/typecheck/rust-tyty.h

Fixes #464 
@philberty I've checked and rust_debug does output on stderr correctly :)
This PR exposes the rust_debug prototype and replaces debug printfs (`fprintf (stderr, ...)`) with calls to rust_debug. This also removes the extra newlines that were added at the end of the fprintf format strings, since calling rust_debug already adds one. Without this, the tests fail due to blank lines in the output.
I have used a template to overload the rust_debug function and pass variadic arguments to the complete version. While the code looks cleaner than using `va_args`, it's also heavier C++. I'm open to changing it and definitely not attached to this implementation.
Most of the PR was made using sed and then clang-format

Expose rust debug and use it

---

gcc/testsuite/lib/rust.exp
gcc/testsuite/rust/compile/debug-diagnostics.rs
gcc/testsuite/rust/compile/generics4.rs
gcc/testsuite/rust/compile/generics6.rs
gcc/testsuite/rust/compile/generics9.rs
gcc/testsuite/rust/compile/issue-407-2.rs
gcc/testsuite/rust/compile/issue-407.rs
gcc/testsuite/rust/compile/method1.rs
gcc/testsuite/rust/compile/method2.rs
gcc/testsuite/rust/compile/shadow1.rs
gcc/testsuite/rust/compile/struct_init1.rs
gcc/testsuite/rust/compile/type-bindings1.rs
gcc/testsuite/rust/compile/unary_negation.rs
gcc/testsuite/rust/compile/unary_not.rs

This is no longer necessary after #466 "Expose rust debug and use it", where
commit 665df329a2ad60580ab593f6cbd646aa55927a37 "rust_debug: Replace fprintf
(stderr) with rust_debug" turned all 'fprintf' to 'stderr' into standard GCC
'inform' ('note: [...]') diagnostics -- which do get pruned by default.
Adjust the testsuite: instead of 'dg-excess-errors', spell out the additional
diagnostics now seen.

Remove diagnostics pruning from 'rust_target_compile' [#301, #466]

---

README.md
gcc/rust/lang.opt
gcc/rust/rust-diagnostics.cc
gcc/rust/rust-diagnostics.h
gcc/rust/rust-gcc-diagnostics.cc
gcc/testsuite/rust/compile/debug-diagnostics-default.rs
gcc/testsuite/rust/compile/debug-diagnostics-off.rs
gcc/testsuite/rust/compile/debug-diagnostics-on.rs
gcc/testsuite/rust/compile/debug-diagnostics.rs

... as discussed in #479, and elsewhere.

Use '-frust-debug' to control dumping of various Rust front end internals

---

gcc/config/arm/bpabi.h

Similar to PowerPC, 32-bit ARM has the issue that TARGET_RUST_OS_INFO
is defined in two separate headers, namely config/arm/bpabi.h and
config/arm/linux-elf.h. We can apply the same fix that was already
used for PowerPC.
gcc/ChangeLog:
2021-06-04  John Paul Adrian Glaubitz <glaubitz@physik.fu-berlin.de>
* config/arm/bpabi.h: Undefine TARGET_RUST_OS_INFO before
defining it.

arm: Override TARGET_RUST_OS_INFO in bpabi.h

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-item.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/hir/rust-ast-lower-base.h
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/testsuite/rust/compile/torture/traits1.rs
gcc/testsuite/rust/compile/torture/traits2.rs

This does not start enforcing anything to do with traits. in order to
implement the traits milestone we need to be able to implement a
trait first.
This makes the Trait impls follow a normal impl block. As the starting
point.
Fixes #395 #472

Trait impls and initial start of traits work

---

gcc/rust/resolve/rust-ast-resolve-toplevel.h

The commit message has a more detailed explanation as to why.
But some toplevel items were not respecting their prefix which is
important for module support.

All toplevel items must respect the prefix for their path

---

gcc/rust/backend/rust-compile.cc

* gcc/rust/backend/rust-compile.cc (legacy_hash): lo and hi are uint64_t use
PRIx64 to print them as hex values instead of %lx which is target specific.

Use PRIx64 to print 64bit hex values in legacy_hash

---

gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h

In order to support Modules, we need to do path resolution properly. The old code assumed a basic A::B but this is not generic enough in order to support modules.

Path resolution fixes

---

gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-full-decls.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir-visitor.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/lint/rust-lint-marklive-base.h
gcc/rust/lint/rust-lint-marklive.cc
gcc/rust/lint/rust-lint-marklive.h
gcc/rust/typecheck/rust-hir-const-fold-base.h
gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
gcc/rust/typecheck/rust-hir-path-probe.h
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-tycheck-dump.h
gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-hir-map.h

The HIR implementation has been bootstrapped from the AST, this has lead to a lot of missed desugaring. This PR removes TraitImpls and refactors the InerhentImpls to be an ImplBlock. The class hierarchy has been simplified in tandem here such that all impl items are of the same base class.
More cleanup is required but this is an isolated change that can go in now.

HIR cleanup

---

gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-name-resolver.h

TraitImpls have a canonical path which is a trait projection such as
```rust
pub trait Trait { // ::a::Trait
fn f(&self); // ::a::Trait::f
}
impl Trait for Struct {
fn f(&self) {} // <::a::Struct as ::a::Trait>::f
}
```

TraitImpl blocks have a different CanonicalPath to normal impl blocks

---

gcc/rust/lex/rust-token.h
gcc/rust/rust-lang.cc
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h

Fixing the build issue in macos by avoiding abort macro override the abort call of std.

Avoid abort macro override the abort of std

---

gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-fnparam.h
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/tree/rust-hir-full-decls.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir-visitor.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/lint/rust-lint-marklive-base.h
gcc/rust/lint/rust-lint-marklive.h
gcc/rust/typecheck/rust-hir-const-fold-base.h
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h

Canonicalizing the paths of the compiler to treat functions and methods 
the same way will ensure we avoid duplication.

Remove HIR::TraitItemMethod, this can be represented by TraitItemFunction

---

gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/rust-diagnostics.cc
gcc/rust/rust-diagnostics.h

This adds the missing override specifier to as_string on identifier
patterns and ensures rust_debug gains printf specifier checks.

Cleanup warnings

---

README.md

The path of header dir and sysroot should be specified when you configure the project.
Fixed #500

Update README.md for building steps on MacOS.

---

gcc/dwarf2out.c
gcc/testsuite/rust/debug/debug.exp
gcc/testsuite/rust/debug/lang.rs
gcc/testsuite/rust/debug/oldlang.rs

This changes the GCC DWARF emitterto use DW_LANG_Rust or
DW_LANG_Rust_old as appropriate.

Use DW_LANG_Rust in DWARF

---

gcc/dwarf2out.c
gcc/rust/rust-gcc.cc
gcc/testsuite/rust/debug/chartype.rs
gcc/testsuite/rust/debug/i8u8.rs

I found a couple of small bugs in the DWARF that is emitted for primitive types.
These two patches fix these.

DWARF for Rust primitive types

---

gcc/rust/hir/rust-ast-lower-type.h

After std::move(mapping), mapping is unspecified

Fix: do not use object after it has been moved

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/typecheck/rust-hir-type-check-type.h

Add more context to some internal error messages (ie. not intended for user)

Make 3 error messages slightly more informational

---

gcc/rust/hir/tree/rust-hir-full-test.cc

Make struct fields more visible in dumps and add the mapping in the dump string.

Add more info in HIR dump for struct

---

gcc/testsuite/rust/debug/chartype.rs
gcc/testsuite/rust/debug/i8u8.rs
gcc/testsuite/rust/debug/lang.rs
gcc/testsuite/rust/debug/oldlang.rs

Mark Wielaard pointed out that the i8u8.rs test that I recently
introduced has a bug: it checks the DW_AT_language attribute, not
DW_AT_encoding.
Sorry about this.
This patch fixes this problem.  I've verified that this notices the
failure after temporarily backing out the corresponding GCC change.
This patch also fixes another problem that he found, namely that it's
possible for these tests to find the wrong answer, because the hex
value that is checked for might be a prefix of some longer value.
This patch also adds a whitespace check to avoid this potential
problem.

Fix up test suite buglets

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile-stmt.h
gcc/rust/backend/rust-compile.cc
gcc/rust/lex/rust-lex.cc
gcc/rust/lex/rust-token.cc
gcc/rust/lint/rust-lint-scan-deadcode.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-tyty.cc
gcc/testsuite/rust/compile/break1.rs
gcc/testsuite/rust/compile/break2.rs
gcc/testsuite/rust/compile/continue1.rs
gcc/testsuite/rust/compile/torture/unused.rs
gcc/testsuite/rust/compile/torture/unused1.rs
gcc/testsuite/rust/compile/tuple_struct1.rs
gcc/testsuite/rust/compile/unary_not.rs

Fix warnings mainly coming from ` being used instead of %< and %>.
Also fixing occurences of :
```
../../gcc/rust/lex/rust-token.cc:126:40: warning: unquoted sequence of 2 consecutive punctuation characters ‘',’ in format [-Wformat-diag]
126 |        "attempted to get string for '%s', which has no string. "
|                                        ^~
../../gcc/rust/lex/rust-token.cc:127:39: warning: spurious trailing punctuation sequence ‘.’ in format [-Wformat-diag]
127 |        "returning empty string instead.",
|                                       ^
../../gcc/rust/lex/rust-token.cc:126:37: warning: unterminated quote character ‘'’ in format [-Wformat-diag]
126 |        "attempted to get string for '%s', which has no string. "
|                                     ^
```
and various …

Fix various Wformat-diag diagnostics

---

gcc/rust/backend/rust-compile-context.h
gcc/testsuite/rust/debug/tuple.rs

Tuples currently use plain integer field names in the DWARF.  However,
rustc prefixes these with "__", and GDB understands this convention.
This patch changes gccrs to match, and adds an explanatory comment.

Rename tuple field names

---

gcc/rust/lex/rust-lex.h

RAIIFile's implementation of operator= can leak a file, because it
doesn't handle the case where the assignee holds an open file handle.

Fix RAIIFile buglet

---

gcc/rust/backend/rust-compile-stmt.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/torture/struct_init_10.rs
gcc/testsuite/rust/compile/torture/struct_init_11.rs
gcc/testsuite/rust/compile/torture/struct_init_9.rs

We still have bugs handling unit-structs but this allows for Tuple Structs
and normal named field structs to be declared within a block and referenced
lexically. This allows rust statements to follow the correct grammar.
Fixes #519

Add support for struct definitions to be within a block

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/torture/tuple_struct_unit.rs

A tuple struct can be empty, in which case it is a unit tuple struct.
Handle this in Parser<ManagedTokenSource>::parse_struct by creating
a empty tuple_field vector instead of calling parse_tuple_fields.
Add a testcase to show empty tuple structs are now accepted.
Addresses: #385

Handle empty/unit tuple structs in the parser.

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/torture/tuple_enum_variants.rs

A tuple enum variant can be empty, in which case it is a unit enum variant.
Handle this in Parser<ManagedTokenSource>::parse_enum_item by creating
a empty tuple_field vector instead of calling parse_tuple_fields.
Add a testcase to show empty tuple enum variant types are now accepted.
But note some part of the test is commented out because using the enum
type isn't actually possible right now.
Addresses #79

Handle empty/unit tuple enum variants in the parser.

---

gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/testsuite/rust/compile/lookup_err1.rs
gcc/testsuite/rust/compile/torture/nested_fn1.rs
gcc/testsuite/rust/compile/torture/nested_fn2.rs

This is a missed pieces of functionality for statements in rust.

Add support for nested functions

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-const-fold.h
gcc/testsuite/rust/compile/torture/unit_type2.rs

Functions with return type of unit are still using void_type_node as there is an ICE in GCC:
```
test.rs: In function ‘main’:                                                                                                                                                                                                                           
test.rs:16:1: internal compiler error: in min_value, at wide-int.cc:346                                                                                                                                                                                
16 | fn main() { …
```

Change unit-type from void_type_node to a zero sized unsigned integer

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/lint/rust-lint-marklive.h
gcc/rust/typecheck/rust-hir-const-fold.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/torture/borrow_function.rs
gcc/testsuite/rust/compile/torture/deref_function.rs
gcc/testsuite/rust/compile/torture/negation_function.rs

Support BorrowExpr, DereferenceExpr, NegationExpr in marking live symbols and corresponding test cases.

Support BorrowExpr, DereferenceExpr, NegationExpr in marking live symbols and corresponding test cases.

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/lint/rust-lint-marklive.cc
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/torture/unit_type3.rs
gcc/testsuite/rust/compile/torture/unit_type4.rs

Unit type can be reference via an identifier expression. Other type references via an identifier expression are not supported yet.

Add unit-type support for Identifier expressions

---

gcc/rust/lex/rust-lex.cc
gcc/rust/lex/rust-lex.h
gcc/rust/lex/rust-token.cc
gcc/rust/lex/rust-token.h
gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/bad_tuple_index.rs
gcc/testsuite/rust/compile/torture/tuple_index.rs

Tuple indexes should be pure decimal integer literals. But the parser just sees an
integer literal. Fix this by introducing a new type hint CORETYPE_PURE_DECIMAL. This
doesn't conflict with any existing type hints since a pure decimal doesn't have a
type suffix.
Introduce a new method is_pure_decimal that the parser can use in parse_tuple_index_expr.
get_type_hint will return CORETYPE_UNKNOWN for pure decimals.
parse_decimal_int_or_float will check whether there are no execissive leading zeros.
parse_in_decimal checks the literal doesn't contain any underscores.
Add two testcases. bad_tuple_index.rs with all variants of integer literals which aren't
pure decimals. And tuple_index.rs with various correct tuple indexes.
Resolves: https://github.com/Rust-GCC/gccrs/issues/511

Reject non-pure decimal tuple indexes.

---

gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/lint/rust-lint-marklive.h
gcc/testsuite/rust/compile/torture/break_function.rs
gcc/testsuite/rust/compile/torture/return_function.rs
gcc/testsuite/rust/compile/torture/while_function.rs

Marking live symbol in break, return, while, whilelet, for expr without test case for last two due to unimplemented.

Marking live symbol in break, return, while, whilelet, for expr

---

gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-trait-resolve.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/testsuite/rust/compile/traits1.rs
gcc/testsuite/rust/compile/traits2.rs

This is a building block for actually enforcing the obligations of a trait.
It includes a query-based lookup of the trait to avoid reloading it so
we only do the hard work once. Then provides the enforcement for
basic functions. Constants, methods and associated types are still
WIP.
Addresses: #440

Trait Obligations building block

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/torture/inner_attributes.rs

parse_inner_attribute tried to skip the right square token twice. This caused odd error
messages in case there were multiple inner attributes. This bug masked another bug in
parse_attr_input where when the (optional) attr input was an assignment to a literal
the parser failed to skip the literal.
The existing top_attr.rs testcase relied on the two bugs cancelling each other out.
Add a new testcase inner_attributes.rs for the first bug.
Resolves: https://github.com/Rust-GCC/gccrs/issues/510

Fix inner attribute parsing

---

gcc/rust/hir/rust-ast-lower-type.h

Translating the AST LifetimeType to the HIR LifetimeType causes a warning:
warning: ‘ltt’ may be used uninitialized
Add a default clause to the switch statement calling gcc_unreachable.
This will suppress the warning and make sure that if the AST lifetime type
is invalid or a new unknown type we immediately know when lowering the AST.

Suppress warning in rust-ast-lower-type.h ASTLowerGenericParam.visit.

---

gcc/rust/resolve/rust-ast-resolve-unused.h
gcc/testsuite/rust/compile/torture/cfg_attr.rs
gcc/testsuite/rust/compile/torture/unused1.rs
gcc/testsuite/rust/compile/torture/unused_struct.rs

The scan dead-code pass will take over this role, but let's keep both
running for a while and then we can update ScanUnused to only scan for
unused labels and variables. Dead Code pass is important as it is not possible
to rely on name resolution to know what symbols are used or not used.
Further resolution occurs during type resolution and the dead code pass runs after type resolution.

Revert change to ScanUnused to not scan Types

---

gcc/rust/rust-session-manager.cc

exit immediately when the type checker find an error

exit immediately when the type checker find an error

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir.h
gcc/rust/lex/rust-lex.cc
gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/torture/not_shebang.rs
gcc/testsuite/rust/compile/torture/not_shebang_block_comment.rs
gcc/testsuite/rust/compile/torture/not_shebang_comment.rs
gcc/testsuite/rust/compile/torture/not_shebang_multiline_comment.rs
gcc/testsuite/rust/compile/torture/not_shebang_spaces.rs
gcc/testsuite/rust/compile/torture/shebang.rs
gcc/testsuite/rust/compile/torture/shebang_plus_attr.rs
gcc/testsuite/rust/compile/torture/shebang_plus_attr2.rs

Mark Wielaard:
> Shebang handling, the first line starting with #! was not done fully
> correct and it isn't necessary to keep track of the shebang line in
> the AST or HIR Crate classes.
> 
> Because an inner attribute also starts with #! the first line isn't
> regarded as a shebang line if the #! is followed by (optional)
> whitespace and comments and a [. In that case the #! is seen as the
> start of an inner attribute.
> 
> I added various testcases that hopefully show the funny things you can
> get when the first line starts with #!.

shebang handling

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/rust-gcc.cc

In #547 it was found that u64's ended up as usize in gimple which confuses
debugging sessions. This take the original implementation of named type
from gccgo showing it was the TYPE_NAME tree getting confused.
Addresses #547

Fix bad naming of primitive types such as u64 which ended up as usize

---

gcc/rust/lint/rust-lint-marklive.cc
gcc/rust/lint/rust-lint-marklive.h

use rust_assert in dead code pass instead of rust_error_at
Fixed #550

use rust_assert in dead code pass instead of rust_error_at

---

gcc/rust/lint/rust-lint-scan-deadcode.h
gcc/rust/rust-session-manager.cc

Call MarkLive inside ScanDeadcode, then the pass entrance will be single in session::parse_file

Call MarkLive inside ScanDeadcode, then the pass entrance will be single in session::parse_file

---

gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/hir/tree/rust-hir-type.h
gcc/rust/hir/tree/rust-hir.h

Remove trailing macro items from HIR
Fixes #69

Remove HIR MacroItem and other hir macro forward declarations

---

gcc/rust/ast/rust-item.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-trait-resolve.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/testsuite/rust/compile/torture/traits6.rs
gcc/testsuite/rust/compile/torture/traits7.rs
gcc/testsuite/rust/compile/traits3.rs
gcc/testsuite/rust/compile/traits4.rs
gcc/testsuite/rust/compile/traits5.rs

This PR introduces enhanced type checking for trait constants
and associated types. It also brings in the check to ensure all
mandatory trait items are implemented. Note optional trait items
cannot be referenced or used yet and will be done in a separate PR.

Further error checking for trait impl blocks

---

gcc/rust/typecheck/rust-hir-type-check-item.h

When a trait item is optional this is not a missing trait item.

Some trait items are optional and should not cause an error

---

gcc/testsuite/rust/compile/torture/unit_type5.rs

This test case will catch regressions in changes to initializing unit structs.
Fixes #155

Add missing test case to close out unit-structs

---

gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

DefIds need to be managed for fntypes which will help in the compilation
of optional traitt functions

Add missing DefId mappings

---

gcc/rust/lint/rust-lint-marklive.h

call accept_vis directly instead of calling it after get().

call accept_vis directly instead of call it after get

---

gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/typecheck/rust-hir-path-probe.h
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty-visitor.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-hir-map.h

As part of an effort to cleanup some of the interfaces within the TyTy module
this PR adds a const visitor for accessing each type and updates the can_eq
interface to also be const as it should not require mutability.
These changes fell out of a branch for optional trait items support.

Cleanup and add const modifiers to equlity interface

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-tyty-coercion.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/reference1.rs
gcc/testsuite/rust/compile/torture/coercion1.rs

This is the initial type coercion code. Coercions are necessary to implement
mutability on reference types and for raw pointers in general.
Fixes #576 #352 
Addresses #434

Initial type coercion code

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/rust-ast-lower-block.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/torture/unsafe1.rs
gcc/testsuite/rust/compile/torture/unsafe2.rs
gcc/testsuite/rust/compile/unsafe.rs

This wires up the code nessecary to compile an unsafe block
it does not implement any rules or checks yet.
Fixes #382

HIR and GENERIC lowering for unsafe blocks

---

gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h

This fixes an issue to allow unsafe within an expression.

unsafe blocks can be used in expressions

---

gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-hir-map.h

This helper will allow use to use mappings to iterate
all impl blocks within the specified crate.

Add iterate impl_blocks helper

---

gcc/testsuite/rust/compile/torture/unsafe3.rs

Add testcase to cover parse errors in unsafe expressions

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/torture/pointer1.rs

Dereference expressions can also be pointer types not just references.
Fixes #588

Support dereference of pointers

---

gcc/rust/parse/rust-parse-impl.h

union is a weak keyword which means it isn't reserved and can be used
as a generic identifier. When we see an identifier where a union could
be declared we check whether the identifier is "union", but only when
the next token is also an identifier. In parse_union we shouldn't skip
the first identifier token, because it is already skipped when we call
expect_token.

Better union support in the parser

---

gcc/rust/parse/rust-parse-impl.h

parse_type_no_bounds tries to be helpful and greedily looks for a PLUS
token after having parsed a typepath so it can produce an error. But
that error breaks parsing expressions that contain "as" Cast
Expressions like "a as usize + b as usize". Drop the explicit error on
seeing a PLUS token and just return the type path parsed.

Remove error handling in parse_type_no_bounds for PLUS token

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/torture/byte_char_str.rs

A byte literal is an u8 created as a ascii char or hex escape
e.g. b'X'.  A byte string literal is a string created from ascii or
hex chars. bytes are represented as u8 and byte strings as str (with
just ascii < 256 chars), but it should really be &'static [u8; n].

Support byte and byte string literals

---

gcc/rust/ast/rust-ast-full-test.cc

Fix crash when extern function item has no return type

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-item.h
gcc/rust/hir/rust-ast-lower-extern.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/resolve/rust-ast-resolve.cc

Add name-resolution and HIR lowering for extern blocks

---

gcc/rust/util/rust-hir-map.cc

These assertions defend against duplicate/bad mappings

Fix assertion for trait item mappings

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-extern.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/hir/rust-ast-lower-extern.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-hir-map.h
gcc/testsuite/rust/execute/torture/helloworld1.rs
gcc/testsuite/rust/execute/torture/helloworld2.rs

```rust
extern "C" {
fn puts(s: *const i8);
}
fn main() {
unsafe {
let a = "Hello World\0";
let b = a as *const str;
let c = b as *const i8;
puts(c);
}
}
```
Fixes #421

Hello world

---

gcc/rust/parse/rust-parse-impl.h

Use correct lookahead to peek after 'while' token when parsing expression with block (parse_expr_with_block).

---

gcc/rust/ast/rust-item.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tycheck-dump.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/torture/union.rs
gcc/testsuite/rust/compile/torture/union_union.rs

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000107.html
> 
> Treat a union as a Struct variant like a tuple struct.  Add an
> iterator and get_identifier functions to the AST Union class.  Same
> for the HIR Union class, plus a get_generics_params method. Add a new
> ADTKind enum and adt_kind field to the ADTType to select the
> underlying abstract data type (struct struct, tuple struct or union,
> with enum as possible future variant).
> 
> An union constructor can have only one field. Add an union_index field
> to StructExprStruct which is set during type checking in the
> TypeCheckStructExpr HIR StructExprStructFields visitor.
> 
> For the Gcc_backend class rename fill_in_struct to fill_in_fields and
> use it from a new union_type method. Handle union_index …

union support for hir type checking and gcc backend

---

gcc/rust/lint/rust-lint-marklive.h
gcc/testsuite/rust/compile/torture/forward_decl_3-unsafe.rs
gcc/testsuite/rust/compile/torture/union.rs
gcc/testsuite/rust/compile/torture/unsafe4.rs

We may then remove the '{ dg-options "-w" }' as discussed in
<http://mid.mail-archive.com/YQciMeKNpCH+ZMsJ@wildebeest.org> and #601.

Handle 'UnsafeBlockExpr' in liveness analysis

---

gcc/rust/ast/rust-item.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/parse/rust-parse-impl.h

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000108.html
> TupleField was missing a Location field and we dropped to locus when
> lowering Union fields to HIR.

Add locus to TupleField and pass it and union variants to HIR class

---

gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/rustspec.cc

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000110.html
> The backend was derived from the go backend which enables split stack
> support by default. This inserts a __morestack call at the start of
> each function. This is not needed for the rust backend. Remove the
> split stack support code from the rust backend and spec.

Remove split-stack from backend

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/torture/identifier-missing-impl-1.rs

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000111.html
> When expect_token fails it produces an error and return a
> nullptr. Make sure to always check the result of expect_token so we
> don't use a nullptr token and crash.
> 
> Resolves: https://github.com/Rust-GCC/gccrs/issues/603

Always check the result of expect_token while parsing

---

gcc/rust/ast/rust-ast-full-decls.h
gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast-visitor.h
gcc/rust/ast/rust-item.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/hir/rust-ast-lower-base.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/resolve/rust-ast-resolve-base.h

This PR merges both kinds of Modules (formerly `ModuleBodied` and `ModuleNoBody`) as one class with an enum. This is the [behavior used by rustc](https://github.com/rust-lang/rust/blob/2939249f294dd54a9ce78a8ee1f2922a44e7fb7c/compiler/rustc_ast/src/ast.rs#L2274), where both variants are kept in an enum with one holding a vector of items.
This change is important for multiple file parsing: An external mod (`mod foo; // defined in foo.rs or foo/mod.rs`) will see its items expanded during expansion, which occurs after parsing. This means that the previous directive will be "replaced" by `mod foo { <items> }` at the AST level. In order to achieve this, we need to be able to modify a previously parsed instance of an AST element.
In rustc, this is done …

Merge both module classes in one

---

gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h

In order to support multiple file parsing, we will need to be able to parse items from a file without specifically parsing an entire crate. This PR splits up the `parse_crate()` function in two and exposes the `parse_items()` function.
The function was previously hidden and didn't have the exact same behavior as the main loop of `parse_crate()`.
This will be especially useful when trying to expand 
```rust
mod <file>;
```
to
```rust
mod <file> {
<items>
}
```
in the AST as we will need to parse the items present in the file.

Add `parse_items()` function from `parse_crate()`

---

gcc/common.opt
gcc/rust/config-lang.in
gcc/rust/rustspec.cc

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000117.html
> rustspec.cc was based on the Go frontend gospec.cc. Remove special
> handling of math and pthread libraries and profiling option. Handle
> .rs files instead of .go files. Keep support for linking with (static)
> librust which is currently commented out. Add generic static-librust
> option to common.opt.

More rustspec.cc cleanups

---

gcc/rust/rust-gcc.cc

Fixes #467 
- \[ ] GCC code require copyright assignment: https://gcc.gnu.org/contribute.html
This is not a large contribution, so copyright assignment seems not needed. Signed-Off-By has been added.

rust to gcc glue layer: Remove excess precision when done

---

gcc/rust/rust-lang.cc
gcc/rust/rust-session-manager.h

This PR changes the behavior of the compiler's session manager: Instead of keeping a single static instance in `rust-lang.cc`, the class now exposes a static instance via a `get_instance()` method. This is important for external module parsing as a new lexer and parser need to be instantiated during macro expansion, and a lexer must rely on a linemap, of which a single instance exists and is contained in the `Session` instance.
I ran into a few issues trying to make this a bit smarter (for example, by calling `init()` on the first `get_instance()` invocation) because I ran into a race condition. I haven't looked into it, but it seems that the calls to the various language hooks are sometimes multithreaded.

Turn Session Manager into basic singleton

---

gcc/rust/lex/rust-lex.cc
gcc/testsuite/rust/execute/torture/str-zero.rs

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000127.html
> 
> Zero characters (codepoints) are acceptable in strings. The current
> Lexer::parse_string skipped such zero codepoints by accidents. The
> zero codepoint was also used as error/skip indicator, but that is only
> true if the third argument of utf8_escape_pair is true (yes, it is
> called pair, but is a triple).
> 
> Add a testcase that checks the (sub)strings are separated by zero
> chars. Since we cannot slice strings yet this uses extern "C"
> functions, printf and memchr.

lex: accept zero codepoints in strings

---

gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile.cc
gcc/rust/typecheck/rust-hir-path-probe.h
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-trait-resolve.h
gcc/rust/typecheck/rust-hir-type-bounds.h
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-tyty-bounds.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-hir-map.h
gcc/testsuite/rust/compile/traits6.rs
gcc/testsuite/rust/compile/traits7.rs

TypeParameters contain specified bounds, when we substitute them we need
to ensure that the argument satisfies those bounds otherwise... it fails
the contract.
Addreses #440

Add check for TypeBounds on argument substitutions

---

gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/resolve/rust-name-resolver.h

This was a fix required for @dkm work on the module support.

Make insert_new_definition permissive of the same mapping.

---

gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-name-resolver.h

`is_error` connotes that an error has been found or that the object is faulty.
It is possible to `create_empty` paths and pass them around. Having to use
`is_error` to test for valid emptiness can be misleading.

Rename CanonicalPath::is_error to is_empty

---

gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h

This change fixes the location to provide better error tracking.

Pass pratt parsed location to expr parser functions to fix expr locus

---

.github/workflows/docker.yml

Recently dockerhub is now charging for automated builds on dockerhub. This
means we no longer have regular updated docker builds of gccrs.

Add docker image builds though github actions.

---

gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/resolve/rust-name-resolver.h
gcc/rust/util/rust-canonical-path.h
gcc/rust/util/rust-hir-map.h
gcc/rust/util/rust-mapping-common.h

We need to be able to lookup canonical paths in order
to do proper name mangling as well as give more meaning
full names to the GENERIC IR. This is important since
the gcc IR is flat and makes it hard to distinguish which function
is which, especially when modules support will be added.

Add mappings for canonical paths

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-item.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/lex/rust-lex.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/rust-system.h

This PR is a first attempt at resolving the filename corresponding to an external module correctly. Some of the cases are not handled yet and a lot of FIXMEs are still here, as I am looking for feedback on certain things:
* Am I correct in assuming that we have to go through directories the C way because we are using C++11 and the `filesystem` header is not available until C++17? Is there some gcc abstraction for this that I'm overlooking?
* How important is the existence of a separate SEPARATOR macro for Windows? From what I'm understanding, the OS also understands normal slashes `/` on top of the backward slashes it usually uses `\`. I don't know what happens when they are mixed and matched or how the file system handles it.
* For review simplicity, outer attributes could be accessed in …

Resolve module filename

---

gcc/rust/typecheck/rust-hir-type-check-expr.h

resolve_root_path can return nullptr in case of error.
Better raise an error than dereference the pointer.

typecheck: add assert on resolve_root_path return value

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/torture/ifunaryexpr.rs

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000140.html
> An if conditional expression doesn't need brackets, but that means
> that it doesn't accept struct expressions. Those are not easy to
> distinquish from the block that follows. What isn't immediately clear
> from the grammar is that unary conditions like minus '-' or not '!'
> also shouldn't accept struct expressions (when part of an if
> conditional expression) because those also cannot be easily
> distinquished from the block that follows.
> 
> Add a testcase "ifunaryexpr.rs" that shows a couple of contructs that
> should be accepted as if conditional expressions and fix the parser to
> pass the restriction of not accepting struct expressions after a unary
> expression.

parse if expression with unary minus or not expression

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/torture/bools_eq.rs

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000141.html 
> The TypeCheckExpr creates a new TyTy::BoolType for a
> ComparisonExpr. This new BoolType is unknown to TyTyResolveCompile
> which causes a crash when trying to compile the inferred new
> BoolType. Resolve this by looking up the builtin bool type.
> The new "bools_eq.rs" testcase uses several bools which show
> this issue.
> 
> Also the lhs and rhs types need to be compatible, but don't
> need to be bool type themselves. So don't append the reference
> to the inferred type. The existing "ifunaryexpr.rs" testcase
> will fail without this fix.

Use builtin bool instead of creating new bool types for ComparisonExpr

---

gcc/rust/typecheck/rust-tyty-cast.h
gcc/testsuite/rust/compile/bad_as_bool_char.rs
gcc/testsuite/rust/compile/torture/as_bool_char.rs

From Mark  Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000147.html
> bools and chars can be cast to any integer type, but not to floats or
> each other. Adjust the BoolCastRule and CharCastRule to allow these
> casts. Add a postive test "as_bool_char.rs" and negative test
> "bad_as_bool_char.rs" to check the correct casts are accepted and the
> illegal casts produce errors.
> 
> Resolves: https://github.com/Rust-GCC/gccrs/issues/629

Allow bool and char to be cast as any integer type

---

gcc/rust/rust-lang.cc
gcc/testsuite/rust/compile/torture/prims_struct_eq.rs

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000144.html
> The gcc constant folding code uses the type_for_size langhook. Use the
> default implementation instead of crashing when the langhook is
> called. Add a new testcase "prims_struct_eq.rs" that creates trees
> that triggers the constant folding.
> 
> Also remove the write_globals langhook which was removed when early
> debug was integrated into gcc.

Use default type_for_size langhook

---

gcc/rust/typecheck/rust-hir-const-fold.h
gcc/testsuite/rust/compile/torture/primconsts.rs

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000143.html
> Handle BOOL and FLOAT in ConstFoldExpr::visit (HIR::LiteralExpr) to
> make it possible to create const bool, f32 and f64 constants. Add a
> new testcase "primconsts.rs". Not yet handled are const char and &str
> types.

Add support for const bool and const float

---

gcc/rust/ast/rust-item.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/resolve/rust-name-resolver.h
gcc/rust/rust-lang.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-tyty-cast.h
gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-hir-map.h
gcc/testsuite/rust/compile/bad_as_bool_char.rs
gcc/testsuite/rust/compile/torture/all_doc_comment_line_blocks.rs
gcc/testsuite/rust/compile/torture/all_doc_comment_line_blocks_crlf.rs
gcc/testsuite/rust/compile/torture/as_bool_char.rs
gcc/testsuite/rust/compile/torture/mod-nameresolve.rs
gcc/testsuite/rust/compile/torture/mod1.rs
gcc/testsuite/rust/compile/torture/mod2.rs
gcc/testsuite/rust/compile/torture/mod3.rs
gcc/testsuite/rust/compile/torture/prims_struct_eq.rs
gcc/testsuite/rust/execute/torture/mod1.rs

Adds name resolution, HIR lowering and type checking. For modules
which should allow for initial multiple file parsing support.
Fixes #432

Initial support for module

---

gcc/rust/typecheck/rust-hir-path-probe.h

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000142.html
> Without handling the default case in the switch statement gcc 10.2.1 will warn:
> 
> rust-hir-path-probe.h:75:40: warning: ‘candidate_type’ may be used uninitialized
>   in this function [-Wmaybe-uninitialized]

Suppress uninitialized candidate_type warning in process_traits_for_candidates

---

gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/tree/rust-hir-full-decls.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir-visitor.h
gcc/rust/lint/rust-lint-marklive-base.h
gcc/rust/typecheck/rust-hir-const-fold-base.h
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-util.h

At this point in the pipeline, all modules are either internal and
contain items, or external and have been previously expanded in the
macro-expand phase. Thus, all HIR modules will contain their final set
of items

hir: Merge both module classes in one

---

gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
gcc/testsuite/rust/compile/traits8.rs

Ignore trait-impls in overlapping check this needs some though for generics traits.

Ignore impl trait blocks in overlap pass

---

gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/testsuite/rust/compile/dup_fields.rs

From Mark Wielaard : https://gcc.gnu.org/pipermail/gcc-rust/2021-August/000150.html
> Odd things happen if structs or unions have duplicate field names.
> Emit an error when lowering an struct/union item or declaration
> statement and a duplicate field name is detected.  A new testcase
> 'dup_fields.rs' checks an error is actually produced.

Reject duplicate field names in structs and unions.

---

gcc/rust/ast/rust-path.h
gcc/rust/parse/rust-parse-impl.h

see https://doc.rust-lang.org/reference/paths.html#qualified-paths
The initial segment is mandatory this changes the AST to reflect this
it simplifies error handling down the line.

Qualified paths have a mandatory initial segment

---

gcc/rust/Make-lang.in
gcc/rust/ast/rust-item.h
gcc/rust/ast/rust-path.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-path-probe.h
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-trait-resolve.cc
gcc/rust/typecheck/rust-hir-trait-resolve.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-path.cc
gcc/rust/typecheck/rust-hir-type-check-type.cc
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyctx.cc
gcc/rust/typecheck/rust-tyty-coercion.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/torture/traits12.rs
gcc/testsuite/rust/compile/torture/traits13.rs
gcc/testsuite/rust/compile/torture/traits14.rs
gcc/testsuite/rust/compile/torture/traits15.rs

This fixes how we handle associated types in relation to generic
traits. Generic traits are interesting because, a TypePath usually
resolves to a normal TyTy type which can be substituted using the
mapper classes, but a trait is a definition of behaviour which 
is made up of types, constants or functions. In order to handle
generic traits we must add substitution support to the associated types
which are represented by projections see this commit for detail on the changes
0798add3d3c1bf4b20ecc1b4fa1047ba4ba19759
Also see https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/sty/struct.ProjectionTy.html
Fixes #434

Generic Qualified Paths

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-item.h
gcc/rust/hir/rust-ast-lower-enumitem.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/rust-ast-lower.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/testsuite/rust/compile/bad_pub_enumitems.rs
gcc/testsuite/rust/compile/bad_stmt_enums.rs
gcc/testsuite/rust/compile/bad_toplevel_enums.rs
gcc/testsuite/rust/compile/torture/tuple_enum_variants.rs

see https://gcc.gnu.org/pipermail/gcc-rust/2021-September/000174.html
This set of patches adds support for parsing, name resolution and HIR lowering for enums.
Typechecking and code-generation are still in progress but these patches are ready to merge now.

Add building blocks for enum support

---

gcc/rust/Make-lang.in
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile.cc
gcc/rust/backend/rust-mangle.cc
gcc/rust/backend/rust-mangle.h
gcc/rust/lang.opt
gcc/rust/rust-session-manager.cc

Add option to choose mangling scheme.
Closes #429 
This PR splits the `Mangler` class in its own set of header and source and adds the base for v0 name mangling.
You are now able to specify the mangling scheme to use using `-frust-mangling=<value>`.
When inputting an invalid value, the compiler errors out using `unrecognized command-line option `-frust-mangling=<not_valid>`. Is there a better way to do this? Is there also a way to test this behaviour using dejagnu?

Add mangling switch

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/testsuite/rust/compile/torture/extern_mod2.rs

`#[path]` attributes were used wrongly in two ways:
- The attribute's value would still contain extra data such as an equal
sign and whitespaces, which need to be discarded in order to fetch the
proper file path.
- `#[path]`s are relative to the directory where the current source file
is located. So we actually need to compute them later on down the line,
once the including directory has been figured out.
Another issue was that in the case that no candidates were found, or too
many were founds, the function `process_file_path` would still return
"successfully" despite erroring out. This causes the function to return
early and thus not assign any string to the `module_file` member.
We also have the ability to emit an error for the module's location,
which looks better for the user, instead …

Fix usage of path attributes and module filename processing

---

gcc/rust/backend/rust-compile-extern.h
gcc/rust/backend/rust-compile-intrinsic.cc
gcc/rust/rust-abi.h
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty.h

Add support for some other ABI options.
I was able to test this with linking against some C code but
these options like stdcall seem to be limited to 32 bit mode
```rust
extern "stdcall" {
pub fn test(a: i32) -> i32;
}
extern "C" {
fn printf(s: *const i8, ...);
}
fn main() -> i32 {
unsafe {
let a = 3;
let res = test(a);
let a = "%i\n\0";
let b = a as *const str;
let c = b as *const i8;
printf(c, res);
}
0
}
```
```c
__attribute__ ((stdcall)) int test(int x)  {
return x + 3;
}
```
Compiling like this:
```
$ gccrs -g -O0 -m32 -c test.rs -o test.o
$ gcc -g -O0 -m32 -c lib.c -o lib.o
$ gcc -m32 -o test test.o lib.o
```
More testing will be required over time here but this was
kind of fun to see that it worked.

Add support for choosing other builtin GCC calling conventions

---

gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/typecheck/rust-hir-trait-resolve.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/torture/traits16.rs
gcc/testsuite/rust/compile/torture/traits17.rs
gcc/testsuite/rust/execute/torture/trait3.rs

This adds initial super traits support. Super traits are implemented by
explicitly adding the super trait bound to the implicit Self type parameter
on traits. This will improve as we enhance the type system to handle bounds
and where constraints in general as they reuse all that same code path.
Fixes #565

Super Traits Support

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-extern.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h

When we monomorphize functions we need to check if we have already
generated this function already. All function items have a DefId which is
unique for the crate and HIR item this means for generic implementations
of an item we end up with mappings of:
DefId -> [ (concete-tyty-fntype, GCC::Function), ... ]
So for any function we can lookup for that DefId is there a suitable
version of this function already compiled. This was working untill we have
generic trait items which also need to be handled in the same way.
Fixes #668

Fix bug with monomorphizing of trait items

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/lint/rust-lint-marklive.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/torture/autoderef1.rs

This allows for fat pointers to be used for tuple or struct field access by
supporting the GCC indirect references by binding the type to the reference.
This might get updated when we support the autoderef mechanism and if the
type supports the deref trait.
Addresses #241

Support indirection for struct and tuple field access

---

gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/typecheck/rust-autoderef.h
gcc/rust/typecheck/rust-hir-dot-operator.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/method1.rs
gcc/testsuite/rust/execute/torture/method1.rs

The commit message contains more detail but this reference is good:
https://doc.rust-lang.org/nightly/nomicon/dot-operator.html
This is not 100% complete since we do not yet support operator overloading
so we will require an update to support the Deref operator overload for
more complex types.
Fixes: #241

Initial autoderef support for method calls

---

gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc

By default the forked GCC wrapper from the go front-end was marking
all functions as DECL_UNINLINABLE this changes the behaviour to
allow GCC to decide what can be inlined.
Fixes #547

Allow GCC to decide to inline functions is possible

---

gcc/testsuite/rust/compile/torture/issue-368.rs

It seems this issue was fixed by 58637abaeab1. This added a test case
to close out the issue.
Fixes #368

Add test case to close out generics bug

---

gcc/rust/backend/rust-compile.cc
gcc/testsuite/rust/execute/torture/trait4.rs

When we have a generic function with a specified type bound, this means the
method resolution can only resolve this to the trait item. During code
generation we must then monomorphize this and lookup the associated impl
block item for this trait (if it exists) and call this function.
Fixes #678

Fix bug when calling method from generic reciever type-bound

---

gcc/rust/ast/rust-type.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-type.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve.cc

This adds name resolution and HIR lowering for TraitObjectTypeOneBound
This is the most basic form of dynamic dispatch but all forms derive from
this piece of work.

Building blocks for TraitObject Types

---

gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-stmt.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/typecheck/rust-hir-const-fold.h
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-trait-resolve.cc
gcc/rust/typecheck/rust-hir-trait-resolve.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-type.cc
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty-bounds.cc
gcc/rust/typecheck/rust-tyty-call.h
gcc/rust/typecheck/rust-tyty-cast.h
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty-coercion.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty-visitor.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/traits10.rs
gcc/testsuite/rust/compile/traits11.rs
gcc/testsuite/rust/compile/traits9.rs
gcc/testsuite/rust/compile/tuple_struct3.rs
gcc/testsuite/rust/execute/torture/trait5.rs

This rebases my branch for dynamic dispatch (dyn bound) support it supports
the HIR::TraitObjectOneBound for now but can be easily extended. The computation
of the addresses of the methods only supports impl items and does not support
optional trait methods yet but the change set was already 10 commits and this seems like
a good initial stab at support here.
Please see the git commits for more detail information on each change.
Fixes #197

Initial Dynamic dispatch support

---

gcc/rust/lex/rust-lex.cc
gcc/testsuite/rust/compile/bytecharstring.rs

Fix byte char and byte string lexing code

---

gcc/rust/backend/rust-mangle.cc

With this and that patch applied there are no more warnings building
the rust frontend, so a --enable-bootstrap (-Werror) build completes
successfully.
Fixes #336

Remove warnings from v0_mangle functions in rust-mangle.cc

---

gcc/rust/rust-diagnostics.cc
gcc/rust/rust-diagnostics.h
gcc/rust/rust-gcc-diagnostics.cc
gcc/rust/rust-location.h

... in preparation for a merge from GCC upstream, where we otherwise run into
several different build errors.
Follow-up to commit ed651fcdec170456f7460703edbd0ca5901f0026
"Add basic wrapper over gcc rich_location".

A bit of 'RichLocation' C++ tuning [#247], [#97, #374]

---

gcc/config/i386/i386-rust.c
gcc/rust/rust-session-manager.cc

... in preparation for a merge from GCC upstream, where the former disappear.

x86: Instead of 'TARGET_ISA_[...]', 'TARGET_ISA2_[...]', use 'TARGET_[...]' [#247]

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-item.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/parse/rust-parse-impl.h

Raw strings and raw byte strings are simply different ways to
create string and byte string literals. Only the lexer cares
how those literals are constructed and which escapes are used
to construct them. The parser and hir simply see strings or
byte strings.

Remove raw string and raw byte string references from ast and hir

---

gcc/rust/lex/rust-lex.cc
gcc/testsuite/rust/compile/unicode_escape.rs

There were a couple of issues in the lexer unicode escape code.
Unicode escape sequences must always start with an opening curly
bracket (and end with a closing one). Underscores are not allowed as
starting character. And the produced values must be unicode scalar
values, which excludes surrogate values (D800 to DFFF) or values
larger than 10FFFF.
Also try to recover more gracefully from errors by trying to skip past
any bad characters to the end of the escape sequence.
Test all of the above in a new testcase unicode_escape.rs.
Patch: https://git.sr.ht/~mjw/gccrs/commit/unicode_escape
Mail: https://gcc.gnu.org/pipermail/gcc-rust/2021-October/000231.html

Fix lexer to not produce bad unicode escape values

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/torture/byte_str.rs

Byte strings are not str's they are arrays of [u8; capacity], this
preserves their type guarantees as a byte string.
This patch merges work from Mark to implement the correct typing, the
missing piece was that each implicit type needed its own implicit id, other
wise their is a loop in looking up the covariant types.
Fixes #697
Co-authored-by: Mark Wielaard <mark@klomp.org>

Implement Byte Strings

---

gcc/rust/ast/rust-item.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/parse/rust-parse-impl.h

Location info has been added to AST::TypeBoundWhereClauseItem and HIR::TypeBoundWhereClauseItem. parse_type_bound_where_clause_item () has been modified to fetch location info and store it in AST::TypeBoundWhereClauseItem.
Fixes #766
Signed-off-by: Nirmal Patel <npate012@gmail.com>

Add location info in AST::TypeBoundWhereClauseItem and HIR::TypeBoundWhereClauseItem

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile-stmt.h

Usually, if 'assert'ions are disabled, 'assert' expressions are not evaluated,
so in that case won't effect any side effects.
Via spurious ICEs/test suite FAILs, this may be observed in GCC/Rust, for
example, if configuring with '--enable-checking=no' and disabling a "more
forgiving" 'gcc/system.h:gcc_assert' definition, so that '0 && (EXPR)' gets
used:
/* Use gcc_assert(EXPR) to test invariants.  */
#if ENABLE_ASSERT_CHECKING
#define gcc_assert(EXPR)                                               \
((void)(!(EXPR) ? fancy_abort (__FILE__, __LINE__, __FUNCTION__), 0 : 0))
-#elif (GCC_VERSION >= 4005)
+#elif (0) //GCC_VERSION >= 4005)
#define gcc_assert(EXPR)                                               \
((void)(__builtin_expect (!(EXPR), 0) ? __builtin_unreachable (), 0 : 0))
#else
/* …

No side effects in 'assert' expressions

---

gcc/rust/ast/rust-path.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/rust-ast-lower.cc

This PR will fix <https://github.com/Rust-GCC/gccrs/issues/718>
Note that you can skip the above if you are just opening a WIP PR in
order to get feedback.

Get rid of lambda within `AST::TypePath` and provide a method to return a reference

---

.github/workflows/bootstrap.yml
.github/workflows/ccpp.yml

They will stick around for 90 days (as per GitHub default limits).
https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
Signed-off-by: Ben Boeckel <mathstuf@gmail.com>
Fixes: #634

gha: save `check-rust` results as artifacts

---

gcc/rust/lang.opt
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h

Signed-off-by: Ben Boeckel <mathstuf@gmail.com>
Fixes: #627

gccrs: add the `-frust-crate=` option to set the crate name

---

gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/rust-diagnostics.cc
gcc/rust/rust-diagnostics.h
gcc/rust/rust-gcc-diagnostics.cc
gcc/rust/rust-system.h

... to be used for internal sanity checks, where in case of failure you'd like to provide/print more information than a plain 'rust_assert'.

'rust_internal_error_at'

---

gcc/rust/rust-diagnostics.h
gcc/rust/rust-system.h

... like GCC's underlying 'fatal_error'.
By definition, we cannot continue, upon having run into a fatal error.

Tag 'rust_fatal_error' as 'noreturn'

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-stmt.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-stmt.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/lint/rust-lint-marklive.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tycheck-dump.h
gcc/testsuite/rust/compile/torture/forward_decl_5.rs

This changes the resolution in BlockExpr's to iterate the Items then Stmts
but we might want to handle this by desugaring the HIR BlockExpr to have
items then stmts to ensure we type resolve the items before the stmts.
Fixes #531

Handle forward declared items within blocks

---

.github/workflows/clang-format.yml
CONTRIBUTING.md

Apparently everyone but me knows how to do that; I'm now documenting it for my
own future use.

Running `clang-format` locally [#242]

---

gcc/rust/typecheck/rust-tyty.h
gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-mapping-common.h

DefId was uint64_t previously but it has been changed to be a struct.
In order to reduce code breakage, ==, !=, and < operators have been implemented
for DefId. Since DefId is now a proper struct, bit manipulation code has been
removed with member accesses.
Fixes #439
Signed-off-by: Nirmal Patel <npate012@gmail.com>

Change DefId type from uint64_t to be struct

---

CONTRIBUTING.md

Add note on using git-clang-format and clang-format-diff.py.
Remove the `clang-format` from the required items of PR as it's not enforced
anymore. It's now handled by regular code review.
Refs #242

More help on running clang-format locally

---

gcc/rust/rust-diagnostics.h

clang-format is confused by attribute macros and does a very bad job at
indenting the code.
Changes merged in #779 make all clang-format checks to fail.

Partially disable clang-format in rust-diagnostics.h

---

gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-block.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-extern.h
gcc/rust/backend/rust-compile-fnparam.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-intrinsic.cc
gcc/rust/backend/rust-compile-intrinsic.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile-resolve-path.h
gcc/rust/backend/rust-compile-stmt.h
gcc/rust/backend/rust-compile-struct-field-expr.h
gcc/rust/backend/rust-compile-tyty.h
gcc/rust/backend/rust-compile-var-decl.h
gcc/rust/backend/rust-compile.cc
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-const-fold-ctx.h
gcc/rust/typecheck/rust-hir-const-fold.cc
gcc/rust/typecheck/rust-hir-const-fold.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-tyty.h

As discussed in #412, the Rust front end inherits an abstraction over gcc from the initial bootstrap via GCCGO. 
This is a cool idea, but adds overhead for the primary goal of gcc compiling Rust. It's not clear that the benefits of maintaining the abstraction are worth the potential extra headaches of maintaining it.
I figured for the sake of discussion, I'd draft an initial step towards removing this abstraction. 
The implementations of classes `Bytpe`, `Bexpression`, `Bstatement`, `Bfunction`, and `Bblock` are only wrappers around gcc's GENERIC `tree` structure, with no added functionality. This PR removes them, and changes all the functions for creating and manipulating these abstract types to just use/return `tree` instead. I also deleted a few functions that are vestiges from GCCGO …

Remove Btype, Bexpression, etc. abstractions over gcc trees

---

gcc/rust/Make-lang.in
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-substitution-mapper.cc
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty-call.h
gcc/rust/typecheck/rust-tyty.cc
gcc/testsuite/rust/compile/torture/issue-808.rs

I think we need to research more into how we probe for potential candidates
for method calls. This fixes a few bugs going on in #808 one where the 
canonical path was empty and one where we fail to probe directly on the
receiver of reference types to impl blocks but we must be able to also support
that autoderef means that a receiver's root type might actually be the type we
care about for example a reference to a generic type-parameter and we probe
its bounds for candidates for example. Lets consult the rustc code and references on this.
Fixes #808

Fix MethodCalls for covariant impl blocks

---

.github/workflows/Remark.yml
.remarkrc
CONTRIBUTING.md
README.md

Fixes #487 
Remark.yml contains the workflow, and .remarkrc is the linter's config file. The configurations follow the same ones as shown in the reference repo specified by @philberty in the issue.
The linter works great, and the Test is shown as unsuccessful if a check fails. I also created a PR ( [here](https://github.com/mvvsmk/gccrs/pull/1) )in my fork to test this.  You can check the results out [here.](https://github.com/mvvsmk/gccrs/runs/4126281781?check_suite_focus=true) The test file's name is TEST.md .
Please note that the run mentioned above also shows errors in CONTRIBUTING.md and README.md, which were not part of the commit, but the linter goes over them regardless, as they are part of the Repository.
- There are two files CONTRIBUTING.md and README.md which have a few …

Added Remark markdown automation 

---

gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/resolve/rust-name-resolver.h
gcc/rust/typecheck/rust-hir-type-check-type.cc

The name resolver also created a bunch of duplicates Self::associated_type
paths in the name resolver so associated types paths of this kind could be resolved
at name resolve time.
Addresses #739

Remove implicit paths hack

---

gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/typecheck/rust-hir-type-bounds.h
gcc/rust/typecheck/rust-hir-type-check-type.cc
gcc/testsuite/rust/compile/torture/associated_types1.rs

The first implementation of qualified paths assumed that they only exist
within trait-impl blocks. Trait impl blocks have the same canonical paths
of <type as trait_path>::segment form but this type of path is more generic
than this.
see the commit for more details on the implementation.
Fixes #739

Support QualifiedPathInType's within the same Trait

---

gcc/rust/Make-lang.in
gcc/rust/backend/rust-compile-fnparam.h
gcc/rust/backend/rust-compile-var-decl.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/typecheck/rust-autoderef.h
gcc/rust/typecheck/rust-hir-address-taken.cc
gcc/rust/typecheck/rust-hir-address-taken.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/execute/torture/operator_overload_6.rs

GCC requires VAR_DECL's and PARAM_DECL's to be marked with TREE_ADDRESSABLE
when the declaration will be used in borrow's ('&' getting the address).
This takes into account the implicit addresses when we do autoderef in
method resolution/operator-overloading.
If it is not set we end up in cases like this:
```c
i32 main ()
{
i32 a.1;
i32 D.86;
i32 a;
a = 1;
a.1 = a; // this is wrong
<i32 as AddAssign>::add_assign (&a.1, 2);
D.86 = 0;
return D.86;
}
```
You can see GCC will automatically make a copy of the VAR_DECL resulting bad code-generation.
Fixes #804

Set TREE_ADDRESSABLE when we need to borrow any expression

---

gcc/rust/backend/rust-mangle.cc

In rust the mangling of names needs to handle cases such as qualified paths
<&mut T as Deref>::deref. Assemblers cannot handle '&' and whitespace
otherwise we will fail to assemble the functions, the legacy mangling
scheme turns all reference's '&' into 'RF' and all whitespace into '$'
this means we can mangle more complex canonical paths. Which are needed
in order to support the deref operator overloading.

Update legacy mangling of names

---

gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/resolve/rust-ast-verify-assignee.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/array3.rs
gcc/testsuite/rust/compile/immutable1.rs
gcc/testsuite/rust/compile/immutable2.rs
gcc/testsuite/rust/compile/immutable3.rs
gcc/testsuite/rust/compile/immutable4.rs
gcc/testsuite/rust/compile/immutable5.rs

This was an initial pass to try and ensure all assignments were valid
with respect to the binding mutability. This pass cannot be done at the
name resolution level and in rustc is achieved on mir as part of the borrow
checker. This patch removes this pass and associated test cases.
This set of patches also adds support for indirection around array index
expressions.
Fixes #815

Remove bad mutability check pass

---

gcc/rust/typecheck/rust-hir-dot-operator.h
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc

Rust is permissive about mutablity in type checking for example, if we have
a function:
fn foo(a:&bar) { ... }
fn caller() {
let a:&mut bar = ...;
foo(a);
}
This is valid since the mutable reference to bar is valid to be turned into
an immutable reference without any conversion. Like in C a non-const
pointer is valid to be passed to a const pointer inferface.

Bug fix mutability checks in can_eq for autoderef

---

gcc/rust/typecheck/rust-substitution-mapper.cc

We need to update the type context type with the newly monomorphized types
we guarded against ADT's and functions because they were never added before
though this does not work for generic reference's to ADT's this updates
the check accordingly.

Always update the type context for monoprhized items except type params

---

gcc/rust/typecheck/rust-tyty.h

This is a second cleanup to the generic interfaces in the type system. The
helper for contains type parameters is akin to asking if a type is concrete
or not. If a type is not concrete ie: contains type parameters then this
can be leveraged instead of adding more complexity.
The TyTy::BaseType::is_concrete is already an abstract method forcing
all types to implement it, this makes it much safer and fixes some bad
infinite recursion bugs if we asked if a type contained type-parameters
which in turn somtimes aksed if it was concrete or not which in turn
again called contains_type_parameters. This cleans it all up. More
cleanup to these interfaces can be done over time.

Make TyTy::BaseType::contains_type_parameters non-virtual

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/util/rust-hir-map.h
gcc/testsuite/rust/execute/torture/operator_overload_10.rs
gcc/testsuite/rust/execute/torture/operator_overload_7.rs
gcc/testsuite/rust/execute/torture/operator_overload_8.rs
gcc/testsuite/rust/execute/torture/operator_overload_9.rs

This adds initial support for dereferencing operator overloading. We need to be able
to use this as part of the autoderef cycle next.
It has two default impl's one for '&T' and '&mut T' to apply genericly.
The reason it is interesting is from the prototype the deref lang item
always returns &Self::Target in all cases regardless of mutability, the
lang item here is designed to wrap up any dereference such that when
applied it guarentees the type system you will get back an immutable
reference to something. The reason for doing this is more clear when
thinking about autoderef and method-resolution and how you apply
dereference operations to custom types and a test case is included for
that.
Fixes #809

Deref operator overloading

---

gcc/rust/typecheck/rust-hir-const-fold.cc
gcc/rust/typecheck/rust-hir-const-fold.h
gcc/rust/typecheck/rust-hir-type-check-enumitem.h
gcc/rust/typecheck/rust-hir-type-check.cc

Removed nullptr checking on results from constant folder because when the
result is already error_mark_node, we no longer need to check if the result
is nullptr.
Fixes #692
Signed-off-by: Nirmal Patel <npate012@gmail.com>

Constant folder now returns error_mark_node instead of nullptr

---

gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-item.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-stmt.h

Cleanup constructs like:
```C
struct_decl.iterate ([&] (AST::TupleField &field) mutable -> bool {
... /* do stuff with field */
});
```
For the following AST classes:
- AST::StructStruct
- AST::TupleStruct
- AST::Union
- AST::ArrayElemsValues
Fixes: #714
Fixes: #715
Fixes: #716
Fixes: #720

Cleanup lambdas within some AST types

---

gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty-coercion.h
gcc/rust/typecheck/rust-tyty-rules.h

In the case of an enum where there are more variants than the number of
fields within any variant we end up hitting an out of bounds exception
as we are using the wrong iterator on the fields during type checking.
This also means we were missing all possible fields in the case during
type checking.

Fix out-of-bounds in typechecking of ADTTypes

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile-type.cc
gcc/rust/backend/rust-compile-type.h
gcc/rust/backend/rust-compile.cc
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/torture/enum1.rs

This adds a naieve first pass approach to enum type code generation. The
original idea was to use GCC's QUAL_UNION_TYPE but I have ran into issues
with the DECL_QUALIFIER as my understanding of how this works is incorrect.
This takes an enum such as:
```rust
enum AnEnum {
A,
B,
C (char),
D (x: i64, y: i64),
}
```
And turns this into one big union consisting of all fields as RECORD_TYPES.
```c
union AnEnum {
record A { RUST$ENUM$DISR };
record B { RUST$ENUM$DISR };
record C { RUST$ENUM$DISR, char };
record D { RUST$ENUM$DISR, i64, i64};
}
```
see: https://github.com/bminor/binutils-gdb/blob/527b8861cd472385fa9160a91dd6d65a25c41987/gdb/dwarf2/read.c#L9010-L9241
With the RUST$ENUM$DISR being the first field in all of the records this
means the alignment allows for indirect memory access of …

Add enum code generation

---

gcc/rust/Make-lang.in
gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-pattern.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-pattern.cc
gcc/rust/hir/rust-ast-lower-pattern.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-full-decls.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/resolve/rust-ast-resolve-pattern.cc
gcc/rust/resolve/rust-ast-resolve-pattern.h

This adds the name-resolution and HIR lowering pass for the match-expr
the type checking pass patch needs some work to be split up but these are
two nice isolated commits which are easier to read.

Add name-resolution and HIR lowering pass for MatchExpr

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-macro.h
gcc/rust/ast/rust-path.h
gcc/rust/ast/rust-pattern.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-stmt.h

The AST constructors implicitly generate new NodeId's, their associated
copy/move constructors ensure that they preserve the NodeId correctly.
The AST::Pattern's here incorrectly had a constructor in the abstract
base class which was generating the NodeId's but when this is used
within AST::MatchArms the fields contain these patterns which can get
copied/moved to cause new NodeId's to be generated which then throws off
type checking as the NodeId changes during HIR lowering and thus each of the
ID's are all off by one during type checking.

BugFix NodeId skew on AST::Patterns

---

gcc/rust/backend/rust-compile-fnparam.h
gcc/rust/backend/rust-compile-var-decl.h
gcc/rust/hir/tree/rust-hir-pattern.h

This makes the fields private again and adds the missing getter for the
identifier.

HIR::IdentifierPattern had all fields public

---

gcc/rust/hir/rust-ast-lower-pattern.cc
gcc/rust/hir/rust-ast-lower-pattern.h
gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-hir-map.h

These mappings are missing within the HIR but are required
to complete typechecking of all patterns in match arms. As the
fields of structures must bind their associated field's types to new
names declared as part of the pattern, these mappings give access
to the associated name-resolved NodeId's to figure this out.

Add mssing mappings to HIR::Pattern

---

gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/hir/tree/rust-hir.h

We have a missing locus here, there many places within the HIR where
we are missing location info such as HIR::MatchCase or HIR::MatchArm
come to mind. We also need to raise an issue to track CanonicalPath's and
location info within the TyTy module as part of a new Identifier structure which
will need to be raised in a separate PR+Issue.

Add missing abstract method HIR::Pattern::get_locus() const

---

gcc/rust/Make-lang.in
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-pattern.cc
gcc/rust/backend/rust-compile-pattern.h
gcc/testsuite/rust/execute/torture/match1.rs
gcc/testsuite/rust/execute/torture/match2.rs

This adds in the initial support MatchExpression which allows us to start testing much
more complex rust code. Ideally we can now start targeing the #682 to find nasty bugs
early as possible.
This takes the MatchExpr and generates a SWITCH_EXPR with associated
CASE_LABEL_EXPR's for the variants that the qualifier contains.
To improve this support in order to take advantage of SWITCH_ALL_CASES_P
to add error checking for all cases being covered. This will require changes
to the enum data structure to use ENUMERAL_TYPES instead of the flat i64
so the enumerable type contains the list of all possible permutations.
This patch is the first pass at the MatchExpr as the patch is already pretty
large and serves as a base to move forward.
Fixes #190

Add support for enums on the match expression

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-mangle.cc
gcc/rust/backend/rust-mangle.h
gcc/testsuite/rust/execute/torture/issue-845.rs

Legacy mangling converts the '<', '>' from their canonical paths into '..'
this means we can simply reuse our normal mangle_item code for all types
of symbols. So we can now remove the mangle_impl_item code prior to having
the canonical path code in place.
Fixes #845

HIR::ImplBlock items should mangle based from their canonical path's

---

gcc/rust/util/rust-hir-map.h
gcc/testsuite/rust/execute/torture/operator_overload_11.rs
gcc/testsuite/rust/execute/torture/operator_overload_12.rs

This adds the missing bitwise lang items:
- bitand: libcore/ops/bit.rs
- bitor: libcore/ops/bit.rs
- bitxor: libcore/ops/bit.rs
- shl: libcore/ops/bit.rs
- shr: libcore/ops/bit.rs
- bitand_assign: libcore/ops/bit.rs
- bitor_assign: libcore/ops/bit.rs
- bitxor_assign: libcore/ops/bit.rs
- shl_assign: libcore/ops/bit.rs
- shr_assign: libcore/ops/bit.rs
Addresses #742

Add missing bitwise lang items for operator overloading

---

gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/execute/torture/issue-851.rs

Dataless variants do not contain fields that can be substituted, which then
hits an assertion on access of the fields for the variant. This patch adds
a guard against the substitution of dataless variants. We could have
removed the assertion which would have also been a good fix but keeping the
assertion for now is very helpful in debugging issues.
Fixs #851

Fix ICE in generic subsitution of enums containing dataless variants

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-pattern.cc
gcc/rust/backend/rust-compile-pattern.h
gcc/rust/hir/rust-ast-lower-pattern.cc
gcc/rust/hir/rust-ast-lower-pattern.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-pattern.cc
gcc/rust/typecheck/rust-hir-type-check-pattern.h
gcc/testsuite/rust/execute/torture/match3.rs

GCC CASE_LABEL_EXPR's contain operand 0 and 1, operand 0 is used for the
low value of a case label and operand 1 for a high value. So with this
CASE_LABEL_EXPR is is possible to support a range of values from low->high
if set apropriately, but for the wildcard case this is effectively a
default case which means we set both operand 0 and 1 to NULL_TREE.
Fixes #853

Add support for wildcard patterns within MatchExprs

---

gcc/rust/backend/rust-compile-fnparam.h
gcc/rust/backend/rust-compile-var-decl.h
gcc/rust/hir/rust-ast-lower-pattern.cc
gcc/rust/hir/rust-ast-lower-pattern.h
gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/resolve/rust-ast-resolve-pattern.h
gcc/testsuite/rust/compile/issue-557.rs

Wildcard bindings allow us to bind expression to be unused such as:
let _ = 123;
They are more commonly used in destructuring of tuples such as:
let my_tuple = (1,2);
let (a,_) = my_tuple;
This is the initial basic support for the basic form of let _ = ...; and
it also allows us to ignore parameters within functions as well.
Fixes #557

Add support for Wildcard pattern binding

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-expr.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/typecheck/rust-hir-const-fold.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-tycheck-dump.h
gcc/rust/typecheck/rust-tyty-cast.h
gcc/testsuite/rust/compile/issue-635-1.rs
gcc/testsuite/rust/compile/issue-635-2.rs

This checks that the literal value is within the bounds of their respective
types. I have omitted code fixing the other issue in the bug report that
overflow/max_val integers should be saturated to infinity when cast to
REAL_TYPE's this seems like something we really should have documentation
to reference in the code as to why this is the correct Rust behaviour.
Addresses #635

Add overflow checking on LiteralExpression

---

gcc/rust/ast/rust-expr.h
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile.cc
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/parse/rust-parse-impl.h

Capture the closing locus of a block during parsing, and remove the old
hack to get the final statement locus within the block now that it is
properly tracked.
Fixes #864

Track end locus of BlockExpr

---

gcc/rust/backend/rust-compile-type.cc
gcc/testsuite/rust/compile/torture/struct_decl.rs

When compiling struct and union types, we were using the wrong HirId
to lookup location information. The resulting GIMPLE nodes therefore
had no source location information, which made them indistinguishable
as user-declarations versus decls created by the compiler. As a result,
the type names were not shown in GIMPLE dumps, e.g. using
-fdump-tree-gimple.
Fix the location lookup, so these types are properly printed, and add a
simple test checking as much.
Fixes: #877

Record correct location when compiling ADT types

---

gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir.h

This allows us to safely switch and cast between the items without the
need for visitors.

Add TraitItemKind to HIR TraitItems

---

gcc/rust/typecheck/rust-tyty.h

This changes the Reference and Pointer types to respect the get_name
convention this means the canonical name for functions with their respective
substitutions string is properly formatted.

Covariant types should respect the get_name

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/method1.rs

Use the locus for the method name segment and print its name as part of the
error message improves the quality of the error handling in the method
resolution.
Fixes #861

Improve error message for failure in Method resolution

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-item.h
gcc/rust/ast/rust-type.h
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/util/rust-common.h

This allows us to reuse the same enum and fix the uninitilized warning
as it has already been setup before hand in the AST.
Fixes #875

Extract AsyncConstStatus to be a shared enum between AST and HIR

---

gcc/rust/Make-lang.in
gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-implitem.h
gcc/rust/backend/rust-compile-item.h
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile-resolve-path.h
gcc/rust/backend/rust-compile-var-decl.h
gcc/rust/backend/rust-compile.cc
gcc/rust/typecheck/rust-autoderef.cc
gcc/rust/typecheck/rust-autoderef.h
gcc/rust/typecheck/rust-hir-dot-operator.h
gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
gcc/rust/typecheck/rust-hir-path-probe.h
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-tyty-bounds.cc
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/execute/torture/method2.rs

Method resolution in rust must respect the autoderef cycle by calling into the deref lang items as required. This
allows for method resolution behind boxing for example. See below for an example gimple dump of two levels
of deref operator overloads. The commit message ee794effe3b55d2aa8acc108fb36bd8d05672dfa holds much
more detail on the changes in this patch.
```
void main ()
{
const struct  bar;
const struct  foo;
const i32 foobar;
try
{
bar.0 = 123;
foo.0 = &bar;
RUSTTMP.3 = <Foo as Deref>::deref<&Bar> (&foo);
RUSTTMP.5 = <&T as Deref>::deref<Bar> (RUSTTMP.3);
foobar = Bar::foobar (*RUSTTMP.5);
}
finally
{
bar = {CLOBBER};
foo = {CLOBBER};
}
}
```
Fixes #884

Method resolution should respect deref lang-items

---

gcc/rust/typecheck/rust-tyty.h

We no longer need the tree within the type modules.

Remove unused include

---

gcc/rust/util/rust-hir-map.h

This does not add support for deref_mut lang-items it just adds the mappings
so we can track the lang_item.

Add deref_mut lang_item mappings

---

gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/lang.opt
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h
gcc/testsuite/rust/compile/cfg1.rs
gcc/testsuite/rust/execute/torture/cfg1.rs

This adds the initial support for config expansion on custom config values
it need support for parsing options such as feature=test with apropriate
error handling withing Session::handle_cfg_option(const std::string&).
This also applies the mark_for_strip checks only on AST::Functions and
will need applied to the rest of the crate in #872.
Addresses #889

Add -frust-cfg=value option for adding config options

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-mangle.cc
gcc/rust/backend/rust-mangle.h
gcc/rust/resolve/rust-ast-resolve-base.h
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-pattern.cc
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/rust/resolve/rust-ast-resolve-struct-expr-field.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/resolve/rust-name-resolver.h
gcc/rust/rust-session-manager.cc
gcc/rust/util/rust-canonical-path.h
gcc/testsuite/rust/compile/canonical_paths1.rs
gcc/testsuite/rust/compile/torture/mod3.rs
gcc/testsuite/rust/compile/traits9.rs

The name resolver there are two types of canonical-path object.
1. The relative canonical path to a type for name resolution
2. The full canonical-path including the crate-name (this-was-missing)
The lack of the crate-name being present in the canonical-path meant the
symbol mangling system was required to append it where appropriate but this
was going to be too messy to handle all cases. Such as module blocks
containing impl blocks requires a ```prefix::<impl crate::path>::item``` and
similarly for trait impl blocks.

Update name-resolution to build up canonical-path with the crate-name

---

gcc/rust/resolve/rust-ast-resolve-item.h

Impl blocks canonical prefix when the size is one will only contain the
respective crate name but impl blocks canonical path will be of the Self
type which has its own respective crate and path so this will become the
canonical path of this. If the segment size greater than one this means it
is likely inside a mod block or other item so this means we should just
append as usual.

Fixup logic in canonical-path for impl-blocks

---

gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/testsuite/rust/execute/torture/cfg2.rs
gcc/testsuite/rust/execute/torture/cfg3.rs

We need to apply this to all levels of the crate:
Item
types
impl-item
trait-item
Stmt
expr's
Fixes #872

Apply the is_marked_for_strip check to the rest of the crate

---

gcc/rust/backend/rust-compile-type.cc
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-enumitem.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-type.cc
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-tyty-cast.h
gcc/rust/typecheck/rust-tyty-coercion.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/rust/util/rust-identifier.h
gcc/testsuite/rust/compile/torture/struct_decl.rs

This refactors our TyTy type abstractions to contain their repspective
canonical-path and location info. This cleans up alot of location tracking
for example when we have generic structures we create implicit hirids which
may or may not have location info this now tracks the location info of
the declaration of the type avoiding any confustion.

Add new RustIdent struct to track canonical-path and location info

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-macro.h
gcc/testsuite/rust/compile/cfg2.rs
gcc/testsuite/rust/compile/cfg3.rs
gcc/testsuite/rust/compile/cfg4.rs
gcc/testsuite/rust/execute/torture/cfg4.rs

Config expansion can be not, any, or all predicate to enforce the config
expansion logic.
This patch refactors the MacroParser to be named AttributeParser as it is
only used to parse attributes into MetaItems that we can work with and
do expansion logic upon. This handles the case of parsing the
inner-meta-item of not(A) to parse it into MetaListNameValueStr and tidies
up some of the code in the area.
Fixes #901

Support cfg expansions predicates

---

gcc/c-family/c-common.cc
gcc/c-family/c-common.h
gcc/diagnostic.cc
gcc/opt-problem.cc
gcc/rust/Make-lang.in
gcc/rust/rust-lang.cc
gcc/selftest-run-tests.cc
gcc/selftest.h

From what I can understand, self tests seem to only be used in the C family of languages and in no other gcc frontend. And for some reason one of the self test for the gccrs frontend seem to be the parsing of C code and C types, which fails, which is why this PR is a draft. Once this is fixed, selftests should be enabled for the frontend and we should be able to add some to the project.

Enable the usage of selftests

---

gcc/rust/typecheck/rust-hir-type-check-pattern.cc
gcc/testsuite/rust/compile/match5.rs

It's alread now diagnosed, non-fatal warning:
[...]/source-gcc/gcc/rust/typecheck/rust-hir-type-check-pattern.cc: In member function ‘virtual void Rust::Resolver::TypeCheckPattern::visit(Rust::HIR::TupleStructPattern&)’:
[...]/source-gcc/gcc/rust/typecheck/rust-hir-type-check-pattern.cc:61:69: warning: unquoted operator ‘::’ in format [-Wformat-diag]
61 |         "expected tuple struct or tuple variant, found %s variant %s::%s",
|                                                                     ^~
A later merge from GCC upstream will bring in
commit 34ba4275dcf5162efb9b634e4665734766faf4e3
"Enable -Werror=format-diag during bootstrap", which then causes:
[...]/source-gcc/gcc/rust/typecheck/rust-hir-type-check-pattern.cc: In member function ‘virtual void …

Fix '-Wformat-diag' issue in 'TypeCheckPattern::visit (HIR::TupleStructPattern &pattern)'

---

gcc/rust/ast/rust-expr.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/parse/rust-parse-impl.h

Fixes #863
- Added location data to Match arm in gcc/rust/ast/rust-expr.h and gcc/rust/hir/tree/rust-hir-expr.h
- Updated the respective constructors and copy constructors
- Updated location info for match arm in code generation in gcc/rust/backend/eust-compile-expr.cc
- Removed unused code in the above rust-expr.h and rust-gir-expr.h files as mentioned in the issue by @philberty.
- Comment removed form rust-expr.h
- Changed partameterized constructor and static function in
rust-hir-expr.h
- Changed line 697 to pass expr.get_locus() in rust-ast-lower
- Changed parameterised constructor in rust-expr.h
- Changed line 8563 in rust-parse-impl.h to pass location data.
Note :
- I also added a public member funtion for the class MatchArm
`Location get_locus ( ) const { return locus; }`
Do me …

Added location data to Match Arm and removed unused code

---

gcc/rust/rust-session-manager.cc
gcc/testsuite/rust/compile/cfg5.rs

This adds in a basic parser to parse out key value pairs for the config
option it needs to be tested poperly once the self-test framework is
merged in.
Fixes #889

Add support for key = value pairs on -frust-cfg=

---

gcc/rust/typecheck/rust-hir-type-check-path.cc
gcc/rust/typecheck/rust-substitution-mapper.cc
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/torture/issue-893-2.rs
gcc/testsuite/rust/compile/torture/issue-893.rs

In this bug the path expression failed to take Foo::<i32> and apply this
bound generic argument into the impl block. The fn type for this function
test is:
fn <T,Y>test(a:T, b:Y);
But the impl block has a Self of Foo<T> so we need to inherit the T
argument from the previous Foo::<i32> which was missing.
Fixes #893

Handle generic substitution on path expressions

---

gcc/rust/backend/rust-compile-base.cc
gcc/rust/backend/rust-compile-base.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/testsuite/rust/compile/inline_1.rs
gcc/testsuite/rust/compile/inline_2.rs

This maps over to DECL_UNINLINEABLE and to use the GCC attribute
always_inline.
Fixes #921

Support inline never and always options

---

gcc/testsuite/rust/compile/macro1.rs
gcc/testsuite/rust/compile/macro2.rs
gcc/testsuite/rust/compile/macro3.rs
gcc/testsuite/rust/compile/macro4.rs
gcc/testsuite/rust/compile/macro5.rs
gcc/testsuite/rust/execute/xfail/macro1.rs
gcc/testsuite/rust/execute/xfail/macro2.rs
gcc/testsuite/rust/execute/xfail/macro3.rs

This PR adds test cases for macros, including parsing and execution.
I am unsure on how to check for proper execution: The solution I have chosen so far is to make sure that a correct amount of lines is printed, which I'm not entirely satisfied with. 
Another solution would be to increase a global integer to use when exiting, which we can then assert on using dejagnu, which is cleaner but relies on unsafe rust code.

macros: Add multiple macro syntax tests

---

gcc/rust/rust-session-manager.cc

Removes a warning generated by `-Wformat-diag`

rust-cfg: Quote option name when erroring out

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-macro.h
gcc/rust/parse/rust-parse-impl.h

Closes #928 
This adds location to the all child classes of the `MacroMatch` abstract class. The current locations are as follow, which I believe is what is expected but might be wrong.
```rust
test.rs:2:6: error: macro match fragment
2 |     ($a:expr, $b:expr) => { $a + $b };
|      ^
test.rs:2:15: error: macro match fragment
2 |     ($a:expr, $b:expr) => { $a + $b };
|               ^
test.rs:2:5: error: macro matcher
2 |     ($a:expr, $b:expr) => { $a + $b };
|     ^
test.rs:3:8: error: macro match fragment
3 |     ($($i:ident)*) => { $($i)* }
|        ^
test.rs:3:17: error: macro match repetition!
3 |     ($($i:ident)*) => { $($i)* }
|                 ^
test.rs:3:5: error: macro matcher
3 |     ($($i:ident)*) => { $($i)* }
|     ^
```
I think this should be rebased on #932 so that I …

macromatch: Add location to abstract MacroMatch class

---

Dockerfile

dockerfile: Install cargo-gccrs alongside gccrs

---

gcc/rust/ast/rust-macro.h
gcc/rust/parse/rust-parse-impl.h

Closes #929 
Adds location info to the macro's transcriber. When generating a `MacroRule` error, this PR creates an empty location for the transcriber, since the error function is only called if no fat arrow is present or if there was an error parsing the macro's matcher. Please let me know if this is the expected behavior

macrotranscriber: Add location info

---

gcc/rust/ast/rust-macro.h
gcc/rust/parse/rust-parse-impl.h

Closes #930 
This PR adds location information to the `MacroRule` structure.
The location is from the beginning of the invokation pattern, so that errors look like so:
```rust
test.rs:2:5: error: ...
2 |     ($a:expr, $b:expr) => { a + b }
|     ^
```

Add location information to MacroRule

---

gcc/rust/Make-lang.in
gcc/rust/parse/rust-cfg-parser.cc
gcc/rust/parse/rust-cfg-parser.h
gcc/rust/parse/rust-parse.cc
gcc/rust/rust-lang.cc
gcc/rust/rust-session-manager.cc
gcc/testsuite/rust/compile/cfg5.rs

Closes #910 
This PR separates the `handle_cfg_option()` function in two, separating the parsing logic from the session logic. The parsing logic is able to be unit tested, and now only allows quoted values.
What remains to be done is to only allow `key` and `value` to be proper rust identifiers. We need to figure out if we'd like to spawn a parser here and parse identifiers, or simply sanitize both strings to make sure they do not contain invalid characters.

frust-cfg: Only allow double quoted values

---

gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-item.h
gcc/rust/ast/rust-path.h
gcc/rust/ast/rust-pattern.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/rust/resolve/rust-ast-resolve.cc

Two classes still remain locus-less: `TupleStructItems` and `TuplePatternItems` as I do not believe they are constructed at the moment.

Add more location info to AST structures

---

gcc/rust/ast/rust-path.h
gcc/rust/hir/rust-ast-lower.cc

Addresses issue #717 
1) Changed the rust-path.h and removed the iterate_path_segments
fuction.
2) Removed the lambda fuction form rust-ast-lower.cc and replaced it
with a for loop.
Do let me know if I missed anything or could improve on something.
Signed-off-by : M V V S Manoj Kumar <mvvsmanojkumar@gmail.com>

 Removed Lambda Function within AST::PathPattern

---

gcc/rust/Make-lang.in
gcc/rust/expand/rust-macro-expand.h
gcc/rust/expand/rust-macro-invoc-lexer.cc
gcc/rust/expand/rust-macro-invoc-lexer.h

macro-invoc-lexer: Split implementation in its own file

---

gcc/rust/ast/rust-ast.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/testsuite/rust/execute/torture/macros10.rs
gcc/testsuite/rust/execute/torture/macros11.rs
gcc/testsuite/rust/execute/torture/macros12.rs
gcc/testsuite/rust/execute/torture/macros13.rs
gcc/testsuite/rust/execute/torture/macros14.rs

Needs #955 
This PR splits up the `substitute_tokens` function into multiple smaller functions. Still a draft until I can get repetitions working.
Closes #960 
Closes #961

Substitute repetitions

---

gcc/rust/backend/rust-compile-type.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

Fixes #734 
Done :
Solution 1
1) Created a new get_params function which returns the parameters.
2) Changed the references of the iterate_params to use get_params.
Solution 2
1) Added get_params2 which returns `std::vector<TyTy::BaseType*>`
2) Changed the references of the iterate_params to use get_params.
Status :  
Currently I have implemented the first solution. 
Signed-off-by : M V V S Manoj Kumar <mvvsmanojkumar@gmail.com>

Implimented Soluion 1 and solution 2 for issue_734

---

gcc/rust/Make-lang.in
gcc/rust/backend/rust-compile-base.cc
gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-stmt.h
gcc/rust/backend/rust-compile.cc
gcc/rust/backend/rust-constexpr.cc
gcc/rust/backend/rust-tree.cc
gcc/rust/backend/rust-tree.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/lang.opt
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/util/rust-attributes.cc
gcc/testsuite/rust/compile/torture/must_use1.rs
gcc/testsuite/rust/compile/torture/must_use2.rs

This is a port of the CPP front-end nodiscard attribute to be used for
must_use. It contains a patch to clean up how we handle expressions vs
statements and removes more of the GCC abstraction. Its my hope that we
can leverage more and more existing code to get the static analysis where
we want it.
Fixes #856

Add must use attribute support

---

gcc/rust/ast/rust-ast-full-decls.h
gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast-visitor.h
gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-item.h
gcc/rust/ast/rust-macro.h
gcc/rust/ast/rust-stmt.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/rust/hir/rust-ast-lower-base.h
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/rust/resolve/rust-ast-resolve-base.h
gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h

When parsing a macro invocation as a statement, the parser would parse
an expression and then try parsing a semicolon. Since no actual
lookahead was done (which is a good thing), we couldn't convert a
`MacroInvocation` to a `MacroInvocationSemi` after the fact.
Since, unlike function calls, macro invocations can act differently
based on whether or not they are followed by a semicolon, we actually
need to differentiate between the two up until expansion.
This commits adds a new virtual method for ExprWithoutBlock when
converting to ExprStmtWithoutBlock so that classes inheriting
ExprWithoutBlock can specify a new behavior. In the case of our
MacroInvocation class, it simply means toggling a boolean: If we're
converting a macro from an expression to a statement, it must mean that
it should …

Parse macro!(); as MacroInvocation with semicolon

---

gcc/rust/expand/rust-macro-substitute-ctx.cc
gcc/testsuite/rust/execute/torture/macros16.rs
gcc/testsuite/rust/execute/torture/macros17.rs
gcc/testsuite/rust/execute/torture/macros18.rs

Closes #982 
We can now do fancy lispy things!
```rust
macro_rules! add {
($e:literal) => {
0 + $e
};
($e:literal $($es:literal)*) => {
$e + add!($($es)*)
};
}
```
I've switched the order of the commits around so that the buildbot is happy

Fix ICE on recursive macro invocation

---

gcc/rust/ast/rust-macro.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/rust/expand/rust-macro-substitute-ctx.cc
gcc/rust/expand/rust-macro-substitute-ctx.h
gcc/testsuite/rust/compile/macro9.rs
gcc/testsuite/rust/execute/torture/macros16.rs
gcc/testsuite/rust/execute/torture/macros17.rs
gcc/testsuite/rust/execute/torture/macros18.rs
gcc/testsuite/rust/execute/torture/macros19.rs
gcc/testsuite/rust/execute/torture/macros20.rs

More nice recursive macros:
```rust
macro_rules! add {
($e:expr | $($es:expr) | *) => {
$e + add!($($es) | *)
};
($e:expr) => {
$e
};
}
add!(1 | 2 | 3 | 4 | 5 | 6);
```
Closes #968
This PR needs #986 to be merged first, as it depends on it for the test cases. You can skip reviewing the first two commits which are just from #986

Match and expand macro separators properly

---

gcc/rust/ast/rust-item.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/testsuite/rust/compile/abi-options1.rs

This is a refactor to cleanup HIR::ExternBlock and HIR::FunctionQualifiers
to have an enum of ABI options to improve the error handling.

Refactor ABI options as part of HIR function qualifiers

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-macro.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/resolve/rust-ast-resolve-expr.cc
gcc/rust/resolve/rust-ast-resolve-expr.h
gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/testsuite/rust/compile/macro11.rs
gcc/testsuite/rust/compile/macro12.rs
gcc/testsuite/rust/compile/macro13.rs
gcc/testsuite/rust/compile/macro14.rs
gcc/testsuite/rust/compile/macro15.rs
gcc/testsuite/rust/compile/macro6.rs
gcc/testsuite/rust/compile/macro7.rs
gcc/testsuite/rust/compile/macro8.rs
gcc/testsuite/rust/execute/torture/macros11.rs
gcc/testsuite/rust/execute/torture/macros17.rs
gcc/testsuite/rust/execute/torture/macros2.rs
gcc/testsuite/rust/execute/torture/macros22.rs
gcc/testsuite/rust/execute/torture/macros3.rs
gcc/testsuite/rust/execute/torture/macros7.rs
gcc/testsuite/rust/execute/torture/macros8.rs
gcc/testsuite/rust/execute/torture/macros9.rs

This PR adds a base for trying to parse statements or items in macro invocations. We are now able to parse multiple items / expressions / statements properly, but do not lower them properly, which is the last remaining task in #943 
New macro parsing logic:
```mermaid
flowchart TD;
has_semi -- Yes --> stmt;
has_semi -- No --> invocation;
invocation -- Is Parens --> expr;
invocation -- Is Square --> expr;
invocation -- Is Curly --> stmt;
```
Closes #943 
Closes #959 
Closes #952

Parse macro expansion properly

---

gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/rust/expand/rust-macro-substitute-ctx.cc
gcc/rust/expand/rust-macro-substitute-ctx.h

Adds an extra layer of abstraction around keeping multiple matches for
the same fragment. This avoids ugly code fetching the first match in
order to get the amounf of matches given by the user, while still
allowing zero-matches to exist.

macros: Add abstraction around multiple matches

---

gcc/rust/backend/rust-compile-fnparam.h
gcc/rust/backend/rust-compile-intrinsic.cc
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-tree.cc
gcc/rust/backend/rust-tree.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/resolve/rust-ast-resolve-type.cc
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-ast-resolve.cc
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/testsuite/rust/compile/never_type_err2.rs

This patch series implements:
1. offset
2. size_of
3. unreachable
4. abort
It removes the GCC wrapper mappings to make them much easier to implement. It also demonstrates in single commits
the implementation of each of these intrinsic to make it easy to follow in how we implement them.
Addresses #658 #849

Add more intrinsics and refactor how we implement them

---

gcc/rust/resolve/rust-ast-resolve-type.cc
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/testsuite/rust/compile/issue-1005.rs

This is part of my patch series for slices. This adds the missing visitors
for name canonicalization. More information in the patch, once we get
slice support in we need to start taking advantage of @dkm's HIR
visitor refactoring to avoid these issues with missing visitors making
simple bugs hard to track down.
Fixes #1005

Add missing canonicalization of slices and raw pointer types

---

gcc/rust/util/rust-lang-item.h

In order to support slices, we need to be able to parse and contain
mappings for the const_ptr lang item. We do not need to do any
special handling of this lang item yet but this adds the mappings
so when we hit it we do not output an unknown lang item error.
Addresses #849

Add const_ptr lang item mappings

---

gcc/rust/hir/tree/rust-hir-type.h
gcc/rust/typecheck/rust-hir-type-check-type.cc
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

This adds in the missing type resolution for slices and generic slices
and arrays. Since Arrays and Slices are both covariant types just like
references and pointers for example they need to handle recursive
substitutions where their element type might be a generic type
that can bind substitution parameters such as functions and ADT's.
Addresses #849

Add missing type resolution to slices and arrays

---

gcc/rust/backend/rust-compile-type.cc
gcc/testsuite/rust/execute/torture/slice1.rs

This type must respect the layout of the FatPtr type in libcore. Rust
implements slices using Rustc types in libcore and uses a neat trick.
Addresses #849

Add code generation for the slice type

---

gcc/rust/expand/rust-macro-builtins.h

@mvvsmk you might find this a little more clear. Sorry about the confusion!

builtin-macros: Add more documentation for defining builtins

---

gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/testsuite/rust/compile/macro17.rs

We need to limit the amount of times that macro get expanded recursively
during macro-expansion. This limits the amount of times an ASTFragment
can be visited by simply incrementing the depth when setting a fragment,
and decreasing it when taking one. This way, recursive expansion which
happens at the expansion level (instead of the matching level) will
still get caught
Fixes #1012

macros: Do not try and re-expand if depth has exceeded recursion limit

---

gcc/rust/Make-lang.in
gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-trait-resolve.h
gcc/rust/typecheck/rust-hir-type-check-base.cc
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check-type.cc
gcc/rust/typecheck/rust-hir-type-check-type.h
gcc/rust/typecheck/rust-tyty-bounds.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/issue-1019.rs
gcc/testsuite/rust/compile/traits12.rs

This is a series of patches that were all required to fix this issue. We
now take advantage of our substitutions abstractions and traits
so that our TypeBoundPredicate's which form the basis of our HRTB code
I think this class is almost akin to rustc existential-trait-references. This now
reuses the same code path to give us the same error checking for generics
as we get with ADT's, functions etc.
With this refactoring in place we can then reuse the abstractions to map the
ID's from the used arguments in the type-bound-predicate, the impl block type
substation mappings and the self type itself.
There are quite a few cases to handle and our testsuite picked up all the regressions
so no behaviour of our existing test-cases have changed now. See each commit for
more detailed information. …

Rewrite our unconstrained type-param error checking

---

gcc/rust/ast/rust-ast.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/testsuite/rust/compile/xfail/slice1.rs

This commit fixes the issue reported in #391, but highlights another
one, which will be reported.
Closes #391

attribute expansion: Fix spurious stripping of tail expression

---

gcc/rust/typecheck/rust-tyty-cmp.h
gcc/testsuite/rust/compile/issue-1031.rs

When we perform method resolution we check if the self arguments can be
matched. Here the bug was that pointer types had a bad vistitor and only
could ever match reference types which is wrong and was a copy paste error.
Fixes #1031
Addresses #849

Fix bad copy-paste in can equal interface for pointer types

---

gcc/rust/expand/rust-macro-expand.cc
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/compile/macro18.rs
gcc/testsuite/rust/compile/macro19.rs
gcc/testsuite/rust/compile/macro9.rs

In certain cases such as macro matching or macro expansion, it is
important to allow the parser to return a valid statement even if no
closing semicolon is given. This commit adds an optional parameter to
the concerned functions to allow a lack of semicolon those special cases
Closes #1011 
Closes #1010

parser: Allow parsing stmts without closing semicolon

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-macro.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/hir/rust-ast-lower.cc
gcc/testsuite/rust/compile/macro16.rs

Closes #1001 
This PR adds a base for adding node information to our AST types. It can be used when requiring to differentiate between multiple kinds of nodes, while not necessarily wanting to do a full static cast. This will open up a lot of cleanup issues and good first issues for Project Pineapple

Add AST kind information

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty.cc
gcc/testsuite/rust/compile/issue-1034.rs

When we setup trait-impls the type-alias are allowed to become any type
this interface was missing a visitor. We also need to support constraining
type-parameters behind slices.
The get_root interface is currently unsafe, it needs a flag for allowing
unsized and for keeping a map of adjustments along the way. This will
be added down the line when we support unsized method resolution.
Fixes #1034
Addresses #849

Support placeholders becoming slices

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-macro.h
gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/expand/rust-attribute-visitor.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/compile/macro20.rs
gcc/testsuite/rust/compile/macro21.rs
gcc/testsuite/rust/compile/macro22.rs
gcc/testsuite/rust/compile/macro23.rs
gcc/testsuite/rust/execute/torture/macros23.rs

Needs #1028 
You can just review the last commit to avoid reviewing twice. Sorry about that!

Macro in trait impl

---

gcc/rust/parse/rust-parse-impl.h

Per the reference, macro fragments actually accept all identifiers, not
NON_KEYWORD_IDENTIFIERS
Fixes #1013

Parse reserved keywords as valid fragments identifiers

---

gcc/rust/expand/rust-macro-expand.cc
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/compile/macro25.rs
gcc/testsuite/rust/compile/macro9.rs

Since parsing repetitions is very eager, the parser might accumulate
bogus errors by trying to match more repetitions than there are. We can
avoid this by clearing the parsing errors if parsing repetitions
returned a valid result. This should not be an issue for previous
matchers erroring out, as they would immediately return upon failure and
not reach inside other match functions.
We need to figure out the best way to emit parser errors, as we do not always want to emit them in `match_fragment`. I think for now the easiest is to just *not* emit parse errors and simply error out with "failed to match macro rule". We will need to think about adding a bunch of hints too in order to make using macros easier.
Fixes #958

Do not propagate parse errors in match repetitions

---

gcc/rust/expand/rust-macro-substitute-ctx.cc
gcc/rust/expand/rust-macro-substitute-ctx.h
gcc/testsuite/rust/compile/macro26.rs
gcc/testsuite/rust/execute/torture/macros24.rs

macros: Only expand merged repetitions if they contain the same amount

---

gcc/rust/expand/rust-macro-expand.cc

Since this is less noisy, I guess we can keep it in at all times instead
of commenting it. Doing it like so - through a single function call -
means that we avoid creating the string entirely in release builds
Fixes #967

Add helper debugging function for substituted tokens

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-macro.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.cc
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/compile/macro27.rs
gcc/testsuite/rust/compile/macro28.rs
gcc/testsuite/rust/compile/macro29.rs
gcc/testsuite/rust/compile/macro30.rs
gcc/testsuite/rust/compile/macro31.rs
gcc/testsuite/rust/execute/torture/macros20.rs

This adds a base for respecting the [Macro Follow-Set Ambiguity specification](https://doc.rust-lang.org/reference/macro-ambiguity.html).
If the design is validated, adding more restrictions on other fragment specifiers should not be difficult
Addresses #947

Restrict follow-up tokens on `expr` and `stmt`

---

gcc/rust/expand/rust-macro-expand.cc
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/compile/macro18.rs
gcc/testsuite/rust/compile/macro32.rs

When parsing macro invocations, rustc does not actually consume the
statement's trailing semicolon.
Let's take the following example:
```rust
macro_rules! one_stmt {
($s:stmt) => {};
}
macro_rules! one_or_more_stmt {
($($s:stmt)*) => {};
}
one_stmt!(let a = 1);
one_stmt!(let b = 2;); // error
one_or_more_stmt!(;); // valid
one_or_more_stmt!(let a = 15;); // valid, two statements!
one_or_more_stmt!(let a = 15 let b = 13); // valid, two statements again
```
A semicolon can count as a valid empty statement, but cannot be part of
a statement (in macro invocations). This commit adds more restrictions
that allow the parser to not always expect a semicolon token after the
statement. Furthermore, this fixes a test that was previously accepted
by the compiler but not by rustc.
Fixes #1046

Add better restrictions around semicolons in statements

---

gcc/rust/parse/rust-parse-impl.h

... recently introduced in #1044 commit 35ca685200830626e5abd623f65a850649beace2
"macros: Add base functions to check for follow-set ambiguities".
GCC doesn't like that:
In file included from [...]
./mm_malloc.h:42:12: error: attempt to use poisoned "malloc"
return malloc (__size);
^
See commit e7b3f654f2ab0400c95c0517387a9ad645a5c4cd, for example.

Fix '#include <algorithm>' [#159]

---

gcc/rust/ast/rust-macro.h

... recently introduced in #1044 commit 35ca685200830626e5abd623f65a850649beace2
"macros: Add base functions to check for follow-set ambiguities".
Otherwise, at least with an oldish GCC 5.2, compilation of
'gcc/rust/parse/rust-parse.cc' fails noisily:
In file included from [GCC]/i686-pc-linux-gnu/include/c++/5.2.0/bits/hashtable.h:35:0,
from [GCC]/i686-pc-linux-gnu/include/c++/5.2.0/unordered_map:47,
from [GCC/Rust]/gcc/rust/rust-system.h:46,
from [GCC/Rust]/gcc/rust/rust-linemap.h:12,
from [GCC/Rust]/gcc/rust/lex/rust-lex.h:22,
from [GCC/Rust]/gcc/rust/parse/rust-parse.h:20,
from [GCC/Rust]/gcc/rust/parse/rust-parse.cc:17:
[GCC]/i686-pc-linux-gnu/include/c++/5.2.0/bits/hashtable_policy.h: In instantiation of 'struct std::__detail::__is_noexcept_hash<Rust::AST::MacroFragSpec::Kind, …

For use as 'std::unordered_map' key, provide 'std::hash' for 'Rust::AST::MacroFragSpec::Kind' enum class

---

gcc/rust/ast/rust-macro.h
gcc/rust/lex/rust-token.h
gcc/rust/parse/rust-parse.cc
gcc/testsuite/rust/compile/macro33.rs
gcc/testsuite/rust/compile/macro34.rs
gcc/testsuite/rust/compile/macro35.rs
gcc/testsuite/rust/compile/macro36.rs

Adds the remaining restrictions for follow-set ambiguities in macros.
This means adding the remaining allowed tokens for all fragment
specifiers with follow-up restrictions, as well as handling allowed
fragment specifiers in certain cases. For example, :vis specifiers can
sometimes be followed by fragments, if they have the :ident, :ty or
:path specifier. Likewise for :path and :ty which can be followed by a
:block.
Finally, we also allow *any* fragment after a matcher: Since the matcher
is delimiter by parentheses, brackets or curlies, anything is allowed
afterwards.
Some edge cases or allowed tokens that we cannot handle yet remain, for which FIXMEs exist. I'll open up corresponding issues. 
Addresses #947

macros: Add remaining restrictions for follow-set restrictions

---

gcc/rust/parse/rust-parse.cc
gcc/testsuite/rust/compile/macro-issue1053-2.rs
gcc/testsuite/rust/compile/macro-issue1053.rs
gcc/testsuite/rust/compile/macro28.rs

When checking if a follow-up is valid, we previously always returned
false when comparing with MacroMatchRepetitions. This is however
invalid, as we should be comparing with the first match of the
repetition to be sure.
Closes #1053 
Addresses #947

Fix overzealous follow set ambiguity

---

gcc/rust/expand/rust-macro-builtins.cc
gcc/rust/expand/rust-macro-builtins.h
gcc/rust/util/rust-hir-map.cc
gcc/testsuite/rust/compile/builtin_macro_include_bytes.rs
gcc/testsuite/rust/compile/builtin_macro_include_str.rs
gcc/testsuite/rust/execute/torture/builtin_macro_include_bytes.rs
gcc/testsuite/rust/execute/torture/builtin_macro_include_str.rs
gcc/testsuite/rust/execute/torture/include.txt

Implement the include_bytes! and include_str! builtin macros.
Addresses:  #927

implement include_bytes! and include_str! macros

---

gcc/rust/expand/rust-macro-expand.cc
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/execute/torture/macros25.rs
gcc/testsuite/rust/execute/torture/macros26.rs

:tt fragments stand for token trees, and are composed of either a token,
or a delimited token tree, which is a token tree surrounded by
delimiters (parentheses, curly brackets or square brackets).
This should allow us to handle a lot more macros, including extremely
powerful macro patterns such as TT munchers

Handle :tt fragments properly

---

gcc/rust/ast/rust-macro.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.cc
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/compile/macro37.rs
gcc/testsuite/rust/compile/macro38.rs

When trying to figure out if a match can follow another, we must figure
out whether or not that match is in the follow-set of the other. If that
match is zeroable (i.e a repetition using the * or ? kleene operators),
then we must be able to check the match after them: should our current
match not be present, the match after must be part of the follow-set.
This commits allows us to performs such checks properly and to "look
past" zeroable matches. This is not done with any lookahead, simply by
keeping a list of pointers to possible previous matches and checking all
of them for ambiguities.
Addresses #947 
Closes #947

Allow keeping list of last matches to check against

---

gcc/rust/ast/rust-expr.h
gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/expand/rust-attribute-visitor.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/execute/torture/cfg5.rs
gcc/testsuite/rust/execute/torture/macros27.rs

This expands :meta fragments properly and allows us to strip assignment expressions

Handle :meta fragments properly

---

gcc/rust/ast/rust-ast.h
gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/testsuite/rust/compile/macro40.rs
gcc/testsuite/rust/execute/torture/macros28.rs

Closes #1067 
This highlighted two issues where parsing types is not entirely correct, which I'll raise. The code necessary to handle macro invocations in these two places should already be implemented.

Handle macro invocations in type contexts

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-macro.h
gcc/rust/expand/rust-macro-builtins.cc
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/testsuite/rust/compile/macro41.rs

When expanding AST fragments containing multiple nodes, we must be aware
that some cases allow expanding zero or more nodes. Any macro
transcription that gets parsed as many nodes (ie any transcriber function that calls `parse_many`) needs to be able to parse zero of those nodes and still get expanded properly (basically, removed).
Previously, this would cause a failure to lower the macro invocation which would remain as a child instead of getting stripped/erased.

Allow transcribing of zero nodes in certain cases

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/rust-session-manager.cc

- Fixed `-frust-crate= option` got incorrectly overridden by a default value (`example`)
- Fix a minor typo in `gcc/rust/ast/rust-ast-full-test.cc`

bugfix: fix several minor issues

---

gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-item.cc
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/testsuite/rust/compile/torture/arrays5.rs
gcc/testsuite/rust/compile/torture/arrays6.rs

This PR changes how we compile initializers for arrays of repeating elements. I use the same approach outlined in the comments of the linked issue, with some tweaks. It is very similar to how the D language front-end compiles, the new function `Gcc_backend::array_initializer` is heavily inspired by the D front-end's `build_array_set`
This fixes the issue where the compiler tries to allocate a vec containing all elements of the array to be constructed, and therefore explodes on huge constructions (e.g. `let x = [0u8; 4 * 1024 * 1024 * 1024 * 1024]`)
However, we can only initialize non-const arrays in this way. For arrays in const contexts we must initialize them at compile time, and therefore continue using the old method.
Fixes: #1068

Use loop to initialize repeat arrays

---

gcc/rust/Make-lang.in

When building gccrs with Buildroot toolchain infrastructure, the gccrs
compiler driver is missing when intalling gcc.
This is due to missing depedency on gccrs$(exeext) in rust.all.cross
target.
With that fixed, the gcc toolchain with Rust support is correctly installed into Buildroot:
$ ./test/gccrs/host/bin/aarch64-linux-gccrs --version
aarch64-linux-gccrs (Buildroot 2022.02-442-g54d638fbd1-dirty) 12.0.1 20220118 (experimental)
Note: We probably needs gccrs-cross target like other supported languages.
Copyright assignment signed between Smile and the FSF to contribute to GNU tools.

gcc/rust/Make-lang.in: add missing rust compiler driver

---

gcc/rust/util/rust-lang-item.h

This will allow us to define the const_slice_ptr lang item attribute
without erroring out as an unknown lang item.
Addresses #849

Add known lang item const_slice_ptr mappings

---

gcc/rust/expand/rust-macro-builtins.cc
gcc/rust/expand/rust-macro-builtins.h
gcc/rust/util/rust-hir-map.cc
gcc/testsuite/rust/compile/builtin_macro_concat.rs
gcc/testsuite/rust/execute/torture/builtin_macro_concat.rs

- extracts parenthesis-matching logic into a function
- adds `concat!` macro

macros: add concat! macro

---

gcc/rust/backend/rust-mangle.cc

The legacy mangling scheme needs to convert the canonical path containing
* for pointers and the [] brackets representing slices into:
* = $BP$
[ = $u5b$
] = $u5d$
These symbols are not allowed in asm symbols.
Addresses #849

Support mangling *const ptr and slices like *const [T]

---

gcc/rust/typecheck/rust-autoderef.cc

This was a typo when unsized method resolution was added, where the
adjustment was wrongly marked as an indirection. The enum is required so
that the code generation adjustment takes place.
Addresses #849

Ensure unsize method resolutions actually unsize

---

gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
gcc/rust/typecheck/rust-hir-path-probe.h
gcc/rust/typecheck/rust-tyty-bounds.cc
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/testsuite/rust/compile/generics7.rs
gcc/testsuite/rust/compile/generics8.rs
gcc/testsuite/rust/compile/torture/issue-1075.rs

When we examine HIR::ImplBlock's we determine if an impl might overlap
another impl based on the Self type. So for example you might have a
generic structure Foo<T>(T), and an associated impl block for Foo<i32>, but
then go on to define an associated impl of Foo<T> the generic one will
overlap any associated impl hiding the generic implementation.
In this case we have two generic impl blocks
*const [T]
*const T
This means the *const T might overlap with the slice one since it is
generic. As bjorn3 pointed out in #1075 , the correct implementation is to
observe that [T] is constrained by size but untill we have the auto trait
of Sized we must example the two generic impls and just determine that
they are not-equal so for now this is the best implementation we can do.
Fixes #1075

Fix bad inherent overlap error

---

gcc/rust/util/rust-mapping-common.h

This just adds a useful helper to as_string DefId's directly

Add helper as_string for DefIds

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile.cc
gcc/rust/typecheck/rust-hir-dot-operator.cc
gcc/rust/typecheck/rust-hir-dot-operator.h
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-trait-resolve.cc
gcc/rust/typecheck/rust-hir-trait-resolve.h
gcc/rust/typecheck/rust-hir-type-check-expr.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-path.cc
gcc/rust/typecheck/rust-substitution-mapper.cc
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty-bounds.cc
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty-coercion.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/torture/traits19.rs
gcc/testsuite/rust/execute/torture/slice-magic.rs
gcc/testsuite/rust/execute/torture/slice-magic2.rs

Please see the commit a8de089969cb45199008027cd8d1b80dff25746f for
a long explanation of what's going on in the patch. Unfortunately, I have not been
able to split this patch up anymore since supporting slices exposed many bugs
in the implementation of generics in general never main the missing support for
generic associated types.
Fixes #849

Slice support

---

gcc/rust/ast/rust-item.h
gcc/rust/backend/rust-compile-base.cc
gcc/rust/backend/rust-compile-implitem.cc
gcc/rust/hir/rust-ast-lower-enumitem.h
gcc/rust/hir/rust-ast-lower-extern.h
gcc/rust/hir/rust-ast-lower-implitem.h
gcc/rust/hir/rust-ast-lower-item.h
gcc/rust/hir/rust-ast-lower-stmt.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/hir/rust-ast-lower.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h

Fixes #1093
This should cover every case since the previous code simply created public HIR visibilities.
The PR refactors the HIR::Visibility struct to be tinier and a desugared version of the AST one.

Lower AST::Visibility to HIR::Visibility properly

---

gcc/rust/expand/rust-macro-builtins.cc
gcc/testsuite/rust/compile/builtin_macro_concat.rs

- Fix concat macro parser issue which caused an infinite loop when invalid token is encountered

macros: fix an infinite loop in `concat!` macro parser

---

gcc/rust/Make-lang.in
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/privacy/rust-privacy-check.cc
gcc/rust/privacy/rust-privacy-check.h
gcc/rust/privacy/rust-privacy-ctx.cc
gcc/rust/privacy/rust-privacy-ctx.h
gcc/rust/privacy/rust-reachability.cc
gcc/rust/privacy/rust-reachability.h
gcc/rust/rust-lang.cc
gcc/rust/rust-session-manager.cc
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-tyctx.cc
gcc/rust/util/rust-mapping-common.h

This PR is extremely early and implements some building blocks for privacy visitors. I'd like to get some feedback on the architecture and, if satisfactory, merge this first "visitor" which only takes care of visiting HIR struct definitions, to make reviewing easier. We could also merge it to a different branch for now, in order to not add an incomplete pass to the compiler.
Thanks!

Add base for privacy visitor

---

.github/workflows/ccpp.yml

This adds a version of the build-and-check job that runs with clang on
macOS.

rust: Clang/macOS Testing

---

.github/workflows/ccpp.yml

This will provide some synchronization for output lines, and so will
make comparisons with known warnings as part of CI more reliable.

rust: Use -Otarget when building and logging warnings

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-item.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/parse/rust-parse-impl.h

When parsing a visibility in `parse_visibility`, it is not an error to
not have a pub token: It simply means we want to create a private
visibility. If we had C++14 or another language, we could instead
represent all visibilities as an optional<AST::Visibility> where the
Visibility class would not need to change. But I think the best course
of action for our case is to instead keep visibilities even when they
are private and have a special case in the `VisKind` enumeration.
This also enables HIR lowering of visibilities to be performed properly for private items

Add AST Private Visibilities

---

gcc/rust/expand/rust-macro-builtins.cc
gcc/rust/expand/rust-macro-builtins.h
gcc/rust/util/rust-hir-map.cc
gcc/testsuite/rust/compile/builtin_macro_env.rs
gcc/testsuite/rust/execute/torture/builtin_macro_env.rs

Added the `env!()` macro and relevant test cases
Fixes: #977 
Signed-off-by: Ondřej Machota <ondrejmachota@gmail.com>

macros: Add env! macro

---

gcc/rust/privacy/rust-reachability.cc
gcc/rust/privacy/rust-reachability.h

This factors generics' predicates visiting in the `ReachabilityVisitor` and calls the function in other items with generic parameters

Add Reachability visitors for items with generics

---

gcc/rust/expand/rust-macro-builtins.cc
gcc/rust/expand/rust-macro-builtins.h
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/rust/util/rust-hir-map.cc

Fixes #1039
Hey team, I need help understanding why the test fails.
Compilation succeeds, all the existing tests pass. However the test that I've added fails with the error:
```
FAIL: rust/compile/cfg_macro.rs (test for excess errors)
Excess errors:
/Users/anton/Documents/projects/gcc2/gccrs/gcc/testsuite/rust/compile/cfg_macro.rs:17:8: fatal error: Failed to lower expr: [MacroInvocation: 
outer attributes: none
cfg!((A))
has semicolon: false]
compilation terminated.
```
I tried to understand what's happening using a debugger. The only thing that I understood is that the `MacroBuiltin::cfg` function runs.
Appreciate any feedback.
Thank you.

Move `cfg!()` macro to builtins. Fixes #1039

---

gcc/testsuite/lib/rust.exp
gcc/testsuite/rust/compile/xfail/macro_return.rs

- add a 10-second timeout for individual compile test
- add a xfail test case to ensure the timeout mechanism is working

tests: Improve timeout handling

---

gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/privacy/rust-reachability.cc

This visits all of an enum's variants and their fields if present. To do that properly, this adds a new `EnumItemKind` enum which allows static casting when visiting each variant of the enum (kept as an `EnumItem` class which is derived three times)

Add reachability visitor to Enum variants

---

gcc/testsuite/rust/compile/xfail/macro_return.rs

- extent `macro_return` xfail targets to three-segment triples

testsuite/rust: fix test case failure on macOS

---

gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-trait-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-substitution-mapper.h
gcc/rust/typecheck/rust-tyty-bounds.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/traits9.rs
gcc/testsuite/rust/execute/torture/issue-1120.rs

When we have a Trait such as:
```
pub unsafe trait SliceIndex<T> {
type Output;
fn index(self, slice: &T) -> &Self::Output;
}
unsafe impl<T> SliceIndex<[T]> for Range<usize> {
type Output = [T];
fn index(self, slice: &[T]) -> &[T] {
unsafe { &*self.get_unchecked(slice) }
}
}
```
When we need to verify that the impl index is compatible fir SliceIndex we
get the Type info for the trait-item which is:
fn<Self, T> index(self: Self, slice: &T)
-> &<placeholder=projection<T>=[T]>
This projection gets setup and the types are substituted with
Self=Range<usize> and T=[T] which ended up substituting the projection
twice resulting in a recursive slice [T=[T]]. In this case the associated
type is already setup for the placeholder and does not require generic
substitution. This means we added a flag …

Fix bad projection substitution

---

gcc/rust/hir/rust-ast-lower-block.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower.cc
gcc/testsuite/rust/execute/torture/issue-858.rs

When we are lowering blocks using the visitor pattern we must use the
BaseClass of ExprWithBlock to abstract away the notion that this expr
has a block such that we can handle cases like a block expr vs expressions
with a block. This makes the usage of hir lowering of match expressions to
be recursive, if we had more fine grained visitors in the AST we could fix
these types of problems with compile time enforced interfaces.
Fixes #858

Fix ICE during HIR lowering of ExprWithBlock MatchExpr

---

gcc/rust/Make-lang.in
gcc/rust/backend/rust-compile-fnparam.cc
gcc/rust/backend/rust-compile-fnparam.h
gcc/rust/backend/rust-compile-pattern.cc
gcc/rust/backend/rust-compile-pattern.h
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-pattern.cc
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/testsuite/rust/execute/torture/issue-995.rs

This reuses our code to handle match-arms within MatchExpressions, we
resolve the pattern's type's and implicitly create types for that binding.
For code-generation we create a tmp var name for the name of the parameter
which is the base type and for the destructuring we reuse the same match
arm code to generate the implicit bindings to the parts of the structure
```c
__attribute__((cdecl))
i32 test::pattern_as_arg (const struct test::Pattern RSTPRM.0)
{
i32 RUSTTMP.1;
return RSTPRM.0.0;
}
```
Fixes #995

Support pattern bindings within function signitures

---

gcc/testsuite/rust/execute/torture/builtin_macro_cfg.rs

See #1116 and #1039
Adding a test for the cfg!() macro. The compilation of the test fails with the message:
```
fatal error: Failed to lower expr: [MacroInvocation: 
outer attributes: none
cfg!((A))
has semicolon: false]
compilation terminated.
```

Add a test for the cfg!() macro

---

gcc/rust/resolve/rust-ast-resolve-item.h
gcc/testsuite/rust/compile/issue-1131.rs

When we name-resolve generic parameters their declaration gets inserted in
to the upper-most rib on the stack. Then when this is referenced we lookup
the relevant binding starting from the uppermost rib this lead to the 2nd
extern item adding the same binding into the same rib which caused this
clash. To fix this we need to have a seperate rib for each declaration
so as reusing the same names don't clash with each other.
Fixes #1131

Fix generic param redefined bug

---

gcc/rust/typecheck/rust-tyty-coercion.h
gcc/testsuite/rust/compile/issue-1129-1.rs
gcc/testsuite/rust/compile/issue-1129-2.rs

Arrays are coercible into slices, this adds the missing type-resolution
the rule which works for now. The other part of this fix is described in #1146 
for coercion_site to be recursive and reuse the adjustment classes so that
we reuse as much code as possible and handle complex coercion sites.
Fixes #1129

Add missing coercion rule from array to slice

---

gcc/rust/typecheck/rust-hir-type-check-base.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/issue-1152.rs

This bug turned out to be that we expected a usize for the array capacity
but the specified capacity turned out to be an integer inference variable
which will default to a signed integer. The type resolution was missing
handling the type-hints of isize and usize
Fixes #1152

Add support for isize and usize type-hints

---

gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/privacy/rust-visibility-resolver.cc
gcc/rust/privacy/rust-visibility-resolver.h

Based on #1155, so you can review just the last commit.
This adds the remaining simple visitors for visibility resolving, as well as a helper method for doing so.

Resolve remaining simple visibilites

---

gcc/rust/backend/rust-compile-base.cc
gcc/rust/backend/rust-compile-base.h
gcc/rust/util/rust-attributes.cc
gcc/testsuite/rust/debug/no_mangle.rs

- handle the `no_mangle` attribute

backend: handle no_mangle attribute

---

gcc/testsuite/rust/compile/attr_cold.rs

- fix a typo in the `rust/compile/attr_cold.rs` file

tests/attr_cold: fix a typo

---

gcc/rust/expand/rust-attribute-visitor.cc
gcc/testsuite/rust/execute/torture/macros29.rs
gcc/testsuite/rust/execute/torture/macros30.rs
gcc/testsuite/rust/execute/torture/macros31.rs

Following up on https://github.com/Rust-GCC/gccrs/issues/1141
Currently the macro expansion doesn't work for ComparisonExpr, LazyBooleanExpr, AssignmentExpr. To fix this, I just copied the code from the `ArithmeticOrLogicalExpr` and it seemed to work. I don't like the code duplication, happy to try refactoring it into a separate function.
Will work on the macro expansion in the `if` expressions next.

Implement macro expansion for ComparisonExpr, LazyBooleanExpr, AssignmentExpr

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-item.h

This is a necessary first step which addresses #1158
I am working on the visibility resolver and simple-path name resolver in parallel and will need those changes. 
I'm not sure if the `has_path` method is necessary since we will have `HIR::Visibilities` in the visibility resolver, which will be desugared. Maybe I am doing this wrong and we should be working on `AST::Visibilities` instead?

Add `NodeId`s to `SimplePath{Segment}`s

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/issue-1165.rs

We used a hack in the parser to turn simple cases such as &Foo(..) into:
BorrowExpr
CallExpr(
IdentifierExpr + <Argument-expressions>))
The IdentifierExpr here is parsed as a PathExpression but to simplify
things at the time it seemed logic to see these as identifier expressions
but this is actually a Path and we need to be careful about generic
arguments here. Identifiers are simply identifiers and must not be changed
or coherence of inference variables will become a jumble of inference
variables trying to infer one another inside purely generic code.
This patch leaves the PathInExpressions as Path's instead of trying to be
clever and turn them into identifiers.
Fixes #1165

Support inference of generic parameters on paths behind reference's

---

.github/emit_test_errors.pl
.github/workflows/ccpp.yml

- catch malformed test cases and use GitHub Actions' annotation feature to mark the failures

CI: catch malformed test cases

---

gcc/rust/typecheck/rust-hir-type-check-path.cc

When we resolve paths we don't have a _type_, in this scenario there is a
bug in our resolution of this generic function so this means the root_tyty
is nullptr but the offset is non zero so we return nullptr.
Addresses #1132
This test case no longer ICE's but still fails. I have a fix in progress for this
```rust
mod mem {
extern "rust-intrinsic" {
fn transmute<U, V>(_: U) -> V;
}
}
pub trait Hasher {
fn write(&mut self, bytes: &[u8]);
fn write_u16(&mut self, i: u16) {
self.write(&mem::transmute::<_, [u8; 2]>(i))
}
}
pub struct SipHasher;
impl Hasher for SipHasher {
#[inline]
fn write(&mut self, msg: &[u8]) {}
}
```

Fix nullptr when resolving the root of a path expression

---

gcc/rust/expand/rust-attribute-visitor.cc
gcc/testsuite/rust/compile/macro42.rs

Addresses #1141. Following up on #1161.
This change adds support for the macros inside the `if` condition expressions.
Things to note:
1. Judging by my research, the `IfExprConseqIfLet` isn't used. The parser treats the syntax `let var = if ...` as a `let` expression followed by `if` expression:
2. I didn't add the macro expansion to the `IfLetExpr...` family of expressions because I wasn't able to write a test case reproducing the missing macro expansion. I've tried the following code
```rust
fn main() -> i32 {
let mut res = 0;
enum E {
X(u8),
Y(u8),
Z(u8),
}
let v = E::Y(12);
if let E::Y(n) = v {
res = 1;
}
0
}
```
which caused the compiler error
```
FAIL: rust/compile/macro43.rs (internal compiler error: in append_reference_for_def, at rust/resolve/rust-name-resolver.h:227)
```

Implement macro expansion in `IfExpr`, `IfExprConseqElse`, `IfExprConseqIf`, `IfExprConseqIfLet`.

---

Dockerfile

- Dockerfile: change base image
This commit fixes a recent Docker building error where the GLibc version mismatches.

Dockerfile: change base image

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/rust-session-manager.cc

This removes the default argument for the locus of `SimplePath`s. Addresses #1159 
There are a lot of places in the code where it is not possible to insert a "correct" location for these `SimplePath`s: namely, when creating the use statement for the standard library's prelude, or when creating the `SimplePath`s of attributes. I've left a few FIXMEs in these cases because I'm unsure about the proper course of action.

Remove default location for `SimplePath`s

---

gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-path.cc
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/issue-1173.rs
gcc/testsuite/rust/compile/torture/issue-893-2.rs

This fix breaks down into two commits the first commit fixes the issue directly
then the second one fixes the regression that was introduced in the first.
The TLDR for this patch set is that when we resolve the path here:
module::transmute
The name-resolver wronly added the specified generic arguments into the canonical
path meaning that the root segment could not be name-resolved such that during
type resolution we iterate and apply the generic arguments appropriately to the root
segment.
In fixing this it introduced a regression exposing a few more complex issues with
inference variables but for a more complete explanation about that please read the
commit message from ea38a59ee8329bb7b309400a7de57d53ad7bde31
Fixes #1173

Fix bad name resolution on path with generic segments

---

gcc/rust/backend/rust-compile-implitem.cc
gcc/rust/backend/rust-compile-item.cc
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/typecheck/rust-hir-path-probe.h
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-trait-resolve.cc
gcc/rust/typecheck/rust-hir-trait-resolve.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-path.cc
gcc/rust/typecheck/rust-hir-type-check-type.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/testsuite/rust/compile/issue-1128.rs

There are several fixes going on to solve these issues which overlap with one
another so it seemed best to pack them within the same PR.
The main issue for #1128 was that we did not resolve a trait when it was unused
leading to us hitting the ICE in the privacy pass. Since the type check context was
empty for the trait since it was not resolved. To fix this we needed to refactor the
trait resolver to resolve the trait as part of iterating the crate. This resulted in some
regressions in the testsuite so this is why we need the the other commits. Which
required us to finally perform the refactor specified in #1105 to fix these.
Fixes #1105 #1128 #1132

Fix ICE in reachability class and refactor associated types code

---

gcc/rust/backend/rust-compile-type.cc
gcc/rust/typecheck/rust-hir-type-check-base.cc
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/rust/util/rust-attributes.cc
gcc/testsuite/rust/compile/struct_align1.rs
gcc/testsuite/rust/compile/struct_align2.rs
gcc/testsuite/rust/compile/struct_pack1.rs
gcc/testsuite/rust/compile/struct_pack2.rs

This is a start at handling the various layout options supported by Rust, beginning with `#[repr(align(N))]` and `#[repr(packed(N))]`, on structs and tuple structs.
There are several other layout options which remain to be supported such as `#[repr(C)]`, `#[repr(transparent)]`, combinations e.g. `#[repr(C, packed(2))]`, as well as layouts on union and enum types.
Fixes: #915

Support align and packed repr layout on structs

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-item.h
gcc/rust/resolve/rust-ast-resolve-item.cc
gcc/rust/resolve/rust-ast-resolve-item.h
gcc/rust/resolve/rust-ast-resolve-type.cc
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/rust-lang.cc
gcc/rust/rust-session-manager.cc
gcc/testsuite/rust/compile/torture/cfg_attr.rs
gcc/testsuite/rust/compile/use_1.rs

In order to resolve `SimplePath`s, we have to expand all paths present
in a `UseDeclaration` and resolve them. For example, we want to resolve
two paths with the following statement `use foo::bar::{baz, bul}`:
`foo::bar::baz` and `foo::bar::bul`
This also removes the prelude inclusion (`use std::prelude::v1::*`)
since we cannot resolve it (yet!)
Needs #1172 to compile
Adresses #1159 
Adresses #1187

Resolve simple paths in use items

---

gcc/rust/backend/rust-compile-base.cc
gcc/rust/backend/rust-compile-base.h

Generic functions cannot be public since the symbols could overlap in
linking other crates reusing the same generic. The other benefit here is
that when optimizations are turned on we can eliminate more code since the
symbol does not _need_ to be public.

Generic functions should not be TREE_PUBLIC

---

gcc/rust/typecheck/rust-tyty-bounds.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

The Gimple names of our dyn trait objects were looking like:
const struct dyn [HIR Trait: FnLike->[C: 0 Nid: 31 Hid: 38 Lid: 13] [(FN call ), ]<Self, &isize, &isize>] & const f
This is a horrible name but useful for debugging this patch fixes this so
we have a seperate naming for generating the type. So now it looks like:
const struct dyn [FnLike<Self, &isize, &isize>] & const f

Add new as_name interface for Dynamic types

---

gcc/rust/backend/rust-compile-base.cc
gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-implitem.cc
gcc/rust/backend/rust-compile-item.cc
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile.cc

There are two changes are part of this PR one where we update the address_expression
helper to take a ptrtype tree. Since the default build_address_expr_loc was automatically
building a pointer type of the TREE_TYPE of the operand which is not correct since we
sometimes want REFERENCE_TYPES instead of POINTER_TYPES. 
The 2nd commit enhances the coercion_site code to recursively walk the tree and their
types to handle coercions to dyn traits or do array bounds checking etc. This gets rid of
the get_root hack used and cleans up the code in general.
Fixes #1146

Support recursive coercion sites

---

README.md

HTTPS cloning is the standard across many projects as well as being simpler and more beginner-friendly.
Signed-off-by: Maximilian Downey Twiss <creatorsmithmdt@gmail.com>

Replace SSH cloning with HTTPS cloning in README.md

---

gcc/rust/backend/rust-compile.cc

The code here was wrongly assuming the unsigned long interface which is not
correctly for all targets.

Use correct format specifiers for unisnged HOST_WIDE_INT

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-pattern.cc
gcc/rust/backend/rust-compile-pattern.h
gcc/testsuite/rust/execute/torture/match_bool1.rs

Enables compiling `match` expressions where the scrutinee is a boolean expression. Also enable compiling match arms with Literal patterns, since `true` and `false` literals are commonly used with matches on boolean expressions.
Fixes: #1207

Allow match on boolean expressions

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/execute/torture/match_loop1.rs

Previously, we would lose the context of being inside a loop when compiling a `match`.
This would lead to incorrect error messages like "cannot 'break' outside of a loop" when
trying to break out of a loop from within a `match` expression.
Fixes: #1196

Preserve inside_loop context when type checking match

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-type.cc
gcc/rust/backend/rust-compile.cc

OBJ_TYPE_REF's are the gcc nodes that signify that this is a virtual call
which gives a hint to the optimizers for devirtualization. This patch also enhaces
the dyn object to hold an array of pointers instead of multiple name fields of addresses.
Fixes #996

Take advantage of OBJ_TYPE_REF'S in dyn calls

---

gcc/rust/backend/rust-compile-expr.h

When we construct a union, we were wrongly compiling the constructor
without taking into account the associated union index. This meant we
if you were constructing a union using any other field than the first one
you had a bad coercion type check resulting in a silent failure of generating
an error_mark_node.
This was caught using an assertion to ensure there is no error on coercion site but it is valid
to have errors from coercion sites.

Ensure the coercion sites are applied correctly on unions

---

gcc/rust/backend/rust-compile-expr.h

Loop expressions can return a value even if its a unit-type so we must
ensure we don't return an error_mark_node for the eventual coercion site
for the unit-type case.
The offending test-case was: rust/compile/torture/loop7.rs
This was found while fixing #1220

Ensure we don't return error_mark_node for loop expressions

---

gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h

When we coerce types we need to destructure from the generics in order to
apply these coercion rules correctly or we end up returning a bad
error_mark_node.
This was found while fixing https://github.com/Rust-GCC/gccrs/pull/1220

Destructure our generics, placeholers or projections during coercion

---

gcc/rust/typecheck/rust-hir-type-check-expr.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/execute/torture/issue-1133.rs

This interface is required when we monomorphize since types might be
placeholder -> projection -> param -> actual-type
This gives us a clean clone interface to destructure this into its actual
type. This is important so for example if we have a generic trait function
and resolve the function for a specific set of generics we update the
associated types. This works, then when we go to substitute the same
generic trait again the placeholders are again updated throwing off the
typing for the first type.
There is more cleanup we can do once this PR is in to make this part of
the general monomorphization path so that we sort out these as part
of the fntype
Fixes #1133

Add new monomorphize_clone interface

---

gcc/rust/expand/rust-macro-substitute-ctx.cc
gcc/testsuite/rust/compile/macro-issue1224.rs

In the case were a repeting metavar was used as a regular metavar ($var
instead of $($var)* for example), the compiler would crash on an
assertion that $var was only repeating once. We should instead error out
and point to the user that this is probably not what they intended to
do.
Some spurious errors are emitted, but improving them requires a major refactor of the SubstitutionContext file to report error states before.
Closes #1224 
Thanks to @bjorn3 for pointing this out.

macros: Error out when repeating metavars which refer to repetitions

---

gcc/rust/Make-lang.in
gcc/rust/parse/rust-parse-impl.h
gcc/rust/rust-lang.cc
gcc/rust/util/rust-make-unique.h
gcc/rust/util/rust-optional.h

This adds a tagged union to try and simulate a sum type. This is safer and more ergonomic
than one of the two alternatives we're currently using in the compiler:
1. Storing a raw pointer, which can be `nullptr` or valid
This is wildly unsafe, and usable in conjunction with local references, stack
variables, or pointers managed elsewhere, which can cause crashes, hard to
debug issues or undefined behavior. Likewise, if you do not check for the
pointer's validity, this will cause a crash.
2. Storing an extra boolean alongside the object
This causes implementors to use a "dummy object": Either an empty version or
an error version. But what happens if what you really wanted to store was
the empty or error version? You can also easily incorporate logic bugs if you
forget to check for the …

Add `Optional<T>` type

---

gcc/rust/typecheck/rust-hir-type-check-struct.cc
gcc/testsuite/rust/compile/issue-1235.rs

Fix missing coercion site call which allows the coecion of a reference to
a pointer type.
Fixes #1235

Assigning members to structures is a coercion site

---

gcc/rust/hir/rust-ast-lower-block.h
gcc/rust/hir/rust-ast-lower.cc

This PR addresses https://github.com/Rust-GCC/gccrs/issues/1177. This change implements the "hir-lowering" part of the plan outlined here https://github.com/Rust-GCC/gccrs/issues/1177#issuecomment-1118530135.

Lower IfLet expressions

---

gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/expand/rust-macro-expand.h
gcc/testsuite/rust/compile/macro-issue1233.rs

This also fixes the undefined behavior. Once again we are hurt by
`std::vector<T>::back()` returning references and not
pointers/`std::optional<T>`s!
The cause of the bug was some overzealous popping from the context
vector in block expressions. The amount of calls to `pop_context` is now
the same as the amount of calls to `push_context`
Closes #1233

Remove undefined behavior in context vector

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/issue-1234.rs

Arithmetic operations like this need a cast to support the range of integer
types which are allow here.
Fixes #1234

Change Artihmetic Operation to be a cast type operation

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-constexpr.cc
gcc/rust/typecheck/rust-tyty-cast.h
gcc/testsuite/rust/compile/issue-1226.rs

This adds the cast rules of integer types and integer inference variables
to pointers. The code-generation needed to remove the bad assertion that
all integer literals were always going to be of type integer. This also
needed a tweak to a bad port from the cp/constexpr.cc code which assumed
that all integer_cst of pointer types would be a zero pointer which was
used to detect cases of bad method pointers in CPP which we does not apply
here.
see gcc/cp/constexpr.cc:6564-6488
Fixes #1226

Allow cast of integers to pointers

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-pattern.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/execute/torture/match_byte1.rs
gcc/testsuite/rust/execute/torture/match_char1.rs
gcc/testsuite/rust/execute/torture/match_int1.rs

Enable compiling match expressions on other primitive types like `i32`, `usize` and `char`.

Allow match on integer and char types

---

gcc/rust/ast/rust-pattern.h
gcc/rust/backend/rust-compile-pattern.cc
gcc/rust/backend/rust-compile-pattern.h
gcc/rust/hir/rust-ast-lower-base.cc
gcc/rust/hir/rust-ast-lower-base.h
gcc/rust/hir/rust-ast-lower-pattern.cc
gcc/rust/hir/rust-ast-lower-pattern.h
gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/resolve/rust-ast-resolve-pattern.cc
gcc/rust/resolve/rust-ast-resolve-pattern.h
gcc/rust/typecheck/rust-hir-type-check-pattern.cc
gcc/rust/typecheck/rust-hir-type-check-pattern.h
gcc/testsuite/rust/execute/torture/match_range1.rs
gcc/testsuite/rust/execute/torture/match_range2.rs

Add name resolution, lowering, type checking and compilation for `RangePattern`s in matches.

Support RangePatterns in matches

---

gcc/testsuite/rust/compile/macro-issue1233.rs

This testcase uncovered a very interesting bug requiring a refactor of
our `AST::Block` class (#1253), but should still be fixed/adapted in the
meantime so that the BE builds on our buildbot do not fail.
I've tested this newtestcase with a compiler from 74e836599ce80a11b1fe28065ed7aae6ffa3b7e2, which was the commit pointed out in #1233. The same ICE would still trigger, so I can safely say that this is a different exemple showing the same underlying issue. I'll work on fixing #1253 but it is a refactor we need to think about a little.
This should make all the architectures on buildbot happy again!

issue #1233: Do not rely on the endianness for testing

---

gcc/rust/privacy/rust-privacy-reporter.cc
gcc/rust/privacy/rust-privacy-reporter.h
gcc/testsuite/rust/compile/privacy3.rs
gcc/testsuite/rust/compile/privacy4.rs

This adds privacy reporting to all expression types inside our HIR. It also restricts the `PrivacyReporter` visitor to `HIR::Expression`s and `HIR::Stmt`s as a lot of the previous types did not need to be visited.

Privacy report expressions

---

gcc/rust/backend/rust-compile-type.cc
gcc/rust/backend/rust-compile-type.h
gcc/rust/lang.opt
gcc/rust/typecheck/rust-tyty.cc

In the case of Generic Associated Types we end up
placeholders->projections->generic-param->i32
This means we need to keep destructuring the TyTy object until we finally
get the real type at the end. In order to do this safely we need to ensure
we add in recursion limits and apply this where it matters such as
compiling types in general too.

Make TyTy::BaseType::destructure recursive

---

gcc/rust/util/rust-optional-test.cc

I seem to be having build issues locally with missing ASSERT macros but works when they are wrapped in CHECKING_P guards.

Wrapup testing code within CHECKING_P guards

---

gcc/rust/typecheck/rust-hir-type-check-expr.cc

This is a small refactor to remove duplicating the work in type checking
the index expression.

Reuse index_expr_ty type

---

gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/typecheck/rust-hir-type-check-expr.h

This change implements the type check for the `IfLet` expression. This is the adapted type checking code from the `MatchExpr`.
Tested on this code
```
enum E {
X(u8),
}
fn main() -> i32 {
let mut res = 0;
let v = E::X(4);
if let E::X(n) = v {
res = n;
}
0
}
```
Compilation finishes without errors.
Next is the implementation of the code generation but I'll need help to find where it's located.
Addresses #192 #1177

Implement type checking for the `IfLet` expression.

---

gcc/rust/typecheck/rust-hir-type-check-expr.h

This reverts the code fix for 89631998d2ffda0c0c05066c148c6fc19398da5c
but keeps the test-case proving that we have not regressed. More info in
the commit message.
Fixes #1274 #1273

Remove old hack to handle type inferencing in untyped decalred bindings

---

gcc/testsuite/rust/compile/issue-1237.rs

This bug was fixed in commit cb4d935508def8b250345ba5205a90ad9e177ab4
with related PR #1223
The issue is that associated types get updated depending on the context
they are used so we need to monomorphize the types when we can so that we
don't then throw off the rest of type checking with bogus errors like this.
Fixes #1237

Add testcase to prove bug is fixed

---

gcc/rust/backend/rust-compile-base.cc
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-expr.h
gcc/rust/backend/rust-compile-pattern.cc
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile-type.cc
gcc/rust/backend/rust-constexpr.cc
gcc/rust/backend/rust-constexpr.h

Card: [Link](https://github.com/Rust-GCC/gccrs/projects/16#card-82300522)
This class had potential to hinder porting further const folding code from C++. This edit makes it easy to copy code from constexpr.cc to rust-constexpr.cc and so on.
Structs `constexpr_ctx` and `constexpr_global_ctx` have been copied as well as to keep `constexpr_ops_count` after removing the class. These structs will be filled further as the port carries on. The prototypes inside ConstCtx have been copied over to rust-constexpr.cc as static prototypes.

const folding in gccrs: remove ConstCtx class.

---

gcc/rust/Make-lang.in
gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h

This adds a base for pretty printing our AST through a new visitor (Addresses #1261).
This adds enough code to pretty print "functions" without types in the parameters or return type. Looking for feedback on the implementation before we keep going with more code :)
Here's a tiny patch if you want to see the output whenever you're running `-frust-dump-all`:
```diff
diff --git a/gcc/rust/rust-session-manager.cc b/gcc/rust/rust-session-manager.cc
index 0b0e5af915f..3e39c6a6e17 100644
--- a/gcc/rust/rust-session-manager.cc
+++ b/gcc/rust/rust-session-manager.cc
@@ -31,6 +31,7 @@
#include "rust-cfg-parser.h"
#include "rust-lint-scan-deadcode.h"
#include "rust-lint-unused-var.h"
+#include "rust-ast-dump.h"
#include "diagnostic.h"
#include "input.h"
@@ -1023,6 +1024,8 @@ Session::dump_ast …
```

Add AST dump visitor

---

gcc/rust/hir/rust-ast-lower-block.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/rust-ast-lower.cc
gcc/rust/resolve/rust-ast-resolve-expr.cc
gcc/rust/resolve/rust-ast-resolve-expr.h

This just adds basic name resolution and hir lowering for
the loop. Eventually we will make all Loops into a single
HIR::LoopExpr but for now its really useful having a separate
visitor to implement this to avoid regressions in the short
term.
Addresses #869

Add name resolution to for loops

---

gcc/rust/resolve/rust-ast-resolve-item.cc
gcc/rust/resolve/rust-ast-resolve-type.cc
gcc/rust/resolve/rust-ast-resolve-type.h

When we generate the path for impl items we need to base this of the Self
type but this was ignoring cases like pointers, references or slices. This
meant generic slices had the same path has generic pointers etc. The only
reason we didn't end up with a linker symbol clash is due to the symbol
hash.

Fixup name canonicalization for impl blocks

---

gcc/rust/typecheck/rust-tyty.cc
gcc/rust/util/rust-lang-item.h
gcc/testsuite/rust/compile/issue-1289.rs

This issue here was the equality checks for reference
and pointer types did not check the mutability.
Fixes #1289

Fix bad impl item overlap check

---

gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-hir-map.h

This patch adds two new interfaces to the mappings class.
- Lookup the child items within a module
- Lookup the parent module id from the child item id
Each of these API's are going to be required so that we can resolve two new
types of path segment:
super::foo::bar
Where we need to be able to lookup the super module node id from the
current scope node id. To then lookup the children within that scope. The
other path is simpler such as: crate::foo::bar. Where we lookup the items
within the current Crate NodeId and follow on as normal.
Addresses #1227

Add new mappings for items within a module

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/ast/rust-item.h

This adds proper AST formatting for inherent impl blocks and traits.
This does not handle trait impls yet (`impl Trait for Type`) but it should be really easy to refactor and add.

AST Dump impl traits

---

gcc/rust/lex/rust-lex.cc
gcc/rust/lex/rust-lex.h
gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/torture/check-doc-attr-string.rs
gcc/testsuite/rust/compile/torture/very-broken-attr-string.rs

- rust/lex: skip broken string expression and unstuck the parser when it could not advance
should fix #1297

rust/lex: skip broken string expression

---

Dockerfile

Sometimes, the GCCRS_BUILD file would end up empty. I believe this is
due to how Dockerfiles work in that there was a "race condition" between
the two `RUN` commands. Hopefully this should fix it.

docker: Fix GCCRS_BUILD info

---

gcc/rust/backend/rust-compile-intrinsic.cc
gcc/rust/hir/tree/rust-hir-type.h
gcc/testsuite/rust/compile/torture/transmute-size-check-1.rs

- rust/intrinsic: add a basic size check for `transmute`
partially addresses #1195

rust/intrinsic: add a basic size check for `transmute`

---

gcc/rust/lex/rust-lex.cc
gcc/testsuite/rust/compile/empty_comment_before_match.rs

Empty comments (comments without any characters including spaces after //) had a bug during lexing. The lexer did not recheck the current character after skipping / characters. When there was no character after //, the lexer skipped the next newline character. This caused lexer to count the next line as a part of the comment to. This commit fixes this bug by rechecking current character after skipping two / characters.
Fixes #1306
Signed-off-by: Nirmal Patel <nirmal@nirmal.dev>

Fix lexing of empty comments continuing till next line

---

gcc/rust/backend/rust-tree.cc
gcc/rust/backend/rust-tree.h

Card: [Link](https://github.com/Rust-GCC/gccrs/projects/16#card-82441327)
Most of TREE_CODEs in the original function belonged to cp/cp-tree.def which have been removed so this ported function is a lot smaller.

gccrs const folding: port over cp_walk_subtrees()

---

gcc/rust/ast/rust-ast-dump.cc

Needs #1295
This adds the dumping of trait implementations for types. However, it is incomplete as I don't believe we can yet handle associated types and associated constants properly? Am I looking in the wrong place?
Will dig deeper, but opening for any early review.

Ast dump trait impl

---

gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-substitute-ctx.cc
gcc/rust/lex/rust-lex.cc
gcc/rust/lint/rust-lint-marklive.cc
gcc/rust/rust-session-manager.cc
gcc/rust/typecheck/rust-hir-type-check-pattern.cc
gcc/rust/typecheck/rust-tyty.cc

Printing size_t as [unsigned] long (%ld or %lu) raises warnings on 32-bits
targets. As the GCC pretty printer doesn't have the equivalent of libc's %z/%zu,
fix all formats to use unsigned long and cast values.
refs #1229
Co-authored-by: Rainer Orth <ro@gcc.gnu.org>

Fix formatting error on 32-bits targets

---

gcc/rust/ast/rust-path.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/compile/const_generics_3.rs

1. Refactor const generic declaration
The default value for const generics now benefits from using the same
function as parsing a regular const generic expression
2. `Parser::parse_type` should not always add errors
In the case that we are parsing a const generic and not a type, we
should not emit bogus errors from `parse_type` such as "unexpected token
in type: LITERAL". Thus, we add a flag to the function to not always
add errors to the error table
3. Figure out how to deal with ambiguities
In the following cases, parsing is ambiguous:
```rust
let a: Foo<N>;
```
What is N? Is it a type to be used as a generic argument? Is it a const
value to be used for a const generic argument? We need to keep both
possibilities and differentiate later during typechecking. We need to
figure out if it …

Add base for parsing const generic application

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/ast/rust-ast-full-decls.h
gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-ast-visitor.h
gcc/rust/ast/rust-ast.h
gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/expand/rust-attribute-visitor.h
gcc/rust/hir/rust-ast-lower-base.cc
gcc/rust/hir/rust-ast-lower-base.h
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/resolve/rust-ast-resolve-base.cc
gcc/rust/resolve/rust-ast-resolve-base.h
gcc/rust/resolve/rust-ast-resolve-type.h

This uses a number of hacks and workarounds to avoid implementing the equivalent HIR node in the same PR. I'll raise issues for each of the `FIXME`s in the code. Needs one commit from #1315 to avoid unecessary conflicts.

Add const generic declaration to AST

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-pattern.cc
gcc/rust/privacy/rust-privacy-reporter.cc
gcc/rust/rust-diagnostics.h

* wrapping GCC's diagnostics `sorry_at` with a new rust macro named `rust_sorry_at` which accepts `Location` instead of the default `location_t`.
* refactoring previous usage of `sorry_at` to `rust_sorry_at`
Fixes #1263

Fixes #1263; diagnostics/feature/wrapper

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-path.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h

This commit adds a new type to the AST which contains const generic
arguments. The `GenericArgs` structure now also keeps a vector of them,
and the parser was modified accordingly. We need to handle these extra
arguments in the various resolvers and type-checking phase.
As pointed out before, const generic arguments are ambiguous at the AST
level. Which is why this "sum type" contains a "Clear" variant when
there is no ambiguity at all (`<5>`, `<{ 5 }>`, `<{ 5 + 15 }>` or
`<{ N }>`) and an "Ambiguous" one if the value in question might be
referring to a type argument (`<N>`) instead of a const generic
argument.

AST for const generic arguments/const application

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-path.h
gcc/rust/hir/rust-ast-lower-base.cc
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/privacy/rust-reachability.cc
gcc/rust/typecheck/rust-hir-trait-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-implitem.h
gcc/rust/typecheck/rust-hir-type-check-item.h
gcc/rust/typecheck/rust-hir-type-check-stmt.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.h
gcc/rust/typecheck/rust-hir-type-check.cc

This PR adds lowering for both the `ConstGenericParam` type and the `ConstGenericArg` one. Ideally, we should be able to avoid ambiguites (`let a: Foo<N>;` -> what is N? A type? A const?) by going through the name resolver, and resolve either to a different `AST::ConstGenericArg` either to a correct `AST::Type` or equivalent. So I think we can avoid doing the same "Ambiguous/Clear" dance in the `HIR::ConstGenericArg` type.
If that ends up not being possible, we can always add it and disambiguate during typechecking or other.
Closes #1318

Lower const generics structures

---

gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/hir/tree/rust-hir-type.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/privacy/rust-privacy-reporter.cc
gcc/rust/privacy/rust-privacy-reporter.h
gcc/testsuite/rust/compile/privacy5.rs

Fix #1256
Adds location to the HIR::Type base class, removes it from all the subclasses and then use it  in the `check_type_privacy` method to improve privacy error reporting.
The privacy error now looks like this (instead of what you can see in the example #1256).
```rust
gcc/testsuite/rust/compile/privacy5.rs:15:20: error: definition is private in this context
15 |         fn any(a0: green::Foo, a1: green::Bar) {}
|                    ^
```

Add location to HIR::Type base class and improve privacy error reporting

---

gcc/rust/backend/rust-compile-intrinsic.cc

> Unfortunately, another instance of this issue sneaked in after my original patch.
Fixed by the attached patch, which makes this work again on i386-pc-solaris2.11

Fix remaining misuses of format specifiers on 32-bit targets

---

gcc/rust/Make-lang.in
gcc/rust/hir/rust-hir-dump.cc
gcc/rust/hir/rust-hir-dump.h
gcc/rust/rust-session-manager.cc

This commit adds a visitor skeleton for pretty printing of the HIR. Also,
modifies the session manager to call the new entry point
`Rust::HIR::Dump::crate` which simply prints the crate the way it used to be.

hir/add: pretty printing visitor skeleton

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-path.h
gcc/rust/parse/rust-parse-impl.h

Add const generic disambiguation

---

gcc/rust/backend/rust-compile-type.cc

When bootstrapping with --enable-checking=no you'll get:
gcc/rust/backend/rust-compile-type.cc: In member function
‘virtual void Rust::Compile::TyTyResolveCompile::visit(const Rust::TyTy::ADTType&)’:
gcc/tree.h:2312:59: error: statement has no effect [-Werror=unused-value]
2312 | #define TYPE_PACKED(NODE) (TYPE_CHECK (NODE)->base.u.bits.packed_flag)
|                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
gcc/rust/backend/rust-compile-type.cc:315:7:
note: in expansion of macro ‘TYPE_PACKED’
315 |       TYPE_PACKED (type_record);
|       ^~~~~~~~~~~
We need to actually set a value for the packed_flag.

Actually set TYPE_PACKED for type_record

---

.github/workflows/Remark.yml

The Remark CI is breaking for seemingly unrelated reasons regarding
JavaScript syntax. Let's disable it in the meantime and investigate so
that our PRs can still get proper feedback

ci: Temporarily disable Remark CI

---

gcc/rust/backend/rust-constexpr.cc
gcc/rust/backend/rust-tree.cc
gcc/rust/backend/rust-tree.h

Card: [Link](https://github.com/Rust-GCC/gccrs/projects/16#card-82300805).
Target function: [Link](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/constexpr.cc#L8350)
Following functions are ported in this changeset:
- [maybe_constexpr_fn](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/constexpr.cc#L5495)
- [get_nth_callarg](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/constexpr.cc#L1333)
- [var_in_maybe_constexpr_fn](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/constexpr.cc#L5507)
- [array_type_nelts_top](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/tree.cc#L3055)
- [builtin_valid_in_constant_expr_p](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/tree.cc#L445)
- [decl_maybe_constant_var_p](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/decl2. …

gccrs const folding port: continue porting potential_constant_expression_1()

---

gcc/rust/hir/tree/rust-hir-expr.h

We overload the assignment operator to clone the vector of patterns for
the match arm. However the existing patterns were not cleared before
inserting the new ones, so the result was to append the new patterns
onto the assignee arm rather than replace them.

HIR: fixup MatchArm assignment operator

---

gcc/rust/ast/rust-path.h
gcc/rust/resolve/rust-ast-resolve-path.cc
gcc/rust/resolve/rust-ast-resolve-type.cc
gcc/testsuite/rust/compile/self-path1.rs
gcc/testsuite/rust/compile/self-path2.rs
gcc/testsuite/rust/execute/torture/issue-1231.rs

This adds support for the self path which is used in two different
contexts. One where it refers to the self parameter within methods
the other is where it can refer to the crate module scope.
Handling self has some limitations where it must be the first
the segment in the path or be a single segment path for example see:
```
struct foo;
fn test() {
crate::self::foo;
}
```
Errors with (rustc 1.61):
```
Error[E0433]: failed to resolve: `self` in paths can only be used in start position
```
crate and super keywords can be chained as expected but self seems to be a special case.
The patch here reorders the algorithm to look at the name/type scope first if its the first segment
and handle the lower case self as a special case. If this fails to result in a resolved node we
then try to look at …

Support self paths

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-path.h
gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/hir/rust-ast-lower-base.cc
gcc/rust/hir/rust-ast-lower-type.h
gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/rust/resolve/rust-ast-resolve-type.cc
gcc/testsuite/rust/compile/const_generics_2.rs

Needs #1354. Only review the last commit :)
ast: Rename ConstGenericArg -> GenericArg
This makes the class clearer and exposes the fact that it may contain a
type OR a const value clearer.
Because we now run in ambiguous cases later in the compiler pipeline,
this commit also adds horrible hacks to simply ignore ambiguous generic
arguments and treat them as type arguments.

Ambiguous generic arg

---

gcc/rust/util/rust-abi.cc

We use this method to turn the string ABI into the enum. The
rust abi was wrongly turned into the C ABI always which was
causing issues on the mangling logic for extern crate items.

Fix bad ABI from string method

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/expand/rust-macro-builtins.cc
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/lex/rust-lex.cc
gcc/rust/lex/rust-lex.h
gcc/rust/parse/rust-cfg-parser.cc
gcc/rust/parse/rust-parse.h
gcc/rust/rust-buffered-queue.h
gcc/rust/rust-session-manager.cc

This patch allows us to remove the fmemopen lex_string hack to support
parsing buffers. This will allow us to support mutliple sources such as
metadata imports etc. The patch here updates the parser to hold onto a
reference to the lexer rather than 'owning' the lexer which allows us to
decouple the move semantics here.
Fixes #1203 
Fixes #1000

Refactor Lexer to support an abstract InputSource class

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/hir/tree/rust-hir.h
gcc/testsuite/rust/execute/torture/match_tuple1.rs

Initial work on supporting more complex match expressions, starting with tuples. It's proven to be quite a bit more complicated than I originally expected. Still this implementation is very naive, probably very poor performance, and skips all the nuanced stuff like bindings in patterns and pattern guards.
Overview
The general idea is that we lower `MatchExpr`s to `SWITCH_EXPR` trees, but a switch can only operate on one value at a time. When scrutinizing a tuple, we can't build a switch that checks all the elements at once. So instead, just before lowering to trees, we construct a new set of nested match expressions which tests the tuple one element at a time, and is (hopefully) semantically identical to the original match. These new nested matches are simplified, so that each one tests …

Initial support for matches on tuples

---

gcc/rust/backend/rust-tree.cc
gcc/rust/backend/rust-tree.h

Needs #1350. Only review the last [commit](https://github.com/Rust-GCC/gccrs/commit/916576a1904976b137140d5cba2c044593688f03).
Following functions are ported in this changeset:
- [var_in_constexpr_fn](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/constexpr.cc#L5484)
- [member_vec_linear_search](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/name-lookup.cc#L1781)
- [member_vec_binary_search](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/name-lookup.cc#L1759)
- [is_overloaded_fn](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/tree.cc#L2545)
- [ovl_make](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/tree.cc#L2331)
- [lookup_add](https://github.com/Rust-GCC/gccrs/blob/master/gcc/cp/tree.cc#L2476)
- [ovl_first](https://github.com/Rust-GCC/gccrs/blob/master/gcc/c …

 gccrs const folding port: continue porting potential_constant_expression_1()

---

gcc/rust/typecheck/rust-hir-type-check-type.cc
gcc/rust/typecheck/rust-hir-type-check-type.h

This PR finishes the refactoring of `typecheck-resolve-type.h` that had been previously started.

typecheck-resolve-type: Move all remaining definitions

---

gcc/rust/rust-object-export.cc

This function is not used and we don't want to disable optimizations
randomly like this.

remove unused go code

---

gcc/rust/backend/rust-compile-base.cc

- backend: explain why `cdecl` is treated differently when setting up the ABIs

backend: explain why cdecl is treated differently when setting up the ABIs

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/testsuite/rust/compile/issue-1383.rs

When we check for valid types we need to be sure to call destructure which
will extract out any generics so that we are checking the actual concrete
type that is being used here.
Fixes #1383

Support generics in check for valid types in arithmetic expressions

---

gcc/rust/backend/rust-compile-intrinsic.cc

In some testcases in libcore transmute is used on aggregate types like
array's. The convert expression code assumes simple integer's. This this
patch uses a gimple convert_expr to try and convert this type. This might
change to a generic memcpy at somepoint but lets try this first and see how
it works.

Support aggregate types in transmute

---

gcc/rust/util/rust-hir-map.cc

As the move semantics for AST and HIR crates are unsafe on older compilers
we are working around this by storing the pointer into the mappings class
this was using the get method to store the pointer. The issue for loading
extern crates the unique_ptr goes out of scope and this the deletion code
resulting in undefined behaviour. This changes it to call release to take
full ownership of the pointer as we expect.

Fix undefined behaviour using .get on unique_ptr

---

gcc/rust/backend/rust-compile-extern.h
gcc/rust/resolve/rust-ast-resolve-item.cc

When compiling external rust abi item requires the fully qualified
canonical path to be mangled in order to link correctly.

External Items with Rust ABI need to mangle the full path

---

gcc/rust/resolve/rust-ast-resolve-path.cc
gcc/rust/resolve/rust-ast-resolve-type.cc
gcc/rust/util/rust-hir-map.cc
gcc/rust/util/rust-hir-map.h

In order to load and resolve extern crates we need to support detection
of node_id is a crate in order to support paths outside of the current
crate.

Add new interfaces to mappings class

---

gcc/rust/Make-lang.in
gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/lang.opt
gcc/rust/metadata/rust-export-metadata.cc
gcc/rust/metadata/rust-export-metadata.h
gcc/rust/metadata/rust-extern-crate.cc
gcc/rust/metadata/rust-extern-crate.h
gcc/rust/metadata/rust-import-archive.cc
gcc/rust/metadata/rust-imports.cc
gcc/rust/metadata/rust-imports.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/rust-object-export.cc
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h
gcc/testsuite/rust/link/generic_function_0.rs
gcc/testsuite/rust/link/generic_function_1.rs
gcc/testsuite/rust/link/link.exp
gcc/testsuite/rust/link/simple_function_0.rs
gcc/testsuite/rust/link/simple_function_1.rs
gcc/testsuite/rust/link/trait_import_0.rs
gcc/testsuite/rust/link/trait_import_1.rs

WIP still trying to write dejagnu to enable automated tests
Extern crates statements to tell the front-end to look for another library.
The mechanism here is heavily inspired from gccgo, so when we compile a
library for example we invoke:
```
gccrs -g -O2 -frust-crate=mylib -c src/lib.rs -o src/mylib.o
```
All going well this object file will now contain extra data inside
.rust-export section inside the object file which will be preserved inside
archives and shared objects. When we have another application which uses
this library 'mylib'.
```rust
extern crate mylib;
use mylib::foo;
fn main() {
foo();
}
```
We compile using:
```
gcc -g -O2 -frust-crate=test -c src/main.rs -o src/main.o
```
When the extern crate line is hit the front-end will look for mylib.o,
libmylib.a, mylib.rox. If it …

extern crate loading 

---

gcc/rust/backend/rust-compile-extern.h
gcc/testsuite/rust/compile/issue-1323-1.rs
gcc/testsuite/rust/compile/issue-1323-2.rs

When we declare an extern block after where it is used the query
compilation system in the backend code-gen pass will resolve this and
compile as required. But when the iteration of the crate as part of the
pipeline we end up compiling this function again. The check we used to stop
this was copy paste from the other function items but in this case the
check for function_completed is not valid as this is a prototype for an
extern item so we dont add this to the translation unit as an fndecl which
meant we hit the ICE where we compile and add it again.
Fixes #1323

Fix ICE on duplicate compilation of ExternBlock items

---

gcc/rust/hir/rust-hir-dump.cc
gcc/rust/hir/rust-hir-dump.h
gcc/rust/hir/tree/rust-hir-full-decls.h
gcc/rust/hir/tree/rust-hir-visitor.h
gcc/rust/hir/tree/rust-hir.h
gcc/rust/typecheck/rust-hir-type-check-toplevel.cc
gcc/testsuite/rust/compile/const_generics_6.rs

```rust
struct Foo<const N: usize>;
struct Bar<const N: usize = { 15i32 }>; // { dg-error "expected .usize. got .i32." }
```
This PR allows us to typecheck the type of const generics as well as make sure that the optional default expression fits that type

Typecheck const generic params

---

gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/compile/issue-1089.rs
gcc/testsuite/rust/compile/test_mod.rs

When compiling code containing module expansions we must first ensure any
possible inner item attributes are parser first and applied to the module,
otherwise we end up in a bad state and ignore attributes.
Fixes #1089

Ensure we parse any inner item attributes when expanding a module

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/issue-1393.rs

When we want to compile a grouped expression we had a check for the
LEFT_PAREN during the parse_expr_without_block but this can't be handled
here since in this paticular example the grouped expressions is simply the
lhs of the bit shift expression. This is already handled as part of
parse_expr so we can simply remove the rule here and rely on parse_expr
handling this.
Fixes #1393

Fix parsing grammer of grouped expressions as the block tail expression

---

gcc/rust/lex/rust-lex.cc
gcc/rust/rust-session-manager.h
gcc/testsuite/rust/compile/macro-issue1395-2.rs
gcc/testsuite/rust/compile/macro-issue1395.rs

Some tokens such as `try` only became reserved keywords in certain
editions. This behavior might happen again in the future and we should
be able to handle it.
Closes #1395

lexer: Allow specifiying tokens as reserved in certain editions

---

gcc/testsuite/rust/link/link.exp

The recent commit 418aef1b006182e84266dcf4f31ee721ed04301a
"Support extern crate" (merged in
commit fd2bd659e44e5b7fea92bc34a4864f057f387490 "Merge #1362"), added
'gcc/testsuite/rust/link/link.exp', which I understand to be a hacked up
variant of the LTO multi-file testing harness (not reviewed in detail).
Since that commit, there are issues in parallel testing, so that, for example
with:
$ make -j12 check-rust RUNTESTFLAGS='--target_board=unix\{,-m32,-mx32\}'
..., the first variant does test as expected:
@@ -6490,9 +6490,31 @@ PASS: rust/execute/torture/trait9.rs   -Os   at line 13 (test for warnings, line
PASS: rust/execute/torture/trait9.rs   -Os  (test for excess errors)
PASS: rust/execute/torture/trait9.rs   -Os  execution test
PASS: rust/execute/torture/trait9.rs   -Os  output …

'gcc/testsuite/rust/link/link.exp': Fix 'runtest_file_p' usage

---

gcc/rust/hir/rust-ast-lower-base.cc
gcc/rust/lex/rust-codepoint.h
gcc/rust/lex/rust-lex.cc
gcc/rust/rust-session-manager.cc
gcc/rust/util/rust-attributes.cc
gcc/rust/util/rust-attributes.h
gcc/testsuite/rust/compile/torture/check-doc-attr-string.rs
gcc/testsuite/rust/compile/torture/undended-string-1.rs
gcc/testsuite/rust/compile/torture/undended-string-2.rs

This PR adds a new attribute checker visitor. Its role is to take care of validating builtin attributes and their inputs.
This is currently a draft as there are multiple issues:
1. The visitor is not complete
2. The lexer is broken, but was also broken before in that it didn't allow multiline string literals. There is a FIXME asking for how to check for an `EOF` character when parsing UTF-8 strings
3. The checking of attributes is very limited. Currently, only the `#[doc(alias = "...")]` is being checked. This is incomplete.
I'm looking for feedback on the implementation and advice for my issues. Thanks :)

Add Attribute checking visitor

---

gcc/rust/Make-lang.in
gcc/rust/checks/errors/rust-unsafe-checker.cc
gcc/rust/checks/errors/rust-unsafe-checker.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/rust-session-manager.cc
gcc/testsuite/rust/compile/unsafe4.rs
gcc/testsuite/rust/compile/unsafe5.rs

This visitor takes care of checking for unsafe expressions in safe
contexts. This first iteration reports the dereferencing of raw
pointers.

unsafe: Add UnsafeCheck visitor

---

gcc/rust/hir/rust-hir-dump.cc
gcc/rust/hir/rust-hir-dump.h

This is draft PR to track the current implementation of the pretty dumping of HIR. @CohenArthur and I have agreed to keep it as simple as possible for now, and enhancements will be added along the way.

hir/dump: simple dumping of crate attrs and adding a few todos

---

gcc/rust/checks/errors/rust-unsafe-checker.cc
gcc/rust/checks/errors/rust-unsafe-checker.h
gcc/rust/hir/tree/rust-hir-item.h
gcc/rust/hir/tree/rust-hir.h
gcc/testsuite/rust/compile/unsafe1.rs
gcc/testsuite/rust/compile/unsafe2.rs
gcc/testsuite/rust/compile/unsafe3.rs

Addresses #1411 
Accessing an extern static or a mut static is unsafe and requires an unsafe function or block

unsafe: check uses of static variables

---

gcc/rust/Make-lang.in
gcc/rust/checks/errors/rust-const-checker.cc
gcc/rust/checks/errors/rust-const-checker.h
gcc/rust/checks/errors/rust-unsafe-checker.h
gcc/rust/hir/rust-ast-lower-expr.h
gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/rust-session-manager.cc
gcc/rust/util/rust-stacked-contexts.h
gcc/testsuite/rust/compile/const1.rs
gcc/testsuite/rust/compile/const2.rs
gcc/testsuite/rust/compile/const3.rs

This commit serves as a base to ensure that only the allowed subset of
the language is called from const contexts. For example, this limits
function calls to calls to const functions only when in a const context
You can skip reviewing b4864c7e5a59a19fea6203c4b581889d4d6c20a1 as it's the exact same commit cherry-picked from #1415

Const checker

---

.github/workflows/Remark.yml

- CI: fix Remark check (fix #1340)

CI Improvements and fixes

---

gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/expand/rust-attribute-visitor.h
gcc/testsuite/rust/compile/torture/macro-issue1403.rs

- expand: further improves the handling of recursive macros.
Now all the attribute visitor that expands the macro fragment will recursively expand the macro using the unified expanding function `expand_macro_fragment_recursive` instead of expanding the fragment only once.
Fixes #1403

expand: further improves the handling of recursive macros

---

gcc/rust/expand/rust-macro-expand.h
gcc/testsuite/rust/compile/macro-issue1403.rs

- expand: correctly handles non-macro nodes when expanding macros recursively to avoid improperly stripping them
Fixes #1426

expand: correctly handles non-macro nodes

---

gcc/rust/backend/rust-compile-intrinsic.cc
gcc/testsuite/rust/compile/torture/issue-1432.rs

This changes the CONVERT_EXPR to use the same ```*(foo*)&bar``` style cast from
the c front-end to handle the case of:
```
int a[1];
int b = (int)a;
```
Which is converted into:
```
int b = *(int*)&a;
```
which the constant folders can turn directly into int b = a[0];
Fixes #1432

Fix bad transmute for aggregate types

---

gcc/rust/typecheck/rust-hir-type-check-expr.cc
gcc/testsuite/rust/compile/usize1.rs
gcc/testsuite/rust/execute/torture/issue-1436.rs

When we define the core code for SliceIndex access its possible for an
array to be fully coerced into a slice DST and follow the normal slice
index access which removes support for GCC -Warray-index checks and
generates unnessecary code for array access.
Fixes #1436

Array index access does not need to unsize to a slice for access

---

gcc/testsuite/rust/compile/builtin_macro_not_found.rs

- testsuite: test for diagnostics shown when a built-in macro does not exist

testsuite: test for diagnostics shown when a built-in macro does not exist

---

gcc/testsuite/rust/compile/torture/macro-issue1426.rs

... that was recently added in #1429 commit 9fc6a27b5c6ea2c775646c4474b9084da76b1764 "expand: correctly handles non-macro nodes ...".
- Rename 'macro-issue1403.rs' -> 'macro-issue1426.rs'.
- Get rid of '-w'; expect diagnostic instead.
- Get rid of debugging options not relevant here.
- Get rid of explicit '-O1'; make it a "torture" test case.
- Replace always-matching 'scan-assembler "14"' ("14" appears in the crate name) with directed dump scanning.
- ..., just not for '-O0', where such optimization is not done.

Enhance #1426 "Invalid recursive :stmt expansion in fragment specifiers" test case

---

gcc/rust/checks/errors/rust-const-checker.cc
gcc/rust/checks/errors/rust-const-checker.h
gcc/testsuite/rust/compile/const-issue1440.rs
gcc/testsuite/rust/compile/issue-1031.rs
gcc/testsuite/rust/compile/issue-1289.rs
gcc/testsuite/rust/compile/torture/issue-1075.rs
gcc/testsuite/rust/execute/torture/issue-1120.rs
gcc/testsuite/rust/execute/torture/issue-1133.rs
gcc/testsuite/rust/execute/torture/issue-1232.rs
gcc/testsuite/rust/execute/torture/issue-1436.rs
gcc/testsuite/rust/execute/torture/slice-magic.rs
gcc/testsuite/rust/execute/torture/slice-magic2.rs
gcc/testsuite/rust/execute/torture/str-layout1.rs

Since extern functions cannot be marked as const (they take no
qualifiers) but some intrinsics are const, while still being `extern
"rust-intrinsic", we need to be able to handle the
`#[rustc_const_stable]` and `#[rustc_const_unstable]` attribute.
Technically, this simply indicates that a certain intrinsic is constant
and can be used in const contexts, such as `size_of` or `offset`.
We also need to mark all const intrinsics with `rustc_const_stable` in
the testsuite.
Closes #1440

Handle `rustc_const_{un}stable` properly for intrinsics

---

gcc/rust/rust-lang.cc
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h
gcc/rust/rustspec.cc

This removes a lot of code that was simply ported from the Go frontend, and forbids the usage of multiple input files.
Addresses #1115

Cleanup frontend entrypoint

---

gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-tyty-coercion.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/testsuite/rust/compile/issue-1447.rs

This patch set adds fixes to ensure we can type inference generic unit-structs.
Fixes #1447

Fix failiure to type inference on unit-structs

---

gcc/rust/backend/rust-builtins.h
gcc/rust/backend/rust-compile-intrinsic.cc
gcc/rust/backend/rust-compile-intrinsic.h

This will allow us to use the class for more than just math builtins

compile: Move and rename `SimpleIntrinsics` -> BuiltinsContext

---

gcc/rust/backend/rust-compile-intrinsic.cc
gcc/testsuite/rust/compile/torture/intrinsics-2.rs

This commit adds helpers around caching, compiling and using intrinsic
functions before extending them with instructions specific to the
intrinsic. We can refactor them further, but this is already a bit
easier to deal with when writing new intrinsics

intrinsics: Refactor compilation of intrinsics

---

gcc/rust/backend/rust-compile-intrinsic.cc
gcc/testsuite/rust/execute/torture/transmute1.rs

This desugars calls to transmute the following way:
`transmute::<T1, T2>(value)`
->
`*((T2 *) &value)`
This always ends up being optimized into a simple copy for small types
and a memcpy for larger types.

transmute: Fix behavior by always performing the raw copy

---

.github/bors.toml
.github/workflows/ccpp.yml
gcc/testsuite/rust/compile/torture/issue-1432.rs
gcc/testsuite/rust/debug/win64-abi.rs

This is to gate PR's which might break builds on 32bit systems.
Fixes #1439 #871

Add in -m32,-m64 configuration to make check-rust

---

gcc/rust/rust-gcc.cc

When we compiling call expressions the GCC helper has quite a simple
implementation to determine if there are SIDE_EFFECTS we have more
information in the front-end to determine this. This adds a check that
the call expression is deemed to have no side effects ensure we check this
against the fndecl used.
Fixes #1460

Ensure we set TREE_SIDE_EFFECTS on call expressions

---

gcc/rust/rust-gcc.cc

This reverts commit f891a13aa2af912584176d2c595c295b77ff5ff9. This fix
ensures the code is added to the block but still as the artifical function
is marked READONLY it ends up being optimized out anyway.

Revert "Ensure we set TREE_SIDE_EFFECTS on call expressions"

---

gcc/rust/rust-gcc.cc

If we return error_mark_node on a bad expression argument we loss alot of
useful debug info from the error node within the -fdump-tree-original which
saves alot of debug printf.

Dont return error_mark_node on bad CallExpr arguments

---

gcc/rust/backend/rust-compile-intrinsic.cc
gcc/rust/rust-lang.cc
gcc/testsuite/rust/execute/torture/wrapping_op1.rs
gcc/testsuite/rust/execute/torture/wrapping_op2.rs

Since wrapping arithmetics are guaranteed in Rust, we turn on the -fwrapv and simply desugar wrapping_{add, sub, mul} to their non-checked inner operations. This is the only difference between a wrapping add and a regular addition: The regular addition will gain some checks for overflows, which are simply not used for the wrapping version.
Fixes #1449 
@bjorn3 if you want to have a look :)

intrinsics: Add wrapping_{add, sub, mul}

---

gcc/rust/backend/rust-builtins.h
gcc/rust/backend/rust-compile-intrinsic.cc
gcc/testsuite/rust/execute/torture/copy_nonoverlapping1.rs

intrinsics: Add copy_nonoverlapping<T>
This intrinsic is similar to C's memcpy (or in our case, GCC's
__builtin_memcpy) with the order of arguments swapped and knowledge
about the type of the operands. So we can desugar the following calls:
`copy_nonoverlapping::<T>(src, dst, count)`
can be converted to
`__builtin_memcpy(dst, src, count * size_of::<T>())`
~~Sadly, calling this intrinsic results in calls being optimized out for some reason. I'll open a separate issue to deal with that as I don't have the skills to resolve it.~~ fixed by not marking the function's declaration as `TREE_READONLY`
Fixes #1450

intrinsics: Add copy_nonoverlapping<T>

---

gcc/rust/resolve/rust-ast-resolve-item.cc
gcc/rust/resolve/rust-ast-resolve-path.cc
gcc/rust/resolve/rust-ast-resolve-type.cc
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/typecheck/rust-hir-type-check-path.cc
gcc/testsuite/rust/execute/torture/issue-1249.rs

The issue here was that our name resolution assumed qualified path always
has an as clause. We also had missing visitors to generate the canonical path
for impl blocks using dynamic trait objects.
We should investigate implementing the fine-grained visitors for the AST
similar to the ones we have for HIR. This will solve the issue where we
have missing visitors.
Fixes #1249

Fix ICE in dyn impl block

---

gcc/rust/backend/rust-constexpr.cc
gcc/testsuite/rust/compile/const4.rs

This adds in missed ported code for handling VAR_DECLS and jump's within
statement lists.

Fix up missing jump_target handling

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h

Let's abuse C++ a little bit to make dumping and the chaining of dumping operations easier. If anyone has input feel free, this is definitely a roundabout way to go about it.
This also adds pretty printing of the expanded AST, which can be useful to debug macros or `cfg` invocations

Improve AST dump

---

gcc/rust/util/rust-attributes.cc
gcc/testsuite/rust/compile/rustc_attr1.rs

We cannot yet handle this attribute, but we should not reject it either.

rustc_attrs: Allow `rustc_inherit_overflow_checks` as a builtin attribute

---

gcc/rust/expand/rust-macro-expand.cc
gcc/rust/expand/rust-macro-expand.h
gcc/testsuite/rust/compile/macro43.rs

This fixes an issue encountered when trying to compile libcore 1.29

macros: Handle matchers properly in repetitions

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/parse_range.rs

Previously the parser would emit the errors despite later allowing the parsed expression to be null.

parser: Parse RangeFullExpr without erroring out

---

gcc/rust/ast/rust-ast-dump.h
gcc/rust/ast/rust-ast.h
gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/expand/rust-macro-expand.cc

Needs #1513, Skip reviewing the first commit

Fix SEGV in transcribe_type when compiling libcore 1.29

---

.github/bors_log_expected_warnings
gcc/diagnostic-core.h
gcc/diagnostic.cc
gcc/rust/rust-diagnostics.cc
gcc/rust/rust-diagnostics.h
gcc/rust/rust-gcc-diagnostics.cc
gcc/rust/typecheck/rust-casts.cc
gcc/testsuite/rust/compile/bad_as_bool_char.rs

rustc has error codes to identify specific errors, with URLs documenting each error.
In GCC 13 I've extended GCC's diagnostic subsystem so that a diagnostic can be associated with zero or more `diagnostic_metadata::rule` instances, which have a textual description and a URL.  I meant this for rules in coding standards and specifications, but it struck me that potentially gccrs could reuse the same error codes as rustc.
The following pull request implements an experimental form of this; I picked a single error at random: [E0054](https://doc.rust-lang.org/error-index.html#E0054).  
With this patch, gccrs emits e.g.:
```
bad_as_bool_char.rs:8:19: error: invalid cast [u8] to [bool] [E0054]
8 |   let nb = 0u8 as bool;
|            ~      ^
```
where the trailing [E0054] is colorized, and, in a …

Experiment: add optional error codes to diagnostics

---

gcc/rust/backend/rust-builtins.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-item.cc
gcc/rust/backend/rust-compile-type.cc
gcc/rust/rust-backend.h
gcc/rust/rust-gcc.cc
gcc/rust/rust-gcc.h
gcc/testsuite/rust/debug/win64-abi.rs
gcc/testsuite/rust/execute/torture/macro-issue1426.rs
gcc/testsuite/rust/execute/torture/overflow1.rs

Opening as a draft since the code is really ugly and some tests still fail. I am looking for feedback on the implementation and my approximative use of functions like `temporary_variable` which I feel I might be using the wrong way.
I'll open up an issue of what still needs to be done, namely:
I'll open up some PRs to clean up some parts of the backend as well.

Add overflow traps

---

gcc/rust/checks/lints/rust-lint-scan-deadcode.h
gcc/testsuite/rust/compile/issue-1031.rs
gcc/testsuite/rust/compile/issue-1289.rs
gcc/testsuite/rust/compile/privacy7.rs
gcc/testsuite/rust/compile/test_mod.rs
gcc/testsuite/rust/compile/torture/raw_identifiers.rs
gcc/testsuite/rust/compile/torture/raw_identifiers_keywords.rs

This fixes the overzealous warnings on public items from the unused pass

lint: Do not emit unused warnings for public items

---

gcc/rust/typecheck/rust-autoderef.cc
gcc/rust/typecheck/rust-coercion.cc
gcc/rust/typecheck/rust-hir-dot-operator.cc
gcc/rust/typecheck/rust-hir-trait-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-base.cc
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-hir-type-check-enumitem.cc
gcc/rust/typecheck/rust-hir-type-check-expr.cc
gcc/rust/typecheck/rust-hir-type-check-expr.h
gcc/rust/typecheck/rust-hir-type-check-implitem.cc
gcc/rust/typecheck/rust-hir-type-check-item.cc
gcc/rust/typecheck/rust-hir-type-check-path.cc
gcc/rust/typecheck/rust-hir-type-check-pattern.cc
gcc/rust/typecheck/rust-hir-type-check-stmt.cc
gcc/rust/typecheck/rust-hir-type-check-struct.cc
gcc/rust/typecheck/rust-hir-type-check-toplevel.cc
gcc/rust/typecheck/rust-hir-type-check-type.cc
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-tyctx.cc
gcc/rust/typecheck/rust-tyty-call.cc
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty-rules.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/issue-1152.rs
gcc/testsuite/rust/compile/tuple1.rs
gcc/testsuite/rust/compile/type-alias1.rs
gcc/testsuite/rust/execute/torture/operator_overload_9.rs
gcc/testsuite/rust/execute/torture/slice1.rs

This is the first pass on a refactor for error handling on unify sites. Eventually we
will be able to get rid of our can_eq interface but this is the first pass to abstract
unify's to use this interface.
Eventually, we will have unify and unify_and_commit. Unify will become our can_eq
interface but will require more helpers around inference variables.

Refactor error handling on unify

---

gcc/rust/backend/rust-compile-base.cc
gcc/rust/backend/rust-tree.cc

In order to compile a block expression constant, the simplest way for us
was to reuse what code we have and to generate an artifical function which
does not get added to the translation unit. The constant then becomes
a CALL_EXPR to this artifical function which we can pass to the constexpr
evaluator to resolve the result of this artifical 'CALL_EXPR'.
Before this patch we seperated the difference between block expressions
and non block expressions in constants. So for non block expressions we
simply compiled them as if it was a simple constant but this is not
guaranteed to be the case in rust, for example coercion sites can generate
temporaries during autoderef which we let the constant evaluator resolve
for us. This makes all constants handled in the same way to simplify the
logic here.

Create canonical process of compiling constant items

---

gcc/rust/backend/rust-compile-expr.cc
gcc/testsuite/rust/execute/torture/loop-condition-eval.rs

- backend: correctly formulate the exit condition. Previously the exit condition was treated the same as the loop condition (which is the inverse condition of the exit condition). Now, this is corrected.
Should fix #1523

backend: correctly formulate the exit condition

---

gcc/rust/backend/rust-compile-item.cc
gcc/rust/backend/rust-tree.cc
gcc/rust/typecheck/rust-hir-type-check-toplevel.cc
gcc/testsuite/rust/compile/rust-const-blog-issue.rs

This adds a test case for the rust issue: https://blog.rust-lang.org/2022/09/15/const-eval-safety-rule-revision.html

Static const eval safety

---

gcc/rust/util/rust-attributes.cc
gcc/testsuite/rust/compile/macro_export_1.rs

Fixes #1531 
I think the checking for builtin attributes should definitely be moved to the `AttributeChecker` visitor. It's also a bit messy at the moment considering it isn't in effect on *everything*, simply some nodes such as `Module`s. Thoughts?

attributes: Add #[macro_use] as builtin

---

gcc/rust/lang.opt
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h
gcc/testsuite/rust/compile/frust-compile-until.rs

This option helps ensure that we do not introduce regressions on various
parts of the compilation pipeline. For example, a testcase (or testsuite
from the `testing` project) might pass attribute checking, expansion and
lowering, but fail during typechecking. Should a change suddenly make
that testcase fail expansion, we would not be able to notice it. By
generating tests that run up until expansion, typechecking, compilation
and so forth we ensure that no regressions are added accidentally to
already failing tests/testsuites.

rust: Add -frust-compile-until option

---

gcc/rust/hir/rust-ast-lower-item.cc
gcc/testsuite/rust/compile/macro44.rs

Some module items do not need to get lowered to HIR such as `macro_rules!` definitions. Hence, module lowering should act the same as crate lowering: Only emplace back the lowered item if it is a valid pointer
Fixes #1533

module lowering: Do not append null pointers as items

---

gcc/rust/typecheck/rust-hir-type-check-base.cc
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-tyty-bounds.cc

When we have a type query where by generic substitution occurs we can hit the case where we need to Probe the bounds of the substited item to determine whether the the bounds are compatible this can cause us to end up querying the same type recursively.
Fixes #1550

Add catch for recusive type queries

---

gcc/rust/lang.opt
gcc/rust/rust-lang.cc

@tschwinge if your patch lands first I'll happily revert that and use `LangInit`

Fix -Wunused using `rust-lang.cc` hack

---

gcc/rust/backend/rust-builtins.cc
gcc/rust/backend/rust-compile-intrinsic.cc
gcc/testsuite/rust/execute/torture/prefetch_data.rs

Addresses #658 
Needs #1564 so only review the last commit
This PR implements the two intrinsics related to data prefetching. I have to say, since these are hints for the backend, I am unsure if the current implementation is right. I believe it should be.

Implement data prefetch intrinsics

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/missing_closing_paren.rs

Fix crash (segfault) on a missing closing parenthesis when parsing the expressions in a block. The returned `expr` was missing a check before being used.
Add corresponding test.

fix ICE on missing closing paren

---

gcc/rust/util/rust-abi.cc
gcc/rust/util/rust-lang-item.h

Adds the missing fn_once lang item and the missing rust-call abi option.

Add missing lang item mappings

---

gcc/rust/backend/rust-compile.cc
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-tyty.cc

When checking if specified bounds satisfy other bounds we must lookup the super traits. To finish the support for super traits we need to redo the computation of method addresses to support super traits.
Addresses #914

Support type resolution on super traits on dyn objects

---

gcc/rust/typecheck/rust-autoderef.cc
gcc/rust/typecheck/rust-hir-dot-operator.cc
gcc/rust/typecheck/rust-hir-dot-operator.h
gcc/rust/typecheck/rust-hir-inherent-impl-overlap.h
gcc/rust/typecheck/rust-hir-type-check-expr.cc
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/generics7.rs
gcc/testsuite/rust/execute/torture/operator_overload_9.rs

This patch fixes bad method resolution in our operator_overload_9 case.
When we have a &mut reference to something and we deref we must resolve to
the mutable reference impl block. The interface we are using to resolve
methods is the can_eq interface which allows for permissive mutability
which means allowing for mutable reference being unified with an immutable
one. This meant we actual match against both the immutable and mutable
version leading to multiple candidate error.
Fixes #1588

Method resolution must support multiple candidates

---

gcc/rust/ast/rust-ast-dump.cc

This PR adds new AST dump visitors for several nodes, and cleans up some minor formatting issues in blocks without tail expressions and if expressions.

AST: more dump improvements

---

gcc/rust/typecheck/rust-hir-trait-resolve.cc
gcc/rust/typecheck/rust-hir-type-check.h
gcc/testsuite/rust/compile/issue-1589.rs

This adds a new RAII style TraitQueryGuard so that we can manage the query lifetime when resolving a trait. This adds in a DefId into a set when we begin to resolve and then finally removes it when completed. This allows us to add in a check at the start if this DefId is already within the set which means this is a trait cycle.
Fixes #1589

Add check for recursive trait cycles

---

gcc/config.gcc
gcc/config/dragonfly-rust.cc
gcc/config/freebsd-rust.cc
gcc/config/fuchsia-rust.cc
gcc/config/linux-rust.cc
gcc/config/netbsd-rust.cc
gcc/config/openbsd-rust.cc
gcc/config/sol2-rust.cc
gcc/config/t-dragonfly
gcc/config/t-freebsd
gcc/config/t-fuchsia
gcc/config/t-linux
gcc/config/t-netbsd
gcc/config/t-openbsd
gcc/config/t-sol2
gcc/config/t-vxworks
gcc/config/t-winnt
gcc/config/vxworks-rust.cc
gcc/config/winnt-rust.cc

Pretty much all follow the same template as how darwin was added in the first commit, so mostly uninteresting.
The only slight deviation is with `*-*-linux*`, where rather than putting it in a common `glibc-rust.cc` file, I've instead opted to force each platform have their own source file. So Linux gets a `linux-rust.cc` file, and anyone who wants to add Hurd, kFreeBSD, or kOpenSolaris later can do so by adding a case to this switch with the appropriately named file (i.e: `gnu-rust.cc` for Hurd).
The same can also be said for MinGW targets - `winnt-rust.cc` is explicitly _not_ set for Cygwin, and I'd prefer that whoever does add Cygwin support will create a separate file for it - otherwise you've either got to modify the target headers to add whatever defines you need in order to …

Add more implementations for TARGET_RUST_OS_INFO

---

gcc/rust/backend/rust-compile-intrinsic.cc
gcc/testsuite/rust/compile/torture/intrinsics-3.rs

This allows us to define intrinsics without implementing their body. This will be useful for atomic intrinsics for example, as there are a lot of them and we should work on implementing them one by one properly and slowly

intrinsics: Add rust_sorry wrapper for unimplemented intrinsics

---

gcc/rust/backend/rust-builtins.cc
gcc/rust/backend/rust-builtins.h
gcc/rust/backend/rust-compile-intrinsic.cc
gcc/testsuite/rust/compile/torture/intrinsics-4.rs
gcc/testsuite/rust/compile/torture/intrinsics-5.rs
gcc/testsuite/rust/execute/torture/atomic_store.rs

Needs #1614 so ignore the first commit
This commit adds support for three `atomic_store_*` intrinsics declared
in the core library. The mapping is as follows:
- atomic_store_seqcst(dst, val) -> __atomic_store_n(dst, val,
__ATOMIC_SEQ_CST)
- atomic_store_relaxed(dst, val) -> __atomic_store_n(dst, val,
__ATOMIC_RELAXED)
- atomic_store_release(dst, val) -> __atomic_store_n(dst, val,
__ATOMIC_RELEASE)
The one remaining question is whether `atomic_store_unordered` can be
abstracted as an atomic store with the __ATOMIC_RELAXED ordering.
This commit also performs the overloading "by hand": Replacing
`atomic_store_release<i32>` with `__atomic_store_4` as I cannot get the
generic version to work. This will be done in future improvements.

intrinsics: Add early implementation for atomic_store_{seqcst, relaxed, release}

---

gcc/rust/parse/rust-parse-impl.h

`pattern` is a `unique_ptr`, which should be set to NULL once `std::move`d, hence causing the ICE as we were dereferencing a NULL pointer to get its location.
Addresses #1612 
This should also help bring the MacOS build back to green

parser: Fix ICE in closure parsing

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h

Unifies all methods to overloads of the visit method and adds new helpers for common patterns (join by separator, visit as lines...)

Ast dump refactor

---

gcc/rust/typecheck/rust-tyty-call.cc

I'm hoping this fixes the MacOS problem

typecheck: Fix overzealous `delete` call

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-item.h
gcc/rust/ast/rust-type.h

Adds dump of the where clause and recursively needed nodes.
Adds visitor compatibility layer for general references except for unique pointers - needed for lifetimes. The enable is necessary to coexist with the unique_ptr overload.
Depends on #1624 and will be rebased when it is merged.

Ast dump where clause

---

gcc/dwarf2out.cc
gcc/testsuite/rust/debug/oldlang.rs

DW_LANG_Rust_old is a non-standard DWARF language code used by old rustc compilers before DWARF5 (released in 2017). Just always emit DW_LANG_Rust unless producing strict DWARF for versions before 5. And in that old strict DWARF case just emit DW_LANG_C instead of a non-standard language code.

dwarf2out.c: Don't emit DW_LANG_Rust_old

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/ast/rust-ast-full-test.cc
gcc/rust/ast/rust-type.h

- N\A - Added any relevant test cases to `gcc/testsuite/rust/`
---
Add/fix AST dump of types incl. generic parameters.

AST dump types

---

.github/workflows/bootstrap.yml
.github/workflows/ccpp.yml

This is a temporary solution since the gcc-patch-dev branch will eventually disappear in favor of another upstreaming strategy

ci: Remove warning checks on gcc-patch-dev

---

gcc/rust/backend/rust-compile-expr.cc

8e52e414f40b: Use build_int_cstu for size expressions

---

gcc/rust/backend/rust-constexpr.cc

58e75f65e56d: Remove HOST_WIDE_INT struct member

---

gcc/rust/backend/rust-compile-expr.cc
gcc/rust/rust-gcc.cc

Use `wide_int_to_tree` instead of `double_int_to_tree`

---

gcc/rust/backend/rust-builtins.cc
gcc/rust/backend/rust-builtins.h
gcc/rust/backend/rust-compile-intrinsic.cc
gcc/rust/rust-gcc.cc
gcc/testsuite/rust/compile/torture/intrinsics-4.rs
gcc/testsuite/rust/execute/torture/atomic_load.rs
gcc/testsuite/rust/execute/torture/atomic_store.rs

This PR adds proper GCC-like handling of builtins, which allows us to not re-define all the builtins we use and fight with declaring the types each time.
This is also safer and works better. Sadly, this has unearthed some problems in our handling of builtins, specifically the ones I've added recently (atomic ones and data prefetching). These are the two issues that remain for this PR to be in a nice state which does not cause regressions:
1. `atomic_{store, load}` (and maybe cmp_xchg) do not work on signed integers. I'm currenty working around this by simply using `u32`s instead of `i32`s for the tests, but that's not a valid solution. These intrinsics need to work on all integer types and I will thus need to add some conversions from `i*` to `u*` before calling the intrinsics. The upside …

Cleanup builtin handling

---

gcc/rust/Make-lang.in

... addressing #1626, <https://inbox.sourceware.org/gcc-patches/CAFiYyc1NQT+bBZXALTs7Qhc-ECbKKBt1tVKip_6C241y3ozT6w@mail.gmail.com>.

'rust-warn += -Wno-unused-parameter'

---

gcc/rust/backend/rust-compile-context.cc
gcc/rust/backend/rust-compile-context.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/backend/rust-compile-type.cc
gcc/rust/resolve/rust-ast-resolve-expr.cc
gcc/rust/resolve/rust-ast-resolve-implitem.h
gcc/rust/resolve/rust-ast-resolve-item.cc
gcc/rust/resolve/rust-ast-resolve-pattern.cc
gcc/rust/resolve/rust-ast-resolve-pattern.h
gcc/rust/resolve/rust-ast-resolve-stmt.h
gcc/rust/resolve/rust-ast-resolve-toplevel.h
gcc/rust/resolve/rust-ast-resolve-type.h
gcc/rust/resolve/rust-name-resolver.cc
gcc/rust/resolve/rust-name-resolver.h
gcc/rust/typecheck/rust-hir-type-check-expr.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/execute/torture/closure3.rs

This patch set adds the initial support closure captures, move semantics are not
handled here. We track what variables are being captured by a closure during
name resolution so that when a VAR_DECL is resolved, we check if we are inside
a closure context node_id which is the same id as its associated rib id. So when
we resolve a name that resides in an outermost rib we can add this to set of 
node-id's that are captured by this closure.
There is a gap here for the case where we need to check if it is inside a nested
function and that function contains closures which could wrongly capture variables
in the enclosing function. This will also be a problem for nested functions in general.
Fixes #195

Initial state capture for closures

---

gcc/rust/hir/tree/rust-hir-expr.h
gcc/rust/hir/tree/rust-hir-full-decls.h
gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/typecheck/rust-hir-type-check-expr.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/debug/chartype.rs

When applying generic arguments to method calls such as:
```receiver.method_name<i32, bool>()```
This ended up wrongly using the default constructor with an empty generic arguments which seems
like a possible bug in the new version of clang. This explicitly sets up all relevant copy constructors
for HIR::PathExprSegment and removes the defaults.

Fix mac-os regression in apply generic arguments to method calls

---

.github/workflows/bootstrap.yml
.github/workflows/ccpp.yml

This locks all of our CI images to Ubuntu-20.04.
This should be upgraded eventually to 22.04, in time. I'll open up an issue to accompany it.
All of yesterday's PRs will need to be rebased on master once this is merged

ci: Lock Ubuntu version to 20.04

---

gcc/rust/lang.opt

... lost in #1527 commit 138a6260124740208b8f3aff2e38617f43b05fe8
"rust: Add -frust-compile-until option".

Repair 'gcc/rust/lang.opt' comment

---

gcc/cp/call.cc
gcc/testsuite/g++.dg/warn/Wdangling-reference5.C

As had also been reported in <https://gcc.gnu.org/PR107633> "Bootstrap failure due to -Werror=unused-parameter and -Werror=dangling-reference", GCC `--enable-bootstrap` build is currently broken:
[...]/gcc/rust/backend/rust-compile-expr.cc: In member function ‘tree_node* Rust::Compile::CompileExpr::resolve_method_address(Rust::TyTy::FnType*, Rust::HirId, Rust::TyTy::BaseType*, Rust::HIR::PathIdentSegment&, Rust::Analysis::NodeMapping, Location)’:
[...]/gcc/rust/backend/rust-compile-expr.cc:2019:13: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
2019 |       auto &candidate = *candidates.begin ();
|             ^~~~~~~~~
[...]/gcc/rust/backend/rust-compile-expr.cc:2019:44: note: the temporary was destroyed at the end of the full expression …

Backport "c++: Quash -Wdangling-reference for member operator* [PR107488]"

---

gcc/rust/Make-lang.in

The Make-lang.in was missing the link serialization support.
PR rust/108113
gcc/rust
* Make-lang.in (rust.serial): New variable. 
(rust1$(exeext)): Depend on $(rust.prev). Call LINK_PROGRESS.

rust: fix link serialization [PR108113]

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/bounds.rs

This patch adds parsing for generic parameters like: <F: Foo<Bar: Foo>>. In current version, this pattern  leads to endless loop.

rust: add bound parsing in parse_generic_arg.

---

gcc/rust/checks/errors/rust-unsafe-checker.cc
gcc/rust/checks/errors/rust-unsafe-checker.h
gcc/rust/util/rust-attributes.cc
gcc/testsuite/rust/compile/unsafe11.rs

The `target_feature` attribute is for conditional compilation and may or may not compile on all platforms. Using it requires an unsafe function or block.
Addresses #1411

unsafe: check use of `target_feature` attribute

---

CONTRIBUTING.md
README.md
gcc/rust/lang.opt
gcc/rust/lex/rust-token.h
gcc/rust/parse/rust-parse-impl.h

Addresses #1680 
Fixes #1680 
Probably does not need a changelog since I assume this commit will just be dropped when we merge

format: Fix git whitespace errors

---

gcc/rust/hir/tree/rust-hir-path.h
gcc/rust/resolve/rust-ast-resolve-type.cc
gcc/rust/typecheck/rust-hir-path-probe.h
gcc/rust/typecheck/rust-hir-trait-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-expr.cc
gcc/rust/typecheck/rust-tyty-bounds.cc
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/bounds.rs
gcc/testsuite/rust/execute/torture/issue-1720.rs

This patch set adds support to specify the associated type via the argument
binding syntax. We are still missing general bounds checking so in order to
properly add more test cases for bad types we need to implement that first.
I have also changed a test case to -fsyntax-only as at the time I always get
confused between Generic arguments of foo=i32 and bar: baz only specifies
the associated type and the latter adds a bound. Currently we are lacking a
way to represent adding a bound in the AST and HIR within generic arguments
so I have raised: #1725 and #1726
Fixes #1720

Add support for generics associated type binding

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-expr.h
gcc/rust/ast/rust-macro.h

This commit adds virtual function get_locus to base class MetaItemInner, which is helpful when we need to print  diagnostics on some sub-classes of MetaItemInner.
This commit is split from pr https://github.com/Rust-GCC/gccrs/pull/1718.
Signed-off-by: Xiao Ma <mxlol233@outlook.com>

Add get_locus function for abstract class MetaItemInner.

---

gcc/rust/lex/rust-lex.cc
gcc/testsuite/rust/compile/diagnostic_underline.rs

Currently, the diagnostics only point to the corresponding token's start position by carets, and lack of underlines for full token.  This commit add support for such underlines in diagnostics by encoding range information in location_t.
the results like this:
```
../gcc/testsuite/rust/compile/bad_as_bool_char.rs:5:14: error: invalid cast 'bool' to 'f32' [E0054]
5 |   let fone = t as f32;   // { dg-error "invalid cast" }
|              ^    ~~~
../gcc/testsuite/rust/compile/bad_as_bool_char.rs:6:15: error: invalid cast 'bool' to 'f64' [E0054]
6 |   let fzero = f as f64;  // { dg-error "invalid cast" }
|               ^    ~~~
../gcc/testsuite/rust/compile/bad_as_bool_char.rs:8:12: error: invalid cast 'u8' to 'bool' [E0054]
8 |   let nb = 0u8 as bool;  // { dg-error "invalid cast .u8. to …
```

diagnostics: Add underline for tokens in diagnostics.

---

gcc/rust/backend/rust-compile-base.cc
gcc/rust/backend/rust-compile-var-decl.h

This allows patterns to declare multiple/no variables
---

Change how CompileVarDecl outputs Bvariable's

---

.github/workflows/commit-format.yml

@philberty what do you think of this? The commits are intentionally "wrong" so that the CI fails and shows the output. Let me know if you think it's good.
I looked into having the action post a comment on the PR but it's more annoying than I thought to do it directly in the github action and still have nice formatting or posting files and a message at once, etc... and I think having an actual bot could be nicer for this.

Add CL checking automation to gcc-patch-dev

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/rust-session-manager.cc
gcc/rust/rust-session-manager.h

* ast/rust-ast-dump.cc (Dump::go): Switch single character string to character
(Dump::emit_attrib): Merge two pretty-print characters in one string
(Dump::emit_indented_string): New
(Dump::visit): Add missing visitors, refactor dumping of operators
(Dump::format_function_common): Refactor
* ast/rust-ast-dump.h: Add documentation for `emit_indented_string`
and
* rust-session-manager.cc (Session::compile_crate): Allow the dump of prettified AST
(Session::dump_ast_pretty): New
* rust-session-manager.h: Add new output file for pretty AST dump
This PR should serve as a tryout for updating Changelog entries in previous, non-upstreamed commits.
I assume the best course of action will be to update `gcc-patch-dev` to the current state of the GCC master …

[CL] First update Changelog tryout: Updating AST dump

---

gcc/rust/backend/rust-compile-base.cc
gcc/rust/backend/rust-compile-intrinsic.cc
gcc/rust/backend/rust-constexpr.cc
gcc/rust/backend/rust-constexpr.h
gcc/rust/backend/rust-tree.cc
gcc/rust/backend/rust-tree.h
gcc/testsuite/rust/compile/const4.rs
gcc/testsuite/rust/compile/const5.rs

```
gccrs: const folding port
This changeset ports cp_global_trees structure which is used throughout the
cp constexpr.cc code. I am not sure what it's purpose is but it seems it is used
to add and manipulate tree information during the c++ compilation process.
It is possible this is not needed in the Rust code and may be taken out later.
Also, the initialization function isn't being called from anywhere yet, so
we will need to find a suitable point for it.
* backend/rust-tree.cc : Add new includes.
(scope_chain): New.
(maybe_add_global): New.
(init_modules): New (copied from cp)
(var_in_constexpr_fn): Likewise.
(member_vec_linear_search): Likewise.
(member_vec_binary_search): Likewise.
(is_overloaded_fn): Likewise.
(ovl_make): Likewise.
(lookup_add): Likewise. …
```

[CL] gccrs: const folding port

---

README.md

(1) There is a need of the flag "-frust-incomplete-and-experimental-compiler-do-not-use" because the rust1 compiler didn't work without this.
(2) The gccrs was not present in the $HOME/gccrs-install/, so updated the path to $HOME/gccrs-install/bin
Signed-off-by: MAHAD <mahadtxt@gmail.com>

README.md: Added experimental flag & updated gccrs path

---

gcc/rust/resolve/rust-ast-resolve-pattern.h

Adds support for GroupedPattern during name resolution.
Addresses #1136

Support GroupedPattern during name resolution

---

gcc/rust/expand/rust-macro-expand.cc
gcc/testsuite/rust/compile/macro45.rs

This PR fixes a compiler crash when expanding an empty macro into an existing AST.
(I ran clang-format but it marked a few other files as dirty, and I therefore did not touch them)
Signed-off-by: Lyra Karenai <teromene@teromene.fr>
Fixes #1712

Do not crash on empty macros expand. Fixes #1712

---

gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/typecheck/rust-hir-type-check-pattern.cc

Adds type resolution for GroupedPattern.

Add type resolution for grouped patterns

---

gcc/rust/backend/rust-compile-pattern.cc
gcc/rust/backend/rust-compile-pattern.h

Implements some missing visitor methods for GroupedPattern compilation.

Added missing GroupedPattern visitors for code generation

---

gcc/testsuite/lib/rust.exp

* Fixes issue #1747 
**Remove the 10-second timeout for each compile case**

Revert 10-second timeout for each test

---

gcc/rust/ast/rust-macro.h
gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/parse/rust-parse-impl.h

* ast/rust-macro.h (enum class): Add `BuiltinMacro` enum class
* expand/rust-attribute-visitor.cc (AttrVisitor::visit): Mention switching on `macro.kind` once builtin macro invocations are properly handled
* parse/rust-parse-impl.h (Parser::parse_macro_invocation): Switch to new MacroInvocation API
(Parser::parse_type): Switch to new MacroInvocation API
(Parser::parse_type_no_bounds): Switch to new MacroInvocation API
This will be necessary for proper handling of builtin macros with the new `EarlyNameResolver` class and associated fixed-point algorithm

macro: Allow builtin `MacroInvocation`s within the AST

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/issue-867.rs

Signed-off-by: Abdul Rafey <abdulrafeyq@gmail.com>
fixed compiler error message on wildcard pattern '_'  within expression.
Added a new testcase for the same.
#867

fixed compiler error message on wildcard pattern within expression

---

.github/workflows/commit-format.yml

Bring over the commit checker from `gcc-patch-dev` with the `gccrs` prefix checker enabled only for `gcc-patch-dev` PRs. I'll open up an issue to make sure that in the future it's easier to keep that folder in sync between the two branches

ci: Add commit format checker

---

gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/compile/multi_reference_type.rs

The parser now recursively tries to parse a reference type after seeing a `&` or `&&` token.
* parse/rust-parse-impl.h (Parser::parse_type): Handle double ampersan properly (Parser::parse_reference_type): Call into `parse_reference_type_inner` and wrap double reference types in another `AST::ReferenceType` node (Parser::parse_reference_type_inner): Add parsing implementation which does not care about the leading token (& or  &&) (Parser::parse_type_no_bounds): Handle double ampersand properly
* parse/rust-parse.h: Declare `parse_reference_type_inner`
* rust/compile/multi_reference_type.rs: New test.
Addresses #1807 partly

parser: Allow parsing multiple reference types

---

gcc/rust/Make-lang.in
gcc/rust/checks/errors/rust-feature-gate.cc
gcc/rust/checks/errors/rust-feature-gate.h
gcc/rust/checks/errors/rust-feature.cc
gcc/rust/checks/errors/rust-feature.h
gcc/rust/rust-session-manager.cc
gcc/testsuite/rust/compile/feature.rs

This commit implements a very basic feature checking module.
The results like this:
```
../gcc/testsuite/rust/compile/feature.rs:1:12: error: unknown feature 'AA'
1 | #![feature(AA)] //{ dg-error "unknown feature 'AA'" }
|            ^
```
This commit is split from pr https://github.com/Rust-GCC/gccrs/pull/1718.
Signed-off-by: Xiao Ma <mxlol233@outlook.com>

Add  support for feature check.

---

gcc/rust/ast/rust-pattern.h
gcc/rust/hir/rust-ast-lower-pattern.cc
gcc/rust/hir/rust-ast-lower-pattern.h
gcc/rust/hir/tree/rust-hir-full-test.cc
gcc/rust/hir/tree/rust-hir-pattern.h

* ast/rust-pattern.h (ReferencePattern::get_has_two_amps): Add method. (ReferencePattern::get_is_mut): Add method.
* hir/rust-ast-lower-pattern.cc (ASTLoweringPattern::visit): Add ReferencePattern visitor.
* hir/rust-ast-lower-pattern.h (ASTLoweringPattern::visit): Add ReferencePattern visitor.
Partially addresses #1813

Implement lowering ReferencePattern from AST to HIR

---

.github/bors.toml
.github/workflows/commit-format.yml

ChangeLog:
* .github/bors.toml: Add commit checkers.
* .github/workflows/commit-format.yml: Rename commit checker jobs.
Fixes #1790

ci: Require commits check to pass for bors to merge and fix CI names

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile-resolve-path.cc
gcc/rust/typecheck/rust-hir-path-probe.h
gcc/rust/typecheck/rust-hir-trait-ref.h
gcc/rust/typecheck/rust-hir-type-check-enumitem.cc
gcc/rust/typecheck/rust-hir-type-check-item.cc
gcc/rust/typecheck/rust-hir-type-check-path.cc
gcc/rust/typecheck/rust-hir-type-check-type.cc
gcc/rust/typecheck/rust-tyty.h
gcc/testsuite/rust/compile/torture/issue-1555.rs

Addresses #1705
Originally #1762 by @dkm 
But since updating gcc-patch-dev, this is throwing weird conflicts that I'd like to avoid fixing in fear of breaking something down the line. Cherry-picking the original commits works fine. I've reused the changelogs from #1762.

[CL] 24e9bd9..b3fcf32

---

.github/bors.toml

ChangeLog:
* .github/workflows/commit-format.yml: Run job on pushes to `trying`.
This should hopefully stop bors from timing out.

ci: Run commit format checker on push to `trying` branch

---

gcc/rust/rust-session-manager.cc

The compiler's warning message about the safety flag did not match cargo-gccrs environment variable name anymore.
* rust-session-manager.cc (Session::compile_crate): Update the environment variable name.
Signed-off-by: Pierre-Emmanuel Patry <pierre-emmanuel.patry@embecosm.com>
Fixes #1829

cli: Update safety warning message

---

gcc/rust/ast/rust-ast-dump.cc

fixes #1785 
Signed-off-by: Abdul Rafey <abdulrafeyq@gmail.com>
---
In Dump::visit (TraitImpl), the for loop adds indentation before calling visit () on every iteration. I think when Dump::visit (Method) is executed it adds extra indentation on top of it.

fixed indentation in AST pretty printed expanded dump of trait.

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/parse_complex_generic_application.rs
gcc/testsuite/rust/compile/parse_complex_generic_application2.rs

The parser was missing code for handling complex type arguments such as type paths or nested generics.
* parse/rust-parse-impl.h (Parser::parse_generic_arg): Handle type paths and nested generics properly.
* rust/compile/parse_complex_generic_application.rs: New test.
* rust/compile/parse_complex_generic_application2.rs: New test.

parser: Improve parsing of complex generic arguments

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/closure_move_expr.rs

* parse/rust-parse-impl.h (Parser::parse_closure_expr): Advance tokens properly when parsing closure param list.
* rust/compile/closure_move_expr.rs: New test.

parser: Fix parsing of closure param list

---

gcc/rust/Make-lang.in
gcc/rust/typecheck/rust-hir-trait-reference.cc
gcc/rust/typecheck/rust-hir-trait-reference.h

Move function body to their own cc file instead of keeping them in the header file.
* Make-lang.in: Add `rust-hir-trait-reference.o`.
* typecheck/rust-hir-trait-reference.h: Remove multiple function body.
* typecheck/rust-hir-trait-reference.cc: Add multiple function body.
Fixes #1835

typecheck: Refactor rust-hir-trait-reference.h

---

.github/workflows/bootstrap.yml
.github/workflows/ccpp.yml
.github/workflows/clang-format.yml
.github/workflows/commit-format.yml

Now that we're using the Github merge queue, this is required to not let the queue hanging.
ChangeLog:
* .github/workflows/bootstrap.yml: Add missing `merge_group` trigger.
* .github/workflows/ccpp.yml: Likewise.
* .github/workflows/clang-format.yml: Likewise.
* .github/workflows/commit-format.yml: Likewise.
This needs to be merged for merge queues to work properly, like we're trying with #1845. I'll merge this quite quickly unless someone has something to say :) This will also be a nice way to ask github to run bootstrap builds once a PR has been approved and sent to the merge queue.

ci: Add missing `merge_group` trigger for workflow

---

gcc/rust/lex/rust-lex.h
gcc/testsuite/rust/compile/issue-1830_bytes.rs
gcc/testsuite/rust/compile/issue-1830_str.rs

RAIIFile constructor was accepting directory filename. This lead to unattended directory opening in some part of the code (load_file_bytes) which resulted in ice. Since RAIIFile are used for the lexer, removing the ability to open directories with RAIIFile fixes those issues and prevent future mistakes.
* lex/rust-lex.h: Add requirement for file write permission.
Signed-off-by: Pierre-Emmanuel Patry <pierre-emmanuel.patry@embecosm.com>
Fixes #1830 
Fixes #1842

lex: Prevent directories in RAIIFile

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/ast/rust-ast-full-decls.h
gcc/rust/ast/rust-ast-visitor.h
gcc/rust/ast/rust-ast.cc
gcc/rust/ast/rust-pattern.h
gcc/rust/checks/errors/rust-feature-gate.h
gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/expand/rust-attribute-visitor.h
gcc/rust/hir/rust-ast-lower-base.cc
gcc/rust/hir/rust-ast-lower-base.h
gcc/rust/resolve/rust-ast-resolve-base.cc
gcc/rust/resolve/rust-ast-resolve-base.h
gcc/rust/resolve/rust-early-name-resolver.cc
gcc/rust/resolve/rust-early-name-resolver.h
gcc/rust/util/rust-attributes.cc
gcc/rust/util/rust-attributes.h

Adds AST::AltPattern to represent alternate patterns (ex: ```12 | 13```).
Addresses #1808

Add AST::AltPattern class

---

gcc/testsuite/rust/compile/issue-1830_bytes.rs
gcc/testsuite/rust/compile/issue-1830_str.rs

'dg-excess-errors' "indicates that the test is expected to fail due to compiler messages that are not handled by 'dg-error', [etc.]".  It's argument doesn't specify the message to match but just just a comment.  Here, however, we'd like to match specific compiler messages, so we should use 'dg-error', etc.  Use the magic line number zero as the compiler error diagnostic doesn't tell which line the error occurred on (separate issue to resolve).  This gives us:
-XFAIL: rust/compile/issue-1830_str.rs (test for excess errors)
+PASS: rust/compile/issue-1830_bytes.rs  at line 8 (test for errors, line )
+PASS: rust/compile/issue-1830_bytes.rs (test for excess errors)
-XFAIL: rust/compile/issue-1830_bytes.rs (test for excess errors)
+PASS: rust/compile/issue-1830_str.rs  at line 8 (test for …

Fix up DejaGnu directives in 'rust/compile/issue-1830_{bytes,str}.rs' test cases [#1838]

---

gcc/rust/ast/rust-ast.h
gcc/rust/ast/rust-item.h
gcc/rust/ast/rust-macro.h

* ast/rust-ast.h: Keep location in TraitItem base class
* ast/rust-item.h (class TraitItemFunc): Use base class location instead.
(class TraitItemMethod): Likewise.
(class TraitItemConst): Likewise.
(class TraitItemType): Likewise.
* ast/rust-macro.h: Likewise.

ast: Refactor TraitItem to keep Location info

---

gcc/rust/ast/rust-ast.cc
gcc/rust/checks/errors/privacy/rust-visibility-resolver.cc
gcc/rust/expand/rust-macro-builtins.cc
gcc/rust/expand/rust-macro-expand.cc
gcc/rust/parse/rust-parse-impl.h
gcc/rust/rust-diagnostics.cc
gcc/rust/rust-diagnostics.h
gcc/rust/rust-session-manager.cc

The class now allows for more variants including a `Hint` one which then gets emitted by calling `rust_inform`. This allows us to display hints/tips/notes in backtracking contexts such as the parser.
* rust-diagnostics.h (struct Error): Add new Kind enum and various new static constructors to allow for hints as well.
* rust-diagnostics.cc (Error::Error): Use new `kind` field properly.
* checks/errors/privacy/rust-visibility-resolver.cc (VisibilityResolver::resolve_module_path): Use new Error API.
* expand/rust-macro-builtins.cc (MacroBuiltin::include_handler): Likewise.
* expand/rust-macro-expand.cc (parse_many): Likewise. (transcribe_type): Likewise.
* parse/rust-parse-impl.h (Parser::parse_crate): Likewise.
* rust-session-manager.cc (Session::handle_crate_name): …

diagnostic: Refactor Error class

---

gcc/rust/ast/rust-ast-full-decls.h
gcc/rust/ast/rust-expr.h

Fixes #1567
Created a AST node InlineAsm similar to the one found in rustc. As there is no Symbol struct/class in gccrs I have made every instance of Symbol a string.
Signed-off-by: M V V S Manoj Kumar <mvvsmanojkumar@gmail.com>
* ast/rust-ast-full-decls.h (class InlineAsm):Added class declaration.
* ast/rust-expr.h (class InlineAsm):Added class definition.
The rustc guide for reference [here](https://rustc-dev-guide.rust-lang.org/asm.html#ast)
I did do a `git gcc-verify` to check if everything was alright with the change log. do let me know if I missed any thing :)

Added AST Node AST::InlineAsm

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/issue-1422.rs

Fixes #1422 and removes a ```FIXME```.

Unsafe block parsing fix

---

gcc/rust/checks/errors/rust-feature-gate.cc
gcc/rust/checks/errors/rust-feature-gate.h
gcc/testsuite/rust/compile/builtin_macro_compile_error.rs
gcc/testsuite/rust/compile/builtin_macro_concat.rs
gcc/testsuite/rust/compile/builtin_macro_eager1.rs
gcc/testsuite/rust/compile/builtin_macro_eager2.rs
gcc/testsuite/rust/compile/builtin_macro_env.rs
gcc/testsuite/rust/compile/builtin_macro_include_bytes.rs
gcc/testsuite/rust/compile/builtin_macro_include_str.rs
gcc/testsuite/rust/compile/builtin_macro_not_found.rs
gcc/testsuite/rust/compile/builtin_macro_recurse2.rs
gcc/testsuite/rust/compile/feature_rust_attri0.rs
gcc/testsuite/rust/compile/feature_rust_attri1.rs
gcc/testsuite/rust/compile/include_empty.rs
gcc/testsuite/rust/compile/issue-1830_bytes.rs
gcc/testsuite/rust/compile/issue-1830_str.rs
gcc/testsuite/rust/compile/macro42.rs
gcc/testsuite/rust/execute/torture/builtin_macro_cfg.rs
gcc/testsuite/rust/execute/torture/builtin_macro_concat.rs
gcc/testsuite/rust/execute/torture/builtin_macro_env.rs
gcc/testsuite/rust/execute/torture/builtin_macro_include_bytes.rs
gcc/testsuite/rust/execute/torture/builtin_macro_include_str.rs
gcc/testsuite/rust/execute/torture/builtin_macro_line.rs
gcc/testsuite/rust/execute/torture/builtin_macros1.rs
gcc/testsuite/rust/execute/torture/builtin_macros3.rs
gcc/testsuite/rust/execute/torture/macros29.rs
gcc/testsuite/rust/execute/torture/macros30.rs
gcc/testsuite/rust/execute/torture/macros31.rs

This commit implemented a basic feature gate to check some attributes for `rustc_attri`.
* checks/errors/rust-feature-gate.cc: Add implementations for `rustc_attri`.
* checks/errors/rust-feature-gate.h: Likewise.
* rust/compile/builtin_macro_compile_error.rs: Add crate feature `rustc_attri`.
* rust/compile/builtin_macro_concat.rs: Likewise.
* rust/compile/builtin_macro_eager1.rs: Likewise.
* rust/compile/builtin_macro_eager2.rs: Likewise.
* rust/compile/builtin_macro_env.rs: Likewise.
* rust/compile/builtin_macro_include_bytes.rs: Likewise.
* rust/compile/builtin_macro_include_str.rs: Likewise.
* rust/compile/builtin_macro_not_found.rs: Likewise.
* rust/compile/builtin_macro_recurse2.rs: Likewise.
* rust/compile/feature_rust_attri0.rs:New file. …

Add feature gate for "rustc_attri".

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/nested_generic.rs
gcc/testsuite/rust/compile/parse_associated_type_as_generic_arg.rs
gcc/testsuite/rust/compile/parse_associated_type_as_generic_arg2.rs
gcc/testsuite/rust/compile/parse_associated_type_as_generic_arg3.rs
gcc/testsuite/rust/compile/path_as_generic_arg.rs

Let's take the example of lexing `Option<<T as Iterator>::Item>` and look at the first few tokens. Originally, `Option<<T` was lexed as 3 tokens:
* IDENTIFIER(Option)
* LEFT_SHIFT
* IDENTIFIER(T)
The parser did not allow a list of generic arguments to start with a left shift, and rejected the above type. We are now splitting the left shift into two left angles, as this allows complex generic arguments and overall makes sense parsing wise. Thus, the above list becomes:
* IDENTIFIER(Option)
* LEFT_ANGLE
* LEFT_ANGLE
* IDENTIFIER(T)
and `<T as Iterator>` is properly parsed as a qualified path.
Fixes #1815
Fixed #1809
Addresses #1524
* parse/rust-parse-impl.h (Parser::parse_path_generic_args): Split leading `LEFT_SHIFT` token into two `LEFT_ANGLE` tokens when parsing …

parser: Allow parsing of qualified type path as nested generic argument

---

.github/workflows/ccpp.yml

We should probably think about building GCC 4.8 from source from time to time and hosting the image on our Dockerhub, but I think this is okay as well for now.
ChangeLog:
* .github/workflows/ccpp.yml: Run GCC 4.8 action in Ubuntu 18.04 container
Fixes #1900 
The choice was between using the GCC 4.8 image which was last updated... 7 years ago, and this Ubuntu image which was updated three weeks ago. I think this should just be a temporary solution however.

ci: Run GCC 4.8 job in Ubuntu 18.04 container

---

gcc/rust/typecheck/rust-autoderef.cc
gcc/rust/typecheck/rust-hir-trait-resolve.cc
gcc/rust/typecheck/rust-hir-type-check-base.cc
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-hir-type-check.cc
gcc/rust/typecheck/rust-type-util.cc
gcc/rust/typecheck/rust-type-util.h
gcc/rust/typecheck/rust-tyty-call.cc

Refactor unify_site to be a simple function in rust-type-util.h.
* typecheck/rust-autoderef.cc: Remove TypeCheckBase qualifier.
* typecheck/rust-hir-trait-resolve.cc: Remove TypeCheckBase qualifier.
* typecheck/rust-hir-type-check-base.cc (TypeCheckBase::unify_site): Remove unify_site.
* typecheck/rust-hir-type-check-base.h: Remove unify_site header.
* typecheck/rust-hir-type-check.cc (TypeResolution::Resolve): Remove TypeCheckBase qualifier.
* typecheck/rust-type-util.cc (unify_site): Add unify_site function.
* typecheck/rust-type-util.h (unify_site): Add unify_site prototype.
* typecheck/rust-tyty-call.cc (TypeCheckMethodCallExpr::check): Remove TypeCheckBase qualifier.
Fixes #1881

typecheck: Refactor unify_site

---

gcc/rust/ast/rust-item.h
gcc/rust/checks/errors/rust-feature.cc
gcc/rust/checks/errors/rust-feature.h
gcc/rust/lex/rust-lex.cc
gcc/rust/lex/rust-token.h
gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/auto_trait_invalid.rs
gcc/testsuite/rust/compile/auto_trait_valid.rs

This adds enough handling to start parsing `auto` traits but not handle
them in the AST, lowering phase or HIR yet.
The feature is named `optin_builtin_traits` in Rust 1.49 but changes to
`auto_traits` later down the line. So we'll need to take care of this later
on.
Fixes #1814
* ast/rust-item.h (class Trait): Add `has_auto` field.
* checks/errors/rust-feature.cc: Add handling for `feature(optin_builtin_traits)`
* checks/errors/rust-feature.h: Likewise.
* lex/rust-token.h: Add `auto` keyword token.
* parse/rust-parse-impl.h (Parser::parse_vis_item): Parse auto traits
on `auto` keyword.
(Parser::parse_trait): Add `is_auto_trait` optional parameter.
* parse/rust-parse.h: Likewise.
* rust/compile/auto_trait_invalid.rs: New test.
* …

parser: Parse auto_traits

---

gcc/rust/expand/rust-macro-invoc-lexer.cc
gcc/testsuite/rust/compile/expand_macro_qual_path_in_type.rs

* expand/rust-macro-invoc-lexer.cc (MacroInvocLexer::split_current_token): Add proper implementation.
* rust/compile/expand_macro_qual_path_in_type.rs: New test.
Fixes #1894

macro_invoc_lexer: Add `split_current_token` implementation

---

gcc/rust/typecheck/rust-hir-type-check-base.cc
gcc/rust/typecheck/rust-hir-type-check-base.h
gcc/rust/typecheck/rust-type-util.cc
gcc/rust/typecheck/rust-type-util.h

Refactor cast_site to be a simple function in rust-type-util.h.
* typecheck/rust-hir-type-check-base.cc (TypeCheckBase::cast_site): Remove cast_site.
* typecheck/rust-hir-type-check-base.h: Remove cast_site prototype.
* typecheck/rust-type-util.cc (cast_site): Add cast_site.
* typecheck/rust-type-util.h (cast_site): Add cast_site prototype.
Fixes #1883

typecheck: Refactor cast_site

---

gcc/rust/ast/rust-item.h
gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/default_not_a_kw.rs
gcc/testsuite/rust/compile/parse_invalid_specialization.rs
gcc/testsuite/rust/compile/parse_specialization.rs

* ast/rust-item.h (class Method): Add `is_default` field. (class Function): Likewise.
* parse/rust-parse-impl.h (Parser::parse_item): Add nice error when parsing `default` keyword outside of an `impl` block (Parser::parse_trait_impl_item): Allow parsing functions or methods when seeing `default` keyword.
* rust/compile/parse_invalid_specialization.rs: New test.
* rust/compile/parse_specialization.rs: New test.
* rust/compile/default_not_a_kw.rs: New test.
Fixes #1919

parser: Parse `default` impl Functions and Methods

---

gcc/rust/parse/rust-parse-impl.h
gcc/rust/parse/rust-parse.h
gcc/testsuite/rust/compile/extern_type_item.rs
gcc/testsuite/rust/compile/extern_type_item_missing_semi.rs

Add the code to parse type item declaration within an extern block.
* parse/rust-parse-impl.h (Parser::parse_external_type_item): Add function to parser an external type item. (Parser::parse_external_item): Add identification and parsing for external type items.
* parse/rust-parse.h: Add parser_external_type_item prototype.
Fixes #1917

parser: Parse external type item

---

gcc/rust/backend/rust-compile-base.h
gcc/rust/backend/rust-compile-expr.cc
gcc/rust/backend/rust-compile.cc
gcc/rust/typecheck/rust-autoderef.cc
gcc/rust/typecheck/rust-autoderef.h
gcc/rust/typecheck/rust-casts.cc
gcc/rust/typecheck/rust-coercion.cc
gcc/rust/typecheck/rust-coercion.h
gcc/rust/typecheck/rust-hir-dot-operator.cc
gcc/rust/typecheck/rust-hir-dot-operator.h
gcc/rust/typecheck/rust-hir-type-check-expr.cc
gcc/rust/typecheck/rust-hir-type-check.h
gcc/rust/typecheck/rust-type-util.cc
gcc/rust/typecheck/rust-type-util.h
gcc/rust/typecheck/rust-typecheck-context.cc
gcc/rust/typecheck/rust-tyty-cmp.h
gcc/rust/typecheck/rust-tyty.cc
gcc/rust/typecheck/rust-tyty.h
gcc/rust/typecheck/rust-unify.cc
gcc/rust/typecheck/rust-unify.h
gcc/testsuite/rust/compile/issue-1901.rs
gcc/testsuite/rust/compile/issue-1930.rs

In order to fix the following issues we need to begin the journey to get rid of
the can_eq interface as well as the autoderef_flag hack inside it. In non-generic
contexts in order to call const pointer lang item methods the can_eq interface
was not possible to infer that these types are valid. This patch set adds a new
unify_and interface so that we can optionally inject inference variables and only
commit them when everything is ok and on failure cleanup. So during method
resolution and picking we can now pick using our TryCoerce interface instead
of the bad can_eq one.
Fixes #1903 #1901 #878

Generic pointers coerceable

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/ast/rust-ast-full-decls.h
gcc/rust/ast/rust-ast-visitor.h
gcc/rust/ast/rust-ast.cc
gcc/rust/ast/rust-pattern.h
gcc/rust/checks/errors/rust-feature-gate.h
gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/expand/rust-attribute-visitor.h
gcc/rust/hir/rust-ast-lower-base.cc
gcc/rust/hir/rust-ast-lower-base.h
gcc/rust/resolve/rust-ast-resolve-base.cc
gcc/rust/resolve/rust-ast-resolve-base.h
gcc/rust/resolve/rust-early-name-resolver.cc
gcc/rust/resolve/rust-early-name-resolver.h
gcc/rust/util/rust-attributes.cc
gcc/rust/util/rust-attributes.h

Add the RestPattern AST node representing `..` code in some rust context. This commit also provides the different visitors for this node.
* ast/rust-ast-dump.cc (Dump::visit): Add visitor.
* ast/rust-ast-dump.h: Add visitor prototype.
* ast/rust-ast-full-decls.h (class RestPattern): Add forward declaration for class RestPattern.
* ast/rust-ast-visitor.h: Add visitor prototype.
* ast/rust-ast.cc (RestPattern::accept_vis): Add function to accept a foreign visitor.
* ast/rust-pattern.h (class RestPattern): Add class RestPattern.
* checks/errors/rust-feature-gate.h: Add visitor prototype.
* expand/rust-attribute-visitor.cc (AttrVisitor::visit): Add visitor implementation.
* expand/rust-attribute-visitor.h: Add visitor prototype.
* hir/rust-ast-lower-base.cc …

Add `RestPattern` AST node

---

gcc/rust/typecheck/rust-casts.cc
gcc/testsuite/rust/compile/cast_generics.rs

Fixes #1897 
```
* typecheck/rust-casts.cc (TypeCastRules::cast_rules): Perform destructure on `from` type
```
```
* rust/compile/cast_generics.rs: New test.
```

Fix casting error behind generics [WIP]

---

gcc/rust/checks/errors/rust-feature-gate.cc
gcc/rust/checks/errors/rust-feature-gate.h
gcc/rust/checks/errors/rust-feature.cc
gcc/rust/checks/errors/rust-feature.h
gcc/testsuite/rust/compile/feature_extern_types.rs

This commit add a basic implementation to gating `ExternalTypeItem` AST node.
* checks/errors/rust-feature-gate.cc: Add definition for `extern_types`.
* checks/errors/rust-feature-gate.h: Likewise.
* checks/errors/rust-feature.cc: Likewise.
* checks/errors/rust-feature.h: Likewise.
See #1925.

Add feature gate definition for `extern_types`.

---

gcc/rust/backend/rust-compile-intrinsic.cc
gcc/testsuite/rust/compile/torture/intrinsics-8.rs

Fixes #1898
* backend/rust-compile-intrinsic.cc (op_with_overflow_inner): (std::function<tree): new wrapper over op_with_overflow (op_with_overflow): generate the intrinsic based on the tree_code op
* rust/compile/torture/intrinsics-8.rs: New test.

gccrs: add {add,sub,mul}_with_overflow intrinsics

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/if_let_expr.rs

The current token was passed as a parameter and therefore out of the lexer's queue. Matching the next token against `let` was an error as `let` was in fact the current token because of this parameter.
Fixes #1904

Parse if let expressions correctly

---

gcc/rust/ast/rust-pattern.h
gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/slice_rest_pattern.rs

This PR introduces the parsing code for `..` commonly known as `RestPattern`.
Fixes #1918

Parse rest pattern in slices

---

gcc/rust/hir/rust-hir-dump.cc

In this draft, I have attempted to implement some part of pretty HIR Dump to show the proposed format for HIR Dump. My approach in this is to avoid printing any empty fields of HIR nodes. In the pretty HIR dump of the code example given below, no attributes are present in the code for the crate, so you will not see  **inner attribute: []** at all. This makes the dump look cleaner as only the available information is printed. 
Try this example for the dump
```rust
fn main() {
let var1=5;
}
fn test_1(arg1:u32, arg2:f32)->u8 {
let new1:u8 = 4;
let new2:u8 = 6 + 5;
new2
}
fn test(mul:u32)->u32 {
let first = 5;
let second = first + 5;
second
}
```
Seeking feedback for making it better :)
I will be making a GSOC proposal for this project.

an attempt to implement pretty HIR dump 

---

gcc/rust/parse/rust-parse-impl.h

The recent changes in the parser bringing the parsing of extern type items also brought a compilation error when boostrapping the compiler.
* parse/rust-parse-impl.h (Parser::parse_external_type_item): Fix compilation error due to unnecessary move.
Fixes #1939

Fix bootstrap compile error

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/zero_sized_slice.rs

Zero sized slice pattern are now checked before attempting to parse any pattern inside the slice.
Fixes #1920

Parse zero sized slice pattern

---

gcc/rust/backend/rust-builtins.cc
gcc/rust/backend/rust-compile-intrinsic.cc
gcc/testsuite/rust/compile/torture/uninit-intrinsic-1.rs

Following an investigation from rustc and discussions on zulip the recommendation was that for uninit we memset to 0x01 which is less likely to be a null ptr but still an invalid reference.
Fixes #1899

gccrs: add uninit intrinsic

---

gcc/rust/parse/rust-parse-impl.h
gcc/testsuite/rust/compile/while_let_expr.rs

While let expr return unit but are valid construct in rust, they should therefore be included in the parsing code.
Fixes #1949

parser: Fix while let expr parsing

---

gcc/rust/typecheck/rust-hir-trait-resolve.cc

Wen computing higher ranked trait bounds where there are multiple type params and ones which are not bound entirely on the impl-type we need to inject inference variables as required to compute the types. The inference variables we inject are missing the callbacks that we can compute the bounds properly so this is the first part of the fix.
Addresses #1893
* typecheck/rust-hir-trait-resolve.cc: use unify_and infer

gccrs: Take advantage of our new unify_and to inject inference

---

gcc/rust/hir/rust-ast-lower-type.cc
gcc/rust/rust-object-export.cc

Fixes issue - #784 & #580 
- Clean up the `rust-backend.c` from `gcc/rust/rust-object-export.c`.
- Make all `rust_fatal_error` to assertion in`rust-ast-lower-type.cc`.

Cleanup and Assertion

---

gcc/rust/typecheck/rust-hir-type-check-pattern.cc
gcc/rust/typecheck/rust-hir-type-check-pattern.h
gcc/testsuite/rust/compile/tuple_mismatch.rs

* typecheck/rust-hir-type-check-pattern.cc (TypeCheckPattern::visit): Add length checking for tuple patters.
* rust/compile/tuple_mismatch.rs: New test.
Signed-off-by: Nikos Alexandris <nikos-alexandris@protonmail.com>

Add length checking for tuple patterns. Resolves issue Rust-GCC#1849

---

gcc/rust/ast/rust-macro.cc
gcc/rust/ast/rust-macro.h
gcc/rust/expand/rust-macro-builtins.cc
gcc/rust/expand/rust-macro-builtins.h
gcc/rust/util/rust-hir-map.cc
gcc/testsuite/rust/compile/stringify.rs
gcc/testsuite/rust/execute/torture/builtin_macro_stringify.rs

Add the stringify macro expansion as well as some tests.
* ast/rust-macro.cc (builtin_macro_from_string): Add identifier identification.
* ast/rust-macro.h (enum class): Add Stringify builtin macro type.
* expand/rust-macro-builtins.cc (make_macro_path_str): Add path for builtin stringify macro. (MacroBuiltin::stringify_handler): Add handler for builtin stringify macro.
* expand/rust-macro-builtins.h: Add stringify handler's prototype.
* util/rust-hir-map.cc (Mappings::insert_macro_def): Add stringify handler to builtin hir map.
* rust/compile/stringify.rs: Add a basic test with some text.
* rust/compile/stringify_macro.rs: Verify the text is left as is without any other macro expansion.
Fixes #1968 
Related to #927

Add stringify macro expansion

---

gcc/rust/hir/tree/rust-hir-pattern.h
gcc/rust/resolve/rust-ast-resolve-pattern.h
gcc/rust/typecheck/rust-hir-type-check-pattern.cc
gcc/testsuite/rust/compile/ref_pattern_fn_param.rs

provide basic resolve and typechecking for `ReferencePattern`.

typecheck: Add basic typechecking for ReferenceType

---

gcc/rust/typecheck/rust-hir-type-check-pattern.cc

The visit for TypeCheckPattern::visit (HIR::ReferencePattern) was missing an assignment to infered.

hir: Fix `ReferencePattern` typechecking

---

gcc/rust/ast/rust-ast-dump.cc
gcc/rust/ast/rust-ast-dump.h
gcc/rust/hir/rust-hir-dump.cc
gcc/rust/hir/rust-hir-dump.h
gcc/rust/util/rust-dump.h

Relates to #1976 (#1976 should be rebased before merging)
make check-rust passed on every commit
Please check the changelog - I have done it for the first time.

Unify AST and HIR dump indentation

---

gcc/rust/expand/rust-attribute-visitor.cc
gcc/rust/resolve/rust-early-name-resolver.cc

This is important as public macros can be present in other modules,
which would otherwise not be loaded until the expansion phase
happening right after the early name resolution.
* resolve/rust-early-name-resolver.cc (EarlyNameResolver::visit): Move
unloaded module item loading to...
* expand/rust-attribute-visitor.cc (AttrVisitor::visit): ...here.
Addresse #1077

enr: Fetch module items during early name resolution
